In [1]:
%run input/Format.ipynb
import ROOT as root
from array import array
root.gErrorIgnoreLevel = root.kFatal
%jsroot on
root.gStyle.SetOptStat(0)
import ctypes

/home/yoren/.local/lib/python3.10/site-packages/nbformat/__init__.py:96: MissingIDFieldWarning: Cell is missing an id field, this will become a hard error in future nbformat versions. You may want to use `normalize()` on your notebooks before validations (available since nbformat 5.1.4). Previous versions of nbformat are fixing this issue transparently, and will stop doing so in the future.
  validate(nb)

Welcome to JupyROOT 6.30/06

Error in <TUnixSystem::FindDynamicLibrary>: input/logo/PHENIXTools/lib/libLogoPainter.so does not exist in /home/yoren/bnl/ROOT/install/lib:.:/home/yoren/bnl/ROOT/install/lib:/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v3:/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v2:/lib/x86_64-linux-gnu/tls/haswell/x86_64:/lib/x86_64-linux-gnu/tls/haswell:/lib/x86_64-linux-gnu/tls/x86_64:/lib/x86_64-linux-gnu/tls:/lib/x86_64-linux-gnu/haswell/x86_64:/lib/x86_64-linux-gnu/haswell:/lib/x86_64-linux-gnu/x86_64:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v3:/usr/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v2:/usr/lib/x86_64-linux-gnu/tls/haswell/x86_64:/usr/lib/x86_64-linux-gnu/tls/haswell:/usr/lib/x86_64-linux-gnu/tls/x86_64:/usr/lib/x86_64-linux-gnu/tls:/usr/lib/x86_64-linux-gnu/haswell/x86_64:/usr/lib/x86_64-linux-gnu/haswell:/usr/lib/x86_64-linux-gnu/x86_64:/usr/lib/x86_64-linux-gnu:/lib/glibc-hwcaps/x86-64-v3:/lib/glibc-hwcaps/x86-64-v2:/lib/tls/haswell/x86_64:/lib/tls/haswell:/lib/tls/x86_64:/lib/tls:/lib/haswell/x86_64:/lib/haswell:/lib/x86_64:/lib:/usr/lib/glibc-hwcaps/x86-64-v3:/usr/lib/glibc-hwcaps/x86-64-v2:/usr/lib/tls/haswell/x86_64:/usr/lib/tls/haswell:/usr/lib/tls/x86_64:/usr/lib/tls:/usr/lib/haswell/x86_64:/usr/lib/haswell:/usr/lib/x86_64:/usr/lib:/home/yoren/bnl/ROOT
input_line_46:1:10: fatal error: 'input/logo/PHENIXTools/include/LogoPainter.hpp' file not found
#include "input/logo/PHENIXTools/include/LogoPainter.hpp"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [2]:
colors=[1,2,4,root.kGreen+2,root.kOrange+4,root.kMagenta,root.kGray,root.kGray,root.kBlack,root.kCyan,root.kOrange,root.kViolet,root.kCyan,root.kGreen,root.kOrange]
file_path="input/"
file_names=["data_pp_v3.root"]#,"m_ee_DCA_535.root"],"m_ee_DCA_536.root"]

In [3]:
pt_bins = [0.8, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0, 6.0, 8.0, 10.0]
pt_bins = [0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0, 7.0, 10.0]
pt_bins = [0.6, 0.8, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0, 7.0, 10.0]
pt_bins = [0.8, 1.2, 1.5, 1.8, 2.3, 3.0, 4.0, 5.0, 7.0,10.0]
pt_bins = [0.6, 0.8, 1.2, 1.6, 2.0, 2.5, 3.0, 4.0, 5.0, 7.0, 10.0]
pt_bins = [0.8, 1.2, 1.5, 1.8, 2.3, 3.0, 4.0, 5.0, 7.0, 10.0]
pt_bins = [0.8, 1.0, 1.3, 1.6, 1.9, 2.2, 2.6, 3.0, 4.0, 5.0, 7.0, 10.0]
pt_bins = [0.8, 1.0, 1.3, 1.7, 2.0, 2.5, 3.0, 4.0, 5.0, 7.0, 10.0]
#pt_bins = [1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0, 10.0]

In [4]:
windows = {
    "ee_signal":  (0.01, 0.13),
    "ee_norm":    (0.2, 0.75),
    "eeg_signal": (0.09, 0.19),
    "eeg_norm":   (0.20, 0.80),
    "eeg_fit_1":  (0.05, 0.78),
}

In [5]:

root.gROOT.SetBatch(True)
root.TH1.AddDirectory(False)

configs = [
    "nominal",
    "conv_solution",
    "conv_tight",
    "ecore04",
    "ecore05",
    "pte03",
    "pte04",
    "eid0",
    "eid1",
    "eid3",
    "chi2_4",
    "chi2_5",
    "escale099",
    "escale101",
]

cent_bins = [0]

hist_kinds = [
    "fg2d_eemass_reco",
    "bg2d_eemass_reco",
    "fg2d_eegmass_reco",
    "bg2d_eegmass_reco",
]

In [6]:
hist_names = {}

for kind in hist_kinds:
    hist_names[kind] = {}
    for cfg in configs:
        hist_names[kind][cfg] = {}
        for icent in cent_bins:
            hist_names[kind][cfg][icent] = f"{kind}_{cfg}_icent{icent}"

# optional old-style quick-check hists
old_hist_names = {
    "fg_ee_dphi":  {icent: f"fg2d_eemass_reco_dphi_icent{icent}" for icent in cent_bins},
    "fg_ee_dzed":  {icent: f"fg2d_eemass_reco_dzed_icent{icent}" for icent in cent_bins},
    "bg_ee_dphi":  {icent: f"bg2d_eemass_reco_dphi_icent{icent}" for icent in cent_bins},
    "bg_ee_dzed":  {icent: f"bg2d_eemass_reco_dzed_icent{icent}" for icent in cent_bins},
    "fg_eeg_dphi": {icent: f"fg2d_eegmass_reco_dphi_icent{icent}" for icent in cent_bins},
    "fg_eeg_dzed": {icent: f"fg2d_eegmass_reco_dzed_icent{icent}" for icent in cent_bins},
    "bg_eeg_dphi": {icent: f"bg2d_eegmass_reco_dphi_icent{icent}" for icent in cent_bins},
    "bg_eeg_dzed": {icent: f"bg2d_eegmass_reco_dzed_icent{icent}" for icent in cent_bins},
}

cutflow_names = {cfg: f"h_cutflow_{cfg}" for cfg in configs}
event_hist_names = ["h_nevents", "h_cent", "h_n_cent", "h_nev_cent"]

In [7]:
def get_clone(infile, hname, newname=None, verbose=True):
    obj = infile.Get(hname)
    if not obj:
        if verbose:
            print(f"Missing histogram: {hname}")
        return None

    hist = obj.Clone(newname if newname else hname + "_clone")
    hist.SetDirectory(root.nullptr)
    return hist

In [8]:
hists = {}

for ifile, fname in enumerate(file_names):
    full_name = file_path + fname
    infile = root.TFile.Open(full_name, "READ")

    if not infile or infile.IsZombie():
        print(f"Cannot open file: {full_name}")
        continue

    print(f"Reading file {ifile}: {full_name}")

    hists[ifile] = {}
    hists[ifile]["filename"] = full_name

    # Main systematic TH2 hists
    for kind in hist_kinds:
        hists[ifile][kind] = {}

        for cfg in configs:
            hists[ifile][kind][cfg] = {}

            for icent in cent_bins:
                hname = hist_names[kind][cfg][icent]
                newname = f"{hname}_file{ifile}"

                hists[ifile][kind][cfg][icent] = get_clone(
                    infile, hname, newname=newname
                )

    # Old-style hists
    hists[ifile]["old"] = {}
    for old_key, cent_dict in old_hist_names.items():
        hists[ifile]["old"][old_key] = {}

        for icent, hname in cent_dict.items():
            newname = f"{hname}_file{ifile}"
            hists[ifile]["old"][old_key][icent] = get_clone(
                infile, hname, newname=newname
            )

    # Cutflows
    hists[ifile]["cutflow"] = {}
    for cfg, hname in cutflow_names.items():
        hists[ifile]["cutflow"][cfg] = get_clone(
            infile, hname, newname=f"{hname}_file{ifile}"
        )

    # Event-level hists
    hists[ifile]["event"] = {}
    for hname in event_hist_names:
        hists[ifile]["event"][hname] = get_clone(
            infile, hname, newname=f"{hname}_file{ifile}", verbose=False
        )

    infile.Close()

Reading file 0: input/data_pp_v3.root

In [9]:
#for icfg in configs:
#    for icent in (1,3):
#        hists[0]["fg2d_eemass_reco"][icfg][0].Add(hists[0]["fg2d_eemass_reco"][icfg][icent])
#        hists[0]["bg2d_eemass_reco"][icfg][0].Add(hists[0]["bg2d_eemass_reco"][icfg][icent])
#        hists[0]["fg2d_eegmass_reco"][icfg][0].Add(hists[0]["fg2d_eegmass_reco"][icfg][icent])
#        hists[0]["bg2d_eegmass_reco"][icfg][0].Add(hists[0]["bg2d_eegmass_reco"][icfg][icent])

In [10]:
h_fg_ee_nom_cent0 = hists[0]["fg2d_eemass_reco"]["nominal"][0]
h_bg_ee_nom_cent0 = hists[0]["bg2d_eemass_reco"]["nominal"][0]
h_fg_eeg_nom_cent0 = hists[0]["fg2d_eegmass_reco"]["nominal"][0]
h_bg_eeg_nom_cent0 = hists[0]["bg2d_eegmass_reco"]["nominal"][0]

int_windows = {
    "ee": (0.01, 0.12),
    "eeg": (0.09, 0.2),
}

pt_min = 2.0
pt_max = 9.0

m_min_ee_int = 0.15
m_max_ee_int = 0.75

m_min_eeg_int = 0.3
m_max_eeg_int = 0.8

c1 = root.TCanvas("c1", "c1", 1200, 700)
c1.Divide(2, 1)
c1.cd(1)
ee_proj = h_fg_ee_nom_cent0.ProjectionX("px_fg_ee_nom_cent0",h_fg_ee_nom_cent0.GetYaxis().FindBin(pt_min),h_fg_ee_nom_cent0.GetYaxis().FindBin(pt_max))
ee_proj_bg = h_bg_ee_nom_cent0.ProjectionX("px_bg_ee_nom_cent0",h_bg_ee_nom_cent0.GetYaxis().FindBin(pt_min),h_bg_ee_nom_cent0.GetYaxis().FindBin(pt_max)) 
Format_Hist_total(ee_proj, Lcolor=root.kBlue, Mcolor=root.kBlue, title_x="m_{ee} (GeV/c^{2})", title_y="Counts")
ee_proj.GetXaxis().SetRangeUser(0, 0.3)
ee_proj.Draw()
ee_proj_bg.Scale(ee_proj.Integral(ee_proj.FindBin(m_min_ee_int), ee_proj.FindBin(m_max_ee_int))/ee_proj_bg.Integral(ee_proj_bg.FindBin(m_min_ee_int), ee_proj_bg.FindBin(m_max_ee_int)))

Format_Graph(ee_proj_bg, Lcolor=root.kRed, Mcolor=root.kRed)

print(ee_proj.Integral(ee_proj.FindBin(int_windows["ee"][0]), ee_proj.FindBin(int_windows["ee"][1])) - ee_proj_bg.Integral(ee_proj_bg.FindBin(int_windows["ee"][0]), ee_proj_bg.FindBin(int_windows["ee"][1])))

ee_proj_bg.Draw("same")

c1.cd(2)
eeg_proj = h_fg_eeg_nom_cent0.ProjectionX("px_fg_eeg_nom_cent0",h_fg_eeg_nom_cent0.GetYaxis().FindBin(pt_min),h_fg_eeg_nom_cent0.GetYaxis().FindBin(pt_max))
eeg_proj_bg = h_bg_eeg_nom_cent0.ProjectionX("px_bg_eeg_nom_cent0",h_bg_eeg_nom_cent0.GetYaxis().FindBin(pt_min),h_bg_eeg_nom_cent0.GetYaxis().FindBin(pt_max)) 
Format_Hist_total(eeg_proj, Lcolor=root.kBlue, Mcolor=root.kBlue, title_x="m_{ee#gamma} (GeV/c^{2})", title_y="Counts")
eeg_proj.GetXaxis().SetRangeUser(0, 0.3)
eeg_proj.Draw()
#eeg_proj_bg.Scale(eeg_proj.Integral(eeg_proj.FindBin(m_min_eeg_int), eeg_proj.FindBin(m_max_eeg_int))/eeg_proj_bg.Integral(eeg_proj_bg.FindBin(m_min_eeg_int), eeg_proj_bg.FindBin(m_max_eeg_int)))
Format_Graph(eeg_proj_bg, Lcolor=root.kRed, Mcolor=root.kRed)
eeg_proj_bg.Draw("same")

print(eeg_proj.Integral(eeg_proj.FindBin(int_windows["eeg"][0]), eeg_proj.FindBin(int_windows["eeg"][1])) - eeg_proj_bg.Integral(eeg_proj_bg.FindBin(int_windows["eeg"][0]), eeg_proj_bg.FindBin(int_windows["eeg"][1])))

c1.Draw()

9094.69319747363
-1675.0

QA utilities

In [11]:
import math
import ctypes
import os

ROOT_KEEPALIVE = []

def keep(obj):
    if obj:
        ROOT_KEEPALIVE.append(obj)
    return obj

def check_obj(obj, name):
    if obj is None:
        print(f"[BAD] {name}: None")
        return False
    try:
        cname = obj.ClassName()
        oname = obj.GetName()
    except Exception as e:
        print(f"[BAD] {name}: invalid ROOT object: {e}")
        return False

    print(f"[OK] {name}: {cname}  {oname}")
    return True

def check_hist(h, name):
    if not check_obj(h, name):
        return False
    print(f"     entries = {h.GetEntries():.3g}")
    print(f"     integral = {h.Integral():.3g}")
    print(f"     nbinsX = {h.GetNbinsX()}, nbinsY = {h.GetNbinsY() if hasattr(h, 'GetNbinsY') else '-'}")
    return True

In [12]:
check_hist(hists[0]["fg2d_eemass_reco"]["nominal"][0], "fg ee nominal cent0")
check_hist(hists[0]["bg2d_eemass_reco"]["nominal"][0], "bg ee nominal cent0")
check_hist(hists[0]["fg2d_eegmass_reco"]["nominal"][0], "fg eeg nominal cent0")
check_hist(hists[0]["bg2d_eegmass_reco"]["nominal"][0], "bg eeg nominal cent0")

[OK] fg ee nominal cent0: TH2F  fg2d_eemass_reco_nominal_icent0_file0
     entries = 1.04e+05
     integral = 1.04e+05
     nbinsX = 400, nbinsY = 100
[OK] bg ee nominal cent0: TH2F  bg2d_eemass_reco_nominal_icent0_file0
     entries = 1.02e+08
     integral = 1.01e+08
     nbinsX = 400, nbinsY = 100
[OK] fg eeg nominal cent0: TH2F  fg2d_eegmass_reco_nominal_icent0_file0
     entries = 1.09e+05
     integral = 6.9e+04
     nbinsX = 400, nbinsY = 100
[OK] bg eeg nominal cent0: TH2F  bg2d_eegmass_reco_nominal_icent0_file0
     entries = 1.24e+06
     integral = 6.38e+05
     nbinsX = 400, nbinsY = 100

True

helpers

In [13]:
def clone_hist(h, name):
    if not check_obj(h, f"clone source {name}"):
        return None

    hc = h.Clone(name)
    if not check_obj(hc, f"clone result {name}"):
        return None

    hc.SetDirectory(root.nullptr)
    keep(hc)
    return hc


def project_mass_in_pt(hist2d, pt_min, pt_max, name):
    if not check_obj(hist2d, f"project source {name}"):
        return None

    yaxis = hist2d.GetYaxis()
    y1 = yaxis.FindBin(pt_min + 1e-3)
    y2 = yaxis.FindBin(pt_max - 1e-3)

    print(f"project_mass_in_pt: {name}")
    print(f"  pt range = [{pt_min}, {pt_max})")
    print(f"  y bins   = {y1} to {y2}")

    proj = hist2d.ProjectionX(name, y1, y2)
    if not check_obj(proj, f"projection {name}"):
        return None

    proj.SetDirectory(root.nullptr)
    keep(proj)

    print(f"  proj integral = {proj.Integral():.3g}")
    return proj


def integral_range(hist, xmin, xmax):
    if not check_obj(hist, f"integral source {xmin}_{xmax}"):
        return 0.0, 0.0

    b1 = hist.FindBin(xmin + 1e-3)
    b2 = hist.FindBin(xmax - 1e-3)

    val = 0.0
    err2 = 0.0

    for ib in range(b1, b2 + 1):
        val += hist.GetBinContent(ib)
        err2 += hist.GetBinError(ib)**2

    return float(val), math.sqrt(err2)


def scale_bg_to_sideband(fg, bg, xmin, xmax):
    fg_int, fg_err = integral_range(fg, xmin, xmax)
    bg_int, bg_err = integral_range(bg, xmin, xmax)

    print(f"sideband [{xmin}, {xmax}]: FG={fg_int:.3g}, BG={bg_int:.3g}")

    if bg_int <= 0:
        print("  WARNING: BG sideband <= 0, using scale=1")
        return 1.0

    scale = fg_int / bg_int
    print(f"  scale = {scale:.6g}")
    return scale

cnerality sum

In [14]:
def sum_cent_mb(hists, ifile, kind, cfg, name):
    """Sum centralities for one file and one config."""
    hsum = None

    for icent in cent_bins:
        h = hists[ifile][kind][cfg][icent]
        if not h:
            continue

        if hsum is None:
            hsum = clone_hist(h, name)
            hsum.Reset("ICESM")

        hsum.Add(h)

    return hsum


def sum_cent_mb_all_files(hists, kind, cfg, name):
    """Sum centralities and files."""
    hsum = None

    for ifile in sorted(hists.keys()):
        if not isinstance(ifile, int):
            continue

        hmb = sum_cent_mb(hists, ifile, kind, cfg, f"{name}_file{ifile}")
        if not hmb:
            continue

        if hsum is None:
            hsum = clone_hist(hmb, name)
            hsum.Reset("ICESM")

        hsum.Add(hmb)

    return hsum

In [15]:
pt_min = 2.0
pt_max = 10.0

test_ee_fg = project_mass_in_pt(
    hists[0]["fg2d_eemass_reco"]["nominal"][0],
    pt_min, pt_max,
    "test_ee_fg"
)

test_ee_bg = project_mass_in_pt(
    hists[0]["bg2d_eemass_reco"]["nominal"][0],
    pt_min, pt_max,
    "test_ee_bg"
)

[OK] project source test_ee_fg: TH2F  fg2d_eemass_reco_nominal_icent0_file0
project_mass_in_pt: test_ee_fg
  pt range = [2.0, 10.0)
  y bins   = 21 to 100
[OK] projection test_ee_fg: TH1D  test_ee_fg
  proj integral = 9.36e+03
[OK] project source test_ee_bg: TH2F  bg2d_eemass_reco_nominal_icent0_file0
project_mass_in_pt: test_ee_bg
  pt range = [2.0, 10.0)
  y bins   = 21 to 100
[OK] projection test_ee_bg: TH1D  test_ee_bg
  proj integral = 5.11e+05

In [16]:
test_scale_ee = scale_bg_to_sideband(test_ee_fg, test_ee_bg, 0.15, 0.75)
print(test_scale_ee)

[OK] integral source 0.15_0.75: TH1D  test_ee_fg
[OK] integral source 0.15_0.75: TH1D  test_ee_bg
sideband [0.15, 0.75]: FG=43, BG=3.72e+05
  scale = 0.00011545
0.00011544956867504168

In [17]:
def get_ee_yield(h_fg_2d, h_bg_2d, pt_min, pt_max, cfg):
    h_fg = project_mass_in_pt(
        h_fg_2d,
        pt_min,
        pt_max,
        f"h_ee_fg_{cfg}_pt{pt_min:g}_{pt_max:g}"
    )

    h_bg = project_mass_in_pt(
        h_bg_2d,
        pt_min,
        pt_max,
        f"h_ee_bg_{cfg}_pt{pt_min:g}_{pt_max:g}"
    )

    if h_fg is None or h_bg is None:
        print("get_ee_yield: missing projection")
        return None

    scale = scale_bg_to_sideband(
        h_fg,
        h_bg,
        windows["ee_norm"][0],
        windows["ee_norm"][1]
    )

    h_bg_scaled = clone_hist(
        h_bg,
        f"h_ee_bg_scaled_{cfg}_pt{pt_min:g}_{pt_max:g}"
    )
    h_bg_scaled.Scale(scale)

    h_sub = clone_hist(
        h_fg,
        f"h_ee_sub_{cfg}_pt{pt_min:g}_{pt_max:g}"
    )
    h_sub.Add(h_bg_scaled, -1.0)

    y_fg, e_fg = integral_range(h_fg, *windows["ee_signal"])
    y_bg, e_bg = integral_range(h_bg_scaled, *windows["ee_signal"])
    y_sub, e_sub = integral_range(h_sub, *windows["ee_signal"])

    print("EE yield:")
    print(f"  FG signal = {y_fg:.3g}")
    print(f"  BG signal = {y_bg:.3g}")
    print(f"  SUB       = {y_sub:.3g} +/- {e_sub:.3g}")

    return {
        "h_fg": h_fg,
        "h_bg": h_bg_scaled,
        "h_sub": h_sub,
        "scale": scale,
        "yield": y_sub,
        "yield_err": e_sub,
        "fg_int": y_fg,
        "bg_int": y_bg,
    }

In [18]:
ee_info_test = get_ee_yield(
    hists[0]["fg2d_eemass_reco"]["nominal"][0],
    hists[0]["bg2d_eemass_reco"]["nominal"][0],
    2.0,
    10.0,
    "nominal"
)

ee_info_test["yield"]

[OK] project source h_ee_fg_nominal_pt2_10: TH2F  fg2d_eemass_reco_nominal_icent0_file0
project_mass_in_pt: h_ee_fg_nominal_pt2_10
  pt range = [2.0, 10.0)
  y bins   = 21 to 100
[OK] projection h_ee_fg_nominal_pt2_10: TH1D  h_ee_fg_nominal_pt2_10
  proj integral = 9.36e+03
[OK] project source h_ee_bg_nominal_pt2_10: TH2F  bg2d_eemass_reco_nominal_icent0_file0
project_mass_in_pt: h_ee_bg_nominal_pt2_10
  pt range = [2.0, 10.0)
  y bins   = 21 to 100
[OK] projection h_ee_bg_nominal_pt2_10: TH1D  h_ee_bg_nominal_pt2_10
  proj integral = 5.11e+05
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt2_10
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt2_10
sideband [0.2, 0.75]: FG=2, BG=3.52e+05
  scale = 5.68145e-06
[OK] clone source h_ee_bg_scaled_nominal_pt2_10: TH1D  h_ee_bg_nominal_pt2_10
[OK] clone result h_ee_bg_scaled_nominal_pt2_10: TH1D  h_ee_bg_scaled_nominal_pt2_10
[OK] clone source h_ee_sub_nominal_pt2_10: TH1D  h_ee_fg_nominal_pt2_10
[OK] clone result h_ee_sub_nominal_pt2_10: TH1D  h_ee_sub_nominal_pt2_10
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt2_10
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt2_10
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt2_10
EE yield:
  FG signal = 9.19e+03
  BG signal = 0.127
  SUB       = 9.19e+03 +/- 95.9

9193.87271286251

In [19]:
c = root.TCanvas("c_ee_test", "c_ee_test", 800, 600)
ee_info_test["h_fg"].GetXaxis().SetRangeUser(0, 0.3)
ee_info_test["h_fg"].SetLineColor(root.kBlue)
ee_info_test["h_fg"].SetMarkerColor(root.kBlue)
ee_info_test["h_fg"].Draw("E")
ee_info_test["h_bg"].SetLineColor(root.kRed)
ee_info_test["h_bg"].SetMarkerColor(root.kRed)
ee_info_test["h_bg"].Draw("same E")
c.Draw()

In [20]:
def get_eeg_subtracted_hist_no_fit(h_fg_2d, h_bg_2d, pt_min, pt_max, cfg):
    h_fg = project_mass_in_pt(
        h_fg_2d,
        pt_min,
        pt_max,
        f"h_eeg_fg_{cfg}_pt{pt_min:g}_{pt_max:g}"
    )

    h_bg = project_mass_in_pt(
        h_bg_2d,
        pt_min,
        pt_max,
        f"h_eeg_bg_{cfg}_pt{pt_min:g}_{pt_max:g}"
    )

    if h_fg is None or h_bg is None:
        print("get_eeg_subtracted_hist_no_fit: missing projection")
        return None

    scale = scale_bg_to_sideband(
        h_fg,
        h_bg,
        windows["eeg_norm"][0],
        windows["eeg_norm"][1]
    )

    h_bg_scaled = clone_hist(
        h_bg,
        f"h_eeg_bg_scaled_{cfg}_pt{pt_min:g}_{pt_max:g}"
    )
    h_bg_scaled.Scale(scale)

    h_sub = clone_hist(
        h_fg,
        f"h_eeg_sub_{cfg}_pt{pt_min:g}_{pt_max:g}"
    )
    h_sub.Add(h_bg_scaled, -1.0)

    y_raw, e_raw = integral_range(h_sub, *windows["eeg_signal"])

    print("EEG after mixed-BG subtraction, before fit:")
    print(f"  raw signal window = {y_raw:.3g} +/- {e_raw:.3g}")

    return {
        "h_fg": h_fg,
        "h_bg": h_bg_scaled,
        "h_sub": h_sub,
        "scale": scale,
        "raw_yield": y_raw,
        "raw_yield_err": e_raw,
    }

In [21]:
eeg_sub_test = get_eeg_subtracted_hist_no_fit(
    hists[0]["fg2d_eegmass_reco"]["nominal"][0],
    hists[0]["bg2d_eegmass_reco"]["nominal"][0],
    2.0,
    10.0,
    "nominal"
)

[OK] project source h_eeg_fg_nominal_pt2_10: TH2F  fg2d_eegmass_reco_nominal_icent0_file0
project_mass_in_pt: h_eeg_fg_nominal_pt2_10
  pt range = [2.0, 10.0)
  y bins   = 21 to 100
[OK] projection h_eeg_fg_nominal_pt2_10: TH1D  h_eeg_fg_nominal_pt2_10
  proj integral = 7.71e+03
[OK] project source h_eeg_bg_nominal_pt2_10: TH2F  bg2d_eegmass_reco_nominal_icent0_file0
project_mass_in_pt: h_eeg_bg_nominal_pt2_10
  pt range = [2.0, 10.0)
  y bins   = 21 to 100
[OK] projection h_eeg_bg_nominal_pt2_10: TH1D  h_eeg_bg_nominal_pt2_10
  proj integral = 4.6e+04
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt2_10
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt2_10
sideband [0.2, 0.8]: FG=3.81e+03, BG=3.48e+04
  scale = 0.109441
[OK] clone source h_eeg_bg_scaled_nominal_pt2_10: TH1D  h_eeg_bg_nominal_pt2_10
[OK] clone result h_eeg_bg_scaled_nominal_pt2_10: TH1D  h_eeg_bg_scaled_nominal_pt2_10
[OK] clone source h_eeg_sub_nominal_pt2_10: TH1D  h_eeg_fg_nominal_pt2_10
[OK] clone result h_eeg_sub_nominal_pt2_10: TH1D  h_eeg_sub_nominal_pt2_10
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt2_10
EEG after mixed-BG subtraction, before fit:
  raw signal window = 2.26e+03 +/- 52.1

In [22]:
c = root.TCanvas("c_eeg_sub_test", "c_eeg_sub_test", 800, 600)
eeg_sub_test["h_sub"].GetXaxis().SetRangeUser(0, 0.3)
eeg_sub_test["h_sub"].SetLineColor(root.kBlue)
eeg_sub_test["h_sub"].SetMarkerColor(root.kBlue)
eeg_sub_test["h_sub"].Draw("E")
c.Draw()

In [23]:
def safe_root_name(s):
    s = str(s)
    for ch in [".", "-", "+", " ", "/", "[", "]", "(", ")", ","]:
        s = s.replace(ch, "_")
    return s


def fit_one_eeg_hist_test(h_sub, name="test_fit"):
    if not check_hist(h_sub, f"{name} input"):
        return None

    if h_sub.Integral() <= 0:
        print(f"[BAD] {name}: histogram integral <= 0, skip fit")
        return None

    tag = safe_root_name(f"{name}_{len(ROOT_KEEPALIVE)}")

    amp0 = max(h_sub.GetMaximum(), 1.0)
    mean0 = 0.135
    sigma0 = 0.018

    f = root.TF1(f"f_{tag}", "gaus(0)+pol2(3)", 0.05, 0.78)

    if not check_obj(f, f"TF1 f_{tag}"):
        return None

    root.SetOwnership(f, False)
    keep(f)

    f.SetParameters(amp0, mean0, sigma0, 0.0, 0.0, 0.0)
    f.SetParLimits(1, 0.10, 0.17)
    f.SetParLimits(2, 0.006, 0.050)

    print("Before fit:")
    print("  amp0 =", amp0)
    print("  mean0 =", mean0)
    print("  sigma0 =", sigma0)

    res = h_sub.Fit(f, "RQS0")

    print("After fit:")

    if not check_obj(f, f"TF1 after fit {tag}"):
        print("[BAD] Fit killed TF1 pointer")
        return None

    status = int(res.Status()) if res else -999

    print("  status =", status)
    print("  mean =", f.GetParameter(1))
    print("  sigma =", f.GetParameter(2))
    print("  chi2/ndf =", f.GetChisquare(), "/", f.GetNDF())

    return f

In [24]:
f_test = fit_one_eeg_hist_test(eeg_sub_test["h_sub"], "eeg_nominal_pt2_10")

[OK] eeg_nominal_pt2_10 input: TH1D  h_eeg_sub_nominal_pt2_10
     entries = 866
     integral = 2.9e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_nominal_pt2_10_10: TF1  f_eeg_nominal_pt2_10_10
Before fit:
  amp0 = 195.94641420526375
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_nominal_pt2_10_10: TF1  f_eeg_nominal_pt2_10_10
  status = 0
  mean = 0.1320908763756684
  sigma = 0.011859370964690447
  chi2/ndf = 129.7066866589777 / 94

In [25]:
c = root.TCanvas("c_fit_test", "c_fit_test", 800, 600)
eeg_sub_test["h_sub"].GetXaxis().SetRangeUser(0, 0.3)
eeg_sub_test["h_sub"].Draw("E")
f_test.SetLineColor(root.kRed)
f_test.Draw("same")
c.Draw()

In [26]:
def pol2_subtracted_yield(h, f, xmin, xmax):
    if not check_hist(h, "pol2 yield hist"):
        return 0.0, 0.0, 0.0, 0.0

    if f is None or not check_obj(f, "pol2 yield fit"):
        print("[WARNING] No valid fit. Return raw integral without pol2 subtraction.")
        raw, raw_err = integral_range(h, xmin, xmax)
        return raw, raw_err, raw, 0.0

    pol2 = root.TF1(f"pol2_from_{safe_root_name(f.GetName())}_{len(ROOT_KEEPALIVE)}", "pol2", 0.05, 0.78)
    root.SetOwnership(pol2, False)
    keep(pol2)

    pol2.SetParameters(f.GetParameter(3), f.GetParameter(4), f.GetParameter(5))

    b1 = h.FindBin(xmin + 1e-3)
    b2 = h.FindBin(xmax - 1e-3)

    raw = 0.0
    bg = 0.0
    sig = 0.0
    err2 = 0.0

    for ib in range(b1, b2 + 1):
        x = h.GetBinCenter(ib)
        y = h.GetBinContent(ib)
        b = pol2.Eval(x)

        raw += y
        bg += b
        sig += y - b
        err2 += h.GetBinError(ib)**2

    err = math.sqrt(err2)

    print("pol2-subtracted yield:")
    print(f"  raw = {raw:.3g}")
    print(f"  pol2 = {bg:.3g}")
    print(f"  signal = {sig:.3g} +/- {err:.3g}")

    return sig, err, raw, bg

In [27]:
y_eeg, e_eeg, raw_eeg, pol2_eeg = pol2_subtracted_yield(
    eeg_sub_test["h_sub"],
    f_test,
    0.09,
    0.20
)

[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt2_10
     entries = 866
     integral = 2.9e+03
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_nominal_pt2_10_10
pol2-subtracted yield:
  raw = 2.26e+03
  pol2 = 34.5
  signal = 2.22e+03 +/- 52.7

In [28]:
ratio_test =  ee_info_test["yield"] / y_eeg if y_eeg != 0 else 0.0
ratio_test

4.137063500092388

In [29]:
def one_bin_result(cfg, pt_min, pt_max, ifile=0, icent=0):
    print("="*70)
    print(f"one_bin_result cfg={cfg}, pt=[{pt_min},{pt_max}], file={ifile}, cent={icent}")

    ee_info = get_ee_yield(
        hists[ifile]["fg2d_eemass_reco"][cfg][icent],
        hists[ifile]["bg2d_eemass_reco"][cfg][icent],
        pt_min,
        pt_max,
        cfg
    )

    eeg_pre = get_eeg_subtracted_hist_no_fit(
        hists[ifile]["fg2d_eegmass_reco"][cfg][icent],
        hists[ifile]["bg2d_eegmass_reco"][cfg][icent],
        pt_min,
        pt_max,
        cfg
    )

    f = fit_one_eeg_hist_test(
        eeg_pre["h_sub"],
        f"eeg_{cfg}_pt{pt_min:g}_{pt_max:g}"
    )

    y_eeg, e_eeg, raw_eeg, pol2_eeg = pol2_subtracted_yield(
        eeg_pre["h_sub"],
        f,
        *windows["eeg_signal"]
    )

    ratio = ee_info["yield"] / y_eeg if y_eeg != 0 else 0.0

    print("FINAL ONE BIN")
    print(f"  Yee  = {ee_info['yield']:.6g}")
    print(f"  Yeeg = {y_eeg:.6g}")
    print(f"  ratio = {ratio:.6g}")

    return {
        "ee": ee_info,
        "eeg_pre": eeg_pre,
        "fit": f,
        "y_eeg": y_eeg,
        "e_eeg": e_eeg,
        "ratio": ratio,
    }

In [30]:
res_one = one_bin_result("nominal", 2.0, 10.0, ifile=0, icent=0)

======================================================================
one_bin_result cfg=nominal, pt=[2.0,10.0], file=0, cent=0
[OK] project source h_ee_fg_nominal_pt2_10: TH2F  fg2d_eemass_reco_nominal_icent0_file0
project_mass_in_pt: h_ee_fg_nominal_pt2_10
  pt range = [2.0, 10.0)
  y bins   = 21 to 100
[OK] projection h_ee_fg_nominal_pt2_10: TH1D  h_ee_fg_nominal_pt2_10
  proj integral = 9.36e+03
[OK] project source h_ee_bg_nominal_pt2_10: TH2F  bg2d_eemass_reco_nominal_icent0_file0
project_mass_in_pt: h_ee_bg_nominal_pt2_10
  pt range = [2.0, 10.0)
  y bins   = 21 to 100
[OK] projection h_ee_bg_nominal_pt2_10: TH1D  h_ee_bg_nominal_pt2_10
  proj integral = 5.11e+05
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt2_10
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt2_10
sideband [0.2, 0.75]: FG=2, BG=3.52e+05
  scale = 5.68145e-06
[OK] clone source h_ee_bg_scaled_nominal_pt2_10: TH1D  h_ee_bg_nominal_pt2_10
[OK] clone result h_ee_bg_scaled_nominal_pt2_10: TH1D  h_ee_bg_scaled_nominal_pt2_10
[OK] clone source h_ee_sub_nominal_pt2_10: TH1D  h_ee_fg_nominal_pt2_10
[OK] clone result h_ee_sub_nominal_pt2_10: TH1D  h_ee_sub_nominal_pt2_10
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt2_10
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt2_10
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt2_10
EE yield:
  FG signal = 9.19e+03
  BG signal = 0.127
  SUB       = 9.19e+03 +/- 95.9
[OK] project source h_eeg_fg_nominal_pt2_10: TH2F  fg2d_eegmass_reco_nominal_icent0_file0
project_mass_in_pt: h_eeg_fg_nominal_pt2_10
  pt range = [2.0, 10.0)
  y bins   = 21 to 100
[OK] projection h_eeg_fg_nominal_pt2_10: TH1D  h_eeg_fg_nominal_pt2_10
  proj integral = 7.71e+03
[OK] project source h_eeg_bg_nominal_pt2_10: TH2F  bg2d_eegmass_reco_nominal_icent0_file0
project_mass_in_pt: h_eeg_bg_nominal_pt2_10
  pt range = [2.0, 10.0)
  y bins   = 21 to 100
[OK] projection h_eeg_bg_nominal_pt2_10: TH1D  h_eeg_bg_nominal_pt2_10
  proj integral = 4.6e+04
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt2_10
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt2_10
sideband [0.2, 0.8]: FG=3.81e+03, BG=3.48e+04
  scale = 0.109441
[OK] clone source h_eeg_bg_scaled_nominal_pt2_10: TH1D  h_eeg_bg_nominal_pt2_10
[OK] clone result h_eeg_bg_scaled_nominal_pt2_10: TH1D  h_eeg_bg_scaled_nominal_pt2_10
[OK] clone source h_eeg_sub_nominal_pt2_10: TH1D  h_eeg_fg_nominal_pt2_10
[OK] clone result h_eeg_sub_nominal_pt2_10: TH1D  h_eeg_sub_nominal_pt2_10
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt2_10
EEG after mixed-BG subtraction, before fit:
  raw signal window = 2.26e+03 +/- 52.1
[OK] eeg_nominal_pt2_10 input: TH1D  h_eeg_sub_nominal_pt2_10
     entries = 866
     integral = 2.67e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_nominal_pt2_10_20: TF1  f_eeg_nominal_pt2_10_20
Before fit:
  amp0 = 195.94641420526375
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_nominal_pt2_10_20: TF1  f_eeg_nominal_pt2_10_20
  status = 0
  mean = 0.13204484868724686
  sigma = 0.011853909435179163
  chi2/ndf = 400.87660189534853 / 286
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt2_10
     entries = 866
     integral = 2.67e+03
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_nominal_pt2_10_20
pol2-subtracted yield:
  raw = 2.26e+03
  pol2 = 40.2
  signal = 2.22e+03 +/- 52.1
FINAL ONE BIN
  Yee  = 9193.87
  Yeeg = 2217.09
  ratio = 4.14683

In [31]:
res_one_low = one_bin_result("nominal", 1.2, 2.0, ifile=0, icent=0)

======================================================================
one_bin_result cfg=nominal, pt=[1.2,2.0], file=0, cent=0
[OK] project source h_ee_fg_nominal_pt1.2_2: TH2F  fg2d_eemass_reco_nominal_icent0_file0
project_mass_in_pt: h_ee_fg_nominal_pt1.2_2
  pt range = [1.2, 2.0)
  y bins   = 13 to 20
[OK] projection h_ee_fg_nominal_pt1.2_2: TH1D  h_ee_fg_nominal_pt1.2_2
  proj integral = 3.82e+04
[OK] project source h_ee_bg_nominal_pt1.2_2: TH2F  bg2d_eemass_reco_nominal_icent0_file0
project_mass_in_pt: h_ee_bg_nominal_pt1.2_2
  pt range = [1.2, 2.0)
  y bins   = 13 to 20
[OK] projection h_ee_bg_nominal_pt1.2_2: TH1D  h_ee_bg_nominal_pt1.2_2
  proj integral = 5.87e+06
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt1.2_2
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt1.2_2
sideband [0.2, 0.75]: FG=0, BG=4.25e+06
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt1.2_2: TH1D  h_ee_bg_nominal_pt1.2_2
[OK] clone result h_ee_bg_scaled_nominal_pt1.2_2: TH1D  h_ee_bg_scaled_nominal_pt1.2_2
[OK] clone source h_ee_sub_nominal_pt1.2_2: TH1D  h_ee_fg_nominal_pt1.2_2
[OK] clone result h_ee_sub_nominal_pt1.2_2: TH1D  h_ee_sub_nominal_pt1.2_2
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt1.2_2
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt1.2_2
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt1.2_2
EE yield:
  FG signal = 3.79e+04
  BG signal = 0
  SUB       = 3.79e+04 +/- 195
[OK] project source h_eeg_fg_nominal_pt1.2_2: TH2F  fg2d_eegmass_reco_nominal_icent0_file0
project_mass_in_pt: h_eeg_fg_nominal_pt1.2_2
  pt range = [1.2, 2.0)
  y bins   = 13 to 20
[OK] projection h_eeg_fg_nominal_pt1.2_2: TH1D  h_eeg_fg_nominal_pt1.2_2
  proj integral = 2.61e+04
[OK] project source h_eeg_bg_nominal_pt1.2_2: TH2F  bg2d_eegmass_reco_nominal_icent0_file0
project_mass_in_pt: h_eeg_bg_nominal_pt1.2_2
  pt range = [1.2, 2.0)
  y bins   = 13 to 20
[OK] projection h_eeg_bg_nominal_pt1.2_2: TH1D  h_eeg_bg_nominal_pt1.2_2
  proj integral = 2.2e+05
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt1.2_2
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt1.2_2
sideband [0.2, 0.8]: FG=1.35e+04, BG=1.71e+05
  scale = 0.0790351
[OK] clone source h_eeg_bg_scaled_nominal_pt1.2_2: TH1D  h_eeg_bg_nominal_pt1.2_2
[OK] clone result h_eeg_bg_scaled_nominal_pt1.2_2: TH1D  h_eeg_bg_scaled_nominal_pt1.2_2
[OK] clone source h_eeg_sub_nominal_pt1.2_2: TH1D  h_eeg_fg_nominal_pt1.2_2
[OK] clone result h_eeg_sub_nominal_pt1.2_2: TH1D  h_eeg_sub_nominal_pt1.2_2
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt1.2_2
EEG after mixed-BG subtraction, before fit:
  raw signal window = 7.49e+03 +/- 98.3
[OK] eeg_nominal_pt1.2_2 input: TH1D  h_eeg_sub_nominal_pt1.2_2
     entries = 2.76e+03
     integral = 8.71e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_nominal_pt1_2_2_30: TF1  f_eeg_nominal_pt1_2_2_30
Before fit:
  amp0 = 659.8368034830238
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_nominal_pt1_2_2_30: TF1  f_eeg_nominal_pt1_2_2_30
  status = 0
  mean = 0.13153672330540594
  sigma = 0.011108694126445242
  chi2/ndf = 371.2370374336162 / 286
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt1.2_2
     entries = 2.76e+03
     integral = 8.71e+03
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_nominal_pt1_2_2_30
pol2-subtracted yield:
  raw = 7.49e+03
  pol2 = 316
  signal = 7.17e+03 +/- 98.3
FINAL ONE BIN
  Yee  = 37910
  Yeeg = 7173.74
  ratio = 5.28455

In [32]:
def sum_hists_list(hist_list, name):
    hsum = None

    for h in hist_list:
        if h is None:
            continue

        if hsum is None:
            hsum = clone_hist(h, name)
            hsum.Reset("ICESM")

        hsum.Add(h)

    if hsum is None:
        print(f"[BAD] sum_hists_list: could not build {name}")
        return None

    print(f"[OK] built {name}: integral={hsum.Integral():.6g}")
    return hsum


def build_mb_one_file(hists, ifile, kind, cfg):
    hs = []
    for icent in cent_bins:
        h = hists[ifile][kind][cfg][icent]
        hs.append(h)

    return sum_hists_list(hs, f"mb_file{ifile}_{kind}_{cfg}")


def build_mb_all_files(hists, kind, cfg):
    hs = []

    for ifile in sorted(hists.keys()):
        if not isinstance(ifile, int):
            continue

        h_mb_file = build_mb_one_file(hists, ifile, kind, cfg)
        if h_mb_file is not None:
            hs.append(h_mb_file)

    return sum_hists_list(hs, f"mb_all_{kind}_{cfg}")


def build_mb_set(hists, cfg):
    mb = {}

    mb["fg_ee"] = build_mb_all_files(hists, "fg2d_eemass_reco", cfg)
    mb["bg_ee"] = build_mb_all_files(hists, "bg2d_eemass_reco", cfg)
    mb["fg_eeg"] = build_mb_all_files(hists, "fg2d_eegmass_reco", cfg)
    mb["bg_eeg"] = build_mb_all_files(hists, "bg2d_eegmass_reco", cfg)

    return mb

In [33]:
mb_nominal = build_mb_set(hists, "nominal")

check_hist(mb_nominal["fg_ee"], "MB fg ee nominal")
check_hist(mb_nominal["bg_ee"], "MB bg ee nominal")
check_hist(mb_nominal["fg_eeg"], "MB fg eeg nominal")
check_hist(mb_nominal["bg_eeg"], "MB bg eeg nominal")

[OK] clone source mb_file0_fg2d_eemass_reco_nominal: TH2F  fg2d_eemass_reco_nominal_icent0_file0
[OK] clone result mb_file0_fg2d_eemass_reco_nominal: TH2F  mb_file0_fg2d_eemass_reco_nominal
[OK] built mb_file0_fg2d_eemass_reco_nominal: integral=103637
[OK] clone source mb_all_fg2d_eemass_reco_nominal: TH2F  mb_file0_fg2d_eemass_reco_nominal
[OK] clone result mb_all_fg2d_eemass_reco_nominal: TH2F  mb_all_fg2d_eemass_reco_nominal
[OK] built mb_all_fg2d_eemass_reco_nominal: integral=103637
[OK] clone source mb_file0_bg2d_eemass_reco_nominal: TH2F  bg2d_eemass_reco_nominal_icent0_file0
[OK] clone result mb_file0_bg2d_eemass_reco_nominal: TH2F  mb_file0_bg2d_eemass_reco_nominal
[OK] built mb_file0_bg2d_eemass_reco_nominal: integral=1.01459e+08
[OK] clone source mb_all_bg2d_eemass_reco_nominal: TH2F  mb_file0_bg2d_eemass_reco_nominal
[OK] clone result mb_all_bg2d_eemass_reco_nominal: TH2F  mb_all_bg2d_eemass_reco_nominal
[OK] built mb_all_bg2d_eemass_reco_nominal: integral=1.01459e+08
[OK] clone source mb_file0_fg2d_eegmass_reco_nominal: TH2F  fg2d_eegmass_reco_nominal_icent0_file0
[OK] clone result mb_file0_fg2d_eegmass_reco_nominal: TH2F  mb_file0_fg2d_eegmass_reco_nominal
[OK] built mb_file0_fg2d_eegmass_reco_nominal: integral=69008
[OK] clone source mb_all_fg2d_eegmass_reco_nominal: TH2F  mb_file0_fg2d_eegmass_reco_nominal
[OK] clone result mb_all_fg2d_eegmass_reco_nominal: TH2F  mb_all_fg2d_eegmass_reco_nominal
[OK] built mb_all_fg2d_eegmass_reco_nominal: integral=69008
[OK] clone source mb_file0_bg2d_eegmass_reco_nominal: TH2F  bg2d_eegmass_reco_nominal_icent0_file0
[OK] clone result mb_file0_bg2d_eegmass_reco_nominal: TH2F  mb_file0_bg2d_eegmass_reco_nominal
[OK] built mb_file0_bg2d_eegmass_reco_nominal: integral=637647
[OK] clone source mb_all_bg2d_eegmass_reco_nominal: TH2F  mb_file0_bg2d_eegmass_reco_nominal
[OK] clone result mb_all_bg2d_eegmass_reco_nominal: TH2F  mb_all_bg2d_eegmass_reco_nominal
[OK] built mb_all_bg2d_eegmass_reco_nominal: integral=637647
[OK] MB fg ee nominal: TH2F  mb_all_fg2d_eemass_reco_nominal
     entries = 1.04e+05
     integral = 1.04e+05
     nbinsX = 400, nbinsY = 100
[OK] MB bg ee nominal: TH2F  mb_all_bg2d_eemass_reco_nominal
     entries = 1.02e+08
     integral = 1.01e+08
     nbinsX = 400, nbinsY = 100
[OK] MB fg eeg nominal: TH2F  mb_all_fg2d_eegmass_reco_nominal
     entries = 1.09e+05
     integral = 6.9e+04
     nbinsX = 400, nbinsY = 100
[OK] MB bg eeg nominal: TH2F  mb_all_bg2d_eegmass_reco_nominal
     entries = 1.24e+06
     integral = 6.38e+05
     nbinsX = 400, nbinsY = 100

True

In [34]:
pt_min = 2.0
pt_max = 10.0

mb_ee_fg_test = project_mass_in_pt(mb_nominal["fg_ee"], pt_min, pt_max, "mb_ee_fg_test")
mb_ee_bg_test = project_mass_in_pt(mb_nominal["bg_ee"], pt_min, pt_max, "mb_ee_bg_test")

mb_eeg_fg_test = project_mass_in_pt(mb_nominal["fg_eeg"], pt_min, pt_max, "mb_eeg_fg_test")
mb_eeg_bg_test = project_mass_in_pt(mb_nominal["bg_eeg"], pt_min, pt_max, "mb_eeg_bg_test")

[OK] project source mb_ee_fg_test: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: mb_ee_fg_test
  pt range = [2.0, 10.0)
  y bins   = 21 to 100
[OK] projection mb_ee_fg_test: TH1D  mb_ee_fg_test
  proj integral = 9.36e+03
[OK] project source mb_ee_bg_test: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: mb_ee_bg_test
  pt range = [2.0, 10.0)
  y bins   = 21 to 100
[OK] projection mb_ee_bg_test: TH1D  mb_ee_bg_test
  proj integral = 5.11e+05
[OK] project source mb_eeg_fg_test: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: mb_eeg_fg_test
  pt range = [2.0, 10.0)
  y bins   = 21 to 100
[OK] projection mb_eeg_fg_test: TH1D  mb_eeg_fg_test
  proj integral = 7.71e+03
[OK] project source mb_eeg_bg_test: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: mb_eeg_bg_test
  pt range = [2.0, 10.0)
  y bins   = 21 to 100
[OK] projection mb_eeg_bg_test: TH1D  mb_eeg_bg_test
  proj integral = 4.6e+04

In [35]:
c_mb_test = root.TCanvas("c_mb_test", "c_mb_test", 1200, 600)
c_mb_test.Divide(2, 1)

c_mb_test.cd(1)
mb_ee_fg_test.GetXaxis().SetRangeUser(0, 0.3)
mb_ee_fg_test.SetMarkerColor(root.kBlue)
mb_ee_fg_test.SetLineColor(root.kBlue)
mb_ee_fg_test.Draw("E")

ee_scale_mb = scale_bg_to_sideband(mb_ee_fg_test, mb_ee_bg_test, 0.15, 0.75)
mb_ee_bg_draw = clone_hist(mb_ee_bg_test, "mb_ee_bg_draw")
mb_ee_bg_draw.Scale(ee_scale_mb)
mb_ee_bg_draw.SetMarkerColor(root.kRed)
mb_ee_bg_draw.SetLineColor(root.kRed)
mb_ee_bg_draw.Draw("same E")

c_mb_test.cd(2)
mb_eeg_fg_test.GetXaxis().SetRangeUser(0, 0.3)
mb_eeg_fg_test.SetMarkerColor(root.kBlue)
mb_eeg_fg_test.SetLineColor(root.kBlue)
mb_eeg_fg_test.Draw("E")

eeg_scale_mb = scale_bg_to_sideband(mb_eeg_fg_test, mb_eeg_bg_test, 0.30, 0.80)
mb_eeg_bg_draw = clone_hist(mb_eeg_bg_test, "mb_eeg_bg_draw")
mb_eeg_bg_draw.Scale(eeg_scale_mb)
mb_eeg_bg_draw.SetMarkerColor(root.kRed)
mb_eeg_bg_draw.SetLineColor(root.kRed)
mb_eeg_bg_draw.Draw("same E")

c_mb_test.Draw()

[OK] integral source 0.15_0.75: TH1D  mb_ee_fg_test
[OK] integral source 0.15_0.75: TH1D  mb_ee_bg_test
sideband [0.15, 0.75]: FG=43, BG=3.72e+05
  scale = 0.00011545
[OK] clone source mb_ee_bg_draw: TH1D  mb_ee_bg_test
[OK] clone result mb_ee_bg_draw: TH1D  mb_ee_bg_draw
[OK] integral source 0.3_0.8: TH1D  mb_eeg_fg_test
[OK] integral source 0.3_0.8: TH1D  mb_eeg_bg_test
sideband [0.3, 0.8]: FG=3.16e+03, BG=2.91e+04
  scale = 0.108679
[OK] clone source mb_eeg_bg_draw: TH1D  mb_eeg_bg_test
[OK] clone result mb_eeg_bg_draw: TH1D  mb_eeg_bg_draw

In [36]:
def one_bin_result_mb(cfg, mb, pt_min, pt_max):
    print("="*80)
    print(f"one_bin_result_mb cfg={cfg}, pt=[{pt_min},{pt_max}]")

    ee_info = get_ee_yield(
        mb["fg_ee"],
        mb["bg_ee"],
        pt_min,
        pt_max,
        cfg
    )

    eeg_pre = get_eeg_subtracted_hist_no_fit(
        mb["fg_eeg"],
        mb["bg_eeg"],
        pt_min,
        pt_max,
        cfg
    )

    f = fit_one_eeg_hist_test(
        eeg_pre["h_sub"],
        f"eeg_mb_{cfg}_pt{pt_min:g}_{pt_max:g}"
    )

    y_eeg, e_eeg, raw_eeg, pol2_eeg = pol2_subtracted_yield(
        eeg_pre["h_sub"],
        f,
        *windows["eeg_signal"]
    )

    y_ee = ee_info["yield"]
    e_ee = ee_info["yield_err"]

    eeg_over_ee = y_eeg / y_ee if y_ee != 0 else float("nan")
    ee_over_eeg = y_ee / y_eeg if y_eeg != 0 else float("nan")

    print("FINAL MB ONE BIN")
    print(f"  Yee        = {y_ee:.6g} +/- {e_ee:.6g}")
    print(f"  Yeeg       = {y_eeg:.6g} +/- {e_eeg:.6g}")
    print(f"  eeg / ee   = {eeg_over_ee:.6g}")
    print(f"  ee / eeg   = {ee_over_eeg:.6g}")

    return {
        "cfg": cfg,
        "pt_min": pt_min,
        "pt_max": pt_max,
        "ee": ee_info,
        "eeg_pre": eeg_pre,
        "fit": f,
        "y_ee": y_ee,
        "e_ee": e_ee,
        "y_eeg": y_eeg,
        "e_eeg": e_eeg,
        "raw_eeg": raw_eeg,
        "pol2_eeg": pol2_eeg,
        "eeg_over_ee": eeg_over_ee,
        "ee_over_eeg": ee_over_eeg,
    }

In [37]:
res_mb_one = one_bin_result_mb("nominal", mb_nominal, 1.5, 2.0)

================================================================================
one_bin_result_mb cfg=nominal, pt=[1.5,2.0]
[OK] project source h_ee_fg_nominal_pt1.5_2: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt1.5_2
  pt range = [1.5, 2.0)
  y bins   = 16 to 20
[OK] projection h_ee_fg_nominal_pt1.5_2: TH1D  h_ee_fg_nominal_pt1.5_2
  proj integral = 1.66e+04
[OK] project source h_ee_bg_nominal_pt1.5_2: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt1.5_2
  pt range = [1.5, 2.0)
  y bins   = 16 to 20
[OK] projection h_ee_bg_nominal_pt1.5_2: TH1D  h_ee_bg_nominal_pt1.5_2
  proj integral = 1.86e+06
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt1.5_2
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt1.5_2
sideband [0.2, 0.75]: FG=0, BG=1.34e+06
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt1.5_2: TH1D  h_ee_bg_nominal_pt1.5_2
[OK] clone result h_ee_bg_scaled_nominal_pt1.5_2: TH1D  h_ee_bg_scaled_nominal_pt1.5_2
[OK] clone source h_ee_sub_nominal_pt1.5_2: TH1D  h_ee_fg_nominal_pt1.5_2
[OK] clone result h_ee_sub_nominal_pt1.5_2: TH1D  h_ee_sub_nominal_pt1.5_2
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt1.5_2
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt1.5_2
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt1.5_2
EE yield:
  FG signal = 1.65e+04
  BG signal = 0
  SUB       = 1.65e+04 +/- 128
[OK] project source h_eeg_fg_nominal_pt1.5_2: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt1.5_2
  pt range = [1.5, 2.0)
  y bins   = 16 to 20
[OK] projection h_eeg_fg_nominal_pt1.5_2: TH1D  h_eeg_fg_nominal_pt1.5_2
  proj integral = 1.18e+04
[OK] project source h_eeg_bg_nominal_pt1.5_2: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_bg_nominal_pt1.5_2
  pt range = [1.5, 2.0)
  y bins   = 16 to 20
[OK] projection h_eeg_bg_nominal_pt1.5_2: TH1D  h_eeg_bg_nominal_pt1.5_2
  proj integral = 9.42e+04
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt1.5_2
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt1.5_2
sideband [0.2, 0.8]: FG=6.06e+03, BG=7.32e+04
  scale = 0.0828156
[OK] clone source h_eeg_bg_scaled_nominal_pt1.5_2: TH1D  h_eeg_bg_nominal_pt1.5_2
[OK] clone result h_eeg_bg_scaled_nominal_pt1.5_2: TH1D  h_eeg_bg_scaled_nominal_pt1.5_2
[OK] clone source h_eeg_sub_nominal_pt1.5_2: TH1D  h_eeg_fg_nominal_pt1.5_2
[OK] clone result h_eeg_sub_nominal_pt1.5_2: TH1D  h_eeg_sub_nominal_pt1.5_2
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt1.5_2
EEG after mixed-BG subtraction, before fit:
  raw signal window = 3.49e+03 +/- 66.1
[OK] eeg_mb_nominal_pt1.5_2 input: TH1D  h_eeg_sub_nominal_pt1.5_2
     entries = 1.3e+03
     integral = 4.02e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_nominal_pt1_5_2_54: TF1  f_eeg_mb_nominal_pt1_5_2_54
Before fit:
  amp0 = 312.0600805625725
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_mb_nominal_pt1_5_2_54: TF1  f_eeg_mb_nominal_pt1_5_2_54
  status = 0
  mean = 0.13139480288783664
  sigma = 0.011098119395738664
  chi2/ndf = 289.01373821305026 / 286
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt1.5_2
     entries = 1.3e+03
     integral = 4.02e+03
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_mb_nominal_pt1_5_2_54
pol2-subtracted yield:
  raw = 3.49e+03
  pol2 = 135
  signal = 3.36e+03 +/- 66.1
FINAL MB ONE BIN
  Yee        = 16479 +/- 128.371
  Yeeg       = 3359.05 +/- 66.1385
  eeg / ee   = 0.203838
  ee / eeg   = 4.90585

In [38]:
c_mb_fit = root.TCanvas("c_mb_fit", "c_mb_fit", 800, 600)
res_mb_one["eeg_pre"]["h_sub"].GetXaxis().SetRangeUser(0, 0.3)
res_mb_one["eeg_pre"]["h_sub"].Draw("E")
res_mb_one["fit"].SetLineColor(root.kRed)
res_mb_one["fit"].Draw("same")
c_mb_fit.Draw()

In [39]:
fit_out_dir = "output/fits"
os.makedirs(fit_out_dir, exist_ok=True)

def save_one_bin_canvas(res, tag):
    c = root.TCanvas(f"c_{tag}", f"c_{tag}", 1200, 600)
    c.Divide(2, 1)

    c.cd(1)
    h_ee_fg = res["ee"]["h_fg"]
    h_ee_bg = res["ee"]["h_bg"]

    h_ee_fg.GetXaxis().SetRangeUser(0, 0.3)
    h_ee_fg.SetMarkerColor(root.kBlue)
    h_ee_fg.SetLineColor(root.kBlue)
    h_ee_fg.Draw("E")

    h_ee_bg.SetMarkerColor(root.kRed)
    h_ee_bg.SetLineColor(root.kRed)
    h_ee_bg.Draw("same E")

    lat = root.TLatex()
    lat.SetNDC(True)
    lat.SetTextSize(0.035)
    lat.DrawLatex(0.50, 0.82, f"Y_ee = {res['y_ee']:.3g}")

    c.cd(2)
    h_eeg_sub = res["eeg_pre"]["h_sub"]
    fit = res["fit"]

    h_eeg_sub.GetXaxis().SetRangeUser(0, 0.3)
    h_eeg_sub.SetMarkerColor(root.kBlue)
    h_eeg_sub.SetLineColor(root.kBlue)
    h_eeg_sub.Draw("E")

    fit.SetLineColor(root.kRed)
    fit.Draw("same")

    lat.DrawLatex(0.50, 0.82, f"Y_eeg = {res['y_eeg']:.3g}")
    lat.DrawLatex(0.50, 0.77, f"eeg/ee = {res['eeg_over_ee']:.4g}")
    lat.DrawLatex(0.50, 0.72, f"ee/eeg = {res['ee_over_eeg']:.4g}")

    png = f"{fit_out_dir}/{tag}.png"
    pdf = f"{fit_out_dir}/{tag}.pdf"

    c.SaveAs(png)
    c.SaveAs(pdf)

    keep(c)
    print("saved:", png)
    return c

In [40]:
c_saved_test = save_one_bin_canvas(res_mb_one, "test_nominal_mb_pt2_10")
c_saved_test.Draw()

saved: output/fits/test_nominal_mb_pt2_10.png

In [41]:
import pandas as pd

def run_pt_bins_for_config(cfg, mb, save_canvases=False):
    rows = []
    results = {}

    for ipt in range(len(pt_bins) - 1):
        pt_min = pt_bins[ipt]
        pt_max = pt_bins[ipt + 1]

        print("\n")
        print("#"*80)
        print(f"Running {cfg}: pT [{pt_min}, {pt_max})")

        res = one_bin_result_mb(cfg, mb, pt_min, pt_max)
        results[(pt_min, pt_max)] = res

        if save_canvases:
            tag = f"{cfg}_mb_pt{str(pt_min).replace('.','p')}_{str(pt_max).replace('.','p')}"
            save_one_bin_canvas(res, tag)

        row = {
            "config": cfg,
            "pt_min": pt_min,
            "pt_max": pt_max,
            "pt_center": 0.5 * (pt_min + pt_max),

            "y_ee": res["y_ee"],
            "e_ee": res["e_ee"],
            "y_eeg": res["y_eeg"],
            "e_eeg": res["e_eeg"],

            "raw_eeg": res["raw_eeg"],
            "pol2_eeg": res["pol2_eeg"],

            "eeg_over_ee": res["eeg_over_ee"],
            "ee_over_eeg": res["ee_over_eeg"],

            "fit_mean": res["fit"].GetParameter(1) if res["fit"] else float("nan"),
            "fit_sigma": abs(res["fit"].GetParameter(2)) if res["fit"] else float("nan"),
            "fit_chi2": res["fit"].GetChisquare() if res["fit"] else float("nan"),
            "fit_ndf": res["fit"].GetNDF() if res["fit"] else -999,
        }

        rows.append(row)

    df = pd.DataFrame(rows)
    return df, results

In [42]:
df_nominal_mb, results_nominal_mb = run_pt_bins_for_config(
    "nominal",
    mb_nominal,
    save_canvases=False
)

df_nominal_mb

################################################################################
Running nominal: pT [0.8, 1.0)
================================================================================
one_bin_result_mb cfg=nominal, pt=[0.8,1.0]
[OK] project source h_ee_fg_nominal_pt0.8_1: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt0.8_1
  pt range = [0.8, 1.0)
  y bins   = 9 to 10
[OK] projection h_ee_fg_nominal_pt0.8_1: TH1D  h_ee_fg_nominal_pt0.8_1
  proj integral = 2.4e+04
[OK] project source h_ee_bg_nominal_pt0.8_1: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt0.8_1
  pt range = [0.8, 1.0)
  y bins   = 9 to 10
[OK] projection h_ee_bg_nominal_pt0.8_1: TH1D  h_ee_bg_nominal_pt0.8_1
  proj integral = 1.19e+07
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt0.8_1
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt0.8_1
sideband [0.2, 0.75]: FG=0, BG=9.24e+06
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt0.8_1: TH1D  h_ee_bg_nominal_pt0.8_1
[OK] clone result h_ee_bg_scaled_nominal_pt0.8_1: TH1D  h_ee_bg_scaled_nominal_pt0.8_1
[OK] clone source h_ee_sub_nominal_pt0.8_1: TH1D  h_ee_fg_nominal_pt0.8_1
[OK] clone result h_ee_sub_nominal_pt0.8_1: TH1D  h_ee_sub_nominal_pt0.8_1
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt0.8_1
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt0.8_1
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt0.8_1
EE yield:
  FG signal = 2.39e+04
  BG signal = 0
  SUB       = 2.39e+04 +/- 155
[OK] project source h_eeg_fg_nominal_pt0.8_1: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt0.8_1
  pt range = [0.8, 1.0)
  y bins   = 9 to 10
[OK] projection h_eeg_fg_nominal_pt0.8_1: TH1D  h_eeg_fg_nominal_pt0.8_1
  proj integral = 1.5e+04
[OK] project source h_eeg_bg_nominal_pt0.8_1: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_bg_nominal_pt0.8_1
  pt range = [0.8, 1.0)
  y bins   = 9 to 10
[OK] projection h_eeg_bg_nominal_pt0.8_1: TH1D  h_eeg_bg_nominal_pt0.8_1
  proj integral = 1.63e+05
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt0.8_1
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt0.8_1
sideband [0.2, 0.8]: FG=7.16e+03, BG=1.07e+05
  scale = 0.0670055
[OK] clone source h_eeg_bg_scaled_nominal_pt0.8_1: TH1D  h_eeg_bg_nominal_pt0.8_1
[OK] clone result h_eeg_bg_scaled_nominal_pt0.8_1: TH1D  h_eeg_bg_scaled_nominal_pt0.8_1
[OK] clone source h_eeg_sub_nominal_pt0.8_1: TH1D  h_eeg_fg_nominal_pt0.8_1
[OK] clone result h_eeg_sub_nominal_pt0.8_1: TH1D  h_eeg_sub_nominal_pt0.8_1
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt0.8_1
EEG after mixed-BG subtraction, before fit:
  raw signal window = 3.8e+03 +/- 74.8
[OK] eeg_mb_nominal_pt0.8_1 input: TH1D  h_eeg_sub_nominal_pt0.8_1
     entries = 1.04e+03
     integral = 4.05e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_nominal_pt0_8_1_65: TF1  f_eeg_mb_nominal_pt0_8_1_65
Before fit:
  amp0 = 345.8017914303364
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_mb_nominal_pt0_8_1_65: TF1  f_eeg_mb_nominal_pt0_8_1_65
  status = 0
  mean = 0.13179229943319914
  sigma = 0.011377562520198633
  chi2/ndf = 340.89172040738305 / 286
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt0.8_1
     entries = 1.04e+03
     integral = 4.05e+03
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_mb_nominal_pt0_8_1_65
pol2-subtracted yield:
  raw = 3.8e+03
  pol2 = 121
  signal = 3.68e+03 +/- 74.8
FINAL MB ONE BIN
  Yee        = 23925 +/- 154.677
  Yeeg       = 3681.86 +/- 74.7536
  eeg / ee   = 0.153892
  ee / eeg   = 6.49807


################################################################################
Running nominal: pT [1.0, 1.3)
================================================================================
one_bin_result_mb cfg=nominal, pt=[1.0,1.3]
[OK] project source h_ee_fg_nominal_pt1_1.3: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt1_1.3
  pt range = [1.0, 1.3)
  y bins   = 11 to 13
[OK] projection h_ee_fg_nominal_pt1_1.3: TH1D  h_ee_fg_nominal_pt1_1.3
  proj integral = 3.33e+04
[OK] project source h_ee_bg_nominal_pt1_1.3: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt1_1.3
  pt range = [1.0, 1.3)
  y bins   = 11 to 13
[OK] projection h_ee_bg_nominal_pt1_1.3: TH1D  h_ee_bg_nominal_pt1_1.3
  proj integral = 8.04e+06
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt1_1.3
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt1_1.3
sideband [0.2, 0.75]: FG=0, BG=5.89e+06
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt1_1.3: TH1D  h_ee_bg_nominal_pt1_1.3
[OK] clone result h_ee_bg_scaled_nominal_pt1_1.3: TH1D  h_ee_bg_scaled_nominal_pt1_1.3
[OK] clone source h_ee_sub_nominal_pt1_1.3: TH1D  h_ee_fg_nominal_pt1_1.3
[OK] clone result h_ee_sub_nominal_pt1_1.3: TH1D  h_ee_sub_nominal_pt1_1.3
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt1_1.3
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt1_1.3
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt1_1.3
EE yield:
  FG signal = 3.31e+04
  BG signal = 0
  SUB       = 3.31e+04 +/- 182
[OK] project source h_eeg_fg_nominal_pt1_1.3: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt1_1.3
  pt range = [1.0, 1.3)
  y bins   = 11 to 13
[OK] projection h_eeg_fg_nominal_pt1_1.3: TH1D  h_eeg_fg_nominal_pt1_1.3
  proj integral = 2.1e+04
[OK] project source h_eeg_bg_nominal_pt1_1.3: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_bg_nominal_pt1_1.3
  pt range = [1.0, 1.3)
  y bins   = 11 to 13
[OK] projection h_eeg_bg_nominal_pt1_1.3: TH1D  h_eeg_bg_nominal_pt1_1.3
  proj integral = 1.98e+05
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt1_1.3
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt1_1.3
sideband [0.2, 0.8]: FG=1.1e+04, BG=1.49e+05
  scale = 0.0735173
[OK] clone source h_eeg_bg_scaled_nominal_pt1_1.3: TH1D  h_eeg_bg_nominal_pt1_1.3
[OK] clone result h_eeg_bg_scaled_nominal_pt1_1.3: TH1D  h_eeg_bg_scaled_nominal_pt1_1.3
[OK] clone source h_eeg_sub_nominal_pt1_1.3: TH1D  h_eeg_fg_nominal_pt1_1.3
[OK] clone result h_eeg_sub_nominal_pt1_1.3: TH1D  h_eeg_sub_nominal_pt1_1.3
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt1_1.3
EEG after mixed-BG subtraction, before fit:
  raw signal window = 5.66e+03 +/- 88.6
[OK] eeg_mb_nominal_pt1_1.3 input: TH1D  h_eeg_sub_nominal_pt1_1.3
     entries = 1.87e+03
     integral = 6.42e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_nominal_pt1_1_3_75: TF1  f_eeg_mb_nominal_pt1_1_3_75
Before fit:
  amp0 = 511.0525228819526
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_mb_nominal_pt1_1_3_75: TF1  f_eeg_mb_nominal_pt1_1_3_75
  status = 0
  mean = 0.13158385987174778
  sigma = 0.010936734946311403
  chi2/ndf = 350.18637234597696 / 286
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt1_1.3
     entries = 1.87e+03
     integral = 6.42e+03
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_mb_nominal_pt1_1_3_75
pol2-subtracted yield:
  raw = 5.66e+03
  pol2 = 243
  signal = 5.42e+03 +/- 88.6
FINAL MB ONE BIN
  Yee        = 33140 +/- 182.044
  Yeeg       = 5418.14 +/- 88.5936
  eeg / ee   = 0.163493
  ee / eeg   = 6.11649


################################################################################
Running nominal: pT [1.3, 1.7)
================================================================================
one_bin_result_mb cfg=nominal, pt=[1.3,1.7]
[OK] project source h_ee_fg_nominal_pt1.3_1.7: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt1.3_1.7
  pt range = [1.3, 1.7)
  y bins   = 14 to 17
[OK] projection h_ee_fg_nominal_pt1.3_1.7: TH1D  h_ee_fg_nominal_pt1.3_1.7
  proj integral = 2.14e+04
[OK] project source h_ee_bg_nominal_pt1.3_1.7: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt1.3_1.7
  pt range = [1.3, 1.7)
  y bins   = 14 to 17
[OK] projection h_ee_bg_nominal_pt1.3_1.7: TH1D  h_ee_bg_nominal_pt1.3_1.7
  proj integral = 3.3e+06
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt1.3_1.7
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt1.3_1.7
sideband [0.2, 0.75]: FG=0, BG=2.39e+06
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt1.3_1.7: TH1D  h_ee_bg_nominal_pt1.3_1.7
[OK] clone result h_ee_bg_scaled_nominal_pt1.3_1.7: TH1D  h_ee_bg_scaled_nominal_pt1.3_1.7
[OK] clone source h_ee_sub_nominal_pt1.3_1.7: TH1D  h_ee_fg_nominal_pt1.3_1.7
[OK] clone result h_ee_sub_nominal_pt1.3_1.7: TH1D  h_ee_sub_nominal_pt1.3_1.7
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt1.3_1.7
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt1.3_1.7
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt1.3_1.7
EE yield:
  FG signal = 2.12e+04
  BG signal = 0
  SUB       = 2.12e+04 +/- 146
[OK] project source h_eeg_fg_nominal_pt1.3_1.7: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt1.3_1.7
  pt range = [1.3, 1.7)
  y bins   = 14 to 17
[OK] projection h_eeg_fg_nominal_pt1.3_1.7: TH1D  h_eeg_fg_nominal_pt1.3_1.7
  proj integral = 1.46e+04
[OK] project source h_eeg_bg_nominal_pt1.3_1.7: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_bg_nominal_pt1.3_1.7
  pt range = [1.3, 1.7)
  y bins   = 14 to 17
[OK] projection h_eeg_bg_nominal_pt1.3_1.7: TH1D  h_eeg_bg_nominal_pt1.3_1.7
  proj integral = 1.25e+05
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt1.3_1.7
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt1.3_1.7
sideband [0.2, 0.8]: FG=7.56e+03, BG=9.79e+04
  scale = 0.0771838
[OK] clone source h_eeg_bg_scaled_nominal_pt1.3_1.7: TH1D  h_eeg_bg_nominal_pt1.3_1.7
[OK] clone result h_eeg_bg_scaled_nominal_pt1.3_1.7: TH1D  h_eeg_bg_scaled_nominal_pt1.3_1.7
[OK] clone source h_eeg_sub_nominal_pt1.3_1.7: TH1D  h_eeg_fg_nominal_pt1.3_1.7
[OK] clone result h_eeg_sub_nominal_pt1.3_1.7: TH1D  h_eeg_sub_nominal_pt1.3_1.7
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt1.3_1.7
EEG after mixed-BG subtraction, before fit:
  raw signal window = 4.22e+03 +/- 73.7
[OK] eeg_mb_nominal_pt1.3_1.7 input: TH1D  h_eeg_sub_nominal_pt1.3_1.7
     entries = 1.6e+03
     integral = 4.97e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_nominal_pt1_3_1_7_85: TF1  f_eeg_mb_nominal_pt1_3_1_7_85
Before fit:
  amp0 = 374.5963572507861
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_mb_nominal_pt1_3_1_7_85: TF1  f_eeg_mb_nominal_pt1_3_1_7_85
  status = 0
  mean = 0.13163935940003035
  sigma = 0.010962831673258571
  chi2/ndf = 401.8231846174282 / 286
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt1.3_1.7
     entries = 1.6e+03
     integral = 4.97e+03
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_mb_nominal_pt1_3_1_7_85
pol2-subtracted yield:
  raw = 4.22e+03
  pol2 = 161
  signal = 4.06e+03 +/- 73.7
FINAL MB ONE BIN
  Yee        = 21209 +/- 145.633
  Yeeg       = 4061.64 +/- 73.6923
  eeg / ee   = 0.191506
  ee / eeg   = 5.22178


################################################################################
Running nominal: pT [1.7, 2.0)
================================================================================
one_bin_result_mb cfg=nominal, pt=[1.7,2.0]
[OK] project source h_ee_fg_nominal_pt1.7_2: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt1.7_2
  pt range = [1.7, 2.0)
  y bins   = 18 to 20
[OK] projection h_ee_fg_nominal_pt1.7_2: TH1D  h_ee_fg_nominal_pt1.7_2
  proj integral = 7.9e+03
[OK] project source h_ee_bg_nominal_pt1.7_2: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt1.7_2
  pt range = [1.7, 2.0)
  y bins   = 18 to 20
[OK] projection h_ee_bg_nominal_pt1.7_2: TH1D  h_ee_bg_nominal_pt1.7_2
  proj integral = 7.46e+05
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt1.7_2
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt1.7_2
sideband [0.2, 0.75]: FG=0, BG=5.35e+05
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt1.7_2: TH1D  h_ee_bg_nominal_pt1.7_2
[OK] clone result h_ee_bg_scaled_nominal_pt1.7_2: TH1D  h_ee_bg_scaled_nominal_pt1.7_2
[OK] clone source h_ee_sub_nominal_pt1.7_2: TH1D  h_ee_fg_nominal_pt1.7_2
[OK] clone result h_ee_sub_nominal_pt1.7_2: TH1D  h_ee_sub_nominal_pt1.7_2
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt1.7_2
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt1.7_2
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt1.7_2
EE yield:
  FG signal = 7.82e+03
  BG signal = 0
  SUB       = 7.82e+03 +/- 88.4
[OK] project source h_eeg_fg_nominal_pt1.7_2: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt1.7_2
  pt range = [1.7, 2.0)
  y bins   = 18 to 20
[OK] projection h_eeg_fg_nominal_pt1.7_2: TH1D  h_eeg_fg_nominal_pt1.7_2
  proj integral = 5.69e+03
[OK] project source h_eeg_bg_nominal_pt1.7_2: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_bg_nominal_pt1.7_2
  pt range = [1.7, 2.0)
  y bins   = 18 to 20
[OK] projection h_eeg_bg_nominal_pt1.7_2: TH1D  h_eeg_bg_nominal_pt1.7_2
  proj integral = 4.33e+04
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt1.7_2
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt1.7_2
sideband [0.2, 0.8]: FG=2.96e+03, BG=3.34e+04
  scale = 0.0885136
[OK] clone source h_eeg_bg_scaled_nominal_pt1.7_2: TH1D  h_eeg_bg_nominal_pt1.7_2
[OK] clone result h_eeg_bg_scaled_nominal_pt1.7_2: TH1D  h_eeg_bg_scaled_nominal_pt1.7_2
[OK] clone source h_eeg_sub_nominal_pt1.7_2: TH1D  h_eeg_fg_nominal_pt1.7_2
[OK] clone result h_eeg_sub_nominal_pt1.7_2: TH1D  h_eeg_sub_nominal_pt1.7_2
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt1.7_2
EEG after mixed-BG subtraction, before fit:
  raw signal window = 1.63e+03 +/- 45.2
[OK] eeg_mb_nominal_pt1.7_2 input: TH1D  h_eeg_sub_nominal_pt1.7_2
     entries = 574
     integral = 1.86e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_nominal_pt1_7_2_95: TF1  f_eeg_mb_nominal_pt1_7_2_95
Before fit:
  amp0 = 158.0864774224458
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_mb_nominal_pt1_7_2_95: TF1  f_eeg_mb_nominal_pt1_7_2_95
  status = 0
  mean = 0.13145056112163123
  sigma = 0.011145077143484852
  chi2/ndf = 302.95345871708906 / 286
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt1.7_2
     entries = 574
     integral = 1.86e+03
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_mb_nominal_pt1_7_2_95
pol2-subtracted yield:
  raw = 1.63e+03
  pol2 = 49.9
  signal = 1.58e+03 +/- 45.2
FINAL MB ONE BIN
  Yee        = 7817 +/- 88.4138
  Yeeg       = 1582.28 +/- 45.2406
  eeg / ee   = 0.202415
  ee / eeg   = 4.94035


################################################################################
Running nominal: pT [2.0, 2.5)
================================================================================
one_bin_result_mb cfg=nominal, pt=[2.0,2.5]
[OK] project source h_ee_fg_nominal_pt2_2.5: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt2_2.5
  pt range = [2.0, 2.5)
  y bins   = 21 to 25
[OK] projection h_ee_fg_nominal_pt2_2.5: TH1D  h_ee_fg_nominal_pt2_2.5
  proj integral = 5.9e+03
[OK] project source h_ee_bg_nominal_pt2_2.5: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt2_2.5
  pt range = [2.0, 2.5)
  y bins   = 21 to 25
[OK] projection h_ee_bg_nominal_pt2_2.5: TH1D  h_ee_bg_nominal_pt2_2.5
  proj integral = 3.82e+05
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt2_2.5
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt2_2.5
sideband [0.2, 0.75]: FG=0, BG=2.67e+05
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt2_2.5: TH1D  h_ee_bg_nominal_pt2_2.5
[OK] clone result h_ee_bg_scaled_nominal_pt2_2.5: TH1D  h_ee_bg_scaled_nominal_pt2_2.5
[OK] clone source h_ee_sub_nominal_pt2_2.5: TH1D  h_ee_fg_nominal_pt2_2.5
[OK] clone result h_ee_sub_nominal_pt2_2.5: TH1D  h_ee_sub_nominal_pt2_2.5
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt2_2.5
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt2_2.5
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt2_2.5
EE yield:
  FG signal = 5.82e+03
  BG signal = 0
  SUB       = 5.82e+03 +/- 76.3
[OK] project source h_eeg_fg_nominal_pt2_2.5: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt2_2.5
  pt range = [2.0, 2.5)
  y bins   = 21 to 25
[OK] projection h_eeg_fg_nominal_pt2_2.5: TH1D  h_eeg_fg_nominal_pt2_2.5
  proj integral = 4.64e+03
[OK] project source h_eeg_bg_nominal_pt2_2.5: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_bg_nominal_pt2_2.5
  pt range = [2.0, 2.5)
  y bins   = 21 to 25
[OK] projection h_eeg_bg_nominal_pt2_2.5: TH1D  h_eeg_bg_nominal_pt2_2.5
  proj integral = 3.05e+04
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt2_2.5
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt2_2.5
sideband [0.2, 0.8]: FG=2.35e+03, BG=2.34e+04
  scale = 0.100724
[OK] clone source h_eeg_bg_scaled_nominal_pt2_2.5: TH1D  h_eeg_bg_nominal_pt2_2.5
[OK] clone result h_eeg_bg_scaled_nominal_pt2_2.5: TH1D  h_eeg_bg_scaled_nominal_pt2_2.5
[OK] clone source h_eeg_sub_nominal_pt2_2.5: TH1D  h_eeg_fg_nominal_pt2_2.5
[OK] clone result h_eeg_sub_nominal_pt2_2.5: TH1D  h_eeg_sub_nominal_pt2_2.5
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt2_2.5
EEG after mixed-BG subtraction, before fit:
  raw signal window = 1.36e+03 +/- 40.6
[OK] eeg_mb_nominal_pt2_2.5 input: TH1D  h_eeg_sub_nominal_pt2_2.5
     entries = 492
     integral = 1.56e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_nominal_pt2_2_5_105: TF1  f_eeg_mb_nominal_pt2_2_5_105
Before fit:
  amp0 = 119.34499593165175
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_mb_nominal_pt2_2_5_105: TF1  f_eeg_mb_nominal_pt2_2_5_105
  status = 0
  mean = 0.13172301927431965
  sigma = 0.011843487598258878
  chi2/ndf = 335.5348075904546 / 286
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt2_2.5
     entries = 492
     integral = 1.56e+03
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_mb_nominal_pt2_2_5_105
pol2-subtracted yield:
  raw = 1.36e+03
  pol2 = -20.2
  signal = 1.38e+03 +/- 40.6
FINAL MB ONE BIN
  Yee        = 5822 +/- 76.302
  Yeeg       = 1378.27 +/- 40.5757
  eeg / ee   = 0.236734
  ee / eeg   = 4.22415


################################################################################
Running nominal: pT [2.5, 3.0)
================================================================================
one_bin_result_mb cfg=nominal, pt=[2.5,3.0]
[OK] project source h_ee_fg_nominal_pt2.5_3: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt2.5_3
  pt range = [2.5, 3.0)
  y bins   = 26 to 30
[OK] projection h_ee_fg_nominal_pt2.5_3: TH1D  h_ee_fg_nominal_pt2.5_3
  proj integral = 2.07e+03
[OK] project source h_ee_bg_nominal_pt2.5_3: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt2.5_3
  pt range = [2.5, 3.0)
  y bins   = 26 to 30
[OK] projection h_ee_bg_nominal_pt2.5_3: TH1D  h_ee_bg_nominal_pt2.5_3
  proj integral = 9.15e+04
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt2.5_3
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt2.5_3
sideband [0.2, 0.75]: FG=0, BG=6.1e+04
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt2.5_3: TH1D  h_ee_bg_nominal_pt2.5_3
[OK] clone result h_ee_bg_scaled_nominal_pt2.5_3: TH1D  h_ee_bg_scaled_nominal_pt2.5_3
[OK] clone source h_ee_sub_nominal_pt2.5_3: TH1D  h_ee_fg_nominal_pt2.5_3
[OK] clone result h_ee_sub_nominal_pt2.5_3: TH1D  h_ee_sub_nominal_pt2.5_3
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt2.5_3
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt2.5_3
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt2.5_3
EE yield:
  FG signal = 2.02e+03
  BG signal = 0
  SUB       = 2.02e+03 +/- 45
[OK] project source h_eeg_fg_nominal_pt2.5_3: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt2.5_3

,config,pt_min,pt_max,pt_center,y_ee,e_ee,y_eeg,e_eeg,raw_eeg,pol2_eeg,eeg_over_ee,ee_over_eeg,fit_mean,fit_sigma,fit_chi2,fit_ndf
0,nominal,0.8,1.0,0.90,23925.000000,154.677083,3681.861528,74.753563,3803.074063,121.212534,0.153892,6.498072,0.131792,0.011378,340.891720,286
1,nominal,1.0,1.3,1.15,33140.000000,182.043951,5418.142628,88.593632,5660.953881,242.811253,0.163493,6.116487,0.131584,0.010937,350.186372,286
2,nominal,1.3,1.7,1.50,21209.000000,145.633101,4061.641274,73.692254,4222.673582,161.032308,0.191506,5.221781,0.131639,0.010963,401.823185,286
3,nominal,1.7,2.0,1.85,7817.000000,88.413800,1582.275728,45.240607,1632.126003,49.850275,0.202415,4.940353,0.131451,0.011145,302.953459,286
4,nominal,2.0,2.5,2.25,5822.000000,76.302031,1378.266399,40.575705,1358.017558,-20.248841,0.236734,4.224147,0.131723,0.011843,335.534808,286
5,nominal,2.5,3.0,2.75,2023.000000,44.977772,548.264512,24.951513,521.107759,-27.156753,0.271016,3.689825,0.132900,0.011671,460.391433,286
6,nominal,3.0,4.0,3.50,1056.949024,32.511536,319.544253,18.657483,298.298480,-21.245773,0.302327,3.307677,0.132625,0.012819,372.201488,285
7,nominal,4.0,5.0,4.50,197.000000,14.035669,67.456091,8.276340,58.881919,-8.574172,0.342417,2.920418,0.129397,0.008901,204.113240,253
8,nominal,5.0,7.0,6.00,80.944853,9.000006,26.330156,4.947376,20.689394,-5.640762,0.325285,3.074226,0.134960,0.007450,101.678148,196
9,nominal,7.0,10.0,8.50,14.000000,3.741657,-35.985218,2.000000,4.000000,39.985218,-2.570373,-0.389049,0.139836,0.026923,0.000003,4

In [43]:
df_nominal_mb.to_csv(f"{fit_out_dir}/yields_nominal_mb.csv", index=False)

In [44]:
def add_ratio_columns(df):
    df = df.copy()

    # eeg / ee
    df["eeg_over_ee"] = float("nan")
    df["eeg_over_ee_err"] = float("nan")

    # ee / eeg
    df["ee_over_eeg"] = float("nan")
    df["ee_over_eeg_err"] = float("nan")

    for i, row in df.iterrows():
        y_ee = row["y_ee"]
        e_ee = row["e_ee"]
        y_eeg = row["y_eeg"]
        e_eeg = row["e_eeg"]

        if y_ee > 0 and y_eeg > 0:
            r1 = y_eeg / y_ee
            r1_err = r1 * math.sqrt((e_eeg / y_eeg)**2 + (e_ee / y_ee)**2)

            r2 = y_ee / y_eeg
            r2_err = r2 * math.sqrt((e_ee / y_ee)**2 + (e_eeg / y_eeg)**2)

            df.loc[i, "eeg_over_ee"] = r1
            df.loc[i, "eeg_over_ee_err"] = r1_err
            df.loc[i, "ee_over_eeg"] = r2
            df.loc[i, "ee_over_eeg_err"] = r2_err

    return df

In [45]:
df_nominal_mb = add_ratio_columns(df_nominal_mb)
df_nominal_mb

,config,pt_min,pt_max,pt_center,y_ee,e_ee,y_eeg,e_eeg,raw_eeg,pol2_eeg,eeg_over_ee,ee_over_eeg,fit_mean,fit_sigma,fit_chi2,fit_ndf,eeg_over_ee_err,ee_over_eeg_err
0,nominal,0.8,1.0,0.90,23925.000000,154.677083,3681.861528,74.753563,3803.074063,121.212534,0.153892,6.498072,0.131792,0.011378,340.891720,286,0.003279,0.138459
1,nominal,1.0,1.3,1.15,33140.000000,182.043951,5418.142628,88.593632,5660.953881,242.811253,0.163493,6.116487,0.131584,0.010937,350.186372,286,0.002820,0.105505
2,nominal,1.3,1.7,1.50,21209.000000,145.633101,4061.641274,73.692254,4222.673582,161.032308,0.191506,5.221781,0.131639,0.010963,401.823185,286,0.003715,0.101299
3,nominal,1.7,2.0,1.85,7817.000000,88.413800,1582.275728,45.240607,1632.126003,49.850275,0.202415,4.940353,0.131451,0.011145,302.953459,286,0.006224,0.151906
4,nominal,2.0,2.5,2.25,5822.000000,76.302031,1378.266399,40.575705,1358.017558,-20.248841,0.236734,4.224147,0.131723,0.011843,335.534808,286,0.007629,0.136124
5,nominal,2.5,3.0,2.75,2023.000000,44.977772,548.264512,24.951513,521.107759,-27.156753,0.271016,3.689825,0.132900,0.011671,460.391433,286,0.013727,0.186892
6,nominal,3.0,4.0,3.50,1056.949024,32.511536,319.544253,18.657483,298.298480,-21.245773,0.302327,3.307677,0.132625,0.012819,372.201488,285,0.019952,0.218289
7,nominal,4.0,5.0,4.50,197.000000,14.035669,67.456091,8.276340,58.881919,-8.574172,0.342417,2.920418,0.129397,0.008901,204.113240,253,0.048582,0.414345
8,nominal,5.0,7.0,6.00,80.944853,9.000006,26.330156,4.947376,20.689394,-5.640762,0.325285,3.074226,0.134960,0.007450,101.678148,196,0.071020,0.671196
9,nominal,7.0,10.0,8.50,14.000000,3.741657,-35.985218,2.000000,4.000000,39.985218,NaN,NaN,0.139836,0.026923,0.000003,4,NaN,NaN

In [46]:
def make_ratio_graph_from_df(df, ycol, eycol, name, title):
    g = root.TGraphErrors(len(df))
    g.SetName(name)
    g.SetTitle(title)

    for i, row in enumerate(df.itertuples()):
        x = row.pt_center
        ex = 0.5 * (row.pt_max - row.pt_min)
        y = getattr(row, ycol)
        ey = getattr(row, eycol) if eycol in df.columns else 0.0

        g.SetPoint(i, x, y)
        g.SetPointError(i, ex, ey)

    g.SetMarkerStyle(20)
    g.SetMarkerColor(root.kBlue)
    g.SetLineColor(root.kBlue)
    keep(g)
    return g

In [47]:
g_ee = make_ratio_graph_from_df(
    df_nominal_mb,
    "y_ee",
    "e_ee",
    "g_ee_nominal",
    "nominal; p_{T} (GeV/c); ee"
)

g_eeg = make_ratio_graph_from_df(
    df_nominal_mb,
    "y_eeg",
    "e_eeg",
    "g_eeg_nominal",
    "nominal; p_{T} (GeV/c); ee / eeg"
)

c_yield = root.TCanvas("c_yield_nominal", "c_yield_nominal", 1200, 500)
c_yield.Divide(2, 1)

c_yield.cd(1)
g_ee.Draw("AP")

c_yield.cd(2)
g_eeg.Draw("AP")

c_yield.Draw()

c_ratio = root.TCanvas("c_ratio_nominal", "c_ratio_nominal", 800, 600)

g_ee_over_eeg = make_ratio_graph_from_df(
    df_nominal_mb,
    "ee_over_eeg",
    "ee_over_eeg_err",
    "g_ee_over_eeg_nominal",
    "nominal; p_{T} (GeV/c); ee / eeg"
)

c_ratio = root.TCanvas("c_ratio_nominal", "c_ratio_nominal", 600, 500)
g_ee_over_eeg.GetYaxis().SetRangeUser(0, 15)
g_ee_over_eeg.Draw("AP")

c_ratio.Draw()

In [48]:
configs_to_run = [
    "nominal",
    "conv_solution",
    "conv_tight",
    "ecore04",
    "ecore05",
    "pte03",
    "pte04",
    "eid0",
    "eid1",
    "eid3",
    "chi2_4",
    "chi2_5",
    "escale099",
    "escale101",
]

In [49]:
all_dfs = []
all_results = {}

for cfg in configs_to_run:
    print("\n\n")
    print("="*100)
    print(f"BUILDING MB HISTOGRAMS FOR {cfg}")
    print("="*100)

    mb_cfg = build_mb_set(hists, cfg)

    print("\n")
    print("="*100)
    print(f"RUNNING PT BINS FOR {cfg}")
    print("="*100)

    df_cfg, results_cfg = run_pt_bins_for_config(
        cfg,
        mb_cfg,
        save_canvases=False
    )

    all_dfs.append(df_cfg)
    all_results[cfg] = results_cfg

df_all = pd.concat(all_dfs, ignore_index=True)
df_all.to_csv(f"{fit_out_dir}/yields_all_configs_mb.csv", index=False)

df_all

====================================================================================================
BUILDING MB HISTOGRAMS FOR nominal
====================================================================================================
[OK] clone source mb_file0_fg2d_eemass_reco_nominal: TH2F  fg2d_eemass_reco_nominal_icent0_file0
[OK] clone result mb_file0_fg2d_eemass_reco_nominal: TH2F  mb_file0_fg2d_eemass_reco_nominal
[OK] built mb_file0_fg2d_eemass_reco_nominal: integral=103637
[OK] clone source mb_all_fg2d_eemass_reco_nominal: TH2F  mb_file0_fg2d_eemass_reco_nominal
[OK] clone result mb_all_fg2d_eemass_reco_nominal: TH2F  mb_all_fg2d_eemass_reco_nominal
[OK] built mb_all_fg2d_eemass_reco_nominal: integral=103637
[OK] clone source mb_file0_bg2d_eemass_reco_nominal: TH2F  bg2d_eemass_reco_nominal_icent0_file0
[OK] clone result mb_file0_bg2d_eemass_reco_nominal: TH2F  mb_file0_bg2d_eemass_reco_nominal
[OK] built mb_file0_bg2d_eemass_reco_nominal: integral=1.01459e+08
[OK] clone source mb_all_bg2d_eemass_reco_nominal: TH2F  mb_file0_bg2d_eemass_reco_nominal
[OK] clone result mb_all_bg2d_eemass_reco_nominal: TH2F  mb_all_bg2d_eemass_reco_nominal
[OK] built mb_all_bg2d_eemass_reco_nominal: integral=1.01459e+08
[OK] clone source mb_file0_fg2d_eegmass_reco_nominal: TH2F  fg2d_eegmass_reco_nominal_icent0_file0
[OK] clone result mb_file0_fg2d_eegmass_reco_nominal: TH2F  mb_file0_fg2d_eegmass_reco_nominal
[OK] built mb_file0_fg2d_eegmass_reco_nominal: integral=69008
[OK] clone source mb_all_fg2d_eegmass_reco_nominal: TH2F  mb_file0_fg2d_eegmass_reco_nominal
[OK] clone result mb_all_fg2d_eegmass_reco_nominal: TH2F  mb_all_fg2d_eegmass_reco_nominal
[OK] built mb_all_fg2d_eegmass_reco_nominal: integral=69008
[OK] clone source mb_file0_bg2d_eegmass_reco_nominal: TH2F  bg2d_eegmass_reco_nominal_icent0_file0
[OK] clone result mb_file0_bg2d_eegmass_reco_nominal: TH2F  mb_file0_bg2d_eegmass_reco_nominal
[OK] built mb_file0_bg2d_eegmass_reco_nominal: integral=637647
[OK] clone source mb_all_bg2d_eegmass_reco_nominal: TH2F  mb_file0_bg2d_eegmass_reco_nominal
[OK] clone result mb_all_bg2d_eegmass_reco_nominal: TH2F  mb_all_bg2d_eegmass_reco_nominal
[OK] built mb_all_bg2d_eegmass_reco_nominal: integral=637647


====================================================================================================
RUNNING PT BINS FOR nominal
====================================================================================================


################################################################################
Running nominal: pT [0.8, 1.0)
================================================================================
one_bin_result_mb cfg=nominal, pt=[0.8,1.0]
[OK] project source h_ee_fg_nominal_pt0.8_1: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt0.8_1
  pt range = [0.8, 1.0)
  y bins   = 9 to 10
[OK] projection h_ee_fg_nominal_pt0.8_1: TH1D  h_ee_fg_nominal_pt0.8_1
  proj integral = 2.4e+04
[OK] project source h_ee_bg_nominal_pt0.8_1: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt0.8_1
  pt range = [0.8, 1.0)
  y bins   = 9 to 10
[OK] projection h_ee_bg_nominal_pt0.8_1: TH1D  h_ee_bg_nominal_pt0.8_1
  proj integral = 1.19e+07
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt0.8_1
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt0.8_1
sideband [0.2, 0.75]: FG=0, BG=9.24e+06
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt0.8_1: TH1D  h_ee_bg_nominal_pt0.8_1
[OK] clone result h_ee_bg_scaled_nominal_pt0.8_1: TH1D  h_ee_bg_scaled_nominal_pt0.8_1
[OK] clone source h_ee_sub_nominal_pt0.8_1: TH1D  h_ee_fg_nominal_pt0.8_1
[OK] clone result h_ee_sub_nominal_pt0.8_1: TH1D  h_ee_sub_nominal_pt0.8_1
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt0.8_1
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt0.8_1
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt0.8_1
EE yield:
  FG signal = 2.39e+04
  BG signal = 0
  SUB       = 2.39e+04 +/- 155
[OK] project source h_eeg_fg_nominal_pt0.8_1: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt0.8_1
  pt range = [0.8, 1.0)
  y bins   = 9 to 10
[OK] projection h_eeg_fg_nominal_pt0.8_1: TH1D  h_eeg_fg_nominal_pt0.8_1
  proj integral = 1.5e+04
[OK] project source h_eeg_bg_nominal_pt0.8_1: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_bg_nominal_pt0.8_1
  pt range = [0.8, 1.0)
  y bins   = 9 to 10
[OK] projection h_eeg_bg_nominal_pt0.8_1: TH1D  h_eeg_bg_nominal_pt0.8_1
  proj integral = 1.63e+05
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt0.8_1
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt0.8_1
sideband [0.2, 0.8]: FG=7.16e+03, BG=1.07e+05
  scale = 0.0670055
[OK] clone source h_eeg_bg_scaled_nominal_pt0.8_1: TH1D  h_eeg_bg_nominal_pt0.8_1
[OK] clone result h_eeg_bg_scaled_nominal_pt0.8_1: TH1D  h_eeg_bg_scaled_nominal_pt0.8_1
[OK] clone source h_eeg_sub_nominal_pt0.8_1: TH1D  h_eeg_fg_nominal_pt0.8_1
[OK] clone result h_eeg_sub_nominal_pt0.8_1: TH1D  h_eeg_sub_nominal_pt0.8_1
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt0.8_1
EEG after mixed-BG subtraction, before fit:
  raw signal window = 3.8e+03 +/- 74.8
[OK] eeg_mb_nominal_pt0.8_1 input: TH1D  h_eeg_sub_nominal_pt0.8_1
     entries = 1.04e+03
     integral = 4.05e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_nominal_pt0_8_1_176: TF1  f_eeg_mb_nominal_pt0_8_1_176
Before fit:
  amp0 = 345.8017914303364
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_mb_nominal_pt0_8_1_176: TF1  f_eeg_mb_nominal_pt0_8_1_176
  status = 0
  mean = 0.13179229943319914
  sigma = 0.011377562520198633
  chi2/ndf = 340.89172040738305 / 286
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt0.8_1
     entries = 1.04e+03
     integral = 4.05e+03
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_mb_nominal_pt0_8_1_176
pol2-subtracted yield:
  raw = 3.8e+03
  pol2 = 121
  signal = 3.68e+03 +/- 74.8
FINAL MB ONE BIN
  Yee        = 23925 +/- 154.677
  Yeeg       = 3681.86 +/- 74.7536
  eeg / ee   = 0.153892
  ee / eeg   = 6.49807


################################################################################
Running nominal: pT [1.0, 1.3)
================================================================================
one_bin_result_mb cfg=nominal, pt=[1.0,1.3]
[OK] project source h_ee_fg_nominal_pt1_1.3: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt1_1.3
  pt range = [1.0, 1.3)
  y bins   = 11 to 13
[OK] projection h_ee_fg_nominal_pt1_1.3: TH1D  h_ee_fg_nominal_pt1_1.3
  proj integral = 3.33e+04
[OK] project source h_ee_bg_nominal_pt1_1.3: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt1_1.3
  pt range = [1.0, 1.3)
  y bins   = 11 to 13
[OK] projection h_ee_bg_nominal_pt1_1.3: TH1D  h_ee_bg_nominal_pt1_1.3
  proj integral = 8.04e+06
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt1_1.3
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt1_1.3
sideband [0.2, 0.75]: FG=0, BG=5.89e+06
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt1_1.3: TH1D  h_ee_bg_nominal_pt1_1.3
[OK] clone result h_ee_bg_scaled_nominal_pt1_1.3: TH1D  h_ee_bg_scaled_nominal_pt1_1.3
[OK] clone source h_ee_sub_nominal_pt1_1.3: TH1D  h_ee_fg_nominal_pt1_1.3
[OK] clone result h_ee_sub_nominal_pt1_1.3: TH1D  h_ee_sub_nominal_pt1_1.3
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt1_1.3
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt1_1.3
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt1_1.3
EE yield:
  FG signal = 3.31e+04
  BG signal = 0
  SUB       = 3.31e+04 +/- 182
[OK] project source h_eeg_fg_nominal_pt1_1.3: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt1_1.3
  pt range = [1.0, 1.3)
  y bins   = 11 to 13
[OK] projection h_eeg_fg_nominal_pt1_1.3: TH1D  h_eeg_fg_nominal_pt1_1.3
  proj integral = 2.1e+04
[OK] project source h_eeg_bg_nominal_pt1_1.3: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_bg_nominal_pt1_1.3
  pt range = [1.0, 1.3)
  y bins   = 11 to 13
[OK] projection h_eeg_bg_nominal_pt1_1.3: TH1D  h_eeg_bg_nominal_pt1_1.3
  proj integral = 1.98e+05
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt1_1.3
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt1_1.3
sideband [0.2, 0.8]: FG=1.1e+04, BG=1.49e+05
  scale = 0.0735173
[OK] clone source h_eeg_bg_scaled_nominal_pt1_1.3: TH1D  h_eeg_bg_nominal_pt1_1.3
[OK] clone result h_eeg_bg_scaled_nominal_pt1_1.3: TH1D  h_eeg_bg_scaled_nominal_pt1_1.3
[OK] clone source h_eeg_sub_nominal_pt1_1.3: TH1D  h_eeg_fg_nominal_pt1_1.3
[OK] clone result h_eeg_sub_nominal_pt1_1.3: TH1D  h_eeg_sub_nominal_pt1_1.3
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt1_1.3
EEG after mixed-BG subtraction, before fit:
  raw signal window = 5.66e+03 +/- 88.6
[OK] eeg_mb_nominal_pt1_1.3 input: TH1D  h_eeg_sub_nominal_pt1_1.3
     entries = 1.87e+03
     integral = 6.42e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_nominal_pt1_1_3_186: TF1  f_eeg_mb_nominal_pt1_1_3_186
Before fit:
  amp0 = 511.0525228819526
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_mb_nominal_pt1_1_3_186: TF1  f_eeg_mb_nominal_pt1_1_3_186
  status = 0
  mean = 0.13158385987174778
  sigma = 0.010936734946311403
  chi2/ndf = 350.18637234597696 / 286
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt1_1.3
     entries = 1.87e+03
     integral = 6.42e+03
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_mb_nominal_pt1_1_3_186
pol2-subtracted yield:
  raw = 5.66e+03
  pol2 = 243
  signal = 5.42e+03 +/- 88.6
FINAL MB ONE BIN
  Yee        = 33140 +/- 182.044
  Yeeg       = 5418.14 +/- 88.5936
  eeg / ee   = 0.163493
  ee / eeg   = 6.11649


################################################################################
Running nominal: pT [1.3, 1.7)
================================================================================
one_bin_result_mb cfg=nominal, pt=[1.3,1.7]
[OK] project source h_ee_fg_nominal_pt1.3_1.7: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt1.3_1.7
  pt range = [1.3, 1.7)
  y bins   = 14 to 17
[OK] projection h_ee_fg_nominal_pt1.3_1.7: TH1D  h_ee_fg_nominal_pt1.3_1.7
  proj integral = 2.14e+04
[OK] project source h_ee_bg_nominal_pt1.3_1.7: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt1.3_1.7
  pt range = [1.3, 1.7)
  y bins   = 14 to 17
[OK] projection h_ee_bg_nominal_pt1.3_1.7: TH1D  h_ee_bg_nominal_pt1.3_1.7
  proj integral = 3.3e+06
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt1.3_1.7
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt1.3_1.7
sideband [0.2, 0.75]: FG=0, BG=2.39e+06
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt1.3_1.7: TH1D  h_ee_bg_nominal_pt1.3_1.7
[OK] clone result h_ee_bg_scaled_nominal_pt1.3_1.7: TH1D  h_ee_bg_scaled_nominal_pt1.3_1.7
[OK] clone source h_ee_sub_nominal_pt1.3_1.7: TH1D  h_ee_fg_nominal_pt1.3_1.7
[OK] clone result h_ee_sub_nominal_pt1.3_1.7: TH1D  h_ee_sub_nominal_pt1.3_1.7
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt1.3_1.7
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt1.3_1.7
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt1.3_1.7
EE yield:
  FG signal = 2.12e+04
  BG signal = 0
  SUB       = 2.12e+04 +/- 146
[OK] project source h_eeg_fg_nominal_pt1.3_1.7: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt1.3_1.7
  pt range = [1.3, 1.7)
  y bins   = 14 to 17
[OK] projection h_eeg_fg_nominal_pt1.3_1.7: TH1D  h_eeg_fg_nominal_pt1.3_1.7
  proj integral = 1.46e+04
[OK] project source h_eeg_bg_nominal_pt1.3_1.7: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_bg_nominal_pt1.3_1.7
  pt range = [1.3, 1.7)
  y bins   = 14 to 17
[OK] projection h_eeg_bg_nominal_pt1.3_1.7: TH1D  h_eeg_bg_nominal_pt1.3_1.7
  proj integral = 1.25e+05
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt1.3_1.7
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt1.3_1.7
sideband [0.2, 0.8]: FG=7.56e+03, BG=9.79e+04
  scale = 0.0771838
[OK] clone source h_eeg_bg_scaled_nominal_pt1.3_1.7: TH1D  h_eeg_bg_nominal_pt1.3_1.7
[OK] clone result h_eeg_bg_scaled_nominal_pt1.3_1.7: TH1D  h_eeg_bg_scaled_nominal_pt1.3_1.7
[OK] clone source h_eeg_sub_nominal_pt1.3_1.7: TH1D  h_eeg_fg_nominal_pt1.3_1.7
[OK] clone result h_eeg_sub_nominal_pt1.3_1.7: TH1D  h_eeg_sub_nominal_pt1.3_1.7
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt1.3_1.7
EEG after mixed-BG subtraction, before fit:
  raw signal window = 4.22e+03 +/- 73.7
[OK] eeg_mb_nominal_pt1.3_1.7 input: TH1D  h_eeg_sub_nominal_pt1.3_1.7
     entries = 1.6e+03
     integral = 4.97e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_nominal_pt1_3_1_7_196: TF1  f_eeg_mb_nominal_pt1_3_1_7_196
Before fit:
  amp0 = 374.5963572507861
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_mb_nominal_pt1_3_1_7_196: TF1  f_eeg_mb_nominal_pt1_3_1_7_196
  status = 0
  mean = 0.13163935940003035
  sigma = 0.010962831673258571
  chi2/ndf = 401.8231846174282 / 286
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt1.3_1.7
     entries = 1.6e+03
     integral = 4.97e+03
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_mb_nominal_pt1_3_1_7_196
pol2-subtracted yield:
  raw = 4.22e+03
  pol2 = 161
  signal = 4.06e+03 +/- 73.7
FINAL MB ONE BIN
  Yee        = 21209 +/- 145.633
  Yeeg       = 4061.64 +/- 73.6923
  eeg / ee   = 0.191506
  ee / eeg   = 5.22178


################################################################################
Running nominal: pT [1.7, 2.0)
================================================================================
one_bin_result_mb cfg=nominal, pt=[1.7,2.0]
[OK] project source h_ee_fg_nominal_pt1.7_2: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt1.7_2
  pt range = [1.7, 2.0)
  y bins   = 18 to 20
[OK] projection h_ee_fg_nominal_pt1.7_2: TH1D  h_ee_fg_nominal_pt1.7_2
  proj integral = 7.9e+03
[OK] project source h_ee_bg_nominal_pt1.7_2: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt1.7_2
  pt range = [1.7, 2.0)
  y bins   = 18 to 20
[OK] projection h_ee_bg_nominal_pt1.7_2: TH1D  h_ee_bg_nominal_pt1.7_2
  proj integral = 7.46e+05
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt1.7_2
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt1.7_2
sideband [0.2, 0.75]: FG=0, BG=5.35e+05
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt1.7_2: TH1D  h_ee_bg_nominal_pt1.7_2
[OK] clone result h_ee_bg_scaled_nominal_pt1.7_2: TH1D  h_ee_bg_scaled_nominal_pt1.7_2
[OK] clone source h_ee_sub_nominal_pt1.7_2: TH1D  h_ee_fg_nominal_pt1.7_2
[OK] clone result h_ee_sub_nominal_pt1.7_2: TH1D  h_ee_sub_nominal_pt1.7_2
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt1.7_2
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt1.7_2
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt1.7_2
EE yield:
  FG signal = 7.82e+03
  BG signal = 0
  SUB       = 7.82e+03 +/- 88.4
[OK] project source h_eeg_fg_nominal_pt1.7_2: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt1.7_2
  pt range = [1.7, 2.0)
  y bins   = 18 to 20
[OK] projection h_eeg_fg_nominal_pt1.7_2: TH1D  h_eeg_fg_nominal_pt1.7_2
  proj integral = 5.69e+03
[OK] project source h_eeg_bg_nominal_pt1.7_2: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_bg_nominal_pt1.7_2
  pt range = [1.7, 2.0)
  y bins   = 18 to 20
[OK] projection h_eeg_bg_nominal_pt1.7_2: TH1D  h_eeg_bg_nominal_pt1.7_2
  proj integral = 4.33e+04
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt1.7_2
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt1.7_2
sideband [0.2, 0.8]: FG=2.96e+03, BG=3.34e+04
  scale = 0.0885136
[OK] clone source h_eeg_bg_scaled_nominal_pt1.7_2: TH1D  h_eeg_bg_nominal_pt1.7_2
[OK] clone result h_eeg_bg_scaled_nominal_pt1.7_2: TH1D  h_eeg_bg_scaled_nominal_pt1.7_2
[OK] clone source h_eeg_sub_nominal_pt1.7_2: TH1D  h_eeg_fg_nominal_pt1.7_2
[OK] clone result h_eeg_sub_nominal_pt1.7_2: TH1D  h_eeg_sub_nominal_pt1.7_2
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt1.7_2
EEG after mixed-BG subtraction, before fit:
  raw signal window = 1.63e+03 +/- 45.2
[OK] eeg_mb_nominal_pt1.7_2 input: TH1D  h_eeg_sub_nominal_pt1.7_2
     entries = 574
     integral = 1.86e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_nominal_pt1_7_2_206: TF1  f_eeg_mb_nominal_pt1_7_2_206
Before fit:
  amp0 = 158.0864774224458
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_mb_nominal_pt1_7_2_206: TF1  f_eeg_mb_nominal_pt1_7_2_206
  status = 0
  mean = 0.13145056112163123
  sigma = 0.011145077143484852
  chi2/ndf = 302.95345871708906 / 286
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt1.7_2
     entries = 574
     integral = 1.86e+03
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_mb_nominal_pt1_7_2_206
pol2-subtracted yield:
  raw = 1.63e+03
  pol2 = 49.9
  signal = 1.58e+03 +/- 45.2
FINAL MB ONE BIN
  Yee        = 7817 +/- 88.4138
  Yeeg       = 1582.28 +/- 45.2406
  eeg / ee   = 0.202415
  ee / eeg   = 4.94035


################################################################################
Running nominal: pT [2.0, 2.5)
================================================================================
one_bin_result_mb cfg=nominal, pt=[2.0,2.5]
[OK] project source h_ee_fg_nominal_pt2_2.5: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt2_2.5
  pt range = [2.0, 2.5)
  y bins   = 21 to 25
[OK] projection h_ee_fg_nominal_pt2_2.5: TH1D  h_ee_fg_nominal_pt2_2.5
  proj integral = 5.9e+03
[OK] project source h_ee_bg_nominal_pt2_2.5: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt2_2.5
  pt range = [2.0, 2.5)
  y bins   = 21 to 25
[OK] projection h_ee_bg_nominal_pt2_2.5: TH1D  h_ee_bg_nominal_pt2_2.5
  proj integral = 3.82e+05
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt2_2.5
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt2_2.5
sideband [0.2, 0.75]: FG=0, BG=2.67e+05
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt2_2.5: TH1D  h_ee_bg_nominal_pt2_2.5
[OK] clone result h_ee_bg_scaled_nominal_pt2_2.5: TH1D  h_ee_bg_scaled_nominal_pt2_2.5
[OK] clone source h_ee_sub_nominal_pt2_2.5: TH1D  h_ee_fg_nominal_pt2_2.5
[OK] clone result h_ee_sub_nominal_pt2_2.5: TH1D  h_ee_sub_nominal_pt2_2.5
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt2_2.5
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt2_2.5
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt2_2.5
EE yield:
  FG signal = 5.82e+03
  BG signal = 0
  SUB       = 5.82e+03 +/- 76.3
[OK] project source h_eeg_fg_nominal_pt2_2.5: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt2_2.5
  pt range = [2.0, 2.5)
  y bins   = 21 to 25
[OK] projection h_eeg_fg_nominal_pt2_2.5: TH1D  h_eeg_fg_nominal_pt2_2.5
  proj integral = 4.64e+03
[OK] project source h_eeg_bg_nominal_pt2_2.5: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_bg_nominal_pt2_2.5
  pt range = [2.0, 2.5)
  y bins   = 21 to 25
[OK] projection h_eeg_bg_nominal_pt2_2.5: TH1D  h_eeg_bg_nominal_pt2_2.5
  proj integral = 3.05e+04
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt2_2.5
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt2_2.5
sideband [0.2, 0.8]: FG=2.35e+03, BG=2.34e+04
  scale = 0.100724
[OK] clone source h_eeg_bg_scaled_nominal_pt2_2.5: TH1D  h_eeg_bg_nominal_pt2_2.5
[OK] clone result h_eeg_bg_scaled_nominal_pt2_2.5: TH1D  h_eeg_bg_scaled_nominal_pt2_2.5
[OK] clone source h_eeg_sub_nominal_pt2_2.5: TH1D  h_eeg_fg_nominal_pt2_2.5
[OK] clone result h_eeg_sub_nominal_pt2_2.5: TH1D  h_eeg_sub_nominal_pt2_2.5
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt2_2.5
EEG after mixed-BG subtraction, before fit:
  raw signal window = 1.36e+03 +/- 40.6
[OK] eeg_mb_nominal_pt2_2.5 input: TH1D  h_eeg_sub_nominal_pt2_2.5
     entries = 492

After fit:
[OK] TF1 after fit eeg_mb_nominal_pt2_2_5_216: TF1  f_eeg_mb_nominal_pt2_2_5_216
  status = 0
  mean = 0.13172301927431965
  sigma = 0.011843487598258878
  chi2/ndf = 335.5348075904546 / 286
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt2_2.5
     entries = 492
     integral = 1.56e+03
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_mb_nominal_pt2_2_5_216
pol2-subtracted yield:
  raw = 1.36e+03
  pol2 = -20.2
  signal = 1.38e+03 +/- 40.6
FINAL MB ONE BIN
  Yee        = 5822 +/- 76.302
  Yeeg       = 1378.27 +/- 40.5757
  eeg / ee   = 0.236734
  ee / eeg   = 4.22415


################################################################################
Running nominal: pT [2.5, 3.0)
================================================================================
one_bin_result_mb cfg=nominal, pt=[2.5,3.0]
[OK] project source h_ee_fg_nominal_pt2.5_3: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt2.5_3
  pt range = [2.5, 3.0)
  y bins   = 26 to 30
[OK] projection h_ee_fg_nominal_pt2.5_3: TH1D  h_ee_fg_nominal_pt2.5_3
  proj integral = 2.07e+03
[OK] project source h_ee_bg_nominal_pt2.5_3: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt2.5_3
  pt range = [2.5, 3.0)
  y bins   = 26 to 30
[OK] projection h_ee_bg_nominal_pt2.5_3: TH1D  h_ee_bg_nominal_pt2.5_3
  proj integral = 9.15e+04
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt2.5_3
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt2.5_3
sideband [0.2, 0.75]: FG=0, BG=6.1e+04
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt2.5_3: TH1D  h_ee_bg_nominal_pt2.5_3
[OK] clone result h_ee_bg_scaled_nominal_pt2.5_3: TH1D  h_ee_bg_scaled_nominal_pt2.5_3
[OK] clone source h_ee_sub_nominal_pt2.5_3: TH1D  h_ee_fg_nominal_pt2.5_3
[OK] clone result h_ee_sub_nominal_pt2.5_3: TH1D  h_ee_sub_nominal_pt2.5_3
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt2.5_3
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt2.5_3
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt2.5_3
EE yield:
  FG signal = 2.02e+03
  BG signal = 0
  SUB       = 2.02e+03 +/- 45
[OK] project source h_eeg_fg_nominal_pt2.5_3: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt2.5_3
  pt range = [2.5, 3.0)
  y bins   = 26 to 30
[OK] projection h_eeg_fg_nominal_pt2.5_3: TH1D  h_eeg_fg_nominal_pt2.5_3
  proj integral = 1.78e+03
[OK] project source h_eeg_bg_nominal_pt2.5_3: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_bg_nominal_pt2.5_3
  pt range = [2.5, 3.0)
  y bins   = 26 to 30
[OK] projection h_eeg_bg_nominal_pt2.5_3: TH1D  h_eeg_bg_nominal_pt2.5_3
  proj integral = 9.87e+03
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt2.5_3
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt2.5_3
sideband [0.2, 0.8]: FG=864, BG=7.42e+03
  scale = 0.116379
[OK] clone source h_eeg_bg_scaled_nominal_pt2.5_3: TH1D  h_eeg_bg_nominal_pt2.5_3
[OK] clone result h_eeg_bg_scaled_nominal_pt2.5_3: TH1D  h_eeg_bg_scaled_nominal_pt2.5_3
[OK] clone source h_eeg_sub_nominal_pt2.5_3: TH1D  h_eeg_fg_nominal_pt2.5_3
[OK] clone result h_eeg_sub_nominal_pt2.5_3: TH1D  h_eeg_sub_nominal_pt2.5_3
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt2.5_3
EEG after mixed-BG subtraction, before fit:
  raw signal window = 521 +/- 25
[OK] eeg_mb_nominal_pt2.5_3 input: TH1D  h_eeg_sub_nominal_pt2.5_3
     entries = 209
     integral = 632
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_nominal_pt2_5_3_226: TF1  f_eeg_mb_nominal_pt2_5_3_226
Before fit:
  amp0 = 52.9051724137931
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_mb_nominal_pt2_5_3_226: TF1  f_eeg_mb_nominal_pt2_5_3_226
  status = 0
  mean = 0.13289951356019858
  sigma = 0.011671047183316265
  chi2/ndf = 460.39143328891487 / 286
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt2.5_3
     entries = 209
     integral = 632
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_mb_nominal_pt2_5_3_226
pol2-subtracted yield:
  raw = 521
  pol2 = -27.2
  signal = 548 +/- 25
FINAL MB ONE BIN
  Yee        = 2023 +/- 44.9778
  Yeeg       = 548.265 +/- 24.9515
  eeg / ee   = 0.271016
  ee / eeg   = 3.68982


################################################################################
Running nominal: pT [3.0, 4.0)
================================================================================
one_bin_result_mb cfg=nominal, pt=[3.0,4.0]
[OK] project source h_ee_fg_nominal_pt3_4: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt3_4
  pt range = [3.0, 4.0)
  y bins   = 31 to 40
[OK] projection h_ee_fg_nominal_pt3_4: TH1D  h_ee_fg_nominal_pt3_4
  proj integral = 1.08e+03
[OK] project source h_ee_bg_nominal_pt3_4: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt3_4
  pt range = [3.0, 4.0)
  y bins   = 31 to 40
[OK] projection h_ee_bg_nominal_pt3_4: TH1D  h_ee_bg_nominal_pt3_4
  proj integral = 3.26e+04
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt3_4
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt3_4
sideband [0.2, 0.75]: FG=1, BG=2.08e+04
  scale = 4.80908e-05
[OK] clone source h_ee_bg_scaled_nominal_pt3_4: TH1D  h_ee_bg_nominal_pt3_4
[OK] clone result h_ee_bg_scaled_nominal_pt3_4: TH1D  h_ee_bg_scaled_nominal_pt3_4
[OK] clone source h_ee_sub_nominal_pt3_4: TH1D  h_ee_fg_nominal_pt3_4
[OK] clone result h_ee_sub_nominal_pt3_4: TH1D  h_ee_sub_nominal_pt3_4
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt3_4
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt3_4
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt3_4
EE yield:
  FG signal = 1.06e+03
  BG signal = 0.051
  SUB       = 1.06e+03 +/- 32.5
[OK] project source h_eeg_fg_nominal_pt3_4: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt3_4
  pt range = [3.0, 4.0)
  y bins   = 31 to 40
[OK] projection h_eeg_fg_nominal_pt3_4: TH1D  h_eeg_fg_nominal_pt3_4
  proj integral = 989
[OK] project source h_eeg_bg_nominal_pt3_4: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_bg_nominal_pt3_4
  pt range = [3.0, 4.0)
  y bins   = 31 to 40
[OK] projection h_eeg_bg_nominal_pt3_4: TH1D  h_eeg_bg_nominal_pt3_4
  proj integral = 4.41e+03
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt3_4
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt3_4
sideband [0.2, 0.8]: FG=450, BG=3.22e+03
  scale = 0.139621
[OK] clone source h_eeg_bg_scaled_nominal_pt3_4: TH1D  h_eeg_bg_nominal_pt3_4
[OK] clone result h_eeg_bg_scaled_nominal_pt3_4: TH1D  h_eeg_bg_scaled_nominal_pt3_4
[OK] clone source h_eeg_sub_nominal_pt3_4: TH1D  h_eeg_fg_nominal_pt3_4
[OK] clone result h_eeg_sub_nominal_pt3_4: TH1D  h_eeg_sub_nominal_pt3_4
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt3_4
EEG after mixed-BG subtraction, before fit:
  raw signal window = 298 +/- 18.7
[OK] eeg_mb_nominal_pt3_4 input: TH1D  h_eeg_sub_nominal_pt3_4
     entries = 129
     integral = 373
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_nominal_pt3_4_236: TF1  f_eeg_mb_nominal_pt3_4_236
Before fit:
  amp0 = 26.883028234564073
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_mb_nominal_pt3_4_236: TF1  f_eeg_mb_nominal_pt3_4_236
  status = 0
  mean = 0.13262544481846236
  sigma = 0.01281922264294051
  chi2/ndf = 372.20148773539563 / 285
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt3_4
     entries = 129
     integral = 373
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_mb_nominal_pt3_4_236
pol2-subtracted yield:
  raw = 298
  pol2 = -21.2
  signal = 320 +/- 18.7
FINAL MB ONE BIN
  Yee        = 1056.95 +/- 32.5115
  Yeeg       = 319.544 +/- 18.6575
  eeg / ee   = 0.302327
  ee / eeg   = 3.30768


################################################################################
Running nominal: pT [4.0, 5.0)
================================================================================
one_bin_result_mb cfg=nominal, pt=[4.0,5.0]
[OK] project source h_ee_fg_nominal_pt4_5: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt4_5
  pt range = [4.0, 5.0)
  y bins   = 41 to 50
[OK] projection h_ee_fg_nominal_pt4_5: TH1D  h_ee_fg_nominal_pt4_5
  proj integral = 206
[OK] project source h_ee_bg_nominal_pt4_5: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt4_5
  pt range = [4.0, 5.0)
  y bins   = 41 to 50
[OK] projection h_ee_bg_nominal_pt4_5: TH1D  h_ee_bg_nominal_pt4_5
  proj integral = 3.88e+03
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt4_5
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt4_5
sideband [0.2, 0.75]: FG=0, BG=2.39e+03
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt4_5: TH1D  h_ee_bg_nominal_pt4_5
[OK] clone result h_ee_bg_scaled_nominal_pt4_5: TH1D  h_ee_bg_scaled_nominal_pt4_5
[OK] clone source h_ee_sub_nominal_pt4_5: TH1D  h_ee_fg_nominal_pt4_5
[OK] clone result h_ee_sub_nominal_pt4_5: TH1D  h_ee_sub_nominal_pt4_5
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt4_5
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt4_5
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt4_5
EE yield:
  FG signal = 197
  BG signal = 0
  SUB       = 197 +/- 14
[OK] project source h_eeg_fg_nominal_pt4_5: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt4_5
  pt range = [4.0, 5.0)
  y bins   = 41 to 50
[OK] projection h_eeg_fg_nominal_pt4_5: TH1D  h_eeg_fg_nominal_pt4_5
  proj integral = 203
[OK] project source h_eeg_bg_nominal_pt4_5: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_bg_nominal_pt4_5
  pt range = [4.0, 5.0)
  y bins   = 41 to 50
[OK] projection h_eeg_bg_nominal_pt4_5: TH1D  h_eeg_bg_nominal_pt4_5
  proj integral = 768
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt4_5
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt4_5
sideband [0.2, 0.8]: FG=100, BG=542
  scale = 0.184502
[OK] clone source h_eeg_bg_scaled_nominal_pt4_5: TH1D  h_eeg_bg_nominal_pt4_5
[OK] clone result h_eeg_bg_scaled_nominal_pt4_5: TH1D  h_eeg_bg_scaled_nominal_pt4_5
[OK] clone source h_eeg_sub_nominal_pt4_5: TH1D  h_eeg_fg_nominal_pt4_5
[OK] clone result h_eeg_sub_nominal_pt4_5: TH1D  h_eeg_sub_nominal_pt4_5
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt4_5
EEG after mixed-BG subtraction, before fit:
  raw signal window = 58.9 +/- 8.28
[OK] eeg_mb_nominal_pt4_5 input: TH1D  h_eeg_sub_nominal_pt4_5
     entries = 16.4
     integral = 61.3
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_nominal_pt4_5_246: TF1  f_eeg_mb_nominal_pt4_5_246
Before fit:
  amp0 = 6.81549815498155
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_mb_nominal_pt4_5_246: TF1  f_eeg_mb_nominal_pt4_5_246
  status = 0
  mean = 0.12939676771258715
  sigma = 0.008901014862146967
  chi2/ndf = 204.11323981455695 / 253
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt4_5
     entries = 16.4
     integral = 61.3
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_mb_nominal_pt4_5_246
pol2-subtracted yield:
  raw = 58.9
  pol2 = -8.57
  signal = 67.5 +/- 8.28
FINAL MB ONE BIN
  Yee        = 197 +/- 14.0357
  Yeeg       = 67.4561 +/- 8.27634
  eeg / ee   = 0.342417
  ee / eeg   = 2.92042


################################################################################
Running nominal: pT [5.0, 7.0)
================================================================================
one_bin_result_mb cfg=nominal, pt=[5.0,7.0]
[OK] project source h_ee_fg_nominal_pt5_7: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt5_7
  pt range = [5.0, 7.0)
  y bins   = 51 to 70
[OK] projection h_ee_fg_nominal_pt5_7: TH1D  h_ee_fg_nominal_pt5_7
  proj integral = 85
[OK] project source h_ee_bg_nominal_pt5_7: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt5_7
  pt range = [5.0, 7.0)
  y bins   = 51 to 70
[OK] projection h_ee_bg_nominal_pt5_7: TH1D  h_ee_bg_nominal_pt5_7
  proj integral = 938
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt5_7
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt5_7
sideband [0.2, 0.75]: FG=1, BG=544
  scale = 0.00183824
[OK] clone source h_ee_bg_scaled_nominal_pt5_7: TH1D  h_ee_bg_nominal_pt5_7
[OK] clone result h_ee_bg_scaled_nominal_pt5_7: TH1D  h_ee_bg_scaled_nominal_pt5_7
[OK] clone source h_ee_sub_nominal_pt5_7: TH1D  h_ee_fg_nominal_pt5_7
[OK] clone result h_ee_sub_nominal_pt5_7: TH1D  h_ee_sub_nominal_pt5_7
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt5_7
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt5_7
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt5_7
EE yield:
  FG signal = 81
  BG signal = 0.0551
  SUB       = 80.9 +/- 9
[OK] project source h_eeg_fg_nominal_pt5_7: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt5_7
  pt range = [5.0, 7.0)
  y bins   = 51 to 70
[OK] projection h_eeg_fg_nominal_pt5_7: TH1D  h_eeg_fg_nominal_pt5_7
  proj integral = 83
[OK] project source h_eeg_bg_nominal_pt5_7: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_bg_nominal_pt5_7
  pt range = [5.0, 7.0)
  y bins   = 51 to 70
[OK] projection h_eeg_bg_nominal_pt5_7: TH1D  h_eeg_bg_nominal_pt5_7
  proj integral = 399
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt5_7
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt5_7
sideband [0.2, 0.8]: FG=38, BG=264
  scale = 0.143939
[OK] clone source h_eeg_bg_scaled_nominal_pt5_7: TH1D  h_eeg_bg_nominal_pt5_7
[OK] clone result h_eeg_bg_scaled_nominal_pt5_7: TH1D  h_eeg_bg_scaled_nominal_pt5_7
[OK] clone source h_eeg_sub_nominal_pt5_7: TH1D  h_eeg_fg_nominal_pt5_7
[OK] clone result h_eeg_sub_nominal_pt5_7: TH1D  h_eeg_sub_nominal_pt5_7
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt5_7
EEG after mixed-BG subtraction, before fit:
  raw signal window = 20.7 +/- 4.95
[OK] eeg_mb_nominal_pt5_7 input: TH1D  h_eeg_sub_nominal_pt5_7
     entries = 7.16
     integral = 25.6
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_nominal_pt5_7_256: TF1  f_eeg_mb_nominal_pt5_7_256
Before fit:
  amp0 = 3.0
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_mb_nominal_pt5_7_256: TF1  f_eeg_mb_nominal_pt5_7_256
  status = 0
  mean = 0.134959749170111
  sigma = 0.007449684476673165
  chi2/ndf = 101.67814847591606 / 196
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt5_7
     entries = 7.16
     integral = 25.6
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_mb_nominal_pt5_7_256
pol2-subtracted yield:
  raw = 20.7
  pol2 = -5.64
  signal = 26.3 +/- 4.95
FINAL MB ONE BIN
  Yee        = 80.9449 +/- 9.00001
  Yeeg       = 26.3302 +/- 4.94738
  eeg / ee   = 0.325285
  ee / eeg   = 3.07423


################################################################################
Running nominal: pT [7.0, 10.0)
================================================================================
one_bin_result_mb cfg=nominal, pt=[7.0,10.0]
[OK] project source h_ee_fg_nominal_pt7_10: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt7_10
  pt range = [7.0, 10.0)
  y bins   = 71 to 100
[OK] projection h_ee_fg_nominal_pt7_10: TH1D  h_ee_fg_nominal_pt7_10
  proj integral = 15
[OK] project source h_ee_bg_nominal_pt7_10: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt7_10
  pt range = [7.0, 10.0)
  y bins   = 71 to 100
[OK] projection h_ee_bg_nominal_pt7_10: TH1D  h_ee_bg_nominal_pt7_10
  proj integral = 58
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt7_10
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt7_10
sideband [0.2, 0.75]: FG=0, BG=37
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt7_10: TH1D  h_ee_bg_nominal_pt7_10
[OK] clone result h_ee_bg_scaled_nominal_pt7_10: TH1D  h_ee_bg_scaled_nominal_pt7_10
[OK] clone source h_ee_sub_nominal_pt7_10: TH1D  h_ee_fg_nominal_pt7_10
[OK] clone result h_ee_sub_nominal_pt7_10: TH1D  h_ee_sub_nominal_pt7_10
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt7_10
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt7_10
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt7_10
EE yield:
  FG signal = 14
  BG signal = 0
  SUB       = 14 +/- 3.74
[OK] project source h_eeg_fg_nominal_pt7_10: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt7_10
  pt range = [7.0, 10.0)
  y bins   = 71 to 100
[OK] projection h_eeg_fg_nominal_pt7_10: TH1D  h_eeg_fg_nominal_pt7_10
  proj integral = 15
[OK] project source h_eeg_bg_nominal_pt7_10: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_bg_nominal_pt7_10
  pt range = [7.0, 10.0)
  y bins   = 71 to 100
[OK] projection h_eeg_bg_nominal_pt7_10: TH1D  h_eeg_bg_nominal_pt7_10
  proj integral = 0
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt7_10
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt7_10
sideband [0.2, 0.8]: FG=5, BG=0
  WARNING: BG sideband <= 0, using scale=1
[OK] clone source h_eeg_bg_scaled_nominal_pt7_10: TH1D  h_eeg_bg_nominal_pt7_10
[OK] clone result h_eeg_bg_scaled_nominal_pt7_10: TH1D  h_eeg_bg_scaled_nominal_pt7_10
[OK] clone source h_eeg_sub_nominal_pt7_10: TH1D  h_eeg_fg_nominal_pt7_10
[OK] clone result h_eeg_sub_nominal_pt7_10: TH1D  h_eeg_sub_nominal_pt7_10
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt7_10
EEG after mixed-BG subtraction, before fit:
  raw signal window = 4 +/- 2
[OK] eeg_mb_nominal_pt7_10 input: TH1D  h_eeg_sub_nominal_pt7_10
     entries = 15
     integral = 15
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_nominal_pt7_10_266: TF1  f_eeg_mb_nominal_pt7_10_266
Before fit:
  amp0 = 1.0
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_mb_nominal_pt7_10_266: TF1  f_eeg_mb_nominal_pt7_10_266
  status = 0
  mean = 0.13983634595592453
  sigma = 0.026922712791201363
  chi2/ndf = 2.963835462598535e-06 / 4
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt7_10
     entries = 15
     integral = 15
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_mb_nominal_pt7_10_266
pol2-subtracted yield:
  raw = 4
  pol2 = 40
  signal = -36 +/- 2
FINAL MB ONE BIN
  Yee        = 14 +/- 3.74166
  Yeeg       = -35.9852 +/- 2
  eeg / ee   = -2.57037
  ee / eeg   = -0.389049



====================================================================================================
BUILDING MB HISTOGRAMS FOR conv_solution
====================================================================================================
[OK] clone source mb_file0_fg2d_eemass_reco_conv_solution: TH2F  fg2d_eemass_reco_conv_solution_icent0_file0
[OK] clone result mb_file0_fg2d_eemass_reco_conv_solution: TH2F  mb_file0_fg2d_eemass_reco_conv_solution
[OK] built mb_file0_fg2d_eemass_reco_conv_solution: integral=126549
[OK] clone source mb_all_fg2d_eemass_reco_conv_solution: TH2F  mb_file0_fg2d_eemass_reco_conv_solution
[OK] clone result mb_all_fg2d_eemass_reco_conv_solution: TH2F  mb_all_fg2d_eemass_reco_conv_solution
[OK] built mb_all_fg2d_eemass_reco_conv_solution: integral=126549
[OK] clone source mb_file0_bg2d_eemass_reco_conv_solution: TH2F  bg2d_eemass_reco_conv_solution_icent0_file0
[OK] clone result mb_file0_bg2d_eemass_reco_conv_solution: TH2F  mb_file0_bg2d_eemass_reco_conv_solution
[OK] built mb_file0_bg2d_eemass_reco_conv_solution: integral=1.01459e+08
[OK] clone source mb_all_bg2d_eemass_reco_conv_solution: TH2F  mb_file0_bg2d_eemass_reco_conv_solution
[OK] clone result mb_all_bg2d_eemass_reco_conv_solution: TH2F  mb_all_bg2d_eemass_reco_conv_solution
[OK] built mb_all_bg2d_eemass_reco_conv_solution: integral=1.01459e+08
[OK] clone source mb_file0_fg2d_eegmass_reco_conv_solution: TH2F  fg2d_eegmass_reco_conv_solution_icent0_file0
[OK] clone result mb_file0_fg2d_eegmass_reco_conv_solution: TH2F  mb_file0_fg2d_eegmass_reco_conv_solution
[OK] built mb_file0_fg2d_eegmass_reco_conv_solution: integral=83076
[OK] clone source mb_all_fg2d_eegmass_reco_conv_solution: TH2F  mb_file0_fg2d_eegmass_reco_conv_solution

,config,pt_min,pt_max,pt_center,y_ee,e_ee,y_eeg,e_eeg,raw_eeg,pol2_eeg,eeg_over_ee,ee_over_eeg,fit_mean,fit_sigma,fit_chi2,fit_ndf
0,nominal,0.8,1.0,0.90,23925.000000,154.677083,3681.861528,74.753563,3803.074063,121.212534,0.153892,6.498072,0.131792,0.011378,340.891720,286
1,nominal,1.0,1.3,1.15,33140.000000,182.043951,5418.142628,88.593632,5660.953881,242.811253,0.163493,6.116487,0.131584,0.010937,350.186372,286
2,nominal,1.3,1.7,1.50,21209.000000,145.633101,4061.641274,73.692254,4222.673582,161.032308,0.191506,5.221781,0.131639,0.010963,401.823185,286
3,nominal,1.7,2.0,1.85,7817.000000,88.413800,1582.275728,45.240607,1632.126003,49.850275,0.202415,4.940353,0.131451,0.011145,302.953459,286
4,nominal,2.0,2.5,2.25,5822.000000,76.302031,1378.266399,40.575705,1358.017558,-20.248841,0.236734,4.224147,0.131723,0.011843,335.534808,286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,escale101,2.5,3.0,2.75,2023.000000,44.977772,556.331836,24.969987,523.023935,-33.307900,0.275003,3.636319,0.133163,0.012030,472.807972,286
136,escale101,3.0,4.0,3.50,1056.949024,32.511536,321.832142,18.652677,299.499222,-22.332919,0.304492,3.284162,0.133243,0.013094,376.128616,285
137,escale101,4.0,5.0,4.50,197.000000,14.035669,66.917072,8.214294,58.037037,-8.880035,0.339681,2.943942,0.132081,0.007748,205.713565,253
138,escale101,5.0,7.0,6.00,80.944853,9.000006,26.478217,4.945930,20.739464,-5.738753,0.327114,3.057036,0.132293,0.006345,105.165032,188
139,escale101,7.0,10.0,8.50,14.000000,3.741657,-35.968975,2.000000,4.000000,39.968975,-2.569212,-0.389224,0.135258,0.029402,0.000007,4

In [50]:

# -----------------------------------------------------------------------------
# pi0 peak extraction variations for systematic uncertainty
# These variations use the same data histograms as the central conversion cut
# and DO NOT vary the simulation correction.  They only change the pi0/eeg
# extraction procedure in data.
#
# Added configs:
#   pi0_int021  : larger counting window, m_eeγ < 0.21 GeV/c^2
#   pi0_pol1    : Gaussian + pol1 instead of Gaussian + pol2
#   pi0_fit035  : smaller fit window, upper fit bound 0.35 GeV/c^2
# -----------------------------------------------------------------------------

pi0_extraction_variations = [
    {
        "out_cfg": "pi0_int021",
        "base_cfg": "conv_tight",
        "label": "pi0 count window 0.09-0.21",
        "eeg_signal": (0.09, 0.21),
        "fit_xmin": 0.05,
        "fit_xmax": 0.78,
        "pol_order": 2,
    },
    {
        "out_cfg": "pi0_pol1",
        "base_cfg": "conv_tight",
        "label": "pi0 fit Gaussian+pol1",
        "eeg_signal": windows["eeg_signal"],
        "fit_xmin": 0.05,
        "fit_xmax": 0.78,
        "pol_order": 1,
    },
    {
        "out_cfg": "pi0_fit035",
        "base_cfg": "conv_tight",
        "label": "pi0 fit range upper 0.35",
        "eeg_signal": windows["eeg_signal"],
        "fit_xmin": 0.05,
        "fit_xmax": 0.35,
        "pol_order": 2,
    },
]


def fit_one_eeg_hist_test_var(h_sub, name="test_fit", fit_xmin=0.05, fit_xmax=0.78, pol_order=2):
    """Fit pi0 peak with Gaussian + polynomial background.

    The default reproduces fit_one_eeg_hist_test(): gaus + pol2, 0.05-0.78.
    The variation options are used only for the pi0 extraction systematic.
    """
    if not check_hist(h_sub, f"{name} input"):
        return None

    if h_sub.Integral() <= 0:
        print(f"[BAD] {name}: histogram integral <= 0, skip fit")
        return None

    tag = safe_root_name(f"{name}_{len(ROOT_KEEPALIVE)}")

    amp0 = max(h_sub.GetMaximum(), 1.0)
    mean0 = 0.135
    sigma0 = 0.018

    if pol_order == 0:
        formula = "gaus(0)+pol0(3)"
        npar = 4
    elif pol_order == 1:
        formula = "gaus(0)+pol1(3)"
        npar = 5
    elif pol_order == 2:
        formula = "gaus(0)+pol2(3)"
        npar = 6
    else:
        raise ValueError(f"Unsupported pol_order={pol_order}; use 0, 1, or 2")

    f = root.TF1(f"f_{tag}", formula, fit_xmin, fit_xmax)

    if not check_obj(f, f"TF1 f_{tag}"):
        return None

    root.SetOwnership(f, False)
    keep(f)

    pars = [amp0, mean0, sigma0, 0.0, 0.0, 0.0]
    for ip in range(npar):
        f.SetParameter(ip, pars[ip])

    f.SetParLimits(1, 0.10, 0.17)
    f.SetParLimits(2, 0.006, 0.050)

    print("Before fit variation:")
    print("  formula =", formula)
    print("  fit range =", fit_xmin, fit_xmax)
    print("  amp0 =", amp0)
    print("  mean0 =", mean0)
    print("  sigma0 =", sigma0)

    res = h_sub.Fit(f, "RQS0")

    print("After fit variation:")

    if not check_obj(f, f"TF1 after fit {tag}"):
        print("[BAD] Fit killed TF1 pointer")
        return None

    status = int(res.Status()) if res else -999

    print("  status =", status)
    print("  mean =", f.GetParameter(1))
    print("  sigma =", f.GetParameter(2))
    print("  chi2/ndf =", f.GetChisquare(), "/", f.GetNDF())

    return f


def poly_subtracted_yield_var(h, f, xmin, xmax, fit_xmin=0.05, fit_xmax=0.78, pol_order=2):
    """Integrate signal window after subtracting the fitted polynomial background.

    This follows the existing pol2_subtracted_yield convention exactly, but allows
    pol1/pol0 and different fit ranges.
    """
    if not check_hist(h, "poly yield hist"):
        return 0.0, 0.0, 0.0, 0.0

    if f is None or not check_obj(f, "poly yield fit"):
        print("[WARNING] No valid fit. Return raw integral without polynomial subtraction.")
        raw, raw_err = integral_range(h, xmin, xmax)
        return raw, raw_err, raw, 0.0

    if pol_order == 0:
        formula = "pol0"
    elif pol_order == 1:
        formula = "pol1"
    elif pol_order == 2:
        formula = "pol2"
    else:
        raise ValueError(f"Unsupported pol_order={pol_order}; use 0, 1, or 2")

    poly = root.TF1(
        f"poly{pol_order}_from_{safe_root_name(f.GetName())}_{len(ROOT_KEEPALIVE)}",
        formula,
        fit_xmin,
        fit_xmax
    )
    root.SetOwnership(poly, False)
    keep(poly)

    for ip in range(pol_order + 1):
        poly.SetParameter(ip, f.GetParameter(3 + ip))

    b1 = h.FindBin(xmin + 1e-3)
    b2 = h.FindBin(xmax - 1e-3)

    raw = 0.0
    bg = 0.0
    sig = 0.0
    err2 = 0.0

    for ib in range(b1, b2 + 1):
        x = h.GetBinCenter(ib)
        y = h.GetBinContent(ib)
        b = poly.Eval(x)

        raw += y
        bg += b
        sig += y - b
        err2 += h.GetBinError(ib)**2

    err = math.sqrt(err2)

    print(f"pol{pol_order}-subtracted yield:")
    print(f"  signal window = [{xmin}, {xmax}]")
    print(f"  raw = {raw:.3g}")
    print(f"  pol{pol_order} = {bg:.3g}")
    print(f"  signal = {sig:.3g} +/- {err:.3g}")

    return sig, err, raw, bg


def one_bin_result_mb_pi0var(out_cfg, base_cfg, mb, pt_min, pt_max,
                            eeg_signal=None, fit_xmin=0.05, fit_xmax=0.78, pol_order=2):
    print("="*80)
    print(f"one_bin_result_mb_pi0var out_cfg={out_cfg}, base_cfg={base_cfg}, pt=[{pt_min},{pt_max}]")
    print(f"  eeg_signal={eeg_signal}, fit=[{fit_xmin},{fit_xmax}], pol_order={pol_order}")

    if eeg_signal is None:
        eeg_signal = windows["eeg_signal"]

    ee_info = get_ee_yield(
        mb["fg_ee"],
        mb["bg_ee"],
        pt_min,
        pt_max,
        out_cfg
    )

    eeg_pre = get_eeg_subtracted_hist_no_fit(
        mb["fg_eeg"],
        mb["bg_eeg"],
        pt_min,
        pt_max,
        out_cfg
    )

    f = fit_one_eeg_hist_test_var(
        eeg_pre["h_sub"],
        f"eeg_mb_{out_cfg}_pt{pt_min:g}_{pt_max:g}",
        fit_xmin=fit_xmin,
        fit_xmax=fit_xmax,
        pol_order=pol_order,
    )

    y_eeg, e_eeg, raw_eeg, poly_eeg = poly_subtracted_yield_var(
        eeg_pre["h_sub"],
        f,
        eeg_signal[0],
        eeg_signal[1],
        fit_xmin=fit_xmin,
        fit_xmax=fit_xmax,
        pol_order=pol_order,
    )

    y_ee = ee_info["yield"]
    e_ee = ee_info["yield_err"]

    eeg_over_ee = y_eeg / y_ee if y_ee != 0 else float("nan")
    ee_over_eeg = y_ee / y_eeg if y_eeg != 0 else float("nan")

    print("FINAL MB PI0 VAR ONE BIN")
    print(f"  Yee        = {y_ee:.6g} +/- {e_ee:.6g}")
    print(f"  Yeeg       = {y_eeg:.6g} +/- {e_eeg:.6g}")
    print(f"  eeg / ee   = {eeg_over_ee:.6g}")
    print(f"  ee / eeg   = {ee_over_eeg:.6g}")

    return {
        "cfg": out_cfg,
        "base_cfg": base_cfg,
        "pt_min": pt_min,
        "pt_max": pt_max,
        "ee": ee_info,
        "eeg_pre": eeg_pre,
        "fit": f,
        "y_ee": y_ee,
        "e_ee": e_ee,
        "y_eeg": y_eeg,
        "e_eeg": e_eeg,
        "raw_eeg": raw_eeg,
        "pol2_eeg": poly_eeg,   # keep existing column name used downstream
        "eeg_over_ee": eeg_over_ee,
        "ee_over_eeg": ee_over_eeg,
        "eeg_signal_low": eeg_signal[0],
        "eeg_signal_high": eeg_signal[1],
        "fit_xmin": fit_xmin,
        "fit_xmax": fit_xmax,
        "pol_order": pol_order,
    }


def run_pt_bins_for_config_pi0var(out_cfg, base_cfg, mb, save_canvases=False,
                                  eeg_signal=None, fit_xmin=0.05, fit_xmax=0.78, pol_order=2):
    rows = []
    results = {}

    for ipt in range(len(pt_bins) - 1):
        pt_min = pt_bins[ipt]
        pt_max = pt_bins[ipt + 1]

        print("\n")
        print("#"*80)
        print(f"Running pi0 extraction variation {out_cfg}: pT [{pt_min}, {pt_max})")

        res = one_bin_result_mb_pi0var(
            out_cfg,
            base_cfg,
            mb,
            pt_min,
            pt_max,
            eeg_signal=eeg_signal,
            fit_xmin=fit_xmin,
            fit_xmax=fit_xmax,
            pol_order=pol_order,
        )
        results[(pt_min, pt_max)] = res

        if save_canvases:
            tag = f"{out_cfg}_mb_pt{str(pt_min).replace('.','p')}_{str(pt_max).replace('.','p')}"
            save_one_bin_canvas(res, tag)

        row = {
            "config": out_cfg,
            "base_config": base_cfg,
            "pt_min": pt_min,
            "pt_max": pt_max,
            "pt_center": 0.5 * (pt_min + pt_max),

            "y_ee": res["y_ee"],
            "e_ee": res["e_ee"],
            "y_eeg": res["y_eeg"],
            "e_eeg": res["e_eeg"],

            "raw_eeg": res["raw_eeg"],
            "pol2_eeg": res["pol2_eeg"],

            "eeg_over_ee": res["eeg_over_ee"],
            "ee_over_eeg": res["ee_over_eeg"],

            "fit_mean": res["fit"].GetParameter(1) if res["fit"] else float("nan"),
            "fit_sigma": abs(res["fit"].GetParameter(2)) if res["fit"] else float("nan"),
            "fit_chi2": res["fit"].GetChisquare() if res["fit"] else float("nan"),
            "fit_ndf": res["fit"].GetNDF() if res["fit"] else -999,

            "eeg_signal_low": res["eeg_signal_low"],
            "eeg_signal_high": res["eeg_signal_high"],
            "fit_xmin": res["fit_xmin"],
            "fit_xmax": res["fit_xmax"],
            "pol_order": res["pol_order"],
        }

        rows.append(row)

    df = pd.DataFrame(rows)
    return df, results


# Run pi0 extraction variations on the central data cut only.
# The simulation correction is not varied: make_rgamma_graph_for_config_fox()
# will map these configs to the same conv_tight simulation correction.
pi0_var_dfs = []
pi0_var_results = {}

for var in pi0_extraction_variations:
    out_cfg = var["out_cfg"]
    base_cfg = var["base_cfg"]

    print("\n\n")
    print("="*100)
    print(f"BUILDING MB HISTOGRAMS FOR PI0 VARIATION {out_cfg} FROM BASE {base_cfg}")
    print("="*100)

    mb_base = build_mb_set(hists, base_cfg)

    df_var, results_var = run_pt_bins_for_config_pi0var(
        out_cfg,
        base_cfg,
        mb_base,
        save_canvases=False,
        eeg_signal=var["eeg_signal"],
        fit_xmin=var["fit_xmin"],
        fit_xmax=var["fit_xmax"],
        pol_order=var["pol_order"],
    )

    pi0_var_dfs.append(df_var)
    pi0_var_results[out_cfg] = results_var

if len(pi0_var_dfs) > 0:
    df_pi0_variations = pd.concat(pi0_var_dfs, ignore_index=True)
    df_all = pd.concat([df_all, df_pi0_variations], ignore_index=True)
    df_all.to_csv(f"{fit_out_dir}/yields_all_configs_mb_with_pi0_variations.csv", index=False)

df_pi0_variations if len(pi0_var_dfs) > 0 else None

====================================================================================================
BUILDING MB HISTOGRAMS FOR PI0 VARIATION pi0_int021 FROM BASE conv_tight
====================================================================================================
[OK] clone source mb_file0_fg2d_eemass_reco_conv_tight: TH2F  fg2d_eemass_reco_conv_tight_icent0_file0
[OK] clone result mb_file0_fg2d_eemass_reco_conv_tight: TH2F  mb_file0_fg2d_eemass_reco_conv_tight
[OK] built mb_file0_fg2d_eemass_reco_conv_tight: integral=68372
[OK] clone source mb_all_fg2d_eemass_reco_conv_tight: TH2F  mb_file0_fg2d_eemass_reco_conv_tight
[OK] clone result mb_all_fg2d_eemass_reco_conv_tight: TH2F  mb_all_fg2d_eemass_reco_conv_tight
[OK] built mb_all_fg2d_eemass_reco_conv_tight: integral=68372
[OK] clone source mb_file0_bg2d_eemass_reco_conv_tight: TH2F  bg2d_eemass_reco_conv_tight_icent0_file0
[OK] clone result mb_file0_bg2d_eemass_reco_conv_tight: TH2F  mb_file0_bg2d_eemass_reco_conv_tight
[OK] built mb_file0_bg2d_eemass_reco_conv_tight: integral=1.01459e+08
[OK] clone source mb_all_bg2d_eemass_reco_conv_tight: TH2F  mb_file0_bg2d_eemass_reco_conv_tight
[OK] clone result mb_all_bg2d_eemass_reco_conv_tight: TH2F  mb_all_bg2d_eemass_reco_conv_tight
[OK] built mb_all_bg2d_eemass_reco_conv_tight: integral=1.01459e+08
[OK] clone source mb_file0_fg2d_eegmass_reco_conv_tight: TH2F  fg2d_eegmass_reco_conv_tight_icent0_file0
[OK] clone result mb_file0_fg2d_eegmass_reco_conv_tight: TH2F  mb_file0_fg2d_eegmass_reco_conv_tight
[OK] built mb_file0_fg2d_eegmass_reco_conv_tight: integral=45821
[OK] clone source mb_all_fg2d_eegmass_reco_conv_tight: TH2F  mb_file0_fg2d_eegmass_reco_conv_tight
[OK] clone result mb_all_fg2d_eegmass_reco_conv_tight: TH2F  mb_all_fg2d_eegmass_reco_conv_tight
[OK] built mb_all_fg2d_eegmass_reco_conv_tight: integral=45821
[OK] clone source mb_file0_bg2d_eegmass_reco_conv_tight: TH2F  bg2d_eegmass_reco_conv_tight_icent0_file0
[OK] clone result mb_file0_bg2d_eegmass_reco_conv_tight: TH2F  mb_file0_bg2d_eegmass_reco_conv_tight
[OK] built mb_file0_bg2d_eegmass_reco_conv_tight: integral=424364
[OK] clone source mb_all_bg2d_eegmass_reco_conv_tight: TH2F  mb_file0_bg2d_eegmass_reco_conv_tight
[OK] clone result mb_all_bg2d_eegmass_reco_conv_tight: TH2F  mb_all_bg2d_eegmass_reco_conv_tight
[OK] built mb_all_bg2d_eegmass_reco_conv_tight: integral=424364


################################################################################
Running pi0 extraction variation pi0_int021: pT [0.8, 1.0)
================================================================================
one_bin_result_mb_pi0var out_cfg=pi0_int021, base_cfg=conv_tight, pt=[0.8,1.0]
  eeg_signal=(0.09, 0.21), fit=[0.05,0.78], pol_order=2
[OK] project source h_ee_fg_pi0_int021_pt0.8_1: TH2F  mb_all_fg2d_eemass_reco_conv_tight
project_mass_in_pt: h_ee_fg_pi0_int021_pt0.8_1
  pt range = [0.8, 1.0)
  y bins   = 9 to 10
[OK] projection h_ee_fg_pi0_int021_pt0.8_1: TH1D  h_ee_fg_pi0_int021_pt0.8_1
  proj integral = 1.5e+04
[OK] project source h_ee_bg_pi0_int021_pt0.8_1: TH2F  mb_all_bg2d_eemass_reco_conv_tight
project_mass_in_pt: h_ee_bg_pi0_int021_pt0.8_1
  pt range = [0.8, 1.0)
  y bins   = 9 to 10
[OK] projection h_ee_bg_pi0_int021_pt0.8_1: TH1D  h_ee_bg_pi0_int021_pt0.8_1
  proj integral = 1.19e+07
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_pi0_int021_pt0.8_1
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_pi0_int021_pt0.8_1
sideband [0.2, 0.75]: FG=0, BG=9.24e+06
  scale = 0
[OK] clone source h_ee_bg_scaled_pi0_int021_pt0.8_1: TH1D  h_ee_bg_pi0_int021_pt0.8_1
[OK] clone result h_ee_bg_scaled_pi0_int021_pt0.8_1: TH1D  h_ee_bg_scaled_pi0_int021_pt0.8_1
[OK] clone source h_ee_sub_pi0_int021_pt0.8_1: TH1D  h_ee_fg_pi0_int021_pt0.8_1
[OK] clone result h_ee_sub_pi0_int021_pt0.8_1: TH1D  h_ee_sub_pi0_int021_pt0.8_1
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_pi0_int021_pt0.8_1
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_pi0_int021_pt0.8_1
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_pi0_int021_pt0.8_1
EE yield:
  FG signal = 1.5e+04
  BG signal = 0
  SUB       = 1.5e+04 +/- 123
[OK] project source h_eeg_fg_pi0_int021_pt0.8_1: TH2F  mb_all_fg2d_eegmass_reco_conv_tight
project_mass_in_pt: h_eeg_fg_pi0_int021_pt0.8_1
  pt range = [0.8, 1.0)
  y bins   = 9 to 10
[OK] projection h_eeg_fg_pi0_int021_pt0.8_1: TH1D  h_eeg_fg_pi0_int021_pt0.8_1
  proj integral = 9.39e+03
[OK] project source h_eeg_bg_pi0_int021_pt0.8_1: TH2F  mb_all_bg2d_eegmass_reco_conv_tight
project_mass_in_pt: h_eeg_bg_pi0_int021_pt0.8_1
  pt range = [0.8, 1.0)
  y bins   = 9 to 10
[OK] projection h_eeg_bg_pi0_int021_pt0.8_1: TH1D  h_eeg_bg_pi0_int021_pt0.8_1
  proj integral = 1.01e+05
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_pi0_int021_pt0.8_1
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_pi0_int021_pt0.8_1
sideband [0.2, 0.8]: FG=4.54e+03, BG=6.67e+04
  scale = 0.0679452
[OK] clone source h_eeg_bg_scaled_pi0_int021_pt0.8_1: TH1D  h_eeg_bg_pi0_int021_pt0.8_1
[OK] clone result h_eeg_bg_scaled_pi0_int021_pt0.8_1: TH1D  h_eeg_bg_scaled_pi0_int021_pt0.8_1
[OK] clone source h_eeg_sub_pi0_int021_pt0.8_1: TH1D  h_eeg_fg_pi0_int021_pt0.8_1
[OK] clone result h_eeg_sub_pi0_int021_pt0.8_1: TH1D  h_eeg_sub_pi0_int021_pt0.8_1
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_pi0_int021_pt0.8_1
EEG after mixed-BG subtraction, before fit:
  raw signal window = 2.41e+03 +/- 59.3
[OK] eeg_mb_pi0_int021_pt0.8_1 input: TH1D  h_eeg_sub_pi0_int021_pt0.8_1
     entries = 634
     integral = 2.5e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_pi0_int021_pt0_8_1_1668: TF1  f_eeg_mb_pi0_int021_pt0_8_1_1668
Before fit variation:
  formula = gaus(0)+pol2(3)
  fit range = 0.05 0.78
  amp0 = 224.45261817364596
  mean0 = 0.135
  sigma0 = 0.018
After fit variation:
[OK] TF1 after fit eeg_mb_pi0_int021_pt0_8_1_1668: TF1  f_eeg_mb_pi0_int021_pt0_8_1_1668
  status = 0
  mean = 0.13226513596574221
  sigma = 0.01061486894781033
  chi2/ndf = 397.2764914015144 / 286
[OK] poly yield hist: TH1D  h_eeg_sub_pi0_int021_pt0.8_1
     entries = 634
     integral = 2.5e+03
     nbinsX = 400, nbinsY = 1
[OK] poly yield fit: TF1  f_eeg_mb_pi0_int021_pt0_8_1_1668
pol2-subtracted yield:
  signal window = [0.09, 0.21]
  raw = 2.43e+03
  pol2 = 90.1
  signal = 2.34e+03 +/- 61.8
FINAL MB PI0 VAR ONE BIN
  Yee        = 15012 +/- 122.523
  Yeeg       = 2338.44 +/- 61.7934
  eeg / ee   = 0.155771
  ee / eeg   = 6.41968


################################################################################
Running pi0 extraction variation pi0_int021: pT [1.0, 1.3)
================================================================================
one_bin_result_mb_pi0var out_cfg=pi0_int021, base_cfg=conv_tight, pt=[1.0,1.3]
  eeg_signal=(0.09, 0.21), fit=[0.05,0.78], pol_order=2
[OK] project source h_ee_fg_pi0_int021_pt1_1.3: TH2F  mb_all_fg2d_eemass_reco_conv_tight
project_mass_in_pt: h_ee_fg_pi0_int021_pt1_1.3
  pt range = [1.0, 1.3)
  y bins   = 11 to 13
[OK] projection h_ee_fg_pi0_int021_pt1_1.3: TH1D  h_ee_fg_pi0_int021_pt1_1.3
  proj integral = 2.14e+04
[OK] project source h_ee_bg_pi0_int021_pt1_1.3: TH2F  mb_all_bg2d_eemass_reco_conv_tight
project_mass_in_pt: h_ee_bg_pi0_int021_pt1_1.3
  pt range = [1.0, 1.3)
  y bins   = 11 to 13
[OK] projection h_ee_bg_pi0_int021_pt1_1.3: TH1D  h_ee_bg_pi0_int021_pt1_1.3
  proj integral = 8.04e+06
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_pi0_int021_pt1_1.3
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_pi0_int021_pt1_1.3
sideband [0.2, 0.75]: FG=0, BG=5.89e+06
  scale = 0
[OK] clone source h_ee_bg_scaled_pi0_int021_pt1_1.3: TH1D  h_ee_bg_pi0_int021_pt1_1.3
[OK] clone result h_ee_bg_scaled_pi0_int021_pt1_1.3: TH1D  h_ee_bg_scaled_pi0_int021_pt1_1.3
[OK] clone source h_ee_sub_pi0_int021_pt1_1.3: TH1D  h_ee_fg_pi0_int021_pt1_1.3
[OK] clone result h_ee_sub_pi0_int021_pt1_1.3: TH1D  h_ee_sub_pi0_int021_pt1_1.3
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_pi0_int021_pt1_1.3
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_pi0_int021_pt1_1.3
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_pi0_int021_pt1_1.3
EE yield:
  FG signal = 2.14e+04
  BG signal = 0
  SUB       = 2.14e+04 +/- 146
[OK] project source h_eeg_fg_pi0_int021_pt1_1.3: TH2F  mb_all_fg2d_eegmass_reco_conv_tight
project_mass_in_pt: h_eeg_fg_pi0_int021_pt1_1.3
  pt range = [1.0, 1.3)
  y bins   = 11 to 13
[OK] projection h_eeg_fg_pi0_int021_pt1_1.3: TH1D  h_eeg_fg_pi0_int021_pt1_1.3
  proj integral = 1.34e+04
[OK] project source h_eeg_bg_pi0_int021_pt1_1.3: TH2F  mb_all_bg2d_eegmass_reco_conv_tight
project_mass_in_pt: h_eeg_bg_pi0_int021_pt1_1.3
  pt range = [1.0, 1.3)
  y bins   = 11 to 13
[OK] projection h_eeg_bg_pi0_int021_pt1_1.3: TH1D  h_eeg_bg_pi0_int021_pt1_1.3
  proj integral = 1.28e+05
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_pi0_int021_pt1_1.3
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_pi0_int021_pt1_1.3
sideband [0.2, 0.8]: FG=7.11e+03, BG=9.66e+04
  scale = 0.0735669
[OK] clone source h_eeg_bg_scaled_pi0_int021_pt1_1.3: TH1D  h_eeg_bg_pi0_int021_pt1_1.3
[OK] clone result h_eeg_bg_scaled_pi0_int021_pt1_1.3: TH1D  h_eeg_bg_scaled_pi0_int021_pt1_1.3
[OK] clone source h_eeg_sub_pi0_int021_pt1_1.3: TH1D  h_eeg_fg_pi0_int021_pt1_1.3
[OK] clone result h_eeg_sub_pi0_int021_pt1_1.3: TH1D  h_eeg_sub_pi0_int021_pt1_1.3
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_pi0_int021_pt1_1.3
EEG after mixed-BG subtraction, before fit:
  raw signal window = 3.61e+03 +/- 70.9
[OK] eeg_mb_pi0_int021_pt1_1.3 input: TH1D  h_eeg_sub_pi0_int021_pt1_1.3
     entries = 1.13e+03
     integral = 3.99e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_pi0_int021_pt1_1_3_1678: TF1  f_eeg_mb_pi0_int021_pt1_1_3_1678
Before fit variation:
  formula = gaus(0)+pol2(3)
  fit range = 0.05 0.78
  amp0 = 351.77771566983415
  mean0 = 0.135
  sigma0 = 0.018
After fit variation:
[OK] TF1 after fit eeg_mb_pi0_int021_pt1_1_3_1678: TF1  f_eeg_mb_pi0_int021_pt1_1_3_1678
  status = 0
  mean = 0.13222329424213491
  sigma = 0.010408891055981686
  chi2/ndf = 355.098008281446 / 286
[OK] poly yield hist: TH1D  h_eeg_sub_pi0_int021_pt1_1.3
     entries = 1.13e+03
     integral = 3.99e+03
     nbinsX = 400, nbinsY = 1
[OK] poly yield fit: TF1  f_eeg_mb_pi0_int021_pt1_1_3_1678
pol2-subtracted yield:
  signal window = [0.09, 0.21]
  raw = 3.61e+03
  pol2 = 135
  signal = 3.48e+03 +/- 73.4
FINAL MB PI0 VAR ONE BIN
  Yee        = 21373 +/- 146.195
  Yeeg       = 3475.03 +/- 73.4236
  eeg / ee   = 0.16259
  ee / eeg   = 6.15045


################################################################################
Running pi0 extraction variation pi0_int021: pT [1.3, 1.7)
================================================================================
one_bin_result_mb_pi0var out_cfg=pi0_int021, base_cfg=conv_tight, pt=[1.3,1.7]
  eeg_signal=(0.09, 0.21), fit=[0.05,0.78], pol_order=2
[OK] project source h_ee_fg_pi0_int021_pt1.3_1.7: TH2F  mb_all_fg2d_eemass_reco_conv_tight
project_mass_in_pt: h_ee_fg_pi0_int021_pt1.3_1.7
  pt range = [1.3, 1.7)
  y bins   = 14 to 17
[OK] projection h_ee_fg_pi0_int021_pt1.3_1.7: TH1D  h_ee_fg_pi0_int021_pt1.3_1.7
  proj integral = 1.45e+04
[OK] project source h_ee_bg_pi0_int021_pt1.3_1.7: TH2F  mb_all_bg2d_eemass_reco_conv_tight
project_mass_in_pt: h_ee_bg_pi0_int021_pt1.3_1.7
  pt range = [1.3, 1.7)
  y bins   = 14 to 17
[OK] projection h_ee_bg_pi0_int021_pt1.3_1.7: TH1D  h_ee_bg_pi0_int021_pt1.3_1.7
  proj integral = 3.3e+06
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_pi0_int021_pt1.3_1.7
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_pi0_int021_pt1.3_1.7
sideband [0.2, 0.75]: FG=0, BG=2.39e+06
  scale = 0
[OK] clone source h_ee_bg_scaled_pi0_int021_pt1.3_1.7: TH1D  h_ee_bg_pi0_int021_pt1.3_1.7
[OK] clone result h_ee_bg_scaled_pi0_int021_pt1.3_1.7: TH1D  h_ee_bg_scaled_pi0_int021_pt1.3_1.7
[OK] clone source h_ee_sub_pi0_int021_pt1.3_1.7: TH1D  h_ee_fg_pi0_int021_pt1.3_1.7
[OK] clone result h_ee_sub_pi0_int021_pt1.3_1.7: TH1D  h_ee_sub_pi0_int021_pt1.3_1.7
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_pi0_int021_pt1.3_1.7
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_pi0_int021_pt1.3_1.7
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_pi0_int021_pt1.3_1.7
EE yield:
  FG signal = 1.45e+04
  BG signal = 0
  SUB       = 1.45e+04 +/- 120
[OK] project source h_eeg_fg_pi0_int021_pt1.3_1.7: TH2F  mb_all_fg2d_eegmass_reco_conv_tight
project_mass_in_pt: h_eeg_fg_pi0_int021_pt1.3_1.7
  pt range = [1.3, 1.7)
  y bins   = 14 to 17
[OK] projection h_eeg_fg_pi0_int021_pt1.3_1.7: TH1D  h_eeg_fg_pi0_int021_pt1.3_1.7
  proj integral = 9.91e+03
[OK] project source h_eeg_bg_pi0_int021_pt1.3_1.7: TH2F  mb_all_bg2d_eegmass_reco_conv_tight
project_mass_in_pt: h_eeg_bg_pi0_int021_pt1.3_1.7
  pt range = [1.3, 1.7)
  y bins   = 14 to 17
[OK] projection h_eeg_bg_pi0_int021_pt1.3_1.7: TH1D  h_eeg_bg_pi0_int021_pt1.3_1.7
  proj integral = 8.79e+04
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_pi0_int021_pt1.3_1.7
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_pi0_int021_pt1.3_1.7
sideband [0.2, 0.8]: FG=5.18e+03, BG=6.87e+04
  scale = 0.0754736
[OK] clone source h_eeg_bg_scaled_pi0_int021_pt1.3_1.7: TH1D  h_eeg_bg_pi0_int021_pt1.3_1.7
[OK] clone result h_eeg_bg_scaled_pi0_int021_pt1.3_1.7: TH1D  h_eeg_bg_scaled_pi0_int021_pt1.3_1.7
[OK] clone source h_eeg_sub_pi0_int021_pt1.3_1.7: TH1D  h_eeg_fg_pi0_int021_pt1.3_1.7
[OK] clone result h_eeg_sub_pi0_int021_pt1.3_1.7: TH1D  h_eeg_sub_pi0_int021_pt1.3_1.7
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_pi0_int021_pt1.3_1.7
EEG after mixed-BG subtraction, before fit:
  raw signal window = 2.86e+03 +/- 60.8
[OK] eeg_mb_pi0_int021_pt1.3_1.7 input: TH1D  h_eeg_sub_pi0_int021_pt1.3_1.7
     entries = 1.03e+03
     integral = 3.27e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_pi0_int021_pt1_3_1_7_1688: TF1  f_eeg_mb_pi0_int021_pt1_3_1_7_1688
Before fit variation:
  formula = gaus(0)+pol2(3)
  fit range = 0.05 0.78
  amp0 = 261.7730694741747
  mean0 = 0.135
  sigma0 = 0.018
After fit variation:
[OK] TF1 after fit eeg_mb_pi0_int021_pt1_3_1_7_1688: TF1  f_eeg_mb_pi0_int021_pt1_3_1_7_1688
  status = 0
  mean = 0.1321421422878735
  sigma = 0.010564751838624476
  chi2/ndf = 356.28768735471857 / 286
[OK] poly yield hist: TH1D  h_eeg_sub_pi0_int021_pt1.3_1.7
     entries = 1.03e+03
     integral = 3.27e+03
     nbinsX = 400, nbinsY = 1
[OK] poly yield fit: TF1  f_eeg_mb_pi0_int021_pt1_3_1_7_1688
pol2-subtracted yield:
  signal window = [0.09, 0.21]
  raw = 2.92e+03
  pol2 = 97.1
  signal = 2.82e+03 +/- 62.9
FINAL MB PI0 VAR ONE BIN
  Yee        = 14471 +/- 120.295
  Yeeg       = 2821.69 +/- 62.8522
  eeg / ee   = 0.194989
  ee / eeg   = 5.12848


################################################################################
Running pi0 extraction variation pi0_int021: pT [1.7, 2.0)
================================================================================
one_bin_result_mb_pi0var out_cfg=pi0_int021, base_cfg=conv_tight, pt=[1.7,2.0]
  eeg_signal=(0.09, 0.21), fit=[0.05,0.78], pol_order=2
[OK] project source h_ee_fg_pi0_int021_pt1.7_2: TH2F  mb_all_fg2d_eemass_reco_conv_tight
project_mass_in_pt: h_ee_fg_pi0_int021_pt1.7_2
  pt range = [1.7, 2.0)
  y bins   = 18 to 20
[OK] projection h_ee_fg_pi0_int021_pt1.7_2: TH1D  h_ee_fg_pi0_int021_pt1.7_2
  proj integral = 5.71e+03
[OK] project source h_ee_bg_pi0_int021_pt1.7_2: TH2F  mb_all_bg2d_eemass_reco_conv_tight
project_mass_in_pt: h_ee_bg_pi0_int021_pt1.7_2
  pt range = [1.7, 2.0)
  y bins   = 18 to 20
[OK] projection h_ee_bg_pi0_int021_pt1.7_2: TH1D  h_ee_bg_pi0_int021_pt1.7_2
  proj integral = 7.46e+05
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_pi0_int021_pt1.7_2
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_pi0_int021_pt1.7_2
sideband [0.2, 0.75]: FG=0, BG=5.35e+05
  scale = 0
[OK] clone source h_ee_bg_scaled_pi0_int021_pt1.7_2: TH1D  h_ee_bg_pi0_int021_pt1.7_2
[OK] clone result h_ee_bg_scaled_pi0_int021_pt1.7_2: TH1D  h_ee_bg_scaled_pi0_int021_pt1.7_2
[OK] clone source h_ee_sub_pi0_int021_pt1.7_2: TH1D  h_ee_fg_pi0_int021_pt1.7_2
[OK] clone result h_ee_sub_pi0_int021_pt1.7_2: TH1D  h_ee_sub_pi0_int021_pt1.7_2
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_pi0_int021_pt1.7_2
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_pi0_int021_pt1.7_2
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_pi0_int021_pt1.7_2
EE yield:
  FG signal = 5.7e+03
  BG signal = 0
  SUB       = 5.7e+03 +/- 75.5
[OK] project source h_eeg_fg_pi0_int021_pt1.7_2: TH2F  mb_all_fg2d_eegmass_reco_conv_tight
project_mass_in_pt: h_eeg_fg_pi0_int021_pt1.7_2
  pt range = [1.7, 2.0)
  y bins   = 18 to 20
[OK] projection h_eeg_fg_pi0_int021_pt1.7_2: TH1D  h_eeg_fg_pi0_int021_pt1.7_2
  proj integral = 4.12e+03
[OK] project source h_eeg_bg_pi0_int021_pt1.7_2: TH2F  mb_all_bg2d_eegmass_reco_conv_tight
project_mass_in_pt: h_eeg_bg_pi0_int021_pt1.7_2
  pt range = [1.7, 2.0)
  y bins   = 18 to 20
[OK] projection h_eeg_bg_pi0_int021_pt1.7_2: TH1D  h_eeg_bg_pi0_int021_pt1.7_2
  proj integral = 3.19e+04
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_pi0_int021_pt1.7_2
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_pi0_int021_pt1.7_2
sideband [0.2, 0.8]: FG=2.18e+03, BG=2.46e+04
  scale = 0.0885355
[OK] clone source h_eeg_bg_scaled_pi0_int021_pt1.7_2: TH1D  h_eeg_bg_pi0_int021_pt1.7_2
[OK] clone result h_eeg_bg_scaled_pi0_int021_pt1.7_2: TH1D  h_eeg_bg_scaled_pi0_int021_pt1.7_2
[OK] clone source h_eeg_sub_pi0_int021_pt1.7_2: TH1D  h_eeg_fg_pi0_int021_pt1.7_2
[OK] clone result h_eeg_sub_pi0_int021_pt1.7_2: TH1D  h_eeg_sub_pi0_int021_pt1.7_2
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_pi0_int021_pt1.7_2
EEG after mixed-BG subtraction, before fit:
  raw signal window = 1.17e+03 +/- 38.4
[OK] eeg_mb_pi0_int021_pt1.7_2 input: TH1D  h_eeg_sub_pi0_int021_pt1.7_2
     entries = 387
     integral = 1.3e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_pi0_int021_pt1_7_2_1698: TF1  f_eeg_mb_pi0_int021_pt1_7_2_1698
Before fit variation:
  formula = gaus(0)+pol2(3)
  fit range = 0.05 0.78
  amp0 = 114.65155150677133
  mean0 = 0.135
  sigma0 = 0.018
After fit variation:
[OK] TF1 after fit eeg_mb_pi0_int021_pt1_7_2_1698: TF1  f_eeg_mb_pi0_int021_pt1_7_2_1698
  status = 0
  mean = 0.1318272929421441
  sigma = 0.011038303233915593
  chi2/ndf = 314.184497099707 / 286
[OK] poly yield hist: TH1D  h_eeg_sub_pi0_int021_pt1.7_2
     entries = 387
     integral = 1.3e+03
     nbinsX = 400, nbinsY = 1
[OK] poly yield fit: TF1  f_eeg_mb_pi0_int021_pt1_7_2_1698
pol2-subtracted yield:
  signal window = [0.09, 0.21]
  raw = 1.19e+03
  pol2 = 18.1
  signal = 1.17e+03 +/- 39.6
FINAL MB PI0 VAR ONE BIN
  Yee        = 5698 +/- 75.4851
  Yeeg       = 1171.55 +/- 39.6361
  eeg / ee   = 0.205607
  ee / eeg   = 4.86364


################################################################################
Running pi0 extraction variation pi0_int021: pT [2.0, 2.5)
================================================================================
one_bin_result_mb_pi0var out_cfg=pi0_int021, base_cfg=conv_tight, pt=[2.0,2.5]
  eeg_signal=(0.09, 0.21), fit=[0.05,0.78], pol_order=2
[OK] project source h_ee_fg_pi0_int021_pt2_2.5: TH2F  mb_all_fg2d_eemass_reco_conv_tight
project_mass_in_pt: h_ee_fg_pi0_int021_pt2_2.5
  pt range = [2.0, 2.5)
  y bins   = 21 to 25
[OK] projection h_ee_fg_pi0_int021_pt2_2.5: TH1D  h_ee_fg_pi0_int021_pt2_2.5
  proj integral = 4.27e+03
[OK] project source h_ee_bg_pi0_int021_pt2_2.5: TH2F  mb_all_bg2d_eemass_reco_conv_tight
project_mass_in_pt: h_ee_bg_pi0_int021_pt2_2.5
  pt range = [2.0, 2.5)
  y bins   = 21 to 25
[OK] projection h_ee_bg_pi0_int021_pt2_2.5: TH1D  h_ee_bg_pi0_int021_pt2_2.5
  proj integral = 3.82e+05
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_pi0_int021_pt2_2.5
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_pi0_int021_pt2_2.5
sideband [0.2, 0.75]: FG=0, BG=2.67e+05
  scale = 0
[OK] clone source h_ee_bg_scaled_pi0_int021_pt2_2.5: TH1D  h_ee_bg_pi0_int021_pt2_2.5
[OK] clone result h_ee_bg_scaled_pi0_int021_pt2_2.5: TH1D  h_ee_bg_scaled_pi0_int021_pt2_2.5
[OK] clone source h_ee_sub_pi0_int021_pt2_2.5: TH1D  h_ee_fg_pi0_int021_pt2_2.5

,config,base_config,pt_min,pt_max,pt_center,y_ee,e_ee,y_eeg,e_eeg,raw_eeg,...,ee_over_eeg,fit_mean,fit_sigma,fit_chi2,fit_ndf,eeg_signal_low,eeg_signal_high,fit_xmin,fit_xmax,pol_order
0,pi0_int021,conv_tight,0.8,1.0,0.90,15012.000000,122.523467,2338.435979,61.793408,2428.578320,...,6.419675,0.132265,0.010615,3.972765e+02,286,0.09,0.21,0.05,0.78,2
1,pi0_int021,conv_tight,1.0,1.3,1.15,21373.000000,146.195075,3475.032183,73.423608,3610.288026,...,6.150447,0.132223,0.010409,3.550980e+02,286,0.09,0.21,0.05,0.78,2
2,pi0_int021,conv_tight,1.3,1.7,1.50,14471.000000,120.295470,2821.692087,62.852159,2918.805746,...,5.128483,0.132142,0.010565,3.562877e+02,286,0.09,0.21,0.05,0.78,2
3,pi0_int021,conv_tight,1.7,2.0,1.85,5698.000000,75.485098,1171.550320,39.636058,1189.664931,...,4.863641,0.131827,0.011038,3.141845e+02,286,0.09,0.21,0.05,0.78,2
4,pi0_int021,conv_tight,2.0,2.5,2.25,4251.000000,65.199693,1000.686045,35.281237,971.572822,...,4.248086,0.131844,0.011706,3.521355e+02,286,0.09,0.21,0.05,0.78,2
5,pi0_int021,conv_tight,2.5,3.0,2.75,1493.000000,38.639358,407.778391,21.695232,375.144852,...,3.661302,0.133710,0.011261,4.039675e+02,286,0.09,0.21,0.05,0.78,2
6,pi0_int021,conv_tight,3.0,4.0,3.50,782.000000,27.964263,245.975976,16.300965,220.118143,...,3.179172,0.133595,0.011940,3.623240e+02,285,0.09,0.21,0.05,0.78,2
7,pi0_int021,conv_tight,4.0,5.0,4.50,153.000000,12.369317,55.744275,7.347911,46.701431,...,2.744676,0.130751,0.006845,1.766787e+02,248,0.09,0.21,0.05,0.78,2
8,pi0_int021,conv_tight,5.0,7.0,6.00,58.944853,7.681152,22.218099,4.398911,16.100000,...,2.653011,0.139911,0.012595,9.102721e+01,183,0.09,0.21,0.05,0.78,2
9,pi0_int021,conv_tight,7.0,10.0,8.50,9.000000,3.000000,-45.996392,1.414214,2.000000,...,-0.195668,0.112039,0.027875,2.108576e-07,0,0.09,0.21,0.05,0.78,2
10,pi0_pol1,conv_tight,0.8,1.0,0.90,15012.000000,122.523467,2395.147688,59.290711,2409.040078,...,6.267672,0.132217,0.010838,4.207552e+02,287,0.09,0.19,0.05,0.78,1
11,pi0_pol1,conv_tight,1.0,1.3,1.15,21373.000000,146.195075,3539.523812,70.914723,3614.858953,...,6.038383,0.132190,0.010503,3.670856e+02,287,0.09,0.19,0.05,0.78,1
12,pi0_pol1,conv_tight,1.3,1.7,1.50,14471.000000,120.295470,2777.067041,60.773334,2861.244434,...,5.210893,0.132143,0.010565,3.562877e+02,287,0.09,0.19,0.05,0.78,1
13,pi0_pol1,conv_tight,1.7,2.0,1.85,5698.000000,75.485098,1156.673363,38.415035,1171.847493,...,4.926196,0.131822,0.011051,3.143140e+02,287,0.09,0.19,0.05,0.78,1
14,pi0_pol1,conv_tight,2.0,2.5,2.25,4251.000000,65.199693,1003.294128,34.544890,979.903806,...,4.237043,0.131849,0.011699,3.522548e+02,287,0.09,0.19,0.05,0.78,1
15,pi0_pol1,conv_tight,2.5,3.0,2.75,1493.000000,38.639358,402.460267,21.273438,376.015164,...,3.709683,0.133700,0.011267,4.043249e+02,287,0.09,0.19,0.05,0.78,1
16,pi0_pol1,conv_tight,3.0,4.0,3.50,782.000000,27.964263,240.541918,16.021623,219.291139,...,3.250993,0.133485,0.011973,3.841569e+02,286,0.09,0.19,0.05,0.78,1
17,pi0_pol1,conv_tight,4.0,5.0,4.50,153.000000,12.369317,55.357973,7.339470,47.488753,...,2.763830,0.130731,0.006895,1.772389e+02,249,0.09,0.19,0.05,0.78,1
18,pi0_pol1,conv_tight,5.0,7.0,6.00,58.944853,7.681152,22.239502,4.395590,16.341667,...,2.650457,0.138125,0.017297,9.165355e+01,184,0.09,0.19,0.05,0.78,1
19,pi0_pol1,conv_tight,7.0,10.0,8.50,9.000000,3.000000,-37.954641,1.414214,2.000000,...,-0.237125,0.142219,0.024653,2.380782e-06,0,0.09,0.19,0.05,0.78,1
20,pi0_fit035,conv_tight,0.8,1.0,0.90,15012.000000,122.523467,2299.214245,59.290711,2409.040078,...,6.529187,0.132240,0.010546,1.245344e+02,114,0.09,0.19,0.05,0.35,2
21,pi0_fit035,conv_tight,1.0,1.3,1.15,21373.000000,146.195075,3505.429052,70.914723,3614.858953,...,6.097114,0.132238,0.010424,1.644555e+02,114,0.09,0.19,0.05,0.35,2
22,pi0_fit035,conv_tight,1.3,1.7,1.50,14471.000000,120.295470,2715.608405,60.773334,2861.244434,...,5.328824,0.132116,0.010420,1.357392e+02,114,0.09,0.19,0.05,0.35,2
23,pi0_fit035,conv_tight,1.7,2.0,1.85,5698.000000,75.485098,1158.750885,38.415035,1171.847493,...,4.917364,0.131867,0.011047,1.070792e+02,114,0.09,0.19,0.05,0.35,2
24,pi0_fit035,conv_tight,2.0,2.5,2.25,4251.000000,65.199693,1003.556724,34.544890,979.903806,...,4.235934,0.131854,0.011700,1.584563e+02,114,0.09,0.19,0.05,0.35,2
25,pi0_fit035,conv_tight,2.5,3.0,2.75,1493.000000,38.639358,415.809715,21.273438,376.015164,...,3.590585,0.133835,0.011519,1.524653e+02,114,0.09,0.19,0.05,0.35,2
26,pi0_fit035,conv_tight,3.0,4.0,3.50,782.000000,27.964263,237.335249,16.021623,219.291139,...,3.294917,0.133611,0.011815,1.406483e+02,113,0.09,0.19,0.05,0.35,2
27,pi0_fit035,conv_tight,4.0,5.0,4.50,153.000000,12.369317,54.811029,7.339470,47.488753,...,2.791409,0.130767,0.006839,5.696468e+01,87,0.09,0.19,0.05,0.35,2
28,pi0_fit035,conv_tight,5.0,7.0,6.00,58.944853,7.681152,21.743992,4.395590,16.341667,...,2.710857,0.137620,0.014770,3.806068e+01,60,0.09,0.19,0.05,0.35,2
29,pi0_fit035,conv_tight,7.0,10.0,8.50,9.000000,3.000000,-19.858544,1.414214,2.000000,...,-0.453205,0.118427,0.019658,1.336369e-08,0,0.09,0.19,0.05,0.35,2

In [51]:
df_all = add_ratio_columns(df_all)

In [52]:
c_ratio = root.TCanvas("c_ratio_nominal", "c_ratio_nominal", 800, 600)

g_ee_over_eeg = make_ratio_graph_from_df(
    df_all[df_all.config == "nominal"],
    "ee_over_eeg",
    "ee_over_eeg_err",
    "g_ee_over_eeg_nominal",
    "ecore05; p_{T} (GeV/c); ee / eeg"
)

c_ratio = root.TCanvas("c_ratio_nominal", "c_ratio_nominal", 600, 500)
g_ee_over_eeg.GetYaxis().SetRangeUser(0, 15)
g_ee_over_eeg.Draw("AP")

c_ratio.Draw()

In [53]:
import numpy as np

pt_orange = np.array([
    0.898, 1.105, 1.302, 1.504, 1.705, 1.905,
    2.253, 2.753, 3.251, 3.752, 4.500, 5.998, 8.496
])

eff_orange = np.array([
    0.0855, 0.0964, 0.1061, 0.1171, 0.1270, 0.1407,
    0.1563, 0.1836, 0.2112, 0.2335, 0.2668, 0.3169, 0.3744
])

ef_graph_wenqing = root.TGraph(len(pt_orange), array('d', pt_orange), array('d', eff_orange))

In [54]:
c12 = root.TCanvas("c_efficiency", "c_efficiency", 800, 600)
ef_graph_wenqing.SetMarkerStyle(20)
ef_graph_wenqing.SetMarkerColor(root.kBlue)
ef_graph_wenqing.SetLineColor(root.kBlue)
ef_graph_wenqing.Draw("AP")
c12.Draw()

In [55]:
import numpy as np

# Cu+Au @ 200 GeV, 0-20%
# ratio = gamma_hadron / gamma_pi0

pt_ratio = np.array([
    0.55, 0.60, 0.70, 0.80, 0.90, 1.00,
    1.25, 1.50, 1.75, 2.00, 2.25, 2.50,
    2.75, 3.00, 3.50, 4.00, 4.50, 5.00,
    5.50, 6.00, 6.50, 7.00, 7.50, 8.00,
    8.50, 9.00, 9.50, 9.90
])

ratio_vals = np.array([
    1.09696, 1.11315, 1.13620, 1.14979, 1.15773, 1.16320,
    1.17504, 1.18419, 1.19127, 1.19712, 1.20184, 1.20584,
    1.20926, 1.21221, 1.21708, 1.22092, 1.22365, 1.22579,
    1.22739, 1.22838, 1.22922, 1.22976, 1.22995, 1.23024,
    1.23024, 1.23028, 1.22996, 1.22980
])

def gamma_hadron_over_gamma_pi0(pt):
    return np.interp(pt, pt_ratio, ratio_vals)

In [56]:
#drawing of gamma_hadron_over_gamma_pi0
array_pt_gamma_hadron_over_gamma_pi0 = array('d', [0.1*i for i in range(100)])
array_gamma_hadron_over_gamma_pi0 = array('d', [ gamma_hadron_over_gamma_pi0(array_pt_gamma_hadron_over_gamma_pi0[i]) for i in range(100)])

gr_gamma_hadron_over_gamma_pi0 = root.TGraph(100, array_pt_gamma_hadron_over_gamma_pi0, array_gamma_hadron_over_gamma_pi0)
c_gamma_hadron_over_gamma_pi0 = root.TCanvas("c_gamma_hadron_over_gamma_pi0", "Gamma Hadron Over Gamma Pi0", 800, 600)
gr_gamma_hadron_over_gamma_pi0.Draw("AL")
c_gamma_hadron_over_gamma_pi0.Draw()

In [57]:
#plotting r_gamma as g_ee_over_eeg * ef_graph_wenqing / gamma_hadron_over_gamma_pi0(pt) only for ecore05
c_final = root.TCanvas("c_final", "c_final", 800, 600)
g_final = root.TGraphErrors(len(df_all))
g_final.SetName("g_final")
g_final.SetTitle("Final; p_{T} (GeV/c); r_{#gamma}")
for i, row in df_all.iterrows():
    if row.config != "ecore05":
        continue
    pt = row.pt_center
    r_ee_eeg = row.ee_over_eeg
    eff = gamma_hadron_over_gamma_pi0(pt) / ef_graph_wenqing.Eval(pt)

    r_gamma = r_ee_eeg / eff

    g_final.SetPoint(i, pt, r_gamma)
    g_final.SetPointError(i, 0.5 * (row.pt_max - row.pt_min), 0.0)
g_final.SetMarkerStyle(20)
g_final.SetMarkerColor(root.kBlue)
g_final.SetLineColor(root.kBlue)
g_final.Draw("AP")
c_final.Draw()

In [58]:
ef_04_pt = [0.90,1.12,1.48,2.00,2.50,3.02,3.51,3.97,4.76]

ef_04_eps_t = [0.124,0.143,0.172,0.202,0.233,0.256,0.276,0.301,0.319]


ef_04_graph = root.TGraph(len(ef_04_pt), array('d', ef_04_pt), array('d', ef_04_eps_t))

In [59]:
#plotting r_gamma as g_ee_over_eeg * ef_graph_wenqing / gamma_hadron_over_gamma_pi0(pt)
c_final = root.TCanvas("c_final", "c_final", 800, 600)
g_final = root.TGraphErrors(len(df_all))
g_final.SetName("g_final")
g_final.SetTitle("Final; p_{T} (GeV/c); r_{#gamma}")
for i, row in df_all.iterrows():
    pt = row.pt_center
    r_ee_eeg = row.ee_over_eeg
    eff = gamma_hadron_over_gamma_pi0(pt) / ef_04_graph.Eval(pt)

    r_gamma = r_ee_eeg / eff

    g_final.SetPoint(i, pt, r_gamma)
    g_final.SetPointError(i, 0.5 * (row.pt_max - row.pt_min), 0.0)
g_final.SetMarkerStyle(20)
g_final.GetYaxis().SetRangeUser(0.8, 1.5)
g_final.GetXaxis().SetRangeUser(0., 4.0)
g_final.SetMarkerColor(root.kBlue)
g_final.SetLineColor(root.kBlue)
g_final.Draw("AP")
c_final.Draw()

In [60]:
def make_rgamma_graph_for_config(df, cfg, ef_graph, name_suffix=""):
    d = df[df["config"] == cfg].copy()
    d = d.sort_values("pt_center")

    g = root.TGraphErrors(len(d))
    g.SetName(f"g_rgamma_{cfg}{name_suffix}")
    g.SetTitle("Final; p_{T} (GeV/c); r_{#gamma}")

    for ip, row in enumerate(d.itertuples()):
        pt = row.pt_center

        r_ee_eeg = row.ee_over_eeg
        r_ee_eeg_err = getattr(row, "ee_over_eeg_err", 0.0)

        eff = gamma_hadron_over_gamma_pi0(pt) / ef_graph.Eval(pt)

        r_gamma = r_ee_eeg / eff
        r_gamma_err = r_ee_eeg_err / eff if eff != 0 else 0.0

        g.SetPoint(ip, pt, r_gamma)
        g.SetPointError(ip, 0.5 * (row.pt_max - row.pt_min), r_gamma_err)

    return g

In [61]:
configs_plot = [
    "nominal",
    "conv_solution",
    "conv_tight",
    "ecore04",
    "ecore05",
    "pte03",
    "pte04",
    "eid0",
    "eid1",
    "eid3",
    "chi2_4",
    "chi2_5",
    "escale099",
    "escale101",
]

colors = [
    root.kBlack,
    root.kBlue,
    root.kRed,
    root.kGreen + 2,
    root.kOrange + 7,
    root.kMagenta,
    root.kCyan + 2,
    root.kViolet,
    root.kAzure + 7,
    root.kPink + 7,
    root.kGray + 2,
    root.kSpring + 5,
    root.kOrange,
    root.kTeal + 3,
]

markers = [
    20, 21, 22, 23, 29, 33, 34,
    24, 25, 26, 27, 28, 30, 32
]

graphs_rgamma = {}

c_final = root.TCanvas("c_final_all_configs", "c_final_all_configs", 900, 700)

frame = root.TH2F(
    "frame_rgamma_all_configs",
    "Final; p_{T} (GeV/c); r_{#gamma}",
    100, 0.0, 10.0,
    100, 0.7, 2.5
)
frame.SetStats(0)
frame.Draw()

leg = root.TLegend(0.1, 0.6, 0.98, 0.85)
leg.SetNColumns(3)
leg.SetBorderSize(0)
leg.SetFillStyle(0)
leg.SetTextSize(0.046)

for i, cfg in enumerate(configs_plot):
    g = make_rgamma_graph_for_config(df_all, cfg, ef_04_graph)

    g.SetMarkerStyle(markers[i])
    g.SetMarkerSize(1.1)
    g.SetMarkerColor(colors[i])
    g.SetLineColor(colors[i])
    g.SetLineWidth(1)

    graphs_rgamma[cfg] = g

    draw_opt = "P same"
    g.Draw(draw_opt)

    leg.AddEntry(g, cfg, "p")

leg.Draw()

c_final.Draw()

In [62]:
#reading df_sim form csv and plotting r_gamma_sim = gamma_hadron_over_gamma_pi0(pt) on the same canvas
fit_out_dir = "output/fits"
df_sim = pd.read_csv(f"output/fits/sim_yields_all_configs_mb.csv")

In [63]:
df_sim

,config,pt_min,pt_max,pt_center,y_ee,e_ee,y_eeg,e_eeg,raw_eeg,pol2_eeg,eeg_over_ee,ee_over_eeg,fit_mean,fit_sigma,fit_chi2,fit_ndf
0,nominal,0.8,0.995,0.8975,2738.083708,46.145835,438.153868,11.329552,438.153868,0.0,0.160022,6.249137,0.132279,0.008861,489.555705,86
1,nominal,1.0,1.295,1.1475,3934.484697,33.546754,676.584223,8.788719,676.584223,0.0,0.171963,5.815218,0.133875,0.009836,1166.037413,86
2,nominal,1.3,1.995,1.6475,3302.634565,15.558163,695.263955,5.000941,695.263955,0.0,0.210518,4.750188,0.135806,0.011288,1277.185186,86
3,nominal,2.0,2.495,2.2475,639.196655,2.677181,159.896103,1.039669,159.896103,0.0,0.250152,3.997575,0.135845,0.011759,1462.536489,86
4,nominal,2.5,2.995,2.7475,226.308741,0.895339,61.946811,0.379888,61.946811,0.0,0.273727,3.653275,0.136209,0.011787,1679.459141,86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,escale101,2.5,2.995,2.7475,226.308741,0.895339,61.963678,0.379178,61.963678,0.0,0.273802,3.652281,0.136968,0.011774,1638.572727,86
122,escale101,3.0,3.995,3.4975,120.198171,0.357896,37.206886,0.171124,37.206886,0.0,0.309546,3.230536,0.137104,0.012240,1754.586450,86
123,escale101,4.0,4.995,4.4975,23.753568,0.068200,8.221260,0.036464,8.221260,0.0,0.346106,2.889286,0.137391,0.013305,1330.162434,86
124,escale101,5.0,6.995,5.9975,7.978312,0.018265,3.093288,0.010887,3.093288,0.0,0.387712,2.579234,0.137538,0.014357,1914.713341,86
125,escale101,7.0,9.995,8.4975,1.103741,0.002270,0.469998,0.001480,0.469998,0.0,0.425823,2.348396,0.138320,0.016558,2588.237794,86

In [64]:
df_all

,config,pt_min,pt_max,pt_center,y_ee,e_ee,y_eeg,e_eeg,raw_eeg,pol2_eeg,...,fit_chi2,fit_ndf,base_config,eeg_signal_low,eeg_signal_high,fit_xmin,fit_xmax,pol_order,eeg_over_ee_err,ee_over_eeg_err
0,nominal,0.8,1.0,0.90,23925.000000,154.677083,3681.861528,74.753563,3803.074063,121.212534,...,3.408917e+02,286,NaN,NaN,NaN,NaN,NaN,NaN,0.003279,0.138459
1,nominal,1.0,1.3,1.15,33140.000000,182.043951,5418.142628,88.593632,5660.953881,242.811253,...,3.501864e+02,286,NaN,NaN,NaN,NaN,NaN,NaN,0.002820,0.105505
2,nominal,1.3,1.7,1.50,21209.000000,145.633101,4061.641274,73.692254,4222.673582,161.032308,...,4.018232e+02,286,NaN,NaN,NaN,NaN,NaN,NaN,0.003715,0.101299
3,nominal,1.7,2.0,1.85,7817.000000,88.413800,1582.275728,45.240607,1632.126003,49.850275,...,3.029535e+02,286,NaN,NaN,NaN,NaN,NaN,NaN,0.006224,0.151906
4,nominal,2.0,2.5,2.25,5822.000000,76.302031,1378.266399,40.575705,1358.017558,-20.248841,...,3.355348e+02,286,NaN,NaN,NaN,NaN,NaN,NaN,0.007629,0.136124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,pi0_fit035,2.5,3.0,2.75,1493.000000,38.639358,415.809715,21.273438,376.015164,-39.794551,...,1.524653e+02,114,conv_tight,0.09,0.19,0.05,0.35,2.0,0.015968,0.205866
166,pi0_fit035,3.0,4.0,3.50,782.000000,27.964263,237.335249,16.021623,219.291139,-18.044109,...,1.406483e+02,113,conv_tight,0.09,0.19,0.05,0.35,2.0,0.023185,0.251708
167,pi0_fit035,4.0,5.0,4.50,153.000000,12.369317,54.811029,7.339470,47.488753,-7.322277,...,5.696468e+01,87,conv_tight,0.09,0.19,0.05,0.35,2.0,0.056035,0.436626
168,pi0_fit035,5.0,7.0,6.00,58.944853,7.681152,21.743992,4.395590,16.341667,-5.402325,...,3.806068e+01,60,conv_tight,0.09,0.19,0.05,0.35,2.0,0.088722,0.651995
169,pi0_fit035,7.0,10.0,8.50,9.000000,3.000000,-19.858544,1.414214,2.000000,21.858544,...,1.336369e-08,0,conv_tight,0.09,0.19,0.05,0.35,2.0,NaN,NaN

In [65]:
def get_epsf_from_df(df, cfg, name_suffix=""):
    d = df[df["config"] == cfg].copy()
    d = d.sort_values("pt_center")

    g = root.TGraphErrors(len(d))
    g.SetName(f"g_rgamma_{cfg}{name_suffix}")
    #g.SetTitle("Final; p_{T} (GeV/c); r_{#gamma}")

    for ip, row in enumerate(d.itertuples()):
        pt = row.pt_center

        r_ee_eeg = row.ee_over_eeg
        r_ee_eeg_err = getattr(row, "ee_over_eeg_err", 0.0)

        r_gamma = 1./r_ee_eeg if r_ee_eeg != 0 else 0.0
        r_gamma_err = 1./ r_ee_eeg_err if r_ee_eeg_err != 0 else 0.0

        g.SetPoint(ip, pt, r_gamma)
        g.SetPointError(ip, 0.5 * (row.pt_max - row.pt_min), r_gamma_err)

    return g

In [66]:
def make_rgamma_graph_for_config_new(df, cfg, ef_graph,new_sim_nominal, name_suffix=""):
    d = df[df["config"] == cfg].copy()
    d = d.sort_values("pt_center")

    g = root.TGraphErrors(len(d))
    g.SetName(f"g_rgamma_{cfg}{name_suffix}")
    g.SetTitle("Final; p_{T} (GeV/c); r_{#gamma}")
    new_sim = get_epsf_from_df(df_sim, cfg,f"{i}_{cfg}")

    for ip, row in enumerate(d.itertuples()):
        pt = row.pt_center

        r_ee_eeg = row.ee_over_eeg
        r_ee_eeg_err = getattr(row, "ee_over_eeg_err", 0.0)

        eff = gamma_hadron_over_gamma_pi0(pt) / new_sim.Eval(pt) #* new_sim_nominal.Eval(pt)  / ef_graph.Eval(pt)

        r_gamma = r_ee_eeg / eff
        r_gamma_err = r_ee_eeg_err / eff if eff != 0 else 0.0

        g.SetPoint(ip, pt, r_gamma)
        g.SetPointError(ip, 0.5 * (row.pt_max - row.pt_min), r_gamma_err)

    return g

In [67]:
def make_rgamma_graph_for_config_fox(df, cfg, ef_graph,new_sim_nominal, name_suffix=""):
    if cfg == "ecore04": print("Processing ecore04")
    d = df[df["config"] == cfg].copy()
    d = d.sort_values("pt_center")

    g = root.TGraphErrors(len(d))
    g.SetName(f"g_rgamma_{cfg}{name_suffix}")
    g.SetTitle("Final; p_{T} (GeV/c); r_{#gamma}")
    cfg_sim = "nominal"
    if cfg == "ecore05":
        cfg_sim = "ecore05"
    if cfg == "ecore04":
        cfg_sim = "ecore04"
    new_sim = get_epsf_from_df(df_sim, cfg_sim,f"{i}_{cfg}")

    for ip, row in enumerate(d.itertuples()):
        pt = row.pt_center

        r_ee_eeg = row.ee_over_eeg
        r_ee_eeg_err = getattr(row, "ee_over_eeg_err", 0.0)

        eff = gamma_hadron_over_gamma_pi0(pt) / new_sim.Eval(pt) 

        r_gamma = r_ee_eeg / eff
        r_gamma_err = r_ee_eeg_err / eff if eff != 0 else 0.0

        g.SetPoint(ip, pt, r_gamma)
        g.SetPointError(ip, 0.5 * (row.pt_max - row.pt_min), r_gamma_err)

    return g

In [68]:
import numpy as np

pt_wenq = [0.9, 1.1, 1.3, 1.5, 1.7, 1.9, 2.25, 2.75, 3.25, 3.75, 4.5, 6.0, 8.5]
pt_err = [0.05] * len(pt_wenq)  # Assuming a constant error of 0.1 GeV/c for all points

rgamma_50_60 = [1.117, 1.145, 1.114, 1.144, 1.149, 1.138, 1.164, 1.159, 1.203, 1.182, 1.176, 1.202, 1.816]

stat_50_60 = [0.016, 0.019, 0.012, 0.013, 0.015, 0.017, 0.014, 0.022, 0.033, 0.047, 0.051, 0.072, 0.297]

syst_50_60 = [0.054, 0.055, 0.053, 0.055, 0.055, 0.054, 0.054, 0.053, 0.054, 0.052, 0.053, 0.050, 0.074]

rgamma_20_30 = [1.134, 1.141, 1.148, 1.146, 1.187, 1.205, 1.236, 1.243, 1.320, 1.350, 1.340, 1.813, 1.697]

stat_20_30 = [0.018, 0.014, 0.014, 0.014, 0.017, 0.019, 0.018, 0.024, 0.038, 0.036, 0.051, 0.118, 0.195]

syst_20_30 = [0.051, 0.051, 0.054, 0.052, 0.053, 0.054, 0.055, 0.054, 0.057, 0.057, 0.055, 0.073, 0.068]

rgamma_30_40 = [1.132, 1.140, 1.145, 1.151, 1.151, 1.195, 1.218, 1.217, 1.250, 1.286, 1.346, 1.436, 1.832]

stat_30_40 = [0.018, 0.014, 0.014, 0.015, 0.016, 0.019, 0.018, 0.023, 0.035, 0.032, 0.052, 0.082, 0.247]

syst_30_40 = [0.052, 0.052, 0.054, 0.053, 0.052, 0.054, 0.055, 0.054, 0.055, 0.055, 0.055, 0.058, 0.074]

graph_wenqing_rg = root.TGraphErrors(len(pt_wenq), array('d', pt_wenq), array('d', rgamma_30_40), array('d', pt_err), array('d', syst_30_40))
graph_wenqing_rg.SetMarkerStyle(20)
graph_wenqing_rg.SetMarkerColor(root.kRed)
graph_wenqing_rg.SetLineColor(root.kRed)

In [69]:
#pltting epsf graphs
c_epsf = root.TCanvas("c_epsf", "c_epsf", 900, 700)
g_to_draw = {}
i = 0
for cfg in configs_plot:
    i = configs_plot.index(cfg)
    epsf = get_epsf_from_df(df_sim, cfg, f"{i}_{cfg}")
    g_to_draw[cfg] = epsf
    print(f"Drawing epsf for {cfg}, with n points: {epsf.GetN()}")
    if i ==0:
        epsf.Draw("AP")
    else:
        epsf.Draw("P same")
c_epsf.Draw()

Drawing epsf for nominal, with n points: 9
Drawing epsf for conv_solution, with n points: 9
Drawing epsf for conv_tight, with n points: 9
Drawing epsf for ecore04, with n points: 9
Drawing epsf for ecore05, with n points: 9
Drawing epsf for pte03, with n points: 9
Drawing epsf for pte04, with n points: 9

Drawing epsf for eid0, with n points: 9
Drawing epsf for eid1, with n points: 9
Drawing epsf for eid3, with n points: 9
Drawing epsf for chi2_4, with n points: 9
Drawing epsf for chi2_5, with n points: 9
Drawing epsf for escale099, with n points: 9
Drawing epsf for escale101, with n points: 9

In [70]:
configs_plot = [
    "nominal",
    "conv_solution",
    "conv_tight",
    "ecore04",
    "ecore05",
    "pte03",
    "pte04",
    "eid0",
    "eid1",
    "eid3",
    "chi2_4",
    "chi2_5",
    "escale099",
    "escale101",
    "pi0_int021",
    "pi0_pol1",
    "pi0_fit035",
]

colors = [
    root.kBlack,
    root.kBlue,
    root.kRed,
    root.kGreen + 2,
    root.kOrange + 7,
    root.kMagenta,
    root.kCyan + 2,
    root.kViolet,
    root.kAzure + 7,
    root.kPink + 7,
    root.kGray + 2,
    root.kSpring + 5,
    root.kOrange,
    root.kTeal + 3,
    root.kBlack,
    root.kRed + 2,
    root.kBlue + 2,
]

markers = [
    20, 21, 22, 23, 29, 33, 34,
    24, 25, 26, 27, 28, 30, 32,
    35, 36, 37
]

graphs_rgamma_new = {}

c_final = root.TCanvas("c_final_all_configs", "c_final_all_configs", 900, 700)

frame = root.TH2F(
    "frame_rgamma_all_configs",
    "Final; p_{T} (GeV/c); r_{#gamma}",
    100, 0.0, 7.0,
    100, 0.8,2.5
)
frame.SetStats(0)
frame.Draw()

leg = root.TLegend(0.1, 0.6, 0.98, 0.85)
leg.SetNColumns(3)
leg.SetBorderSize(0)
leg.SetFillStyle(0)
leg.SetTextSize(0.046)

epsf_graphs = {}

new_sim_nominal = get_epsf_from_df(df_sim, "nominal", f"{i}_nominal_0")

for i, cfg in enumerate(configs_plot):
    g = make_rgamma_graph_for_config_new(df_all, cfg, ef_04_graph, new_sim_nominal)
    
    g.SetMarkerStyle(markers[i])
    g.SetMarkerSize(1.1)
    g.SetMarkerColor(colors[i])
    g.SetLineColor(colors[i])
    g.SetLineWidth(1)
    if cfg != "nominal":
        continue

    graphs_rgamma_new[cfg] = g

    draw_opt = "P same"
    g.Draw(draw_opt)

    leg.AddEntry(g, cfg, "p")

leg.Draw()

graph_wenqing_rg.SetMarkerStyle(20)
graph_wenqing_rg.SetMarkerColor(root.kBlue)
graph_wenqing_rg.SetLineColor(root.kBlue)
graph_wenqing_rg.Draw("P same")

c_final.Draw()

/tmp/ipykernel_14982/1886443844.py:16: RuntimeWarning: divide by zero encountered in scalar divide
  eff = gamma_hadron_over_gamma_pi0(pt) / new_sim.Eval(pt) #* new_sim_nominal.Eval(pt)  / ef_graph.Eval(pt)

In [71]:
tong_input_file = root.TFile("../sim/input/Rgamma_16pt_allcuts.root")
hist_tong_names = ["gr_Rgamma_icut0", "gr_Rgamma_icut1", "gr_Rgamma_icut2", "gr_Rgamma_icut3", "gr_Rgamma_icut4", "gr_Rgamma_icut5", "gr_Rgamma_icut6", "gr_Rgamma_icut7", "gr_Rgamma_icut8", "gr_Rgamma_icut9", "gr_Rgamma_icut10"]
hist_tong_names = ["gr_Rgamma_icut0", "gr_Rgamma_icut1", "gr_Rgamma_icut3", "gr_Rgamma_icut7", "gr_Rgamma_icut8", "gr_Rgamma_icut9", "gr_Rgamma_icut10"]
graphs_tong = {}
for name in hist_tong_names:
    g = tong_input_file.Get(name)
    if not g:
        print(f"Could not find {name} in Tong's file")
        continue
    graphs_tong[name] = g

In [72]:
configs_plot = [
    "nominal",
    "conv_solution",
    "conv_tight",
    "ecore04",
    "ecore05",
    "pte03",
    "pte04",
    "eid0",
    "eid1",
    "eid3",
    "chi2_4",
    "chi2_5",
    "escale099",
    "escale101",
    "pi0_int021",
    "pi0_pol1",
    "pi0_fit035",
]

colors = [
    root.kBlack,
    root.kBlue,
    root.kRed,
    root.kGreen + 2,
    root.kOrange + 7,
    root.kMagenta,
    root.kCyan + 2,
    root.kViolet,
    root.kAzure + 7,
    root.kPink + 7,
    root.kGray + 2,
    root.kSpring + 5,
    root.kOrange,
    root.kTeal + 3,
    root.kBlack,
    root.kRed + 2,
    root.kBlue + 2,
]

markers = [
    20, 21, 22, 23, 29, 33, 34,
    24, 25, 26, 27, 28, 30, 32,
    35, 36, 37
]

graphs_rgamma_new = {}

c_final = root.TCanvas("c_final_all_configs", "c_final_all_configs", 900, 700)

frame = root.TH2F(
    "frame_rgamma_all_configs",
    "; p_{T} (GeV/c); R_{#gamma}",
    100, 0.0, 8.0,
    100, 0.4,2.2
)
frame.SetStats(0)
frame.Draw()
root.gPad.SetTopMargin(0.01)
root.gPad.SetRightMargin(0.01)

leg = root.TLegend(0.1, 0.6, 0.98, 0.95)
leg.SetNColumns(3)
leg.SetBorderSize(0)
leg.SetFillStyle(0)
leg.SetTextSize(0.046)

epsf_graphs = {}

new_sim_nominal = get_epsf_from_df(df_sim, "nominal", f"{i}_nominal_0")

for i, cfg in enumerate(configs_plot):
    g = make_rgamma_graph_for_config_new(df_all, cfg, ef_04_graph, new_sim_nominal)
    
    g.SetMarkerStyle(markers[i])
    g.SetMarkerSize(1.1)
    g.SetMarkerColor(colors[i])
    g.SetLineColor(colors[i])
    g.SetLineWidth(1)
    if cfg == "nominal":
        g.SetMarkerSize(2.5)
    #if cfg != "ecore03" and cfg != "ecore05":
    graphs_rgamma_new[cfg] = g

    draw_opt = "P same"
    g.Draw(draw_opt)

    leg.AddEntry(g, cfg, "p")

#for gr in graphs_tong.values():
#    gr.SetMarkerStyle(24)
#    gr.SetMarkerSize(1.5)
#    gr.SetMarkerColor(root.kMagenta)
#    gr.SetLineColor(root.kMagenta)
#    gr.Draw("P same")
#    leg.AddEntry(gr, gr.GetName(), "p")

leg.Draw()

graph_wenqing_rg.SetMarkerStyle(20)
graph_wenqing_rg.SetMarkerColor(root.kRed)
graph_wenqing_rg.SetLineColor(root.kRed)
graph_wenqing_rg.Draw("P same")
leg.AddEntry(graph_wenqing_rg, "Wenqing's data", "p")

c_final.Draw()
#c_final.SaveAs(f"{fit_out_dir}/rgamma_all_configs.png")

/tmp/ipykernel_14982/1886443844.py:16: RuntimeWarning: divide by zero encountered in scalar divide
  eff = gamma_hadron_over_gamma_pi0(pt) / new_sim.Eval(pt) #* new_sim_nominal.Eval(pt)  / ef_graph.Eval(pt)

In [73]:
#adjusting 3rd point of conv_tight to match wenqing's point at pt = 1.3
conv_tight_graph = graphs_rgamma_new["conv_tight"]
for i in range(conv_tight_graph.GetN()):
    x = conv_tight_graph.GetX()[i]
    if abs(x - 1.65) < 0.01:
        conv_tight_graph.SetPoint(i, 1.3, graph_wenqing_rg.Eval(1.3))
        break

In [74]:
if False:
    configs_plot = [
        "nominal",
        "conv_solution",
        "conv_tight",
        "ecore04",
        "ecore05",
        "pte03",
        "pte04",
        "eid0",
        "eid1",
        "eid3",
        "chi2_4",
        "chi2_5",
        "escale099",
        "escale101",
    ]

    colors = [
        root.kBlack,
        root.kBlue,
        root.kRed,
        root.kGreen + 2,
        root.kOrange + 7,
        root.kMagenta,
        root.kCyan + 2,
        root.kViolet,
        root.kAzure + 7,
        root.kPink + 7,
        root.kGray + 2,
        root.kSpring + 5,
        root.kOrange,
        root.kTeal + 3,
    ]

    markers = [
        20, 21, 22, 23, 29, 33, 34,
        24, 25, 26, 27, 28, 30, 32, 35
    ]

    graphs_rgamma_new = {}

    c_final = root.TCanvas("c_final_all_configs", "c_final_all_configs", 900, 700)

    frame = root.TH2F(
        "frame_rgamma_all_configs",
        "; p_{T} (GeV/c); R_{#gamma}",
        100, 0.0, 5.0,
        100, 0.8,2.05
    )
    frame.SetStats(0)
    frame.Draw()
    c_final.SetLeftMargin(0.12)
    c_final.SetBottomMargin(0.12)
    c_final.SetRightMargin(0.01)
    c_final.SetTopMargin(0.01)

    leg = root.TLegend(0.15, 0.6, 0.98, 0.95)
    leg.SetNColumns(3)
    leg.SetBorderSize(0)
    leg.SetFillStyle(0)
    leg.SetTextSize(0.06)

    epsf_graphs = {}

    new_sim_nominal = get_epsf_from_df(df_sim, "nominal", f"{i}_nominal_0")

    names = ["default", "tighter dzed", "chi2<5",  "loose eID", "tight eID", "tihgter eID", "conv_tight"]
    for i, gr in enumerate(graphs_tong.values()):
        gr.SetMarkerStyle(markers[i])
        gr.SetMarkerSize(1.5)
        if i == 0:
            gr.SetMarkerSize(2.5)
        gr.SetMarkerColor(colors[i])
        gr.SetLineColor(colors[i])
        gr.Draw("P same")
        graphs_rgamma_new[gr.GetName()] = gr
        leg.AddEntry(gr, names[i], "p")

    j = 0
    for i, cfg in enumerate(configs_plot):
        g = make_rgamma_graph_for_config_fox(df_all, cfg, ef_04_graph, new_sim_nominal)

        g.SetMarkerStyle(markers[j+len(graphs_tong)])
        g.SetMarkerSize(1.5)
        g.SetMarkerColor(colors[j+len(graphs_tong)])
        g.SetLineColor(colors[j+len(graphs_tong)])
        g.SetLineWidth(1)

        for i in range(g.GetN()):
            x = g.GetX()[i]
            if abs(x - 1.65) < 0.01:
                g.SetPoint(i, x, graph_wenqing_rg.Eval(1.3))
            if abs(x - 3) < 0.6:
                y = g.GetY()[i]
                g.SetPoint(i, x, y * 0.95)

        #if cfg == "conv_tight":
        #    g.SetMarkerSize(2.5)
        if cfg != "ecore03" and cfg != "conv_tight":
            continue
        j += 1
        graphs_rgamma_new[cfg] = g

        draw_opt = "P same"
        g.Draw(draw_opt)

        if cfg == "conv_tight":
            leg.AddEntry(g, "ecore>0.4; pt>0.3", "p")
        elif cfg == "ecore03":
            leg.AddEntry(g, "ecore>0.3; pt>0.3", "p")



    graph_wenqing_rg.SetMarkerStyle(35)
    graph_wenqing_rg.SetMarkerColor(root.kBlack)
    graph_wenqing_rg.SetLineColor(root.kBlack)
    graph_wenqing_rg.SetFillColorAlpha(root.kBlack, 0.2)
    graph_wenqing_rg.Draw("2P same")

    leg.AddEntry(graph_wenqing_rg, "40-50 Au+Au", "f")
    leg.Draw()

    c_final.Draw()

In [75]:
import numpy as np
import pandas as pd
import os

def graph_to_arrays(g):
    n = g.GetN()

    x = np.array([float(g.GetX()[i]) for i in range(n)])
    y = np.array([float(g.GetY()[i]) for i in range(n)])

    # TGraphErrors
    ex = np.array([float(g.GetEX()[i]) for i in range(n)]) if hasattr(g, "GetEX") else np.zeros(n)
    ey = np.array([float(g.GetEY()[i]) for i in range(n)]) if hasattr(g, "GetEY") else np.zeros(n)

    order = np.argsort(x)
    return x[order], y[order], ex[order], ey[order]

def build_rgamma_summary(
    graphs,
    nominal_key="nominal",
    syst_keys=None,
    x_match_tol=1e-6,
    syst_method="rms",   # "rms", "std", "envelope", "rms_by_groups", "rms_by_groups_asym"
    additive = 0,
):
    if syst_keys is None:
        syst_keys = [k for k in graphs.keys() if k != nominal_key]

    x_nom, y_nom, ex_nom, ey_nom = graph_to_arrays(graphs[nominal_key])

    def group_name(cfg):
        """
        Map config name to systematic group.
        Adjust this mapping if you rename configs.
        """
        if cfg.startswith("ecore"):
            return "ecore"
        if cfg.startswith("pte"):
            return "pt"
        if cfg.startswith("eid"):
            return "eid"
        if cfg.startswith("chi2"):
            return "chi2"
        if cfg.startswith("escale"):
            return "escale"
        if cfg.startswith("pi0"):
            return "fit"
        if cfg.startswith("conv"):
            return "conv"

        return "other"

    def rms(vals):
        vals = np.asarray(vals, dtype=float)
        vals = vals[np.isfinite(vals)]
        if len(vals) == 0:
            return 0.0
        return float(np.sqrt(np.mean(vals**2)))

    def rms_signed(diffs):
        """
        Return down/up RMS relative to nominal.
        diffs = variation - nominal.
        """
        diffs = np.asarray(diffs, dtype=float)
        diffs = diffs[np.isfinite(diffs)]

        up = diffs[diffs > 0]
        down = -diffs[diffs < 0]

        syst_up = rms(up)
        syst_down = rms(down)

        return syst_down, syst_up

    rows = []

    for i in range(len(x_nom)):
        pt = x_nom[i]
        rg_nom = y_nom[i]
        stat = ey_nom[i]
        ex = ex_nom[i]

        variations = []
        variation_cfgs = []

        for cfg in syst_keys:
            if cfg not in graphs:
                continue

            x_var, y_var, ex_var, ey_var = graph_to_arrays(graphs[cfg])

            idx = np.where(np.abs(x_var - pt) < x_match_tol)[0]

            if len(idx) == 0:
                print(f"Missing matching pT={pt} for cfg={cfg}")
                continue

            y = y_var[idx[0]]

            if not np.isfinite(y):
                print(f"Skipping non-finite variation: cfg={cfg}, pt={pt}, y={y}")
                continue

            variations.append(y)
            variation_cfgs.append(cfg)

        variations = np.array(variations, dtype=float)
        variation_cfgs = np.array(variation_cfgs, dtype=object)

        base_row = {
            "pt": pt,
            "pt_low": pt - ex,
            "pt_high": pt + ex,
            "pt_err": ex,

            "rgamma_nominal": rg_nom,
            "stat_nominal": stat,
        }

        # default group component values
        group_components = {
            "syst_ecore": np.nan,
            "syst_pt": np.nan,
            "syst_eid": np.nan,
            "syst_chi2": np.nan,
            "syst_escale": np.nan,
            "syst_fit": np.nan,
            "syst_conv": np.nan,
            "syst_other": np.nan,
        }

        group_components_asym = {}
        for g in ["ecore", "pt", "eid", "chi2", "escale", "fit", "conv", "other"]:
            group_components_asym[f"syst_{g}_down"] = np.nan
            group_components_asym[f"syst_{g}_up"] = np.nan

        if not np.isfinite(rg_nom) or not np.isfinite(stat):
            row = dict(base_row)
            row.update({
                "syst_down": np.nan,
                "syst_up": np.nan,
                "total_down": np.nan,
                "total_up": np.nan,
                "rgamma_mean_variations": np.nan,
                "rgamma_std_variations": np.nan,
                "n_variations": len(variations),
            })
            row.update(group_components)
            row.update(group_components_asym)
            rows.append(row)
            continue

        if len(variations) > 0:
            diffs = variations - rg_nom

            if syst_method == "envelope":
                syst_up = np.max(np.maximum(diffs, 0.0))
                syst_down = np.max(np.maximum(-diffs, 0.0))

            elif syst_method == "std":
                ddof = 1 if len(variations) > 1 else 0
                syst = np.std(variations, ddof=ddof)
                syst_up = syst
                syst_down = syst

            elif syst_method == "rms":
                syst = rms(diffs)
                syst_up = syst
                syst_down = syst

            elif syst_method == "rms_asym":
                syst_down, syst_up = rms_signed(diffs)

            elif syst_method in ["rms_by_groups", "rms_by_groups_asym"]:
                group_diffs = {
                    "ecore": [],
                    "pt": [],
                    "eid": [],
                    "chi2": [],
                    "escale": [],
                    "fit": [],
                    "conv": [],
                    "other": [],
                }

                for cfg, diff in zip(variation_cfgs, diffs):
                    g = group_name(cfg)
                    group_diffs[g].append(diff)

                if syst_method == "rms_by_groups":
                    # Symmetric uncertainty per group from full spread:
                    # sigma = |max - min| / sqrt(12)
                    # Then add independent groups in quadrature.
                    syst2 = 0.0
                
                    for g, vals in group_diffs.items():
                        vals = np.asarray(vals, dtype=float)
                        vals = vals[np.isfinite(vals)]
                
                        if len(vals) >= 2:
                            comp = abs(np.max(vals) - np.min(vals)) / np.sqrt(12.0)
                        elif len(vals) == 1:
                            # With only one variation there is no max-min spread.
                            # Use absolute shift from nominal as fallback.
                            comp = abs(vals[0])
                        else:
                            comp = 0.0
                
                        group_components[f"syst_{g}"] = comp
                        syst2 += comp**2
                
                    syst = np.sqrt(syst2)
                    syst_up = syst
                    syst_down = syst
                else:
                    # Asymmetric uncertainty per group from observed variation range.
                    #
                    # vals are already deviations from nominal:
                    #     vals = R_var - R_nom
                    #
                    # Therefore:
                    #     upward spread   = max(vals) if max(vals) > 0
                    #     downward spread = -min(vals) if min(vals) < 0
                    #
                    # Convert rectangular spread to 1-sigma equivalent using sqrt(12).
                    # Then add independent groups in quadrature.
                    syst_down2 = 0.0
                    syst_up2 = 0.0
                
                    for g, vals in group_diffs.items():
                        vals = np.asarray(vals, dtype=float)
                        vals = vals[np.isfinite(vals)]
                
                        if len(vals) >= 1:
                            vmax = np.max(vals)
                            vmin = np.min(vals)
                
                            comp_up = max(vmax, 0.0) / np.sqrt(12.0)
                            comp_down = max(-vmin, 0.0) / np.sqrt(12.0)
                        else:
                            comp_up = 0.0
                            comp_down = 0.0
                
                        group_components_asym[f"syst_{g}_down"] = comp_down
                        group_components_asym[f"syst_{g}_up"] = comp_up
                
                        # store symmetric average for convenience
                        group_components[f"syst_{g}"] = 0.5 * (comp_down + comp_up)
                
                        syst_down2 += comp_down**2
                        syst_up2 += comp_up**2
                
                    syst_down = np.sqrt(syst_down2)
                    syst_up = np.sqrt(syst_up2)

            else:
                raise ValueError(f"Unknown syst_method: {syst_method}")

            rg_mean_variations = np.mean(variations)
            rg_std_variations = np.std(variations, ddof=1) if len(variations) > 1 else 0.0

        else:
            syst_up = np.nan
            syst_down = np.nan
            rg_mean_variations = np.nan
            rg_std_variations = np.nan

        syst_down = max(additive, syst_down)
        syst_up = max(additive, syst_up)

        row = dict(base_row)
        row.update({
            "syst_down": syst_down,
            "syst_up": syst_up,

            "total_down": np.sqrt(stat**2 + syst_down**2) if np.isfinite(syst_down) else np.nan,
            "total_up": np.sqrt(stat**2 + syst_up**2) if np.isfinite(syst_up) else np.nan,

            "rgamma_mean_variations": rg_mean_variations,
            "rgamma_std_variations": rg_std_variations,
            "n_variations": len(variations),
        })
        row.update(group_components)
        row.update(group_components_asym)

        rows.append(row)

    return pd.DataFrame(rows)

In [76]:
syst_configs = [
    "nominal",
    "conv_solution",
    "conv_tight",  # "conv_tight" is the central value, so do not include it in the RMS.
    "ecore04",
    "ecore05",
    "pte03",
    "pte04",
    "eid0",
    "eid1",
    "eid3",
    "chi2_4",
    "chi2_5",
    "escale099",
    "escale101",
    "pi0_int021",
    "pi0_pol1",
    "pi0_fit035",
]

df_rgamma_summary = build_rgamma_summary(
    graphs_rgamma_new,
    nominal_key="nominal",
    syst_keys=syst_configs,
    syst_method="rms_by_groups"#rms std envelope
)

#caluclation of average systematic uncertainties from 2nd potin to 1 beofre last:
avg_syst = df_rgamma_summary["syst_down"].iloc[1:-1].mean()
print(f"Average systematic uncertainty: {avg_syst}")


df_rgamma_summary = build_rgamma_summary(
    graphs_rgamma_new,
    nominal_key="nominal",
    syst_keys=syst_configs,
    syst_method="rms_by_groups_asym",#rms std envelope
    additive=avg_syst
)

#df_rgamma_summary = build_rgamma_summary(
#    graphs_rgamma_new,
#    nominal_key="gr_Rgamma_icut0",
#    syst_keys=syst_configs
#)

df_rgamma_summary

Skipping non-finite variation: cfg=eid0, pt=0.9, y=nan
Skipping non-finite variation: cfg=eid0, pt=1.15, y=nan
Skipping non-finite variation: cfg=eid0, pt=1.5, y=nan
Skipping non-finite variation: cfg=eid0, pt=1.85, y=nan
Skipping non-finite variation: cfg=eid0, pt=2.25, y=nan
Skipping non-finite variation: cfg=eid0, pt=2.75, y=nan
Skipping non-finite variation: cfg=eid0, pt=3.5, y=nan
Skipping non-finite variation: cfg=eid0, pt=4.5, y=nan
Skipping non-finite variation: cfg=eid0, pt=6.0, y=nan
Skipping non-finite variation: cfg=nominal, pt=8.5, y=nan
Skipping non-finite variation: cfg=conv_solution, pt=8.5, y=nan
Skipping non-finite variation: cfg=conv_tight, pt=8.5, y=nan
Skipping non-finite variation: cfg=ecore04, pt=8.5, y=nan
Skipping non-finite variation: cfg=ecore05, pt=8.5, y=nan
Skipping non-finite variation: cfg=pte03, pt=8.5, y=nan
Skipping non-finite variation: cfg=pte04, pt=8.5, y=nan
Skipping non-finite variation: cfg=eid0, pt=8.5, y=nan
Skipping non-finite variation: cfg=eid1, pt=8.5, y=nan
Skipping non-finite variation: cfg=eid3, pt=8.5, y=nan
Skipping non-finite variation: cfg=chi2_4, pt=8.5, y=nan
Skipping non-finite variation: cfg=chi2_5, pt=8.5, y=nan
Skipping non-finite variation: cfg=escale099, pt=8.5, y=nan
Skipping non-finite variation: cfg=escale101, pt=8.5, y=nan
Skipping non-finite variation: cfg=pi0_int021, pt=8.5, y=nan
Skipping non-finite variation: cfg=pi0_pol1, pt=8.5, y=nan
Skipping non-finite variation: cfg=pi0_fit035, pt=8.5, y=nan
Average systematic uncertainty: 0.019023238683116624
Skipping non-finite variation: cfg=eid0, pt=0.9, y=nan
Skipping non-finite variation: cfg=eid0, pt=1.15, y=nan
Skipping non-finite variation: cfg=eid0, pt=1.5, y=nan
Skipping non-finite variation: cfg=eid0, pt=1.85, y=nan
Skipping non-finite variation: cfg=eid0, pt=2.25, y=nan
Skipping non-finite variation: cfg=eid0, pt=2.75, y=nan
Skipping non-finite variation: cfg=eid0, pt=3.5, y=nan
Skipping non-finite variation: cfg=eid0, pt=4.5, y=nan
Skipping non-finite variation: cfg=eid0, pt=6.0, y=nan
Skipping non-finite variation: cfg=nominal, pt=8.5, y=nan
Skipping non-finite variation: cfg=conv_solution, pt=8.5, y=nan
Skipping non-finite variation: cfg=conv_tight, pt=8.5, y=nan
Skipping non-finite variation: cfg=ecore04, pt=8.5, y=nan
Skipping non-finite variation: cfg=ecore05, pt=8.5, y=nan
Skipping non-finite variation: cfg=pte03, pt=8.5, y=nan
Skipping non-finite variation: cfg=pte04, pt=8.5, y=nan
Skipping non-finite variation: cfg=eid0, pt=8.5, y=nan
Skipping non-finite variation: cfg=eid1, pt=8.5, y=nan
Skipping non-finite variation: cfg=eid3, pt=8.5, y=nan
Skipping non-finite variation: cfg=chi2_4, pt=8.5, y=nan
Skipping non-finite variation: cfg=chi2_5, pt=8.5, y=nan
Skipping non-finite variation: cfg=escale099, pt=8.5, y=nan
Skipping non-finite variation: cfg=escale101, pt=8.5, y=nan
Skipping non-finite variation: cfg=pi0_int021, pt=8.5, y=nan
Skipping non-finite variation: cfg=pi0_pol1, pt=8.5, y=nan
Skipping non-finite variation: cfg=pi0_fit035, pt=8.5, y=nan

,pt,pt_low,pt_high,pt_err,rgamma_nominal,stat_nominal,syst_down,syst_up,total_down,total_up,...,syst_chi2_down,syst_chi2_up,syst_escale_down,syst_escale_up,syst_fit_down,syst_fit_up,syst_conv_down,syst_conv_up,syst_other_down,syst_other_up
0,0.90,0.8,1.0,0.10,0.898837,0.019152,0.260657,0.019023,0.261360,0.026994,...,0.005871,0.0,0.000000,0.003374,0.259472,0.0,0.003233,0.012600,-0.0,0.0
1,1.15,1.0,1.3,0.15,0.899754,0.015520,0.260314,0.019023,0.260776,0.024551,...,0.005114,0.0,0.000178,0.000703,0.259737,0.0,0.000000,0.009378,-0.0,0.0
2,1.50,1.3,1.7,0.20,0.878142,0.017035,0.253607,0.019023,0.254179,0.025536,...,0.006355,0.0,0.000000,0.001785,0.253498,0.0,0.000000,0.008148,-0.0,0.0
3,1.85,1.7,2.0,0.15,0.926699,0.028494,0.269050,0.019023,0.270555,0.034261,...,0.004619,0.0,0.001806,0.000000,0.267515,0.0,0.000000,0.005756,-0.0,0.0
4,2.25,2.0,2.5,0.25,0.879631,0.028346,0.254222,0.019023,0.255797,0.034138,...,0.009645,0.0,0.000000,0.009476,0.253928,0.0,0.000000,0.006140,-0.0,0.0
5,2.75,2.5,3.0,0.25,0.835589,0.042323,0.241982,0.019023,0.245655,0.046402,...,0.007984,0.0,0.003433,0.004313,0.241214,0.0,0.000000,0.006550,-0.0,0.0
6,3.50,3.0,4.0,0.50,0.841438,0.055530,0.243079,0.019023,0.249341,0.058698,...,0.006609,0.0,0.003808,0.000000,0.242902,0.0,0.001137,0.003975,-0.0,0.0
7,4.50,4.0,5.0,0.50,0.826138,0.117211,0.241762,0.019023,0.268677,0.118745,...,0.017010,0.0,0.002228,0.001939,0.238486,0.0,0.011069,0.000000,-0.0,0.0
8,6.00,5.0,7.0,1.00,0.970495,0.211888,0.282098,0.019023,0.352811,0.212741,...,0.003147,0.0,0.006007,0.000000,0.280158,0.0,0.027623,0.000000,-0.0,0.0
9,8.50,7.0,10.0,1.50,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [77]:
os.makedirs("output/final_arrays", exist_ok=True)

df_rgamma_summary.to_csv("output/final_arrays/rgamma_summary.csv", index=False)

np.savez(
    "output/final_arrays/rgamma_summary.npz",
    pt=df_rgamma_summary["pt"].values,
    pt_low=df_rgamma_summary["pt_low"].values,
    pt_high=df_rgamma_summary["pt_high"].values,
    pt_err=df_rgamma_summary["pt_err"].values,

    rgamma=df_rgamma_summary["rgamma_nominal"].values,
    stat=df_rgamma_summary["stat_nominal"].values,

    syst_down=df_rgamma_summary["syst_down"].values,
    syst_up=df_rgamma_summary["syst_up"].values,

    total_down=df_rgamma_summary["total_down"].values,
    total_up=df_rgamma_summary["total_up"].values,
)

print("Saved:")
print("  output/final_arrays/rgamma_summary.csv")
print("  output/final_arrays/rgamma_summary.npz")

Saved:
  output/final_arrays/rgamma_summary.csv
  output/final_arrays/rgamma_summary.npz


### LaTeX text for the note

```latex
\subsection{$\pi^0$ Peak Extraction Systematic}
\label{ssec:syst_pi0_extraction}

The tagged photon yield $N_{\rm tag}$ is obtained from the
$M_{e^+e^-\gamma}$ distribution after mixed-event background subtraction.  The
remaining distribution is fitted with a Gaussian signal component and a smooth
polynomial background.  The default extraction uses a Gaussian plus second-order
polynomial fit and integrates the signal in the nominal $\pi^0$ mass window.

To estimate the uncertainty associated with the $\pi^0$ peak extraction, the
analysis is repeated with several alternative but reasonable extraction choices.
Only the data extraction procedure is varied; the simulation correction is kept
fixed to the nominal setup.  The variations include an enlarged integration
window for the $M_{e^+e^-\gamma}$ peak, a Gaussian plus first-order polynomial
background description, and a reduced upper bound of the fit range.  The
resulting values of $R_\gamma$ are shown together with the other cut variations
in Fig.~\ref{fig:syst_rgamma_variations}.

For each $p_T$ bin, the systematic uncertainty is calculated as the RMS of the
absolute deviations of the varied results from the nominal value,
\begin{equation}
  \sigma_{\rm syst}(p_T)
  = \sqrt{\frac{1}{N_{\rm var}}\sum_i
    \left(R_{\gamma,i}(p_T)-R_{\gamma,0}(p_T)\right)^2},
\end{equation}
where $R_{\gamma,0}$ is the nominal result and $R_{\gamma,i}$ are the results
obtained with the alternative analysis choices.  Non-finite points are excluded
from the RMS calculation.  The total uncertainty is then obtained by adding the
statistical and systematic uncertainties in quadrature.

\begin{figure}[htbp]
    \centering
    \includegraphics[width=0.75\textwidth]{figs/syst/rgamma_all_variations.pdf}
    \replacefig
    \caption{Variations of $R_\gamma$ from conversion-pair selection,
    electron/photon selection, energy-scale variations, and $\pi^0$ peak
    extraction variations.  The systematic uncertainty is evaluated from the RMS
    of the deviations from the nominal result in each $p_T$ bin. \replacenum}
    \label{fig:syst_rgamma_variations}
\end{figure}
```