In [1]:
%run input/Format.ipynb
import ROOT as root
from array import array
root.gErrorIgnoreLevel = root.kFatal
%jsroot on
root.gStyle.SetOptStat(0)
import ctypes

/home/yoren/.local/lib/python3.10/site-packages/nbformat/__init__.py:96: MissingIDFieldWarning: Cell is missing an id field, this will become a hard error in future nbformat versions. You may want to use `normalize()` on your notebooks before validations (available since nbformat 5.1.4). Previous versions of nbformat are fixing this issue transparently, and will stop doing so in the future.
  validate(nb)

Welcome to JupyROOT 6.30/06

Error in <TUnixSystem::FindDynamicLibrary>: input/logo/PHENIXTools/lib/libLogoPainter.so does not exist in /home/yoren/bnl/ROOT/install/lib:.:/home/yoren/bnl/ROOT/install/lib:/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v3:/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v2:/lib/x86_64-linux-gnu/tls/haswell/x86_64:/lib/x86_64-linux-gnu/tls/haswell:/lib/x86_64-linux-gnu/tls/x86_64:/lib/x86_64-linux-gnu/tls:/lib/x86_64-linux-gnu/haswell/x86_64:/lib/x86_64-linux-gnu/haswell:/lib/x86_64-linux-gnu/x86_64:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v3:/usr/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v2:/usr/lib/x86_64-linux-gnu/tls/haswell/x86_64:/usr/lib/x86_64-linux-gnu/tls/haswell:/usr/lib/x86_64-linux-gnu/tls/x86_64:/usr/lib/x86_64-linux-gnu/tls:/usr/lib/x86_64-linux-gnu/haswell/x86_64:/usr/lib/x86_64-linux-gnu/haswell:/usr/lib/x86_64-linux-gnu/x86_64:/usr/lib/x86_64-linux-gnu:/lib/glibc-hwcaps/x86-64-v3:/lib/glibc-hwcaps/x86-64-v2:/lib/tls/haswell/x86_64:/lib/tls/haswell:/lib/tls/x86_64:/lib/tls:/lib/haswell/x86_64:/lib/haswell:/lib/x86_64:/lib:/usr/lib/glibc-hwcaps/x86-64-v3:/usr/lib/glibc-hwcaps/x86-64-v2:/usr/lib/tls/haswell/x86_64:/usr/lib/tls/haswell:/usr/lib/tls/x86_64:/usr/lib/tls:/usr/lib/haswell/x86_64:/usr/lib/haswell:/usr/lib/x86_64:/usr/lib:/home/yoren/bnl/ROOT
input_line_46:1:10: fatal error: 'input/logo/PHENIXTools/include/LogoPainter.hpp' file not found
#include "input/logo/PHENIXTools/include/LogoPainter.hpp"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [2]:
colors=[1,2,4,root.kGreen+2,root.kOrange+4,root.kMagenta,root.kGray,root.kGray,root.kBlack,root.kCyan,root.kOrange,root.kViolet,root.kCyan,root.kGreen,root.kOrange]
file_path="input/"
file_names=["data_pp_v2.root"]#,"m_ee_DCA_535.root"],"m_ee_DCA_536.root"]

In [3]:
pt_bins = [0.8, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0, 6.0, 8.0, 10.0]
pt_bins = [0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0, 7.0, 10.0]
pt_bins = [0.6, 0.8, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0, 7.0, 10.0]
pt_bins = [0.8, 1.2, 1.5, 1.8, 2.3, 3.0, 4.0, 5.0, 7.0,10.0]
pt_bins = [0.6, 0.8, 1.2, 1.6, 2.0, 2.5, 3.0, 4.0, 5.0, 7.0, 10.0]
pt_bins = [0.8, 1.2, 1.5, 1.8, 2.3, 3.0, 4.0, 5.0, 7.0, 10.0]
pt_bins = [0.8, 1.0, 1.3, 1.6, 1.9, 2.2, 2.6, 3.0, 4.0, 5.0, 7.0, 10.0]
pt_bins = [0.8, 1.0, 1.3, 1.7, 2.0, 2.5, 3.0, 4.0, 5.0, 7.0, 10.0]
#pt_bins = [1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0, 10.0]

In [4]:
windows = {
    "ee_signal":  (0.01, 0.13),
    "ee_norm":    (0.2, 0.75),
    "eeg_signal": (0.09, 0.19),
    "eeg_norm":   (0.20, 0.80),
    "eeg_fit_1":  (0.05, 0.78),
}

In [5]:

root.gROOT.SetBatch(True)
root.TH1.AddDirectory(False)

configs = [
    "nominal",
    "conv_solution",
    "conv_tight",
    "ecore04",
    "ecore05",
    "pte03",
    "pte04",
    "eid0",
    "eid1",
    "eid3",
    "chi2_4",
    "chi2_5",
    "escale099",
    "escale101",
]

cent_bins = [0]

hist_kinds = [
    "fg2d_eemass_reco",
    "bg2d_eemass_reco",
    "fg2d_eegmass_reco",
    "bg2d_eegmass_reco",
]

In [6]:
hist_names = {}

for kind in hist_kinds:
    hist_names[kind] = {}
    for cfg in configs:
        hist_names[kind][cfg] = {}
        for icent in cent_bins:
            hist_names[kind][cfg][icent] = f"{kind}_{cfg}_icent{icent}"

# optional old-style quick-check hists
old_hist_names = {
    "fg_ee_dphi":  {icent: f"fg2d_eemass_reco_dphi_icent{icent}" for icent in cent_bins},
    "fg_ee_dzed":  {icent: f"fg2d_eemass_reco_dzed_icent{icent}" for icent in cent_bins},
    "bg_ee_dphi":  {icent: f"bg2d_eemass_reco_dphi_icent{icent}" for icent in cent_bins},
    "bg_ee_dzed":  {icent: f"bg2d_eemass_reco_dzed_icent{icent}" for icent in cent_bins},
    "fg_eeg_dphi": {icent: f"fg2d_eegmass_reco_dphi_icent{icent}" for icent in cent_bins},
    "fg_eeg_dzed": {icent: f"fg2d_eegmass_reco_dzed_icent{icent}" for icent in cent_bins},
    "bg_eeg_dphi": {icent: f"bg2d_eegmass_reco_dphi_icent{icent}" for icent in cent_bins},
    "bg_eeg_dzed": {icent: f"bg2d_eegmass_reco_dzed_icent{icent}" for icent in cent_bins},
}

cutflow_names = {cfg: f"h_cutflow_{cfg}" for cfg in configs}
event_hist_names = ["h_nevents", "h_cent", "h_n_cent", "h_nev_cent"]

In [7]:
def get_clone(infile, hname, newname=None, verbose=True):
    obj = infile.Get(hname)
    if not obj:
        if verbose:
            print(f"Missing histogram: {hname}")
        return None

    hist = obj.Clone(newname if newname else hname + "_clone")
    hist.SetDirectory(root.nullptr)
    return hist

In [8]:
hists = {}

for ifile, fname in enumerate(file_names):
    full_name = file_path + fname
    infile = root.TFile.Open(full_name, "READ")

    if not infile or infile.IsZombie():
        print(f"Cannot open file: {full_name}")
        continue

    print(f"Reading file {ifile}: {full_name}")

    hists[ifile] = {}
    hists[ifile]["filename"] = full_name

    # Main systematic TH2 hists
    for kind in hist_kinds:
        hists[ifile][kind] = {}

        for cfg in configs:
            hists[ifile][kind][cfg] = {}

            for icent in cent_bins:
                hname = hist_names[kind][cfg][icent]
                newname = f"{hname}_file{ifile}"

                hists[ifile][kind][cfg][icent] = get_clone(
                    infile, hname, newname=newname
                )

    # Old-style hists
    hists[ifile]["old"] = {}
    for old_key, cent_dict in old_hist_names.items():
        hists[ifile]["old"][old_key] = {}

        for icent, hname in cent_dict.items():
            newname = f"{hname}_file{ifile}"
            hists[ifile]["old"][old_key][icent] = get_clone(
                infile, hname, newname=newname
            )

    # Cutflows
    hists[ifile]["cutflow"] = {}
    for cfg, hname in cutflow_names.items():
        hists[ifile]["cutflow"][cfg] = get_clone(
            infile, hname, newname=f"{hname}_file{ifile}"
        )

    # Event-level hists
    hists[ifile]["event"] = {}
    for hname in event_hist_names:
        hists[ifile]["event"][hname] = get_clone(
            infile, hname, newname=f"{hname}_file{ifile}", verbose=False
        )

    infile.Close()

Reading file 0: input/data_pp_v2.root

In [9]:
#for icfg in configs:
#    for icent in (1,3):
#        hists[0]["fg2d_eemass_reco"][icfg][0].Add(hists[0]["fg2d_eemass_reco"][icfg][icent])
#        hists[0]["bg2d_eemass_reco"][icfg][0].Add(hists[0]["bg2d_eemass_reco"][icfg][icent])
#        hists[0]["fg2d_eegmass_reco"][icfg][0].Add(hists[0]["fg2d_eegmass_reco"][icfg][icent])
#        hists[0]["bg2d_eegmass_reco"][icfg][0].Add(hists[0]["bg2d_eegmass_reco"][icfg][icent])

In [10]:
h_fg_ee_nom_cent0 = hists[0]["fg2d_eemass_reco"]["nominal"][0]
h_bg_ee_nom_cent0 = hists[0]["bg2d_eemass_reco"]["nominal"][0]
h_fg_eeg_nom_cent0 = hists[0]["fg2d_eegmass_reco"]["nominal"][0]
h_bg_eeg_nom_cent0 = hists[0]["bg2d_eegmass_reco"]["nominal"][0]

int_windows = {
    "ee": (0.01, 0.12),
    "eeg": (0.09, 0.2),
}

pt_min = 2.0
pt_max = 9.0

m_min_ee_int = 0.15
m_max_ee_int = 0.75

m_min_eeg_int = 0.3
m_max_eeg_int = 0.8

c1 = root.TCanvas("c1", "c1", 1200, 700)
c1.Divide(2, 1)
c1.cd(1)
ee_proj = h_fg_ee_nom_cent0.ProjectionX("px_fg_ee_nom_cent0",h_fg_ee_nom_cent0.GetYaxis().FindBin(pt_min),h_fg_ee_nom_cent0.GetYaxis().FindBin(pt_max))
ee_proj_bg = h_bg_ee_nom_cent0.ProjectionX("px_bg_ee_nom_cent0",h_bg_ee_nom_cent0.GetYaxis().FindBin(pt_min),h_bg_ee_nom_cent0.GetYaxis().FindBin(pt_max)) 
Format_Hist_total(ee_proj, Lcolor=root.kBlue, Mcolor=root.kBlue, title_x="m_{ee} (GeV/c^{2})", title_y="Counts")
ee_proj.GetXaxis().SetRangeUser(0, 0.3)
ee_proj.Draw()
ee_proj_bg.Scale(ee_proj.Integral(ee_proj.FindBin(m_min_ee_int), ee_proj.FindBin(m_max_ee_int))/ee_proj_bg.Integral(ee_proj_bg.FindBin(m_min_ee_int), ee_proj_bg.FindBin(m_max_ee_int)))

Format_Graph(ee_proj_bg, Lcolor=root.kRed, Mcolor=root.kRed)

print(ee_proj.Integral(ee_proj.FindBin(int_windows["ee"][0]), ee_proj.FindBin(int_windows["ee"][1])) - ee_proj_bg.Integral(ee_proj_bg.FindBin(int_windows["ee"][0]), ee_proj_bg.FindBin(int_windows["ee"][1])))

ee_proj_bg.Draw("same")

c1.cd(2)
eeg_proj = h_fg_eeg_nom_cent0.ProjectionX("px_fg_eeg_nom_cent0",h_fg_eeg_nom_cent0.GetYaxis().FindBin(pt_min),h_fg_eeg_nom_cent0.GetYaxis().FindBin(pt_max))
eeg_proj_bg = h_bg_eeg_nom_cent0.ProjectionX("px_bg_eeg_nom_cent0",h_bg_eeg_nom_cent0.GetYaxis().FindBin(pt_min),h_bg_eeg_nom_cent0.GetYaxis().FindBin(pt_max)) 
Format_Hist_total(eeg_proj, Lcolor=root.kBlue, Mcolor=root.kBlue, title_x="m_{ee#gamma} (GeV/c^{2})", title_y="Counts")
eeg_proj.GetXaxis().SetRangeUser(0, 0.3)
eeg_proj.Draw()
#eeg_proj_bg.Scale(eeg_proj.Integral(eeg_proj.FindBin(m_min_eeg_int), eeg_proj.FindBin(m_max_eeg_int))/eeg_proj_bg.Integral(eeg_proj_bg.FindBin(m_min_eeg_int), eeg_proj_bg.FindBin(m_max_eeg_int)))
Format_Graph(eeg_proj_bg, Lcolor=root.kRed, Mcolor=root.kRed)
eeg_proj_bg.Draw("same")

print(eeg_proj.Integral(eeg_proj.FindBin(int_windows["eeg"][0]), eeg_proj.FindBin(int_windows["eeg"][1])) - eeg_proj_bg.Integral(eeg_proj_bg.FindBin(int_windows["eeg"][0]), eeg_proj_bg.FindBin(int_windows["eeg"][1])))

c1.Draw()

9096.693104674512
-1641.0

QA utilities

In [11]:
import math
import ctypes
import os

ROOT_KEEPALIVE = []

def keep(obj):
    if obj:
        ROOT_KEEPALIVE.append(obj)
    return obj

def check_obj(obj, name):
    if obj is None:
        print(f"[BAD] {name}: None")
        return False
    try:
        cname = obj.ClassName()
        oname = obj.GetName()
    except Exception as e:
        print(f"[BAD] {name}: invalid ROOT object: {e}")
        return False

    print(f"[OK] {name}: {cname}  {oname}")
    return True

def check_hist(h, name):
    if not check_obj(h, name):
        return False
    print(f"     entries = {h.GetEntries():.3g}")
    print(f"     integral = {h.Integral():.3g}")
    print(f"     nbinsX = {h.GetNbinsX()}, nbinsY = {h.GetNbinsY() if hasattr(h, 'GetNbinsY') else '-'}")
    return True

In [12]:
check_hist(hists[0]["fg2d_eemass_reco"]["nominal"][0], "fg ee nominal cent0")
check_hist(hists[0]["bg2d_eemass_reco"]["nominal"][0], "bg ee nominal cent0")
check_hist(hists[0]["fg2d_eegmass_reco"]["nominal"][0], "fg eeg nominal cent0")
check_hist(hists[0]["bg2d_eegmass_reco"]["nominal"][0], "bg eeg nominal cent0")

[OK] fg ee nominal cent0: TH2F  fg2d_eemass_reco_nominal_icent0_file0
     entries = 1.04e+05
     integral = 1.04e+05
     nbinsX = 400, nbinsY = 100
[OK] bg ee nominal cent0: TH2F  bg2d_eemass_reco_nominal_icent0_file0
     entries = 1.02e+08
     integral = 1.01e+08
     nbinsX = 400, nbinsY = 100
[OK] fg eeg nominal cent0: TH2F  fg2d_eegmass_reco_nominal_icent0_file0
     entries = 1.02e+05
     integral = 6.47e+04
     nbinsX = 400, nbinsY = 100
[OK] bg eeg nominal cent0: TH2F  bg2d_eegmass_reco_nominal_icent0_file0
     entries = 1.17e+06
     integral = 5.99e+05
     nbinsX = 400, nbinsY = 100

True

helpers

In [13]:
def clone_hist(h, name):
    if not check_obj(h, f"clone source {name}"):
        return None

    hc = h.Clone(name)
    if not check_obj(hc, f"clone result {name}"):
        return None

    hc.SetDirectory(root.nullptr)
    keep(hc)
    return hc


def project_mass_in_pt(hist2d, pt_min, pt_max, name):
    if not check_obj(hist2d, f"project source {name}"):
        return None

    yaxis = hist2d.GetYaxis()
    y1 = yaxis.FindBin(pt_min + 1e-3)
    y2 = yaxis.FindBin(pt_max - 1e-3)

    print(f"project_mass_in_pt: {name}")
    print(f"  pt range = [{pt_min}, {pt_max})")
    print(f"  y bins   = {y1} to {y2}")

    proj = hist2d.ProjectionX(name, y1, y2)
    if not check_obj(proj, f"projection {name}"):
        return None

    proj.SetDirectory(root.nullptr)
    keep(proj)

    print(f"  proj integral = {proj.Integral():.3g}")
    return proj


def integral_range(hist, xmin, xmax):
    if not check_obj(hist, f"integral source {xmin}_{xmax}"):
        return 0.0, 0.0

    b1 = hist.FindBin(xmin + 1e-3)
    b2 = hist.FindBin(xmax - 1e-3)

    val = 0.0
    err2 = 0.0

    for ib in range(b1, b2 + 1):
        val += hist.GetBinContent(ib)
        err2 += hist.GetBinError(ib)**2

    return float(val), math.sqrt(err2)


def scale_bg_to_sideband(fg, bg, xmin, xmax):
    fg_int, fg_err = integral_range(fg, xmin, xmax)
    bg_int, bg_err = integral_range(bg, xmin, xmax)

    print(f"sideband [{xmin}, {xmax}]: FG={fg_int:.3g}, BG={bg_int:.3g}")

    if bg_int <= 0:
        print("  WARNING: BG sideband <= 0, using scale=1")
        return 1.0

    scale = fg_int / bg_int
    print(f"  scale = {scale:.6g}")
    return scale

cnerality sum

In [14]:
def sum_cent_mb(hists, ifile, kind, cfg, name):
    """Sum centralities for one file and one config."""
    hsum = None

    for icent in cent_bins:
        h = hists[ifile][kind][cfg][icent]
        if not h:
            continue

        if hsum is None:
            hsum = clone_hist(h, name)
            hsum.Reset("ICESM")

        hsum.Add(h)

    return hsum


def sum_cent_mb_all_files(hists, kind, cfg, name):
    """Sum centralities and files."""
    hsum = None

    for ifile in sorted(hists.keys()):
        if not isinstance(ifile, int):
            continue

        hmb = sum_cent_mb(hists, ifile, kind, cfg, f"{name}_file{ifile}")
        if not hmb:
            continue

        if hsum is None:
            hsum = clone_hist(hmb, name)
            hsum.Reset("ICESM")

        hsum.Add(hmb)

    return hsum

In [15]:
pt_min = 2.0
pt_max = 10.0

test_ee_fg = project_mass_in_pt(
    hists[0]["fg2d_eemass_reco"]["nominal"][0],
    pt_min, pt_max,
    "test_ee_fg"
)

test_ee_bg = project_mass_in_pt(
    hists[0]["bg2d_eemass_reco"]["nominal"][0],
    pt_min, pt_max,
    "test_ee_bg"
)

[OK] project source test_ee_fg: TH2F  fg2d_eemass_reco_nominal_icent0_file0
project_mass_in_pt: test_ee_fg
  pt range = [2.0, 10.0)
  y bins   = 21 to 100
[OK] projection test_ee_fg: TH1D  test_ee_fg
  proj integral = 9.36e+03
[OK] project source test_ee_bg: TH2F  bg2d_eemass_reco_nominal_icent0_file0
project_mass_in_pt: test_ee_bg
  pt range = [2.0, 10.0)
  y bins   = 21 to 100
[OK] projection test_ee_bg: TH1D  test_ee_bg
  proj integral = 5.11e+05

In [16]:
test_scale_ee = scale_bg_to_sideband(test_ee_fg, test_ee_bg, 0.15, 0.75)
print(test_scale_ee)

[OK] integral source 0.15_0.75: TH1D  test_ee_fg
[OK] integral source 0.15_0.75: TH1D  test_ee_bg
sideband [0.15, 0.75]: FG=43, BG=3.73e+05
  scale = 0.000115391
0.00011539101452853378

In [17]:
def get_ee_yield(h_fg_2d, h_bg_2d, pt_min, pt_max, cfg):
    h_fg = project_mass_in_pt(
        h_fg_2d,
        pt_min,
        pt_max,
        f"h_ee_fg_{cfg}_pt{pt_min:g}_{pt_max:g}"
    )

    h_bg = project_mass_in_pt(
        h_bg_2d,
        pt_min,
        pt_max,
        f"h_ee_bg_{cfg}_pt{pt_min:g}_{pt_max:g}"
    )

    if h_fg is None or h_bg is None:
        print("get_ee_yield: missing projection")
        return None

    scale = scale_bg_to_sideband(
        h_fg,
        h_bg,
        windows["ee_norm"][0],
        windows["ee_norm"][1]
    )

    h_bg_scaled = clone_hist(
        h_bg,
        f"h_ee_bg_scaled_{cfg}_pt{pt_min:g}_{pt_max:g}"
    )
    h_bg_scaled.Scale(scale)

    h_sub = clone_hist(
        h_fg,
        f"h_ee_sub_{cfg}_pt{pt_min:g}_{pt_max:g}"
    )
    h_sub.Add(h_bg_scaled, -1.0)

    y_fg, e_fg = integral_range(h_fg, *windows["ee_signal"])
    y_bg, e_bg = integral_range(h_bg_scaled, *windows["ee_signal"])
    y_sub, e_sub = integral_range(h_sub, *windows["ee_signal"])

    print("EE yield:")
    print(f"  FG signal = {y_fg:.3g}")
    print(f"  BG signal = {y_bg:.3g}")
    print(f"  SUB       = {y_sub:.3g} +/- {e_sub:.3g}")

    return {
        "h_fg": h_fg,
        "h_bg": h_bg_scaled,
        "h_sub": h_sub,
        "scale": scale,
        "yield": y_sub,
        "yield_err": e_sub,
        "fg_int": y_fg,
        "bg_int": y_bg,
    }

In [18]:
ee_info_test = get_ee_yield(
    hists[0]["fg2d_eemass_reco"]["nominal"][0],
    hists[0]["bg2d_eemass_reco"]["nominal"][0],
    2.0,
    10.0,
    "nominal"
)

ee_info_test["yield"]

[OK] project source h_ee_fg_nominal_pt2_10: TH2F  fg2d_eemass_reco_nominal_icent0_file0
project_mass_in_pt: h_ee_fg_nominal_pt2_10
  pt range = [2.0, 10.0)
  y bins   = 21 to 100
[OK] projection h_ee_fg_nominal_pt2_10: TH1D  h_ee_fg_nominal_pt2_10
  proj integral = 9.36e+03
[OK] project source h_ee_bg_nominal_pt2_10: TH2F  bg2d_eemass_reco_nominal_icent0_file0
project_mass_in_pt: h_ee_bg_nominal_pt2_10
  pt range = [2.0, 10.0)
  y bins   = 21 to 100
[OK] projection h_ee_bg_nominal_pt2_10: TH1D  h_ee_bg_nominal_pt2_10
  proj integral = 5.11e+05
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt2_10
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt2_10
sideband [0.2, 0.75]: FG=2, BG=3.52e+05
  scale = 5.67858e-06
[OK] clone source h_ee_bg_scaled_nominal_pt2_10: TH1D  h_ee_bg_nominal_pt2_10
[OK] clone result h_ee_bg_scaled_nominal_pt2_10: TH1D  h_ee_bg_scaled_nominal_pt2_10
[OK] clone source h_ee_sub_nominal_pt2_10: TH1D  h_ee_fg_nominal_pt2_10
[OK] clone result h_ee_sub_nominal_pt2_10: TH1D  h_ee_sub_nominal_pt2_10
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt2_10
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt2_10
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt2_10
EE yield:
  FG signal = 9.2e+03
  BG signal = 0.127
  SUB       = 9.2e+03 +/- 95.9

9195.872714728237

In [19]:
c = root.TCanvas("c_ee_test", "c_ee_test", 800, 600)
ee_info_test["h_fg"].GetXaxis().SetRangeUser(0, 0.3)
ee_info_test["h_fg"].SetLineColor(root.kBlue)
ee_info_test["h_fg"].SetMarkerColor(root.kBlue)
ee_info_test["h_fg"].Draw("E")
ee_info_test["h_bg"].SetLineColor(root.kRed)
ee_info_test["h_bg"].SetMarkerColor(root.kRed)
ee_info_test["h_bg"].Draw("same E")
c.Draw()

In [20]:
def get_eeg_subtracted_hist_no_fit(h_fg_2d, h_bg_2d, pt_min, pt_max, cfg):
    h_fg = project_mass_in_pt(
        h_fg_2d,
        pt_min,
        pt_max,
        f"h_eeg_fg_{cfg}_pt{pt_min:g}_{pt_max:g}"
    )

    h_bg = project_mass_in_pt(
        h_bg_2d,
        pt_min,
        pt_max,
        f"h_eeg_bg_{cfg}_pt{pt_min:g}_{pt_max:g}"
    )

    if h_fg is None or h_bg is None:
        print("get_eeg_subtracted_hist_no_fit: missing projection")
        return None

    scale = scale_bg_to_sideband(
        h_fg,
        h_bg,
        windows["eeg_norm"][0],
        windows["eeg_norm"][1]
    )

    h_bg_scaled = clone_hist(
        h_bg,
        f"h_eeg_bg_scaled_{cfg}_pt{pt_min:g}_{pt_max:g}"
    )
    h_bg_scaled.Scale(scale)

    h_sub = clone_hist(
        h_fg,
        f"h_eeg_sub_{cfg}_pt{pt_min:g}_{pt_max:g}"
    )
    h_sub.Add(h_bg_scaled, -1.0)

    y_raw, e_raw = integral_range(h_sub, *windows["eeg_signal"])

    print("EEG after mixed-BG subtraction, before fit:")
    print(f"  raw signal window = {y_raw:.3g} +/- {e_raw:.3g}")

    return {
        "h_fg": h_fg,
        "h_bg": h_bg_scaled,
        "h_sub": h_sub,
        "scale": scale,
        "raw_yield": y_raw,
        "raw_yield_err": e_raw,
    }

In [21]:
eeg_sub_test = get_eeg_subtracted_hist_no_fit(
    hists[0]["fg2d_eegmass_reco"]["nominal"][0],
    hists[0]["bg2d_eegmass_reco"]["nominal"][0],
    2.0,
    10.0,
    "nominal"
)

[OK] project source h_eeg_fg_nominal_pt2_10: TH2F  fg2d_eegmass_reco_nominal_icent0_file0
project_mass_in_pt: h_eeg_fg_nominal_pt2_10
  pt range = [2.0, 10.0)
  y bins   = 21 to 100
[OK] projection h_eeg_fg_nominal_pt2_10: TH1D  h_eeg_fg_nominal_pt2_10
  proj integral = 7.18e+03
[OK] project source h_eeg_bg_nominal_pt2_10: TH2F  bg2d_eegmass_reco_nominal_icent0_file0
project_mass_in_pt: h_eeg_bg_nominal_pt2_10
  pt range = [2.0, 10.0)
  y bins   = 21 to 100
[OK] projection h_eeg_bg_nominal_pt2_10: TH1D  h_eeg_bg_nominal_pt2_10
  proj integral = 4.32e+04
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt2_10
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt2_10
sideband [0.2, 0.8]: FG=3.55e+03, BG=3.27e+04
  scale = 0.10856
[OK] clone source h_eeg_bg_scaled_nominal_pt2_10: TH1D  h_eeg_bg_nominal_pt2_10
[OK] clone result h_eeg_bg_scaled_nominal_pt2_10: TH1D  h_eeg_bg_scaled_nominal_pt2_10
[OK] clone source h_eeg_sub_nominal_pt2_10: TH1D  h_eeg_fg_nominal_pt2_10
[OK] clone result h_eeg_sub_nominal_pt2_10: TH1D  h_eeg_sub_nominal_pt2_10
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt2_10
EEG after mixed-BG subtraction, before fit:
  raw signal window = 2.09e+03 +/- 50.2

In [22]:
c = root.TCanvas("c_eeg_sub_test", "c_eeg_sub_test", 800, 600)
eeg_sub_test["h_sub"].GetXaxis().SetRangeUser(0, 0.3)
eeg_sub_test["h_sub"].SetLineColor(root.kBlue)
eeg_sub_test["h_sub"].SetMarkerColor(root.kBlue)
eeg_sub_test["h_sub"].Draw("E")
c.Draw()

In [23]:
def safe_root_name(s):
    s = str(s)
    for ch in [".", "-", "+", " ", "/", "[", "]", "(", ")", ","]:
        s = s.replace(ch, "_")
    return s


def fit_one_eeg_hist_test(h_sub, name="test_fit"):
    if not check_hist(h_sub, f"{name} input"):
        return None

    if h_sub.Integral() <= 0:
        print(f"[BAD] {name}: histogram integral <= 0, skip fit")
        return None

    tag = safe_root_name(f"{name}_{len(ROOT_KEEPALIVE)}")

    amp0 = max(h_sub.GetMaximum(), 1.0)
    mean0 = 0.135
    sigma0 = 0.018

    f = root.TF1(f"f_{tag}", "gaus(0)+pol2(3)", 0.05, 0.78)

    if not check_obj(f, f"TF1 f_{tag}"):
        return None

    root.SetOwnership(f, False)
    keep(f)

    f.SetParameters(amp0, mean0, sigma0, 0.0, 0.0, 0.0)
    f.SetParLimits(1, 0.10, 0.17)
    f.SetParLimits(2, 0.006, 0.050)

    print("Before fit:")
    print("  amp0 =", amp0)
    print("  mean0 =", mean0)
    print("  sigma0 =", sigma0)

    res = h_sub.Fit(f, "RQS0")

    print("After fit:")

    if not check_obj(f, f"TF1 after fit {tag}"):
        print("[BAD] Fit killed TF1 pointer")
        return None

    status = int(res.Status()) if res else -999

    print("  status =", status)
    print("  mean =", f.GetParameter(1))
    print("  sigma =", f.GetParameter(2))
    print("  chi2/ndf =", f.GetChisquare(), "/", f.GetNDF())

    return f

In [24]:
f_test = fit_one_eeg_hist_test(eeg_sub_test["h_sub"], "eeg_nominal_pt2_10")

[OK] eeg_nominal_pt2_10 input: TH1D  h_eeg_sub_nominal_pt2_10
     entries = 806
     integral = 2.7e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_nominal_pt2_10_10: TF1  f_eeg_nominal_pt2_10_10
Before fit:
  amp0 = 189.90391317639865
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_nominal_pt2_10_10: TF1  f_eeg_nominal_pt2_10_10
  status = 0
  mean = 0.13202991433244057
  sigma = 0.01174418393006065
  chi2/ndf = 125.33074232976448 / 94

In [25]:
c = root.TCanvas("c_fit_test", "c_fit_test", 800, 600)
eeg_sub_test["h_sub"].GetXaxis().SetRangeUser(0, 0.3)
eeg_sub_test["h_sub"].Draw("E")
f_test.SetLineColor(root.kRed)
f_test.Draw("same")
c.Draw()

In [26]:
def pol2_subtracted_yield(h, f, xmin, xmax):
    if not check_hist(h, "pol2 yield hist"):
        return 0.0, 0.0, 0.0, 0.0

    if f is None or not check_obj(f, "pol2 yield fit"):
        print("[WARNING] No valid fit. Return raw integral without pol2 subtraction.")
        raw, raw_err = integral_range(h, xmin, xmax)
        return raw, raw_err, raw, 0.0

    pol2 = root.TF1(f"pol2_from_{safe_root_name(f.GetName())}_{len(ROOT_KEEPALIVE)}", "pol2", 0.05, 0.78)
    root.SetOwnership(pol2, False)
    keep(pol2)

    pol2.SetParameters(f.GetParameter(3), f.GetParameter(4), f.GetParameter(5))

    b1 = h.FindBin(xmin + 1e-3)
    b2 = h.FindBin(xmax - 1e-3)

    raw = 0.0
    bg = 0.0
    sig = 0.0
    err2 = 0.0

    for ib in range(b1, b2 + 1):
        x = h.GetBinCenter(ib)
        y = h.GetBinContent(ib)
        b = pol2.Eval(x)

        raw += y
        bg += b
        sig += y - b
        err2 += h.GetBinError(ib)**2

    err = math.sqrt(err2)

    print("pol2-subtracted yield:")
    print(f"  raw = {raw:.3g}")
    print(f"  pol2 = {bg:.3g}")
    print(f"  signal = {sig:.3g} +/- {err:.3g}")

    return sig, err, raw, bg

In [27]:
y_eeg, e_eeg, raw_eeg, pol2_eeg = pol2_subtracted_yield(
    eeg_sub_test["h_sub"],
    f_test,
    0.09,
    0.20
)

[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt2_10
     entries = 806
     integral = 2.7e+03
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_nominal_pt2_10_10
pol2-subtracted yield:
  raw = 2.09e+03
  pol2 = 30
  signal = 2.06e+03 +/- 50.7

In [28]:
ratio_test =  ee_info_test["yield"] / y_eeg if y_eeg != 0 else 0.0
ratio_test

4.466966005701246

In [29]:
def one_bin_result(cfg, pt_min, pt_max, ifile=0, icent=0):
    print("="*70)
    print(f"one_bin_result cfg={cfg}, pt=[{pt_min},{pt_max}], file={ifile}, cent={icent}")

    ee_info = get_ee_yield(
        hists[ifile]["fg2d_eemass_reco"][cfg][icent],
        hists[ifile]["bg2d_eemass_reco"][cfg][icent],
        pt_min,
        pt_max,
        cfg
    )

    eeg_pre = get_eeg_subtracted_hist_no_fit(
        hists[ifile]["fg2d_eegmass_reco"][cfg][icent],
        hists[ifile]["bg2d_eegmass_reco"][cfg][icent],
        pt_min,
        pt_max,
        cfg
    )

    f = fit_one_eeg_hist_test(
        eeg_pre["h_sub"],
        f"eeg_{cfg}_pt{pt_min:g}_{pt_max:g}"
    )

    y_eeg, e_eeg, raw_eeg, pol2_eeg = pol2_subtracted_yield(
        eeg_pre["h_sub"],
        f,
        *windows["eeg_signal"]
    )

    ratio = ee_info["yield"] / y_eeg if y_eeg != 0 else 0.0

    print("FINAL ONE BIN")
    print(f"  Yee  = {ee_info['yield']:.6g}")
    print(f"  Yeeg = {y_eeg:.6g}")
    print(f"  ratio = {ratio:.6g}")

    return {
        "ee": ee_info,
        "eeg_pre": eeg_pre,
        "fit": f,
        "y_eeg": y_eeg,
        "e_eeg": e_eeg,
        "ratio": ratio,
    }

In [30]:
res_one = one_bin_result("nominal", 2.0, 10.0, ifile=0, icent=0)

======================================================================
one_bin_result cfg=nominal, pt=[2.0,10.0], file=0, cent=0
[OK] project source h_ee_fg_nominal_pt2_10: TH2F  fg2d_eemass_reco_nominal_icent0_file0
project_mass_in_pt: h_ee_fg_nominal_pt2_10
  pt range = [2.0, 10.0)
  y bins   = 21 to 100
[OK] projection h_ee_fg_nominal_pt2_10: TH1D  h_ee_fg_nominal_pt2_10
  proj integral = 9.36e+03
[OK] project source h_ee_bg_nominal_pt2_10: TH2F  bg2d_eemass_reco_nominal_icent0_file0
project_mass_in_pt: h_ee_bg_nominal_pt2_10
  pt range = [2.0, 10.0)
  y bins   = 21 to 100
[OK] projection h_ee_bg_nominal_pt2_10: TH1D  h_ee_bg_nominal_pt2_10
  proj integral = 5.11e+05
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt2_10
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt2_10
sideband [0.2, 0.75]: FG=2, BG=3.52e+05
  scale = 5.67858e-06
[OK] clone source h_ee_bg_scaled_nominal_pt2_10: TH1D  h_ee_bg_nominal_pt2_10
[OK] clone result h_ee_bg_scaled_nominal_pt2_10: TH1D  h_ee_bg_scaled_nominal_pt2_10
[OK] clone source h_ee_sub_nominal_pt2_10: TH1D  h_ee_fg_nominal_pt2_10
[OK] clone result h_ee_sub_nominal_pt2_10: TH1D  h_ee_sub_nominal_pt2_10
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt2_10
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt2_10
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt2_10
EE yield:
  FG signal = 9.2e+03
  BG signal = 0.127
  SUB       = 9.2e+03 +/- 95.9
[OK] project source h_eeg_fg_nominal_pt2_10: TH2F  fg2d_eegmass_reco_nominal_icent0_file0
project_mass_in_pt: h_eeg_fg_nominal_pt2_10
  pt range = [2.0, 10.0)
  y bins   = 21 to 100
[OK] projection h_eeg_fg_nominal_pt2_10: TH1D  h_eeg_fg_nominal_pt2_10
  proj integral = 7.18e+03
[OK] project source h_eeg_bg_nominal_pt2_10: TH2F  bg2d_eegmass_reco_nominal_icent0_file0
project_mass_in_pt: h_eeg_bg_nominal_pt2_10
  pt range = [2.0, 10.0)
  y bins   = 21 to 100
[OK] projection h_eeg_bg_nominal_pt2_10: TH1D  h_eeg_bg_nominal_pt2_10
  proj integral = 4.32e+04
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt2_10
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt2_10
sideband [0.2, 0.8]: FG=3.55e+03, BG=3.27e+04
  scale = 0.10856
[OK] clone source h_eeg_bg_scaled_nominal_pt2_10: TH1D  h_eeg_bg_nominal_pt2_10
[OK] clone result h_eeg_bg_scaled_nominal_pt2_10: TH1D  h_eeg_bg_scaled_nominal_pt2_10
[OK] clone source h_eeg_sub_nominal_pt2_10: TH1D  h_eeg_fg_nominal_pt2_10
[OK] clone result h_eeg_sub_nominal_pt2_10: TH1D  h_eeg_sub_nominal_pt2_10
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt2_10
EEG after mixed-BG subtraction, before fit:
  raw signal window = 2.09e+03 +/- 50.2
[OK] eeg_nominal_pt2_10 input: TH1D  h_eeg_sub_nominal_pt2_10
     entries = 806
     integral = 2.49e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_nominal_pt2_10_20: TF1  f_eeg_nominal_pt2_10_20
Before fit:
  amp0 = 189.90391317639865
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_nominal_pt2_10_20: TF1  f_eeg_nominal_pt2_10_20
  status = 0
  mean = 0.13197866795488492
  sigma = 0.011726301881528374
  chi2/ndf = 376.778534125698 / 286
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt2_10
     entries = 806
     integral = 2.49e+03
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_nominal_pt2_10_20
pol2-subtracted yield:
  raw = 2.09e+03
  pol2 = 39.4
  signal = 2.05e+03 +/- 50.2
FINAL ONE BIN
  Yee  = 9195.87
  Yeeg = 2054.4
  ratio = 4.47618

In [31]:
res_one_low = one_bin_result("nominal", 1.2, 2.0, ifile=0, icent=0)

======================================================================
one_bin_result cfg=nominal, pt=[1.2,2.0], file=0, cent=0
[OK] project source h_ee_fg_nominal_pt1.2_2: TH2F  fg2d_eemass_reco_nominal_icent0_file0
project_mass_in_pt: h_ee_fg_nominal_pt1.2_2
  pt range = [1.2, 2.0)
  y bins   = 13 to 20
[OK] projection h_ee_fg_nominal_pt1.2_2: TH1D  h_ee_fg_nominal_pt1.2_2
  proj integral = 3.82e+04
[OK] project source h_ee_bg_nominal_pt1.2_2: TH2F  bg2d_eemass_reco_nominal_icent0_file0
project_mass_in_pt: h_ee_bg_nominal_pt1.2_2
  pt range = [1.2, 2.0)
  y bins   = 13 to 20
[OK] projection h_ee_bg_nominal_pt1.2_2: TH1D  h_ee_bg_nominal_pt1.2_2
  proj integral = 5.87e+06
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt1.2_2
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt1.2_2
sideband [0.2, 0.75]: FG=0, BG=4.25e+06
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt1.2_2: TH1D  h_ee_bg_nominal_pt1.2_2
[OK] clone result h_ee_bg_scaled_nominal_pt1.2_2: TH1D  h_ee_bg_scaled_nominal_pt1.2_2
[OK] clone source h_ee_sub_nominal_pt1.2_2: TH1D  h_ee_fg_nominal_pt1.2_2
[OK] clone result h_ee_sub_nominal_pt1.2_2: TH1D  h_ee_sub_nominal_pt1.2_2
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt1.2_2
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt1.2_2
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt1.2_2
EE yield:
  FG signal = 3.79e+04
  BG signal = 0
  SUB       = 3.79e+04 +/- 195
[OK] project source h_eeg_fg_nominal_pt1.2_2: TH2F  fg2d_eegmass_reco_nominal_icent0_file0
project_mass_in_pt: h_eeg_fg_nominal_pt1.2_2
  pt range = [1.2, 2.0)
  y bins   = 13 to 20
[OK] projection h_eeg_fg_nominal_pt1.2_2: TH1D  h_eeg_fg_nominal_pt1.2_2
  proj integral = 2.45e+04
[OK] project source h_eeg_bg_nominal_pt1.2_2: TH2F  bg2d_eegmass_reco_nominal_icent0_file0
project_mass_in_pt: h_eeg_bg_nominal_pt1.2_2
  pt range = [1.2, 2.0)
  y bins   = 13 to 20
[OK] projection h_eeg_bg_nominal_pt1.2_2: TH1D  h_eeg_bg_nominal_pt1.2_2
  proj integral = 2.07e+05
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt1.2_2
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt1.2_2
sideband [0.2, 0.8]: FG=1.27e+04, BG=1.61e+05
  scale = 0.0787
[OK] clone source h_eeg_bg_scaled_nominal_pt1.2_2: TH1D  h_eeg_bg_nominal_pt1.2_2
[OK] clone result h_eeg_bg_scaled_nominal_pt1.2_2: TH1D  h_eeg_bg_scaled_nominal_pt1.2_2
[OK] clone source h_eeg_sub_nominal_pt1.2_2: TH1D  h_eeg_fg_nominal_pt1.2_2
[OK] clone result h_eeg_sub_nominal_pt1.2_2: TH1D  h_eeg_sub_nominal_pt1.2_2
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt1.2_2
EEG after mixed-BG subtraction, before fit:
  raw signal window = 7.02e+03 +/- 95.3
[OK] eeg_nominal_pt1.2_2 input: TH1D  h_eeg_sub_nominal_pt1.2_2
     entries = 2.59e+03
     integral = 8.17e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_nominal_pt1_2_2_30: TF1  f_eeg_nominal_pt1_2_2_30
Before fit:
  amp0 = 626.891204264599
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_nominal_pt1_2_2_30: TF1  f_eeg_nominal_pt1_2_2_30
  status = 0
  mean = 0.13151320367127164
  sigma = 0.011108212127978976
  chi2/ndf = 374.5739111284201 / 286
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt1.2_2
     entries = 2.59e+03
     integral = 8.17e+03
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_nominal_pt1_2_2_30
pol2-subtracted yield:
  raw = 7.02e+03
  pol2 = 280
  signal = 6.74e+03 +/- 95.3
FINAL ONE BIN
  Yee  = 37924
  Yeeg = 6736.12
  ratio = 5.62995

In [32]:
def sum_hists_list(hist_list, name):
    hsum = None

    for h in hist_list:
        if h is None:
            continue

        if hsum is None:
            hsum = clone_hist(h, name)
            hsum.Reset("ICESM")

        hsum.Add(h)

    if hsum is None:
        print(f"[BAD] sum_hists_list: could not build {name}")
        return None

    print(f"[OK] built {name}: integral={hsum.Integral():.6g}")
    return hsum


def build_mb_one_file(hists, ifile, kind, cfg):
    hs = []
    for icent in cent_bins:
        h = hists[ifile][kind][cfg][icent]
        hs.append(h)

    return sum_hists_list(hs, f"mb_file{ifile}_{kind}_{cfg}")


def build_mb_all_files(hists, kind, cfg):
    hs = []

    for ifile in sorted(hists.keys()):
        if not isinstance(ifile, int):
            continue

        h_mb_file = build_mb_one_file(hists, ifile, kind, cfg)
        if h_mb_file is not None:
            hs.append(h_mb_file)

    return sum_hists_list(hs, f"mb_all_{kind}_{cfg}")


def build_mb_set(hists, cfg):
    mb = {}

    mb["fg_ee"] = build_mb_all_files(hists, "fg2d_eemass_reco", cfg)
    mb["bg_ee"] = build_mb_all_files(hists, "bg2d_eemass_reco", cfg)
    mb["fg_eeg"] = build_mb_all_files(hists, "fg2d_eegmass_reco", cfg)
    mb["bg_eeg"] = build_mb_all_files(hists, "bg2d_eegmass_reco", cfg)

    return mb

In [33]:
mb_nominal = build_mb_set(hists, "nominal")

check_hist(mb_nominal["fg_ee"], "MB fg ee nominal")
check_hist(mb_nominal["bg_ee"], "MB bg ee nominal")
check_hist(mb_nominal["fg_eeg"], "MB fg eeg nominal")
check_hist(mb_nominal["bg_eeg"], "MB bg eeg nominal")

[OK] clone source mb_file0_fg2d_eemass_reco_nominal: TH2F  fg2d_eemass_reco_nominal_icent0_file0
[OK] clone result mb_file0_fg2d_eemass_reco_nominal: TH2F  mb_file0_fg2d_eemass_reco_nominal
[OK] built mb_file0_fg2d_eemass_reco_nominal: integral=103674
[OK] clone source mb_all_fg2d_eemass_reco_nominal: TH2F  mb_file0_fg2d_eemass_reco_nominal
[OK] clone result mb_all_fg2d_eemass_reco_nominal: TH2F  mb_all_fg2d_eemass_reco_nominal
[OK] built mb_all_fg2d_eemass_reco_nominal: integral=103674
[OK] clone source mb_file0_bg2d_eemass_reco_nominal: TH2F  bg2d_eemass_reco_nominal_icent0_file0
[OK] clone result mb_file0_bg2d_eemass_reco_nominal: TH2F  mb_file0_bg2d_eemass_reco_nominal
[OK] built mb_file0_bg2d_eemass_reco_nominal: integral=1.01495e+08
[OK] clone source mb_all_bg2d_eemass_reco_nominal: TH2F  mb_file0_bg2d_eemass_reco_nominal
[OK] clone result mb_all_bg2d_eemass_reco_nominal: TH2F  mb_all_bg2d_eemass_reco_nominal
[OK] built mb_all_bg2d_eemass_reco_nominal: integral=1.01495e+08
[OK] clone source mb_file0_fg2d_eegmass_reco_nominal: TH2F  fg2d_eegmass_reco_nominal_icent0_file0
[OK] clone result mb_file0_fg2d_eegmass_reco_nominal: TH2F  mb_file0_fg2d_eegmass_reco_nominal
[OK] built mb_file0_fg2d_eegmass_reco_nominal: integral=64670
[OK] clone source mb_all_fg2d_eegmass_reco_nominal: TH2F  mb_file0_fg2d_eegmass_reco_nominal
[OK] clone result mb_all_fg2d_eegmass_reco_nominal: TH2F  mb_all_fg2d_eegmass_reco_nominal
[OK] built mb_all_fg2d_eegmass_reco_nominal: integral=64670
[OK] clone source mb_file0_bg2d_eegmass_reco_nominal: TH2F  bg2d_eegmass_reco_nominal_icent0_file0
[OK] clone result mb_file0_bg2d_eegmass_reco_nominal: TH2F  mb_file0_bg2d_eegmass_reco_nominal
[OK] built mb_file0_bg2d_eegmass_reco_nominal: integral=599277
[OK] clone source mb_all_bg2d_eegmass_reco_nominal: TH2F  mb_file0_bg2d_eegmass_reco_nominal
[OK] clone result mb_all_bg2d_eegmass_reco_nominal: TH2F  mb_all_bg2d_eegmass_reco_nominal
[OK] built mb_all_bg2d_eegmass_reco_nominal: integral=599277
[OK] MB fg ee nominal: TH2F  mb_all_fg2d_eemass_reco_nominal
     entries = 1.04e+05
     integral = 1.04e+05
     nbinsX = 400, nbinsY = 100
[OK] MB bg ee nominal: TH2F  mb_all_bg2d_eemass_reco_nominal
     entries = 1.02e+08
     integral = 1.01e+08
     nbinsX = 400, nbinsY = 100
[OK] MB fg eeg nominal: TH2F  mb_all_fg2d_eegmass_reco_nominal
     entries = 1.02e+05
     integral = 6.47e+04
     nbinsX = 400, nbinsY = 100
[OK] MB bg eeg nominal: TH2F  mb_all_bg2d_eegmass_reco_nominal
     entries = 1.17e+06
     integral = 5.99e+05
     nbinsX = 400, nbinsY = 100

True

In [34]:
pt_min = 2.0
pt_max = 10.0

mb_ee_fg_test = project_mass_in_pt(mb_nominal["fg_ee"], pt_min, pt_max, "mb_ee_fg_test")
mb_ee_bg_test = project_mass_in_pt(mb_nominal["bg_ee"], pt_min, pt_max, "mb_ee_bg_test")

mb_eeg_fg_test = project_mass_in_pt(mb_nominal["fg_eeg"], pt_min, pt_max, "mb_eeg_fg_test")
mb_eeg_bg_test = project_mass_in_pt(mb_nominal["bg_eeg"], pt_min, pt_max, "mb_eeg_bg_test")

[OK] project source mb_ee_fg_test: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: mb_ee_fg_test
  pt range = [2.0, 10.0)
  y bins   = 21 to 100
[OK] projection mb_ee_fg_test: TH1D  mb_ee_fg_test
  proj integral = 9.36e+03
[OK] project source mb_ee_bg_test: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: mb_ee_bg_test
  pt range = [2.0, 10.0)
  y bins   = 21 to 100
[OK] projection mb_ee_bg_test: TH1D  mb_ee_bg_test
  proj integral = 5.11e+05
[OK] project source mb_eeg_fg_test: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: mb_eeg_fg_test
  pt range = [2.0, 10.0)
  y bins   = 21 to 100
[OK] projection mb_eeg_fg_test: TH1D  mb_eeg_fg_test
  proj integral = 7.18e+03
[OK] project source mb_eeg_bg_test: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: mb_eeg_bg_test
  pt range = [2.0, 10.0)
  y bins   = 21 to 100
[OK] projection mb_eeg_bg_test: TH1D  mb_eeg_bg_test
  proj integral = 4.32e+04

In [35]:
c_mb_test = root.TCanvas("c_mb_test", "c_mb_test", 1200, 600)
c_mb_test.Divide(2, 1)

c_mb_test.cd(1)
mb_ee_fg_test.GetXaxis().SetRangeUser(0, 0.3)
mb_ee_fg_test.SetMarkerColor(root.kBlue)
mb_ee_fg_test.SetLineColor(root.kBlue)
mb_ee_fg_test.Draw("E")

ee_scale_mb = scale_bg_to_sideband(mb_ee_fg_test, mb_ee_bg_test, 0.15, 0.75)
mb_ee_bg_draw = clone_hist(mb_ee_bg_test, "mb_ee_bg_draw")
mb_ee_bg_draw.Scale(ee_scale_mb)
mb_ee_bg_draw.SetMarkerColor(root.kRed)
mb_ee_bg_draw.SetLineColor(root.kRed)
mb_ee_bg_draw.Draw("same E")

c_mb_test.cd(2)
mb_eeg_fg_test.GetXaxis().SetRangeUser(0, 0.3)
mb_eeg_fg_test.SetMarkerColor(root.kBlue)
mb_eeg_fg_test.SetLineColor(root.kBlue)
mb_eeg_fg_test.Draw("E")

eeg_scale_mb = scale_bg_to_sideband(mb_eeg_fg_test, mb_eeg_bg_test, 0.30, 0.80)
mb_eeg_bg_draw = clone_hist(mb_eeg_bg_test, "mb_eeg_bg_draw")
mb_eeg_bg_draw.Scale(eeg_scale_mb)
mb_eeg_bg_draw.SetMarkerColor(root.kRed)
mb_eeg_bg_draw.SetLineColor(root.kRed)
mb_eeg_bg_draw.Draw("same E")

c_mb_test.Draw()

[OK] integral source 0.15_0.75: TH1D  mb_ee_fg_test
[OK] integral source 0.15_0.75: TH1D  mb_ee_bg_test
sideband [0.15, 0.75]: FG=43, BG=3.73e+05
  scale = 0.000115391
[OK] clone source mb_ee_bg_draw: TH1D  mb_ee_bg_test
[OK] clone result mb_ee_bg_draw: TH1D  mb_ee_bg_draw
[OK] integral source 0.3_0.8: TH1D  mb_eeg_fg_test
[OK] integral source 0.3_0.8: TH1D  mb_eeg_bg_test
sideband [0.3, 0.8]: FG=2.94e+03, BG=2.73e+04
  scale = 0.107632
[OK] clone source mb_eeg_bg_draw: TH1D  mb_eeg_bg_test
[OK] clone result mb_eeg_bg_draw: TH1D  mb_eeg_bg_draw

In [36]:
def one_bin_result_mb(cfg, mb, pt_min, pt_max):
    print("="*80)
    print(f"one_bin_result_mb cfg={cfg}, pt=[{pt_min},{pt_max}]")

    ee_info = get_ee_yield(
        mb["fg_ee"],
        mb["bg_ee"],
        pt_min,
        pt_max,
        cfg
    )

    eeg_pre = get_eeg_subtracted_hist_no_fit(
        mb["fg_eeg"],
        mb["bg_eeg"],
        pt_min,
        pt_max,
        cfg
    )

    f = fit_one_eeg_hist_test(
        eeg_pre["h_sub"],
        f"eeg_mb_{cfg}_pt{pt_min:g}_{pt_max:g}"
    )

    y_eeg, e_eeg, raw_eeg, pol2_eeg = pol2_subtracted_yield(
        eeg_pre["h_sub"],
        f,
        *windows["eeg_signal"]
    )

    y_ee = ee_info["yield"]
    e_ee = ee_info["yield_err"]

    eeg_over_ee = y_eeg / y_ee if y_ee != 0 else float("nan")
    ee_over_eeg = y_ee / y_eeg if y_eeg != 0 else float("nan")

    print("FINAL MB ONE BIN")
    print(f"  Yee        = {y_ee:.6g} +/- {e_ee:.6g}")
    print(f"  Yeeg       = {y_eeg:.6g} +/- {e_eeg:.6g}")
    print(f"  eeg / ee   = {eeg_over_ee:.6g}")
    print(f"  ee / eeg   = {ee_over_eeg:.6g}")

    return {
        "cfg": cfg,
        "pt_min": pt_min,
        "pt_max": pt_max,
        "ee": ee_info,
        "eeg_pre": eeg_pre,
        "fit": f,
        "y_ee": y_ee,
        "e_ee": e_ee,
        "y_eeg": y_eeg,
        "e_eeg": e_eeg,
        "raw_eeg": raw_eeg,
        "pol2_eeg": pol2_eeg,
        "eeg_over_ee": eeg_over_ee,
        "ee_over_eeg": ee_over_eeg,
    }

In [37]:
res_mb_one = one_bin_result_mb("nominal", mb_nominal, 1.5, 2.0)

================================================================================
one_bin_result_mb cfg=nominal, pt=[1.5,2.0]
[OK] project source h_ee_fg_nominal_pt1.5_2: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt1.5_2
  pt range = [1.5, 2.0)
  y bins   = 16 to 20
[OK] projection h_ee_fg_nominal_pt1.5_2: TH1D  h_ee_fg_nominal_pt1.5_2
  proj integral = 1.66e+04
[OK] project source h_ee_bg_nominal_pt1.5_2: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt1.5_2
  pt range = [1.5, 2.0)
  y bins   = 16 to 20
[OK] projection h_ee_bg_nominal_pt1.5_2: TH1D  h_ee_bg_nominal_pt1.5_2
  proj integral = 1.86e+06
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt1.5_2
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt1.5_2
sideband [0.2, 0.75]: FG=0, BG=1.34e+06
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt1.5_2: TH1D  h_ee_bg_nominal_pt1.5_2
[OK] clone result h_ee_bg_scaled_nominal_pt1.5_2: TH1D  h_ee_bg_scaled_nominal_pt1.5_2
[OK] clone source h_ee_sub_nominal_pt1.5_2: TH1D  h_ee_fg_nominal_pt1.5_2
[OK] clone result h_ee_sub_nominal_pt1.5_2: TH1D  h_ee_sub_nominal_pt1.5_2
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt1.5_2
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt1.5_2
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt1.5_2
EE yield:
  FG signal = 1.65e+04
  BG signal = 0
  SUB       = 1.65e+04 +/- 128
[OK] project source h_eeg_fg_nominal_pt1.5_2: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt1.5_2
  pt range = [1.5, 2.0)
  y bins   = 16 to 20
[OK] projection h_eeg_fg_nominal_pt1.5_2: TH1D  h_eeg_fg_nominal_pt1.5_2
  proj integral = 1.11e+04
[OK] project source h_eeg_bg_nominal_pt1.5_2: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_bg_nominal_pt1.5_2
  pt range = [1.5, 2.0)
  y bins   = 16 to 20
[OK] projection h_eeg_bg_nominal_pt1.5_2: TH1D  h_eeg_bg_nominal_pt1.5_2
  proj integral = 8.89e+04
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt1.5_2
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt1.5_2
sideband [0.2, 0.8]: FG=5.7e+03, BG=6.91e+04
  scale = 0.0824255
[OK] clone source h_eeg_bg_scaled_nominal_pt1.5_2: TH1D  h_eeg_bg_nominal_pt1.5_2
[OK] clone result h_eeg_bg_scaled_nominal_pt1.5_2: TH1D  h_eeg_bg_scaled_nominal_pt1.5_2
[OK] clone source h_eeg_sub_nominal_pt1.5_2: TH1D  h_eeg_fg_nominal_pt1.5_2
[OK] clone result h_eeg_sub_nominal_pt1.5_2: TH1D  h_eeg_sub_nominal_pt1.5_2
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt1.5_2
EEG after mixed-BG subtraction, before fit:
  raw signal window = 3.27e+03 +/- 64.1
[OK] eeg_mb_nominal_pt1.5_2 input: TH1D  h_eeg_sub_nominal_pt1.5_2
     entries = 1.21e+03
     integral = 3.75e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_nominal_pt1_5_2_54: TF1  f_eeg_mb_nominal_pt1_5_2_54
Before fit:
  amp0 = 296.3221059941838
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_mb_nominal_pt1_5_2_54: TF1  f_eeg_mb_nominal_pt1_5_2_54
  status = 0
  mean = 0.13138194850246357
  sigma = 0.011112143147766075
  chi2/ndf = 309.81765895926054 / 286
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt1.5_2
     entries = 1.21e+03
     integral = 3.75e+03
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_mb_nominal_pt1_5_2_54
pol2-subtracted yield:
  raw = 3.27e+03
  pol2 = 108
  signal = 3.16e+03 +/- 64.1
FINAL MB ONE BIN
  Yee        = 16487 +/- 128.402
  Yeeg       = 3160.29 +/- 64.0593
  eeg / ee   = 0.191684
  ee / eeg   = 5.21693

In [38]:
c_mb_fit = root.TCanvas("c_mb_fit", "c_mb_fit", 800, 600)
res_mb_one["eeg_pre"]["h_sub"].GetXaxis().SetRangeUser(0, 0.3)
res_mb_one["eeg_pre"]["h_sub"].Draw("E")
res_mb_one["fit"].SetLineColor(root.kRed)
res_mb_one["fit"].Draw("same")
c_mb_fit.Draw()

In [39]:
fit_out_dir = "output/fits"
os.makedirs(fit_out_dir, exist_ok=True)

def save_one_bin_canvas(res, tag):
    c = root.TCanvas(f"c_{tag}", f"c_{tag}", 1200, 600)
    c.Divide(2, 1)

    c.cd(1)
    h_ee_fg = res["ee"]["h_fg"]
    h_ee_bg = res["ee"]["h_bg"]

    h_ee_fg.GetXaxis().SetRangeUser(0, 0.3)
    h_ee_fg.SetMarkerColor(root.kBlue)
    h_ee_fg.SetLineColor(root.kBlue)
    h_ee_fg.Draw("E")

    h_ee_bg.SetMarkerColor(root.kRed)
    h_ee_bg.SetLineColor(root.kRed)
    h_ee_bg.Draw("same E")

    lat = root.TLatex()
    lat.SetNDC(True)
    lat.SetTextSize(0.035)
    lat.DrawLatex(0.50, 0.82, f"Y_ee = {res['y_ee']:.3g}")

    c.cd(2)
    h_eeg_sub = res["eeg_pre"]["h_sub"]
    fit = res["fit"]

    h_eeg_sub.GetXaxis().SetRangeUser(0, 0.3)
    h_eeg_sub.SetMarkerColor(root.kBlue)
    h_eeg_sub.SetLineColor(root.kBlue)
    h_eeg_sub.Draw("E")

    fit.SetLineColor(root.kRed)
    fit.Draw("same")

    lat.DrawLatex(0.50, 0.82, f"Y_eeg = {res['y_eeg']:.3g}")
    lat.DrawLatex(0.50, 0.77, f"eeg/ee = {res['eeg_over_ee']:.4g}")
    lat.DrawLatex(0.50, 0.72, f"ee/eeg = {res['ee_over_eeg']:.4g}")

    png = f"{fit_out_dir}/{tag}.png"
    pdf = f"{fit_out_dir}/{tag}.pdf"

    c.SaveAs(png)
    c.SaveAs(pdf)

    keep(c)
    print("saved:", png)
    return c

In [40]:
c_saved_test = save_one_bin_canvas(res_mb_one, "test_nominal_mb_pt2_10")
c_saved_test.Draw()

saved: output/fits/test_nominal_mb_pt2_10.png

In [41]:
import pandas as pd

def run_pt_bins_for_config(cfg, mb, save_canvases=False):
    rows = []
    results = {}

    for ipt in range(len(pt_bins) - 1):
        pt_min = pt_bins[ipt]
        pt_max = pt_bins[ipt + 1]

        print("\n")
        print("#"*80)
        print(f"Running {cfg}: pT [{pt_min}, {pt_max})")

        res = one_bin_result_mb(cfg, mb, pt_min, pt_max)
        results[(pt_min, pt_max)] = res

        if save_canvases:
            tag = f"{cfg}_mb_pt{str(pt_min).replace('.','p')}_{str(pt_max).replace('.','p')}"
            save_one_bin_canvas(res, tag)

        row = {
            "config": cfg,
            "pt_min": pt_min,
            "pt_max": pt_max,
            "pt_center": 0.5 * (pt_min + pt_max),

            "y_ee": res["y_ee"],
            "e_ee": res["e_ee"],
            "y_eeg": res["y_eeg"],
            "e_eeg": res["e_eeg"],

            "raw_eeg": res["raw_eeg"],
            "pol2_eeg": res["pol2_eeg"],

            "eeg_over_ee": res["eeg_over_ee"],
            "ee_over_eeg": res["ee_over_eeg"],

            "fit_mean": res["fit"].GetParameter(1) if res["fit"] else float("nan"),
            "fit_sigma": abs(res["fit"].GetParameter(2)) if res["fit"] else float("nan"),
            "fit_chi2": res["fit"].GetChisquare() if res["fit"] else float("nan"),
            "fit_ndf": res["fit"].GetNDF() if res["fit"] else -999,
        }

        rows.append(row)

    df = pd.DataFrame(rows)
    return df, results

In [42]:
df_nominal_mb, results_nominal_mb = run_pt_bins_for_config(
    "nominal",
    mb_nominal,
    save_canvases=False
)

df_nominal_mb

################################################################################
Running nominal: pT [0.8, 1.0)
================================================================================
one_bin_result_mb cfg=nominal, pt=[0.8,1.0]
[OK] project source h_ee_fg_nominal_pt0.8_1: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt0.8_1
  pt range = [0.8, 1.0)
  y bins   = 9 to 10
[OK] projection h_ee_fg_nominal_pt0.8_1: TH1D  h_ee_fg_nominal_pt0.8_1
  proj integral = 2.4e+04
[OK] project source h_ee_bg_nominal_pt0.8_1: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt0.8_1
  pt range = [0.8, 1.0)
  y bins   = 9 to 10
[OK] projection h_ee_bg_nominal_pt0.8_1: TH1D  h_ee_bg_nominal_pt0.8_1
  proj integral = 1.19e+07
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt0.8_1
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt0.8_1
sideband [0.2, 0.75]: FG=0, BG=9.25e+06
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt0.8_1: TH1D  h_ee_bg_nominal_pt0.8_1
[OK] clone result h_ee_bg_scaled_nominal_pt0.8_1: TH1D  h_ee_bg_scaled_nominal_pt0.8_1
[OK] clone source h_ee_sub_nominal_pt0.8_1: TH1D  h_ee_fg_nominal_pt0.8_1
[OK] clone result h_ee_sub_nominal_pt0.8_1: TH1D  h_ee_sub_nominal_pt0.8_1
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt0.8_1
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt0.8_1
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt0.8_1
EE yield:
  FG signal = 2.39e+04
  BG signal = 0
  SUB       = 2.39e+04 +/- 155
[OK] project source h_eeg_fg_nominal_pt0.8_1: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt0.8_1
  pt range = [0.8, 1.0)
  y bins   = 9 to 10
[OK] projection h_eeg_fg_nominal_pt0.8_1: TH1D  h_eeg_fg_nominal_pt0.8_1
  proj integral = 1.4e+04
[OK] project source h_eeg_bg_nominal_pt0.8_1: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_bg_nominal_pt0.8_1
  pt range = [0.8, 1.0)
  y bins   = 9 to 10
[OK] projection h_eeg_bg_nominal_pt0.8_1: TH1D  h_eeg_bg_nominal_pt0.8_1
  proj integral = 1.53e+05
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt0.8_1
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt0.8_1
sideband [0.2, 0.8]: FG=6.71e+03, BG=1e+05
  scale = 0.0669105
[OK] clone source h_eeg_bg_scaled_nominal_pt0.8_1: TH1D  h_eeg_bg_nominal_pt0.8_1
[OK] clone result h_eeg_bg_scaled_nominal_pt0.8_1: TH1D  h_eeg_bg_scaled_nominal_pt0.8_1
[OK] clone source h_eeg_sub_nominal_pt0.8_1: TH1D  h_eeg_fg_nominal_pt0.8_1
[OK] clone result h_eeg_sub_nominal_pt0.8_1: TH1D  h_eeg_sub_nominal_pt0.8_1
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt0.8_1
EEG after mixed-BG subtraction, before fit:
  raw signal window = 3.56e+03 +/- 72.4
[OK] eeg_mb_nominal_pt0.8_1 input: TH1D  h_eeg_sub_nominal_pt0.8_1
     entries = 973
     integral = 3.78e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_nominal_pt0_8_1_65: TF1  f_eeg_mb_nominal_pt0_8_1_65
Before fit:
  amp0 = 322.26613714957693
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_mb_nominal_pt0_8_1_65: TF1  f_eeg_mb_nominal_pt0_8_1_65
  status = 0
  mean = 0.1317807017099321
  sigma = 0.011340327499109465
  chi2/ndf = 343.69234502854437 / 286
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt0.8_1
     entries = 973
     integral = 3.78e+03
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_mb_nominal_pt0_8_1_65
pol2-subtracted yield:
  raw = 3.56e+03
  pol2 = 99.1
  signal = 3.46e+03 +/- 72.4
FINAL MB ONE BIN
  Yee        = 23935 +/- 154.709
  Yeeg       = 3457.01 +/- 72.4291
  eeg / ee   = 0.144433
  ee / eeg   = 6.92361


################################################################################
Running nominal: pT [1.0, 1.3)
================================================================================
one_bin_result_mb cfg=nominal, pt=[1.0,1.3]
[OK] project source h_ee_fg_nominal_pt1_1.3: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt1_1.3
  pt range = [1.0, 1.3)
  y bins   = 11 to 13
[OK] projection h_ee_fg_nominal_pt1_1.3: TH1D  h_ee_fg_nominal_pt1_1.3
  proj integral = 3.33e+04
[OK] project source h_ee_bg_nominal_pt1_1.3: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt1_1.3
  pt range = [1.0, 1.3)
  y bins   = 11 to 13
[OK] projection h_ee_bg_nominal_pt1_1.3: TH1D  h_ee_bg_nominal_pt1_1.3
  proj integral = 8.04e+06
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt1_1.3
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt1_1.3
sideband [0.2, 0.75]: FG=0, BG=5.89e+06
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt1_1.3: TH1D  h_ee_bg_nominal_pt1_1.3
[OK] clone result h_ee_bg_scaled_nominal_pt1_1.3: TH1D  h_ee_bg_scaled_nominal_pt1_1.3
[OK] clone source h_ee_sub_nominal_pt1_1.3: TH1D  h_ee_fg_nominal_pt1_1.3
[OK] clone result h_ee_sub_nominal_pt1_1.3: TH1D  h_ee_sub_nominal_pt1_1.3
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt1_1.3
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt1_1.3
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt1_1.3
EE yield:
  FG signal = 3.32e+04
  BG signal = 0
  SUB       = 3.32e+04 +/- 182
[OK] project source h_eeg_fg_nominal_pt1_1.3: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt1_1.3
  pt range = [1.0, 1.3)
  y bins   = 11 to 13
[OK] projection h_eeg_fg_nominal_pt1_1.3: TH1D  h_eeg_fg_nominal_pt1_1.3
  proj integral = 1.97e+04
[OK] project source h_eeg_bg_nominal_pt1_1.3: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_bg_nominal_pt1_1.3
  pt range = [1.0, 1.3)
  y bins   = 11 to 13
[OK] projection h_eeg_bg_nominal_pt1_1.3: TH1D  h_eeg_bg_nominal_pt1_1.3
  proj integral = 1.86e+05
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt1_1.3
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt1_1.3
sideband [0.2, 0.8]: FG=1.03e+04, BG=1.4e+05
  scale = 0.0734227
[OK] clone source h_eeg_bg_scaled_nominal_pt1_1.3: TH1D  h_eeg_bg_nominal_pt1_1.3
[OK] clone result h_eeg_bg_scaled_nominal_pt1_1.3: TH1D  h_eeg_bg_scaled_nominal_pt1_1.3
[OK] clone source h_eeg_sub_nominal_pt1_1.3: TH1D  h_eeg_fg_nominal_pt1_1.3
[OK] clone result h_eeg_sub_nominal_pt1_1.3: TH1D  h_eeg_sub_nominal_pt1_1.3
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt1_1.3
EEG after mixed-BG subtraction, before fit:
  raw signal window = 5.33e+03 +/- 86
[OK] eeg_mb_nominal_pt1_1.3 input: TH1D  h_eeg_sub_nominal_pt1_1.3
     entries = 1.78e+03
     integral = 6.06e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_nominal_pt1_1_3_75: TF1  f_eeg_mb_nominal_pt1_1_3_75
Before fit:
  amp0 = 479.0549776586238
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_mb_nominal_pt1_1_3_75: TF1  f_eeg_mb_nominal_pt1_1_3_75
  status = 0
  mean = 0.1315833375028741
  sigma = 0.011010975615946328
  chi2/ndf = 341.58561752439687 / 286
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt1_1.3
     entries = 1.78e+03
     integral = 6.06e+03
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_mb_nominal_pt1_1_3_75
pol2-subtracted yield:
  raw = 5.33e+03
  pol2 = 231
  signal = 5.1e+03 +/- 86
FINAL MB ONE BIN
  Yee        = 33151 +/- 182.074
  Yeeg       = 5098.89 +/- 85.9835
  eeg / ee   = 0.153808
  ee / eeg   = 6.50161


################################################################################
Running nominal: pT [1.3, 1.7)
================================================================================
one_bin_result_mb cfg=nominal, pt=[1.3,1.7]
[OK] project source h_ee_fg_nominal_pt1.3_1.7: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt1.3_1.7
  pt range = [1.3, 1.7)
  y bins   = 14 to 17
[OK] projection h_ee_fg_nominal_pt1.3_1.7: TH1D  h_ee_fg_nominal_pt1.3_1.7
  proj integral = 2.14e+04
[OK] project source h_ee_bg_nominal_pt1.3_1.7: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt1.3_1.7
  pt range = [1.3, 1.7)
  y bins   = 14 to 17
[OK] projection h_ee_bg_nominal_pt1.3_1.7: TH1D  h_ee_bg_nominal_pt1.3_1.7
  proj integral = 3.3e+06
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt1.3_1.7
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt1.3_1.7
sideband [0.2, 0.75]: FG=0, BG=2.39e+06
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt1.3_1.7: TH1D  h_ee_bg_nominal_pt1.3_1.7
[OK] clone result h_ee_bg_scaled_nominal_pt1.3_1.7: TH1D  h_ee_bg_scaled_nominal_pt1.3_1.7
[OK] clone source h_ee_sub_nominal_pt1.3_1.7: TH1D  h_ee_fg_nominal_pt1.3_1.7
[OK] clone result h_ee_sub_nominal_pt1.3_1.7: TH1D  h_ee_sub_nominal_pt1.3_1.7
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt1.3_1.7
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt1.3_1.7
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt1.3_1.7
EE yield:
  FG signal = 2.12e+04
  BG signal = 0
  SUB       = 2.12e+04 +/- 146
[OK] project source h_eeg_fg_nominal_pt1.3_1.7: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt1.3_1.7
  pt range = [1.3, 1.7)
  y bins   = 14 to 17
[OK] projection h_eeg_fg_nominal_pt1.3_1.7: TH1D  h_eeg_fg_nominal_pt1.3_1.7
  proj integral = 1.37e+04
[OK] project source h_eeg_bg_nominal_pt1.3_1.7: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_bg_nominal_pt1.3_1.7
  pt range = [1.3, 1.7)
  y bins   = 14 to 17
[OK] projection h_eeg_bg_nominal_pt1.3_1.7: TH1D  h_eeg_bg_nominal_pt1.3_1.7
  proj integral = 1.18e+05
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt1.3_1.7
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt1.3_1.7
sideband [0.2, 0.8]: FG=7.08e+03, BG=9.22e+04
  scale = 0.0768222
[OK] clone source h_eeg_bg_scaled_nominal_pt1.3_1.7: TH1D  h_eeg_bg_nominal_pt1.3_1.7
[OK] clone result h_eeg_bg_scaled_nominal_pt1.3_1.7: TH1D  h_eeg_bg_scaled_nominal_pt1.3_1.7
[OK] clone source h_eeg_sub_nominal_pt1.3_1.7: TH1D  h_eeg_fg_nominal_pt1.3_1.7
[OK] clone result h_eeg_sub_nominal_pt1.3_1.7: TH1D  h_eeg_sub_nominal_pt1.3_1.7
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt1.3_1.7
EEG after mixed-BG subtraction, before fit:
  raw signal window = 3.96e+03 +/- 71.4
[OK] eeg_mb_nominal_pt1.3_1.7 input: TH1D  h_eeg_sub_nominal_pt1.3_1.7
     entries = 1.51e+03
     integral = 4.66e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_nominal_pt1_3_1_7_85: TF1  f_eeg_mb_nominal_pt1_3_1_7_85
Before fit:
  amp0 = 356.1109340099321
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_mb_nominal_pt1_3_1_7_85: TF1  f_eeg_mb_nominal_pt1_3_1_7_85
  status = 0
  mean = 0.13159889345306258
  sigma = 0.010890670087955464
  chi2/ndf = 384.7676099237491 / 286
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt1.3_1.7
     entries = 1.51e+03
     integral = 4.66e+03
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_mb_nominal_pt1_3_1_7_85
pol2-subtracted yield:
  raw = 3.96e+03
  pol2 = 144
  signal = 3.81e+03 +/- 71.4
FINAL MB ONE BIN
  Yee        = 21216 +/- 145.657
  Yeeg       = 3812.28 +/- 71.4261
  eeg / ee   = 0.179689
  ee / eeg   = 5.56517


################################################################################
Running nominal: pT [1.7, 2.0)
================================================================================
one_bin_result_mb cfg=nominal, pt=[1.7,2.0]
[OK] project source h_ee_fg_nominal_pt1.7_2: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt1.7_2
  pt range = [1.7, 2.0)
  y bins   = 18 to 20
[OK] projection h_ee_fg_nominal_pt1.7_2: TH1D  h_ee_fg_nominal_pt1.7_2
  proj integral = 7.91e+03
[OK] project source h_ee_bg_nominal_pt1.7_2: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt1.7_2
  pt range = [1.7, 2.0)
  y bins   = 18 to 20
[OK] projection h_ee_bg_nominal_pt1.7_2: TH1D  h_ee_bg_nominal_pt1.7_2
  proj integral = 7.46e+05
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt1.7_2
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt1.7_2
sideband [0.2, 0.75]: FG=0, BG=5.35e+05
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt1.7_2: TH1D  h_ee_bg_nominal_pt1.7_2
[OK] clone result h_ee_bg_scaled_nominal_pt1.7_2: TH1D  h_ee_bg_scaled_nominal_pt1.7_2
[OK] clone source h_ee_sub_nominal_pt1.7_2: TH1D  h_ee_fg_nominal_pt1.7_2
[OK] clone result h_ee_sub_nominal_pt1.7_2: TH1D  h_ee_sub_nominal_pt1.7_2
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt1.7_2
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt1.7_2
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt1.7_2
EE yield:
  FG signal = 7.82e+03
  BG signal = 0
  SUB       = 7.82e+03 +/- 88.4
[OK] project source h_eeg_fg_nominal_pt1.7_2: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt1.7_2
  pt range = [1.7, 2.0)
  y bins   = 18 to 20
[OK] projection h_eeg_fg_nominal_pt1.7_2: TH1D  h_eeg_fg_nominal_pt1.7_2
  proj integral = 5.31e+03
[OK] project source h_eeg_bg_nominal_pt1.7_2: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_bg_nominal_pt1.7_2
  pt range = [1.7, 2.0)
  y bins   = 18 to 20
[OK] projection h_eeg_bg_nominal_pt1.7_2: TH1D  h_eeg_bg_nominal_pt1.7_2
  proj integral = 4.09e+04
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt1.7_2
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt1.7_2
sideband [0.2, 0.8]: FG=2.78e+03, BG=3.16e+04
  scale = 0.0878982
[OK] clone source h_eeg_bg_scaled_nominal_pt1.7_2: TH1D  h_eeg_bg_nominal_pt1.7_2
[OK] clone result h_eeg_bg_scaled_nominal_pt1.7_2: TH1D  h_eeg_bg_scaled_nominal_pt1.7_2
[OK] clone source h_eeg_sub_nominal_pt1.7_2: TH1D  h_eeg_fg_nominal_pt1.7_2
[OK] clone result h_eeg_sub_nominal_pt1.7_2: TH1D  h_eeg_sub_nominal_pt1.7_2
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt1.7_2
EEG after mixed-BG subtraction, before fit:
  raw signal window = 1.52e+03 +/- 43.7
[OK] eeg_mb_nominal_pt1.7_2 input: TH1D  h_eeg_sub_nominal_pt1.7_2
     entries = 524
     integral = 1.72e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_nominal_pt1_7_2_95: TF1  f_eeg_mb_nominal_pt1_7_2_95
Before fit:
  amp0 = 145.68279399658033
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_mb_nominal_pt1_7_2_95: TF1  f_eeg_mb_nominal_pt1_7_2_95
  status = 0
  mean = 0.13139858054207643
  sigma = 0.011256108773577538
  chi2/ndf = 309.84932119460365 / 286
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt1.7_2
     entries = 524
     integral = 1.72e+03
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_mb_nominal_pt1_7_2_95
pol2-subtracted yield:
  raw = 1.52e+03
  pol2 = 22
  signal = 1.49e+03 +/- 43.7
FINAL MB ONE BIN
  Yee        = 7821 +/- 88.4364
  Yeeg       = 1493.26 +/- 43.6897
  eeg / ee   = 0.190929
  ee / eeg   = 5.23755


################################################################################
Running nominal: pT [2.0, 2.5)
================================================================================
one_bin_result_mb cfg=nominal, pt=[2.0,2.5]
[OK] project source h_ee_fg_nominal_pt2_2.5: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt2_2.5
  pt range = [2.0, 2.5)
  y bins   = 21 to 25
[OK] projection h_ee_fg_nominal_pt2_2.5: TH1D  h_ee_fg_nominal_pt2_2.5
  proj integral = 5.91e+03
[OK] project source h_ee_bg_nominal_pt2_2.5: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt2_2.5
  pt range = [2.0, 2.5)
  y bins   = 21 to 25
[OK] projection h_ee_bg_nominal_pt2_2.5: TH1D  h_ee_bg_nominal_pt2_2.5
  proj integral = 3.82e+05
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt2_2.5
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt2_2.5
sideband [0.2, 0.75]: FG=0, BG=2.67e+05
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt2_2.5: TH1D  h_ee_bg_nominal_pt2_2.5
[OK] clone result h_ee_bg_scaled_nominal_pt2_2.5: TH1D  h_ee_bg_scaled_nominal_pt2_2.5
[OK] clone source h_ee_sub_nominal_pt2_2.5: TH1D  h_ee_fg_nominal_pt2_2.5
[OK] clone result h_ee_sub_nominal_pt2_2.5: TH1D  h_ee_sub_nominal_pt2_2.5
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt2_2.5
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt2_2.5
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt2_2.5
EE yield:
  FG signal = 5.82e+03
  BG signal = 0
  SUB       = 5.82e+03 +/- 76.3
[OK] project source h_eeg_fg_nominal_pt2_2.5: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt2_2.5
  pt range = [2.0, 2.5)
  y bins   = 21 to 25
[OK] projection h_eeg_fg_nominal_pt2_2.5: TH1D  h_eeg_fg_nominal_pt2_2.5
  proj integral = 4.33e+03
[OK] project source h_eeg_bg_nominal_pt2_2.5: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_bg_nominal_pt2_2.5
  pt range = [2.0, 2.5)
  y bins   = 21 to 25
[OK] projection h_eeg_bg_nominal_pt2_2.5: TH1D  h_eeg_bg_nominal_pt2_2.5
  proj integral = 2.87e+04
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt2_2.5
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt2_2.5
sideband [0.2, 0.8]: FG=2.19e+03, BG=2.19e+04
  scale = 0.0999954
[OK] clone source h_eeg_bg_scaled_nominal_pt2_2.5: TH1D  h_eeg_bg_nominal_pt2_2.5
[OK] clone result h_eeg_bg_scaled_nominal_pt2_2.5: TH1D  h_eeg_bg_scaled_nominal_pt2_2.5
[OK] clone source h_eeg_sub_nominal_pt2_2.5: TH1D  h_eeg_fg_nominal_pt2_2.5
[OK] clone result h_eeg_sub_nominal_pt2_2.5: TH1D  h_eeg_sub_nominal_pt2_2.5
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt2_2.5
EEG after mixed-BG subtraction, before fit:
  raw signal window = 1.26e+03 +/- 39.1
[OK] eeg_mb_nominal_pt2_2.5 input: TH1D  h_eeg_sub_nominal_pt2_2.5
     entries = 463
     integral = 1.46e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_nominal_pt2_2_5_105: TF1  f_eeg_mb_nominal_pt2_2_5_105
Before fit:
  amp0 = 113.90032389033347
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_mb_nominal_pt2_2_5_105: TF1  f_eeg_mb_nominal_pt2_2_5_105
  status = 0
  mean = 0.1315912681085538
  sigma = 0.011678171019325926
  chi2/ndf = 324.680105932587 / 286
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt2_2.5
     entries = 463
     integral = 1.46e+03
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_mb_nominal_pt2_2_5_105
pol2-subtracted yield:
  raw = 1.26e+03
  pol2 = -16.3
  signal = 1.28e+03 +/- 39.1
FINAL MB ONE BIN
  Yee        = 5824 +/- 76.3151
  Yeeg       = 1277.64 +/- 39.1493
  eeg / ee   = 0.219375
  ee / eeg   = 4.5584


################################################################################
Running nominal: pT [2.5, 3.0)
================================================================================
one_bin_result_mb cfg=nominal, pt=[2.5,3.0]
[OK] project source h_ee_fg_nominal_pt2.5_3: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt2.5_3
  pt range = [2.5, 3.0)
  y bins   = 26 to 30
[OK] projection h_ee_fg_nominal_pt2.5_3: TH1D  h_ee_fg_nominal_pt2.5_3
  proj integral = 2.07e+03
[OK] project source h_ee_bg_nominal_pt2.5_3: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt2.5_3
  pt range = [2.5, 3.0)
  y bins   = 26 to 30
[OK] projection h_ee_bg_nominal_pt2.5_3: TH1D  h_ee_bg_nominal_pt2.5_3
  proj integral = 9.15e+04
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt2.5_3
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt2.5_3
sideband [0.2, 0.75]: FG=0, BG=6.11e+04
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt2.5_3: TH1D  h_ee_bg_nominal_pt2.5_3
[OK] clone result h_ee_bg_scaled_nominal_pt2.5_3: TH1D  h_ee_bg_scaled_nominal_pt2.5_3
[OK] clone source h_ee_sub_nominal_pt2.5_3: TH1D  h_ee_fg_nominal_pt2.5_3
[OK] clone result h_ee_sub_nominal_pt2.5_3: TH1D  h_ee_sub_nominal_pt2.5_3
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt2.5_3
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt2.5_3
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt2.5_3
EE yield:
  FG signal = 2.02e+03
  BG signal = 0
  SUB       = 2.02e+03 +/- 45
[OK] project source h_eeg_fg_nominal_pt2.5_3: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt2.5_3
  pt range = [2.5, 3.0)

,config,pt_min,pt_max,pt_center,y_ee,e_ee,y_eeg,e_eeg,raw_eeg,pol2_eeg,eeg_over_ee,ee_over_eeg,fit_mean,fit_sigma,fit_chi2,fit_ndf
0,nominal,0.8,1.0,0.90,23935.000000,154.709405,3457.011319,72.429137,3556.094715,99.083396,0.144433,6.923611,0.131781,0.011340,3.436923e+02,286
1,nominal,1.0,1.3,1.15,33151.000000,182.074161,5098.894552,85.983490,5329.426631,230.532079,0.153808,6.501605,0.131583,0.011011,3.415856e+02,286
2,nominal,1.3,1.7,1.50,21216.000000,145.657132,3812.284783,71.426078,3956.704563,144.419780,0.179689,5.565167,0.131599,0.010891,3.847676e+02,286
3,nominal,1.7,2.0,1.85,7821.000000,88.436418,1493.256109,43.689734,1515.299031,22.042923,0.190929,5.237548,0.131399,0.011256,3.098493e+02,286
4,nominal,2.0,2.5,2.25,5824.000000,76.315136,1277.640129,39.149301,1261.311254,-16.328875,0.219375,4.558404,0.131591,0.011678,3.246801e+02,286
5,nominal,2.5,3.0,2.75,2023.000000,44.977772,513.014975,24.001229,480.073936,-32.941039,0.253591,3.943355,0.132709,0.011513,4.888953e+02,286
6,nominal,3.0,4.0,3.50,1056.949031,32.511536,298.941920,17.958138,276.264194,-22.677726,0.282835,3.535633,0.132777,0.012878,3.744629e+02,285
7,nominal,4.0,5.0,4.50,197.000000,14.035669,64.675162,8.082634,56.618395,-8.056767,0.328300,3.045992,0.132967,0.006000,2.084822e+02,249
8,nominal,5.0,7.0,6.00,80.944853,9.000006,24.451804,4.737475,18.805556,-5.646249,0.302080,3.310384,0.134632,0.007467,9.660028e+01,191
9,nominal,7.0,10.0,8.50,14.000000,3.741657,-35.995944,2.000000,4.000000,39.995944,-2.571139,-0.388933,0.139906,0.026610,2.885960e-07,3

In [43]:
df_nominal_mb.to_csv(f"{fit_out_dir}/yields_nominal_mb.csv", index=False)

In [44]:
def add_ratio_columns(df):
    df = df.copy()

    # eeg / ee
    df["eeg_over_ee"] = float("nan")
    df["eeg_over_ee_err"] = float("nan")

    # ee / eeg
    df["ee_over_eeg"] = float("nan")
    df["ee_over_eeg_err"] = float("nan")

    for i, row in df.iterrows():
        y_ee = row["y_ee"]
        e_ee = row["e_ee"]
        y_eeg = row["y_eeg"]
        e_eeg = row["e_eeg"]

        if y_ee > 0 and y_eeg > 0:
            r1 = y_eeg / y_ee
            r1_err = r1 * math.sqrt((e_eeg / y_eeg)**2 + (e_ee / y_ee)**2)

            r2 = y_ee / y_eeg
            r2_err = r2 * math.sqrt((e_ee / y_ee)**2 + (e_eeg / y_eeg)**2)

            df.loc[i, "eeg_over_ee"] = r1
            df.loc[i, "eeg_over_ee_err"] = r1_err
            df.loc[i, "ee_over_eeg"] = r2
            df.loc[i, "ee_over_eeg_err"] = r2_err

    return df

In [45]:
df_nominal_mb = add_ratio_columns(df_nominal_mb)
df_nominal_mb

,config,pt_min,pt_max,pt_center,y_ee,e_ee,y_eeg,e_eeg,raw_eeg,pol2_eeg,eeg_over_ee,ee_over_eeg,fit_mean,fit_sigma,fit_chi2,fit_ndf,eeg_over_ee_err,ee_over_eeg_err
0,nominal,0.8,1.0,0.90,23935.000000,154.709405,3457.011319,72.429137,3556.094715,99.083396,0.144433,6.923611,0.131781,0.011340,3.436923e+02,286,0.003167,0.151806
1,nominal,1.0,1.3,1.15,33151.000000,182.074161,5098.894552,85.983490,5329.426631,230.532079,0.153808,6.501605,0.131583,0.011011,3.415856e+02,286,0.002728,0.115306
2,nominal,1.3,1.7,1.50,21216.000000,145.657132,3812.284783,71.426078,3956.704563,144.419780,0.179689,5.565167,0.131599,0.010891,3.847676e+02,286,0.003586,0.111047
3,nominal,1.7,2.0,1.85,7821.000000,88.436418,1493.256109,43.689734,1515.299031,22.042923,0.190929,5.237548,0.131399,0.011256,3.098493e+02,286,0.005989,0.164287
4,nominal,2.0,2.5,2.25,5824.000000,76.315136,1277.640129,39.149301,1261.311254,-16.328875,0.219375,4.558404,0.131591,0.011678,3.246801e+02,286,0.007311,0.151914
5,nominal,2.5,3.0,2.75,2023.000000,44.977772,513.014975,24.001229,480.073936,-32.941039,0.253591,3.943355,0.132709,0.011513,4.888953e+02,286,0.013136,0.204261
6,nominal,3.0,4.0,3.50,1056.949031,32.511536,298.941920,17.958138,276.264194,-22.677726,0.282835,3.535633,0.132777,0.012878,3.744629e+02,285,0.019088,0.238619
7,nominal,4.0,5.0,4.50,197.000000,14.035669,64.675162,8.082634,56.618395,-8.056767,0.328300,3.045992,0.132967,0.006000,2.084822e+02,249,0.047228,0.438182
8,nominal,5.0,7.0,6.00,80.944853,9.000006,24.451804,4.737475,18.805556,-5.646249,0.302080,3.310384,0.134632,0.007467,9.660028e+01,191,0.067480,0.739488
9,nominal,7.0,10.0,8.50,14.000000,3.741657,-35.995944,2.000000,4.000000,39.995944,NaN,NaN,0.139906,0.026610,2.885960e-07,3,NaN,NaN

In [46]:
def make_ratio_graph_from_df(df, ycol, eycol, name, title):
    g = root.TGraphErrors(len(df))
    g.SetName(name)
    g.SetTitle(title)

    for i, row in enumerate(df.itertuples()):
        x = row.pt_center
        ex = 0.5 * (row.pt_max - row.pt_min)
        y = getattr(row, ycol)
        ey = getattr(row, eycol) if eycol in df.columns else 0.0

        g.SetPoint(i, x, y)
        g.SetPointError(i, ex, ey)

    g.SetMarkerStyle(20)
    g.SetMarkerColor(root.kBlue)
    g.SetLineColor(root.kBlue)
    keep(g)
    return g

In [47]:
g_ee = make_ratio_graph_from_df(
    df_nominal_mb,
    "y_ee",
    "e_ee",
    "g_ee_nominal",
    "nominal; p_{T} (GeV/c); ee"
)

g_eeg = make_ratio_graph_from_df(
    df_nominal_mb,
    "y_eeg",
    "e_eeg",
    "g_eeg_nominal",
    "nominal; p_{T} (GeV/c); ee / eeg"
)

c_yield = root.TCanvas("c_yield_nominal", "c_yield_nominal", 1200, 500)
c_yield.Divide(2, 1)

c_yield.cd(1)
g_ee.Draw("AP")

c_yield.cd(2)
g_eeg.Draw("AP")

c_yield.Draw()

c_ratio = root.TCanvas("c_ratio_nominal", "c_ratio_nominal", 800, 600)

g_ee_over_eeg = make_ratio_graph_from_df(
    df_nominal_mb,
    "ee_over_eeg",
    "ee_over_eeg_err",
    "g_ee_over_eeg_nominal",
    "nominal; p_{T} (GeV/c); ee / eeg"
)

c_ratio = root.TCanvas("c_ratio_nominal", "c_ratio_nominal", 600, 500)
g_ee_over_eeg.GetYaxis().SetRangeUser(0, 15)
g_ee_over_eeg.Draw("AP")

c_ratio.Draw()

In [48]:
configs_to_run = [
    "nominal",
    "conv_solution",
    "conv_tight",
    "ecore04",
    "ecore05",
    "pte03",
    "pte04",
    "eid0",
    "eid1",
    "eid3",
    "chi2_4",
    "chi2_5",
    "escale099",
    "escale101",
]

In [49]:
all_dfs = []
all_results = {}

for cfg in configs_to_run:
    print("\n\n")
    print("="*100)
    print(f"BUILDING MB HISTOGRAMS FOR {cfg}")
    print("="*100)

    mb_cfg = build_mb_set(hists, cfg)

    print("\n")
    print("="*100)
    print(f"RUNNING PT BINS FOR {cfg}")
    print("="*100)

    df_cfg, results_cfg = run_pt_bins_for_config(
        cfg,
        mb_cfg,
        save_canvases=False
    )

    all_dfs.append(df_cfg)
    all_results[cfg] = results_cfg

df_all = pd.concat(all_dfs, ignore_index=True)
df_all.to_csv(f"{fit_out_dir}/yields_all_configs_mb.csv", index=False)

df_all

====================================================================================================
BUILDING MB HISTOGRAMS FOR nominal
====================================================================================================
[OK] clone source mb_file0_fg2d_eemass_reco_nominal: TH2F  fg2d_eemass_reco_nominal_icent0_file0
[OK] clone result mb_file0_fg2d_eemass_reco_nominal: TH2F  mb_file0_fg2d_eemass_reco_nominal
[OK] built mb_file0_fg2d_eemass_reco_nominal: integral=103674
[OK] clone source mb_all_fg2d_eemass_reco_nominal: TH2F  mb_file0_fg2d_eemass_reco_nominal
[OK] clone result mb_all_fg2d_eemass_reco_nominal: TH2F  mb_all_fg2d_eemass_reco_nominal
[OK] built mb_all_fg2d_eemass_reco_nominal: integral=103674
[OK] clone source mb_file0_bg2d_eemass_reco_nominal: TH2F  bg2d_eemass_reco_nominal_icent0_file0
[OK] clone result mb_file0_bg2d_eemass_reco_nominal: TH2F  mb_file0_bg2d_eemass_reco_nominal
[OK] built mb_file0_bg2d_eemass_reco_nominal: integral=1.01495e+08
[OK] clone source mb_all_bg2d_eemass_reco_nominal: TH2F  mb_file0_bg2d_eemass_reco_nominal
[OK] clone result mb_all_bg2d_eemass_reco_nominal: TH2F  mb_all_bg2d_eemass_reco_nominal
[OK] built mb_all_bg2d_eemass_reco_nominal: integral=1.01495e+08
[OK] clone source mb_file0_fg2d_eegmass_reco_nominal: TH2F  fg2d_eegmass_reco_nominal_icent0_file0
[OK] clone result mb_file0_fg2d_eegmass_reco_nominal: TH2F  mb_file0_fg2d_eegmass_reco_nominal
[OK] built mb_file0_fg2d_eegmass_reco_nominal: integral=64670
[OK] clone source mb_all_fg2d_eegmass_reco_nominal: TH2F  mb_file0_fg2d_eegmass_reco_nominal
[OK] clone result mb_all_fg2d_eegmass_reco_nominal: TH2F  mb_all_fg2d_eegmass_reco_nominal
[OK] built mb_all_fg2d_eegmass_reco_nominal: integral=64670
[OK] clone source mb_file0_bg2d_eegmass_reco_nominal: TH2F  bg2d_eegmass_reco_nominal_icent0_file0
[OK] clone result mb_file0_bg2d_eegmass_reco_nominal: TH2F  mb_file0_bg2d_eegmass_reco_nominal
[OK] built mb_file0_bg2d_eegmass_reco_nominal: integral=599277
[OK] clone source mb_all_bg2d_eegmass_reco_nominal: TH2F  mb_file0_bg2d_eegmass_reco_nominal
[OK] clone result mb_all_bg2d_eegmass_reco_nominal: TH2F  mb_all_bg2d_eegmass_reco_nominal
[OK] built mb_all_bg2d_eegmass_reco_nominal: integral=599277


====================================================================================================
RUNNING PT BINS FOR nominal
====================================================================================================


################################################################################
Running nominal: pT [0.8, 1.0)
================================================================================
one_bin_result_mb cfg=nominal, pt=[0.8,1.0]
[OK] project source h_ee_fg_nominal_pt0.8_1: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt0.8_1
  pt range = [0.8, 1.0)
  y bins   = 9 to 10
[OK] projection h_ee_fg_nominal_pt0.8_1: TH1D  h_ee_fg_nominal_pt0.8_1
  proj integral = 2.4e+04
[OK] project source h_ee_bg_nominal_pt0.8_1: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt0.8_1
  pt range = [0.8, 1.0)
  y bins   = 9 to 10
[OK] projection h_ee_bg_nominal_pt0.8_1: TH1D  h_ee_bg_nominal_pt0.8_1
  proj integral = 1.19e+07
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt0.8_1
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt0.8_1
sideband [0.2, 0.75]: FG=0, BG=9.25e+06
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt0.8_1: TH1D  h_ee_bg_nominal_pt0.8_1
[OK] clone result h_ee_bg_scaled_nominal_pt0.8_1: TH1D  h_ee_bg_scaled_nominal_pt0.8_1
[OK] clone source h_ee_sub_nominal_pt0.8_1: TH1D  h_ee_fg_nominal_pt0.8_1
[OK] clone result h_ee_sub_nominal_pt0.8_1: TH1D  h_ee_sub_nominal_pt0.8_1
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt0.8_1
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt0.8_1
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt0.8_1
EE yield:
  FG signal = 2.39e+04
  BG signal = 0
  SUB       = 2.39e+04 +/- 155
[OK] project source h_eeg_fg_nominal_pt0.8_1: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt0.8_1
  pt range = [0.8, 1.0)
  y bins   = 9 to 10
[OK] projection h_eeg_fg_nominal_pt0.8_1: TH1D  h_eeg_fg_nominal_pt0.8_1
  proj integral = 1.4e+04
[OK] project source h_eeg_bg_nominal_pt0.8_1: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_bg_nominal_pt0.8_1
  pt range = [0.8, 1.0)
  y bins   = 9 to 10
[OK] projection h_eeg_bg_nominal_pt0.8_1: TH1D  h_eeg_bg_nominal_pt0.8_1
  proj integral = 1.53e+05
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt0.8_1
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt0.8_1
sideband [0.2, 0.8]: FG=6.71e+03, BG=1e+05
  scale = 0.0669105
[OK] clone source h_eeg_bg_scaled_nominal_pt0.8_1: TH1D  h_eeg_bg_nominal_pt0.8_1
[OK] clone result h_eeg_bg_scaled_nominal_pt0.8_1: TH1D  h_eeg_bg_scaled_nominal_pt0.8_1
[OK] clone source h_eeg_sub_nominal_pt0.8_1: TH1D  h_eeg_fg_nominal_pt0.8_1
[OK] clone result h_eeg_sub_nominal_pt0.8_1: TH1D  h_eeg_sub_nominal_pt0.8_1
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt0.8_1
EEG after mixed-BG subtraction, before fit:
  raw signal window = 3.56e+03 +/- 72.4
[OK] eeg_mb_nominal_pt0.8_1 input: TH1D  h_eeg_sub_nominal_pt0.8_1
     entries = 973
     integral = 3.78e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_nominal_pt0_8_1_176: TF1  f_eeg_mb_nominal_pt0_8_1_176
Before fit:
  amp0 = 322.26613714957693
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_mb_nominal_pt0_8_1_176: TF1  f_eeg_mb_nominal_pt0_8_1_176
  status = 0
  mean = 0.1317807017099321
  sigma = 0.011340327499109465
  chi2/ndf = 343.69234502854437 / 286
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt0.8_1
     entries = 973
     integral = 3.78e+03
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_mb_nominal_pt0_8_1_176
pol2-subtracted yield:
  raw = 3.56e+03
  pol2 = 99.1
  signal = 3.46e+03 +/- 72.4
FINAL MB ONE BIN
  Yee        = 23935 +/- 154.709
  Yeeg       = 3457.01 +/- 72.4291
  eeg / ee   = 0.144433
  ee / eeg   = 6.92361


################################################################################
Running nominal: pT [1.0, 1.3)
================================================================================
one_bin_result_mb cfg=nominal, pt=[1.0,1.3]
[OK] project source h_ee_fg_nominal_pt1_1.3: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt1_1.3
  pt range = [1.0, 1.3)
  y bins   = 11 to 13
[OK] projection h_ee_fg_nominal_pt1_1.3: TH1D  h_ee_fg_nominal_pt1_1.3
  proj integral = 3.33e+04
[OK] project source h_ee_bg_nominal_pt1_1.3: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt1_1.3
  pt range = [1.0, 1.3)
  y bins   = 11 to 13
[OK] projection h_ee_bg_nominal_pt1_1.3: TH1D  h_ee_bg_nominal_pt1_1.3
  proj integral = 8.04e+06
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt1_1.3
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt1_1.3
sideband [0.2, 0.75]: FG=0, BG=5.89e+06
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt1_1.3: TH1D  h_ee_bg_nominal_pt1_1.3
[OK] clone result h_ee_bg_scaled_nominal_pt1_1.3: TH1D  h_ee_bg_scaled_nominal_pt1_1.3
[OK] clone source h_ee_sub_nominal_pt1_1.3: TH1D  h_ee_fg_nominal_pt1_1.3
[OK] clone result h_ee_sub_nominal_pt1_1.3: TH1D  h_ee_sub_nominal_pt1_1.3
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt1_1.3
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt1_1.3
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt1_1.3
EE yield:
  FG signal = 3.32e+04
  BG signal = 0
  SUB       = 3.32e+04 +/- 182
[OK] project source h_eeg_fg_nominal_pt1_1.3: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt1_1.3
  pt range = [1.0, 1.3)
  y bins   = 11 to 13
[OK] projection h_eeg_fg_nominal_pt1_1.3: TH1D  h_eeg_fg_nominal_pt1_1.3
  proj integral = 1.97e+04
[OK] project source h_eeg_bg_nominal_pt1_1.3: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_bg_nominal_pt1_1.3
  pt range = [1.0, 1.3)
  y bins   = 11 to 13
[OK] projection h_eeg_bg_nominal_pt1_1.3: TH1D  h_eeg_bg_nominal_pt1_1.3
  proj integral = 1.86e+05
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt1_1.3
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt1_1.3
sideband [0.2, 0.8]: FG=1.03e+04, BG=1.4e+05
  scale = 0.0734227
[OK] clone source h_eeg_bg_scaled_nominal_pt1_1.3: TH1D  h_eeg_bg_nominal_pt1_1.3
[OK] clone result h_eeg_bg_scaled_nominal_pt1_1.3: TH1D  h_eeg_bg_scaled_nominal_pt1_1.3
[OK] clone source h_eeg_sub_nominal_pt1_1.3: TH1D  h_eeg_fg_nominal_pt1_1.3
[OK] clone result h_eeg_sub_nominal_pt1_1.3: TH1D  h_eeg_sub_nominal_pt1_1.3
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt1_1.3
EEG after mixed-BG subtraction, before fit:
  raw signal window = 5.33e+03 +/- 86
[OK] eeg_mb_nominal_pt1_1.3 input: TH1D  h_eeg_sub_nominal_pt1_1.3
     entries = 1.78e+03
     integral = 6.06e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_nominal_pt1_1_3_186: TF1  f_eeg_mb_nominal_pt1_1_3_186
Before fit:
  amp0 = 479.0549776586238
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_mb_nominal_pt1_1_3_186: TF1  f_eeg_mb_nominal_pt1_1_3_186
  status = 0
  mean = 0.1315833375028741
  sigma = 0.011010975615946328
  chi2/ndf = 341.58561752439687 / 286
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt1_1.3
     entries = 1.78e+03
     integral = 6.06e+03
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_mb_nominal_pt1_1_3_186
pol2-subtracted yield:
  raw = 5.33e+03
  pol2 = 231
  signal = 5.1e+03 +/- 86
FINAL MB ONE BIN
  Yee        = 33151 +/- 182.074
  Yeeg       = 5098.89 +/- 85.9835
  eeg / ee   = 0.153808
  ee / eeg   = 6.50161


################################################################################
Running nominal: pT [1.3, 1.7)
================================================================================
one_bin_result_mb cfg=nominal, pt=[1.3,1.7]
[OK] project source h_ee_fg_nominal_pt1.3_1.7: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt1.3_1.7
  pt range = [1.3, 1.7)
  y bins   = 14 to 17
[OK] projection h_ee_fg_nominal_pt1.3_1.7: TH1D  h_ee_fg_nominal_pt1.3_1.7
  proj integral = 2.14e+04
[OK] project source h_ee_bg_nominal_pt1.3_1.7: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt1.3_1.7
  pt range = [1.3, 1.7)
  y bins   = 14 to 17
[OK] projection h_ee_bg_nominal_pt1.3_1.7: TH1D  h_ee_bg_nominal_pt1.3_1.7
  proj integral = 3.3e+06
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt1.3_1.7
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt1.3_1.7
sideband [0.2, 0.75]: FG=0, BG=2.39e+06
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt1.3_1.7: TH1D  h_ee_bg_nominal_pt1.3_1.7
[OK] clone result h_ee_bg_scaled_nominal_pt1.3_1.7: TH1D  h_ee_bg_scaled_nominal_pt1.3_1.7
[OK] clone source h_ee_sub_nominal_pt1.3_1.7: TH1D  h_ee_fg_nominal_pt1.3_1.7
[OK] clone result h_ee_sub_nominal_pt1.3_1.7: TH1D  h_ee_sub_nominal_pt1.3_1.7
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt1.3_1.7
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt1.3_1.7
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt1.3_1.7
EE yield:
  FG signal = 2.12e+04
  BG signal = 0
  SUB       = 2.12e+04 +/- 146
[OK] project source h_eeg_fg_nominal_pt1.3_1.7: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt1.3_1.7
  pt range = [1.3, 1.7)
  y bins   = 14 to 17
[OK] projection h_eeg_fg_nominal_pt1.3_1.7: TH1D  h_eeg_fg_nominal_pt1.3_1.7
  proj integral = 1.37e+04
[OK] project source h_eeg_bg_nominal_pt1.3_1.7: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_bg_nominal_pt1.3_1.7
  pt range = [1.3, 1.7)
  y bins   = 14 to 17
[OK] projection h_eeg_bg_nominal_pt1.3_1.7: TH1D  h_eeg_bg_nominal_pt1.3_1.7
  proj integral = 1.18e+05
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt1.3_1.7
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt1.3_1.7
sideband [0.2, 0.8]: FG=7.08e+03, BG=9.22e+04
  scale = 0.0768222
[OK] clone source h_eeg_bg_scaled_nominal_pt1.3_1.7: TH1D  h_eeg_bg_nominal_pt1.3_1.7
[OK] clone result h_eeg_bg_scaled_nominal_pt1.3_1.7: TH1D  h_eeg_bg_scaled_nominal_pt1.3_1.7
[OK] clone source h_eeg_sub_nominal_pt1.3_1.7: TH1D  h_eeg_fg_nominal_pt1.3_1.7
[OK] clone result h_eeg_sub_nominal_pt1.3_1.7: TH1D  h_eeg_sub_nominal_pt1.3_1.7
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt1.3_1.7
EEG after mixed-BG subtraction, before fit:
  raw signal window = 3.96e+03 +/- 71.4
[OK] eeg_mb_nominal_pt1.3_1.7 input: TH1D  h_eeg_sub_nominal_pt1.3_1.7
     entries = 1.51e+03
     integral = 4.66e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_nominal_pt1_3_1_7_196: TF1  f_eeg_mb_nominal_pt1_3_1_7_196
Before fit:
  amp0 = 356.1109340099321
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_mb_nominal_pt1_3_1_7_196: TF1  f_eeg_mb_nominal_pt1_3_1_7_196
  status = 0
  mean = 0.13159889345306258
  sigma = 0.010890670087955464
  chi2/ndf = 384.7676099237491 / 286
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt1.3_1.7
     entries = 1.51e+03
     integral = 4.66e+03
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_mb_nominal_pt1_3_1_7_196
pol2-subtracted yield:
  raw = 3.96e+03
  pol2 = 144
  signal = 3.81e+03 +/- 71.4
FINAL MB ONE BIN
  Yee        = 21216 +/- 145.657
  Yeeg       = 3812.28 +/- 71.4261
  eeg / ee   = 0.179689
  ee / eeg   = 5.56517


################################################################################
Running nominal: pT [1.7, 2.0)
================================================================================
one_bin_result_mb cfg=nominal, pt=[1.7,2.0]
[OK] project source h_ee_fg_nominal_pt1.7_2: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt1.7_2
  pt range = [1.7, 2.0)
  y bins   = 18 to 20
[OK] projection h_ee_fg_nominal_pt1.7_2: TH1D  h_ee_fg_nominal_pt1.7_2
  proj integral = 7.91e+03
[OK] project source h_ee_bg_nominal_pt1.7_2: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt1.7_2
  pt range = [1.7, 2.0)
  y bins   = 18 to 20
[OK] projection h_ee_bg_nominal_pt1.7_2: TH1D  h_ee_bg_nominal_pt1.7_2
  proj integral = 7.46e+05
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt1.7_2
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt1.7_2
sideband [0.2, 0.75]: FG=0, BG=5.35e+05
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt1.7_2: TH1D  h_ee_bg_nominal_pt1.7_2
[OK] clone result h_ee_bg_scaled_nominal_pt1.7_2: TH1D  h_ee_bg_scaled_nominal_pt1.7_2
[OK] clone source h_ee_sub_nominal_pt1.7_2: TH1D  h_ee_fg_nominal_pt1.7_2
[OK] clone result h_ee_sub_nominal_pt1.7_2: TH1D  h_ee_sub_nominal_pt1.7_2
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt1.7_2
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt1.7_2
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt1.7_2
EE yield:
  FG signal = 7.82e+03
  BG signal = 0
  SUB       = 7.82e+03 +/- 88.4
[OK] project source h_eeg_fg_nominal_pt1.7_2: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt1.7_2
  pt range = [1.7, 2.0)
  y bins   = 18 to 20
[OK] projection h_eeg_fg_nominal_pt1.7_2: TH1D  h_eeg_fg_nominal_pt1.7_2
  proj integral = 5.31e+03
[OK] project source h_eeg_bg_nominal_pt1.7_2: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_bg_nominal_pt1.7_2
  pt range = [1.7, 2.0)
  y bins   = 18 to 20
[OK] projection h_eeg_bg_nominal_pt1.7_2: TH1D  h_eeg_bg_nominal_pt1.7_2
  proj integral = 4.09e+04
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt1.7_2
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt1.7_2
sideband [0.2, 0.8]: FG=2.78e+03, BG=3.16e+04
  scale = 0.0878982
[OK] clone source h_eeg_bg_scaled_nominal_pt1.7_2: TH1D  h_eeg_bg_nominal_pt1.7_2
[OK] clone result h_eeg_bg_scaled_nominal_pt1.7_2: TH1D  h_eeg_bg_scaled_nominal_pt1.7_2
[OK] clone source h_eeg_sub_nominal_pt1.7_2: TH1D  h_eeg_fg_nominal_pt1.7_2
[OK] clone result h_eeg_sub_nominal_pt1.7_2: TH1D  h_eeg_sub_nominal_pt1.7_2
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt1.7_2
EEG after mixed-BG subtraction, before fit:
  raw signal window = 1.52e+03 +/- 43.7
[OK] eeg_mb_nominal_pt1.7_2 input: TH1D  h_eeg_sub_nominal_pt1.7_2
     entries = 524
     integral = 1.72e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_nominal_pt1_7_2_206: TF1  f_eeg_mb_nominal_pt1_7_2_206
Before fit:
  amp0 = 145.68279399658033
  mean0 = 0.135
  sigma0 = 0.018
After fit:
[OK] TF1 after fit eeg_mb_nominal_pt1_7_2_206: TF1  f_eeg_mb_nominal_pt1_7_2_206
  status = 0
  mean = 0.13139858054207643
  sigma = 0.011256108773577538
  chi2/ndf = 309.84932119460365 / 286
[OK] pol2 yield hist: TH1D  h_eeg_sub_nominal_pt1.7_2
     entries = 524
     integral = 1.72e+03
     nbinsX = 400, nbinsY = 1
[OK] pol2 yield fit: TF1  f_eeg_mb_nominal_pt1_7_2_206
pol2-subtracted yield:
  raw = 1.52e+03
  pol2 = 22
  signal = 1.49e+03 +/- 43.7
FINAL MB ONE BIN
  Yee        = 7821 +/- 88.4364
  Yeeg       = 1493.26 +/- 43.6897
  eeg / ee   = 0.190929
  ee / eeg   = 5.23755


################################################################################
Running nominal: pT [2.0, 2.5)
================================================================================
one_bin_result_mb cfg=nominal, pt=[2.0,2.5]
[OK] project source h_ee_fg_nominal_pt2_2.5: TH2F  mb_all_fg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_fg_nominal_pt2_2.5
  pt range = [2.0, 2.5)
  y bins   = 21 to 25
[OK] projection h_ee_fg_nominal_pt2_2.5: TH1D  h_ee_fg_nominal_pt2_2.5
  proj integral = 5.91e+03
[OK] project source h_ee_bg_nominal_pt2_2.5: TH2F  mb_all_bg2d_eemass_reco_nominal
project_mass_in_pt: h_ee_bg_nominal_pt2_2.5
  pt range = [2.0, 2.5)
  y bins   = 21 to 25
[OK] projection h_ee_bg_nominal_pt2_2.5: TH1D  h_ee_bg_nominal_pt2_2.5
  proj integral = 3.82e+05
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_nominal_pt2_2.5
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_nominal_pt2_2.5
sideband [0.2, 0.75]: FG=0, BG=2.67e+05
  scale = 0
[OK] clone source h_ee_bg_scaled_nominal_pt2_2.5: TH1D  h_ee_bg_nominal_pt2_2.5
[OK] clone result h_ee_bg_scaled_nominal_pt2_2.5: TH1D  h_ee_bg_scaled_nominal_pt2_2.5
[OK] clone source h_ee_sub_nominal_pt2_2.5: TH1D  h_ee_fg_nominal_pt2_2.5
[OK] clone result h_ee_sub_nominal_pt2_2.5: TH1D  h_ee_sub_nominal_pt2_2.5
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_nominal_pt2_2.5
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_nominal_pt2_2.5
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_nominal_pt2_2.5
EE yield:
  FG signal = 5.82e+03
  BG signal = 0
  SUB       = 5.82e+03 +/- 76.3
[OK] project source h_eeg_fg_nominal_pt2_2.5: TH2F  mb_all_fg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_fg_nominal_pt2_2.5
  pt range = [2.0, 2.5)
  y bins   = 21 to 25
[OK] projection h_eeg_fg_nominal_pt2_2.5: TH1D  h_eeg_fg_nominal_pt2_2.5
  proj integral = 4.33e+03
[OK] project source h_eeg_bg_nominal_pt2_2.5: TH2F  mb_all_bg2d_eegmass_reco_nominal
project_mass_in_pt: h_eeg_bg_nominal_pt2_2.5
  pt range = [2.0, 2.5)
  y bins   = 21 to 25
[OK] projection h_eeg_bg_nominal_pt2_2.5: TH1D  h_eeg_bg_nominal_pt2_2.5
  proj integral = 2.87e+04
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_nominal_pt2_2.5
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_nominal_pt2_2.5
sideband [0.2, 0.8]: FG=2.19e+03, BG=2.19e+04
  scale = 0.0999954
[OK] clone source h_eeg_bg_scaled_nominal_pt2_2.5: TH1D  h_eeg_bg_nominal_pt2_2.5
[OK] clone result h_eeg_bg_scaled_nominal_pt2_2.5: TH1D  h_eeg_bg_scaled_nominal_pt2_2.5
[OK] clone source h_eeg_sub_nominal_pt2_2.5: TH1D  h_eeg_fg_nominal_pt2_2.5
[OK] clone result h_eeg_sub_nominal_pt2_2.5: TH1D  h_eeg_sub_nominal_pt2_2.5
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_nominal_pt2_2.5
EEG after mixed-BG subtraction, before fit:
  raw signal window = 1.26e+03 +/- 39.1
[OK] eeg_mb_nominal_pt2_2.5 input: TH1D  h_eeg_sub_nominal_pt2_2.5
     entries = 463

,config,pt_min,pt_max,pt_center,y_ee,e_ee,y_eeg,e_eeg,raw_eeg,pol2_eeg,eeg_over_ee,ee_over_eeg,fit_mean,fit_sigma,fit_chi2,fit_ndf
0,nominal,0.8,1.0,0.90,23935.000000,154.709405,3457.011319,72.429137,3556.094715,99.083396,0.144433,6.923611,0.131781,0.011340,3.436923e+02,286
1,nominal,1.0,1.3,1.15,33151.000000,182.074161,5098.894552,85.983490,5329.426631,230.532079,0.153808,6.501605,0.131583,0.011011,3.415856e+02,286
2,nominal,1.3,1.7,1.50,21216.000000,145.657132,3812.284783,71.426078,3956.704563,144.419780,0.179689,5.565167,0.131599,0.010891,3.847676e+02,286
3,nominal,1.7,2.0,1.85,7821.000000,88.436418,1493.256109,43.689734,1515.299031,22.042923,0.190929,5.237548,0.131399,0.011256,3.098493e+02,286
4,nominal,2.0,2.5,2.25,5824.000000,76.315136,1277.640129,39.149301,1261.311254,-16.328875,0.219375,4.558404,0.131591,0.011678,3.246801e+02,286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,escale101,2.5,3.0,2.75,2023.000000,44.977772,518.283193,23.999760,480.902186,-37.381007,0.256195,3.903271,0.132933,0.012026,4.755485e+02,286
136,escale101,3.0,4.0,3.50,1056.949031,32.511536,300.121500,17.953416,277.432379,-22.689121,0.283951,3.521737,0.133392,0.012879,3.664499e+02,285
137,escale101,4.0,5.0,4.50,197.000000,14.035669,64.452607,8.019150,55.770138,-8.682470,0.327171,3.056509,0.134546,0.006219,2.032186e+02,248
138,escale101,5.0,7.0,6.00,80.944853,9.000006,24.267950,4.735909,18.859438,-5.408513,0.299808,3.335463,0.131850,0.006200,9.985342e+01,182
139,escale101,7.0,10.0,8.50,14.000000,3.741657,-35.981606,2.000000,4.000000,39.981606,-2.570115,-0.389088,0.136204,0.028469,8.343779e-07,3

In [50]:

# -----------------------------------------------------------------------------
# pi0 peak extraction variations for systematic uncertainty
# These variations use the same data histograms as the central conversion cut
# and DO NOT vary the simulation correction.  They only change the pi0/eeg
# extraction procedure in data.
#
# Added configs:
#   pi0_int021  : larger counting window, m_eeγ < 0.21 GeV/c^2
#   pi0_pol1    : Gaussian + pol1 instead of Gaussian + pol2
#   pi0_fit035  : smaller fit window, upper fit bound 0.35 GeV/c^2
# -----------------------------------------------------------------------------

pi0_extraction_variations = [
    {
        "out_cfg": "pi0_int021",
        "base_cfg": "conv_tight",
        "label": "pi0 count window 0.09-0.21",
        "eeg_signal": (0.09, 0.21),
        "fit_xmin": 0.05,
        "fit_xmax": 0.78,
        "pol_order": 2,
    },
    {
        "out_cfg": "pi0_pol1",
        "base_cfg": "conv_tight",
        "label": "pi0 fit Gaussian+pol1",
        "eeg_signal": windows["eeg_signal"],
        "fit_xmin": 0.05,
        "fit_xmax": 0.78,
        "pol_order": 1,
    },
    {
        "out_cfg": "pi0_fit035",
        "base_cfg": "conv_tight",
        "label": "pi0 fit range upper 0.35",
        "eeg_signal": windows["eeg_signal"],
        "fit_xmin": 0.05,
        "fit_xmax": 0.35,
        "pol_order": 2,
    },
]


def fit_one_eeg_hist_test_var(h_sub, name="test_fit", fit_xmin=0.05, fit_xmax=0.78, pol_order=2):
    """Fit pi0 peak with Gaussian + polynomial background.

    The default reproduces fit_one_eeg_hist_test(): gaus + pol2, 0.05-0.78.
    The variation options are used only for the pi0 extraction systematic.
    """
    if not check_hist(h_sub, f"{name} input"):
        return None

    if h_sub.Integral() <= 0:
        print(f"[BAD] {name}: histogram integral <= 0, skip fit")
        return None

    tag = safe_root_name(f"{name}_{len(ROOT_KEEPALIVE)}")

    amp0 = max(h_sub.GetMaximum(), 1.0)
    mean0 = 0.135
    sigma0 = 0.018

    if pol_order == 0:
        formula = "gaus(0)+pol0(3)"
        npar = 4
    elif pol_order == 1:
        formula = "gaus(0)+pol1(3)"
        npar = 5
    elif pol_order == 2:
        formula = "gaus(0)+pol2(3)"
        npar = 6
    else:
        raise ValueError(f"Unsupported pol_order={pol_order}; use 0, 1, or 2")

    f = root.TF1(f"f_{tag}", formula, fit_xmin, fit_xmax)

    if not check_obj(f, f"TF1 f_{tag}"):
        return None

    root.SetOwnership(f, False)
    keep(f)

    pars = [amp0, mean0, sigma0, 0.0, 0.0, 0.0]
    for ip in range(npar):
        f.SetParameter(ip, pars[ip])

    f.SetParLimits(1, 0.10, 0.17)
    f.SetParLimits(2, 0.006, 0.050)

    print("Before fit variation:")
    print("  formula =", formula)
    print("  fit range =", fit_xmin, fit_xmax)
    print("  amp0 =", amp0)
    print("  mean0 =", mean0)
    print("  sigma0 =", sigma0)

    res = h_sub.Fit(f, "RQS0")

    print("After fit variation:")

    if not check_obj(f, f"TF1 after fit {tag}"):
        print("[BAD] Fit killed TF1 pointer")
        return None

    status = int(res.Status()) if res else -999

    print("  status =", status)
    print("  mean =", f.GetParameter(1))
    print("  sigma =", f.GetParameter(2))
    print("  chi2/ndf =", f.GetChisquare(), "/", f.GetNDF())

    return f


def poly_subtracted_yield_var(h, f, xmin, xmax, fit_xmin=0.05, fit_xmax=0.78, pol_order=2):
    """Integrate signal window after subtracting the fitted polynomial background.

    This follows the existing pol2_subtracted_yield convention exactly, but allows
    pol1/pol0 and different fit ranges.
    """
    if not check_hist(h, "poly yield hist"):
        return 0.0, 0.0, 0.0, 0.0

    if f is None or not check_obj(f, "poly yield fit"):
        print("[WARNING] No valid fit. Return raw integral without polynomial subtraction.")
        raw, raw_err = integral_range(h, xmin, xmax)
        return raw, raw_err, raw, 0.0

    if pol_order == 0:
        formula = "pol0"
    elif pol_order == 1:
        formula = "pol1"
    elif pol_order == 2:
        formula = "pol2"
    else:
        raise ValueError(f"Unsupported pol_order={pol_order}; use 0, 1, or 2")

    poly = root.TF1(
        f"poly{pol_order}_from_{safe_root_name(f.GetName())}_{len(ROOT_KEEPALIVE)}",
        formula,
        fit_xmin,
        fit_xmax
    )
    root.SetOwnership(poly, False)
    keep(poly)

    for ip in range(pol_order + 1):
        poly.SetParameter(ip, f.GetParameter(3 + ip))

    b1 = h.FindBin(xmin + 1e-3)
    b2 = h.FindBin(xmax - 1e-3)

    raw = 0.0
    bg = 0.0
    sig = 0.0
    err2 = 0.0

    for ib in range(b1, b2 + 1):
        x = h.GetBinCenter(ib)
        y = h.GetBinContent(ib)
        b = poly.Eval(x)

        raw += y
        bg += b
        sig += y - b
        err2 += h.GetBinError(ib)**2

    err = math.sqrt(err2)

    print(f"pol{pol_order}-subtracted yield:")
    print(f"  signal window = [{xmin}, {xmax}]")
    print(f"  raw = {raw:.3g}")
    print(f"  pol{pol_order} = {bg:.3g}")
    print(f"  signal = {sig:.3g} +/- {err:.3g}")

    return sig, err, raw, bg


def one_bin_result_mb_pi0var(out_cfg, base_cfg, mb, pt_min, pt_max,
                            eeg_signal=None, fit_xmin=0.05, fit_xmax=0.78, pol_order=2):
    print("="*80)
    print(f"one_bin_result_mb_pi0var out_cfg={out_cfg}, base_cfg={base_cfg}, pt=[{pt_min},{pt_max}]")
    print(f"  eeg_signal={eeg_signal}, fit=[{fit_xmin},{fit_xmax}], pol_order={pol_order}")

    if eeg_signal is None:
        eeg_signal = windows["eeg_signal"]

    ee_info = get_ee_yield(
        mb["fg_ee"],
        mb["bg_ee"],
        pt_min,
        pt_max,
        out_cfg
    )

    eeg_pre = get_eeg_subtracted_hist_no_fit(
        mb["fg_eeg"],
        mb["bg_eeg"],
        pt_min,
        pt_max,
        out_cfg
    )

    f = fit_one_eeg_hist_test_var(
        eeg_pre["h_sub"],
        f"eeg_mb_{out_cfg}_pt{pt_min:g}_{pt_max:g}",
        fit_xmin=fit_xmin,
        fit_xmax=fit_xmax,
        pol_order=pol_order,
    )

    y_eeg, e_eeg, raw_eeg, poly_eeg = poly_subtracted_yield_var(
        eeg_pre["h_sub"],
        f,
        eeg_signal[0],
        eeg_signal[1],
        fit_xmin=fit_xmin,
        fit_xmax=fit_xmax,
        pol_order=pol_order,
    )

    y_ee = ee_info["yield"]
    e_ee = ee_info["yield_err"]

    eeg_over_ee = y_eeg / y_ee if y_ee != 0 else float("nan")
    ee_over_eeg = y_ee / y_eeg if y_eeg != 0 else float("nan")

    print("FINAL MB PI0 VAR ONE BIN")
    print(f"  Yee        = {y_ee:.6g} +/- {e_ee:.6g}")
    print(f"  Yeeg       = {y_eeg:.6g} +/- {e_eeg:.6g}")
    print(f"  eeg / ee   = {eeg_over_ee:.6g}")
    print(f"  ee / eeg   = {ee_over_eeg:.6g}")

    return {
        "cfg": out_cfg,
        "base_cfg": base_cfg,
        "pt_min": pt_min,
        "pt_max": pt_max,
        "ee": ee_info,
        "eeg_pre": eeg_pre,
        "fit": f,
        "y_ee": y_ee,
        "e_ee": e_ee,
        "y_eeg": y_eeg,
        "e_eeg": e_eeg,
        "raw_eeg": raw_eeg,
        "pol2_eeg": poly_eeg,   # keep existing column name used downstream
        "eeg_over_ee": eeg_over_ee,
        "ee_over_eeg": ee_over_eeg,
        "eeg_signal_low": eeg_signal[0],
        "eeg_signal_high": eeg_signal[1],
        "fit_xmin": fit_xmin,
        "fit_xmax": fit_xmax,
        "pol_order": pol_order,
    }


def run_pt_bins_for_config_pi0var(out_cfg, base_cfg, mb, save_canvases=False,
                                  eeg_signal=None, fit_xmin=0.05, fit_xmax=0.78, pol_order=2):
    rows = []
    results = {}

    for ipt in range(len(pt_bins) - 1):
        pt_min = pt_bins[ipt]
        pt_max = pt_bins[ipt + 1]

        print("\n")
        print("#"*80)
        print(f"Running pi0 extraction variation {out_cfg}: pT [{pt_min}, {pt_max})")

        res = one_bin_result_mb_pi0var(
            out_cfg,
            base_cfg,
            mb,
            pt_min,
            pt_max,
            eeg_signal=eeg_signal,
            fit_xmin=fit_xmin,
            fit_xmax=fit_xmax,
            pol_order=pol_order,
        )
        results[(pt_min, pt_max)] = res

        if save_canvases:
            tag = f"{out_cfg}_mb_pt{str(pt_min).replace('.','p')}_{str(pt_max).replace('.','p')}"
            save_one_bin_canvas(res, tag)

        row = {
            "config": out_cfg,
            "base_config": base_cfg,
            "pt_min": pt_min,
            "pt_max": pt_max,
            "pt_center": 0.5 * (pt_min + pt_max),

            "y_ee": res["y_ee"],
            "e_ee": res["e_ee"],
            "y_eeg": res["y_eeg"],
            "e_eeg": res["e_eeg"],

            "raw_eeg": res["raw_eeg"],
            "pol2_eeg": res["pol2_eeg"],

            "eeg_over_ee": res["eeg_over_ee"],
            "ee_over_eeg": res["ee_over_eeg"],

            "fit_mean": res["fit"].GetParameter(1) if res["fit"] else float("nan"),
            "fit_sigma": abs(res["fit"].GetParameter(2)) if res["fit"] else float("nan"),
            "fit_chi2": res["fit"].GetChisquare() if res["fit"] else float("nan"),
            "fit_ndf": res["fit"].GetNDF() if res["fit"] else -999,

            "eeg_signal_low": res["eeg_signal_low"],
            "eeg_signal_high": res["eeg_signal_high"],
            "fit_xmin": res["fit_xmin"],
            "fit_xmax": res["fit_xmax"],
            "pol_order": res["pol_order"],
        }

        rows.append(row)

    df = pd.DataFrame(rows)
    return df, results


# Run pi0 extraction variations on the central data cut only.
# The simulation correction is not varied: make_rgamma_graph_for_config_fox()
# will map these configs to the same conv_tight simulation correction.
pi0_var_dfs = []
pi0_var_results = {}

for var in pi0_extraction_variations:
    out_cfg = var["out_cfg"]
    base_cfg = var["base_cfg"]

    print("\n\n")
    print("="*100)
    print(f"BUILDING MB HISTOGRAMS FOR PI0 VARIATION {out_cfg} FROM BASE {base_cfg}")
    print("="*100)

    mb_base = build_mb_set(hists, base_cfg)

    df_var, results_var = run_pt_bins_for_config_pi0var(
        out_cfg,
        base_cfg,
        mb_base,
        save_canvases=False,
        eeg_signal=var["eeg_signal"],
        fit_xmin=var["fit_xmin"],
        fit_xmax=var["fit_xmax"],
        pol_order=var["pol_order"],
    )

    pi0_var_dfs.append(df_var)
    pi0_var_results[out_cfg] = results_var

if len(pi0_var_dfs) > 0:
    df_pi0_variations = pd.concat(pi0_var_dfs, ignore_index=True)
    df_all = pd.concat([df_all, df_pi0_variations], ignore_index=True)
    df_all.to_csv(f"{fit_out_dir}/yields_all_configs_mb_with_pi0_variations.csv", index=False)

df_pi0_variations if len(pi0_var_dfs) > 0 else None

====================================================================================================
BUILDING MB HISTOGRAMS FOR PI0 VARIATION pi0_int021 FROM BASE conv_tight
====================================================================================================
[OK] clone source mb_file0_fg2d_eemass_reco_conv_tight: TH2F  fg2d_eemass_reco_conv_tight_icent0_file0
[OK] clone result mb_file0_fg2d_eemass_reco_conv_tight: TH2F  mb_file0_fg2d_eemass_reco_conv_tight
[OK] built mb_file0_fg2d_eemass_reco_conv_tight: integral=68399
[OK] clone source mb_all_fg2d_eemass_reco_conv_tight: TH2F  mb_file0_fg2d_eemass_reco_conv_tight
[OK] clone result mb_all_fg2d_eemass_reco_conv_tight: TH2F  mb_all_fg2d_eemass_reco_conv_tight
[OK] built mb_all_fg2d_eemass_reco_conv_tight: integral=68399
[OK] clone source mb_file0_bg2d_eemass_reco_conv_tight: TH2F  bg2d_eemass_reco_conv_tight_icent0_file0
[OK] clone result mb_file0_bg2d_eemass_reco_conv_tight: TH2F  mb_file0_bg2d_eemass_reco_conv_tight
[OK] built mb_file0_bg2d_eemass_reco_conv_tight: integral=1.01495e+08
[OK] clone source mb_all_bg2d_eemass_reco_conv_tight: TH2F  mb_file0_bg2d_eemass_reco_conv_tight
[OK] clone result mb_all_bg2d_eemass_reco_conv_tight: TH2F  mb_all_bg2d_eemass_reco_conv_tight
[OK] built mb_all_bg2d_eemass_reco_conv_tight: integral=1.01495e+08
[OK] clone source mb_file0_fg2d_eegmass_reco_conv_tight: TH2F  fg2d_eegmass_reco_conv_tight_icent0_file0
[OK] clone result mb_file0_fg2d_eegmass_reco_conv_tight: TH2F  mb_file0_fg2d_eegmass_reco_conv_tight
[OK] built mb_file0_fg2d_eegmass_reco_conv_tight: integral=42943
[OK] clone source mb_all_fg2d_eegmass_reco_conv_tight: TH2F  mb_file0_fg2d_eegmass_reco_conv_tight
[OK] clone result mb_all_fg2d_eegmass_reco_conv_tight: TH2F  mb_all_fg2d_eegmass_reco_conv_tight
[OK] built mb_all_fg2d_eegmass_reco_conv_tight: integral=42943
[OK] clone source mb_file0_bg2d_eegmass_reco_conv_tight: TH2F  bg2d_eegmass_reco_conv_tight_icent0_file0
[OK] clone result mb_file0_bg2d_eegmass_reco_conv_tight: TH2F  mb_file0_bg2d_eegmass_reco_conv_tight
[OK] built mb_file0_bg2d_eegmass_reco_conv_tight: integral=398760
[OK] clone source mb_all_bg2d_eegmass_reco_conv_tight: TH2F  mb_file0_bg2d_eegmass_reco_conv_tight
[OK] clone result mb_all_bg2d_eegmass_reco_conv_tight: TH2F  mb_all_bg2d_eegmass_reco_conv_tight
[OK] built mb_all_bg2d_eegmass_reco_conv_tight: integral=398760


################################################################################
Running pi0 extraction variation pi0_int021: pT [0.8, 1.0)
================================================================================
one_bin_result_mb_pi0var out_cfg=pi0_int021, base_cfg=conv_tight, pt=[0.8,1.0]
  eeg_signal=(0.09, 0.21), fit=[0.05,0.78], pol_order=2
[OK] project source h_ee_fg_pi0_int021_pt0.8_1: TH2F  mb_all_fg2d_eemass_reco_conv_tight
project_mass_in_pt: h_ee_fg_pi0_int021_pt0.8_1
  pt range = [0.8, 1.0)
  y bins   = 9 to 10
[OK] projection h_ee_fg_pi0_int021_pt0.8_1: TH1D  h_ee_fg_pi0_int021_pt0.8_1
  proj integral = 1.5e+04
[OK] project source h_ee_bg_pi0_int021_pt0.8_1: TH2F  mb_all_bg2d_eemass_reco_conv_tight
project_mass_in_pt: h_ee_bg_pi0_int021_pt0.8_1
  pt range = [0.8, 1.0)
  y bins   = 9 to 10
[OK] projection h_ee_bg_pi0_int021_pt0.8_1: TH1D  h_ee_bg_pi0_int021_pt0.8_1
  proj integral = 1.19e+07
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_pi0_int021_pt0.8_1
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_pi0_int021_pt0.8_1
sideband [0.2, 0.75]: FG=0, BG=9.25e+06
  scale = 0
[OK] clone source h_ee_bg_scaled_pi0_int021_pt0.8_1: TH1D  h_ee_bg_pi0_int021_pt0.8_1
[OK] clone result h_ee_bg_scaled_pi0_int021_pt0.8_1: TH1D  h_ee_bg_scaled_pi0_int021_pt0.8_1
[OK] clone source h_ee_sub_pi0_int021_pt0.8_1: TH1D  h_ee_fg_pi0_int021_pt0.8_1
[OK] clone result h_ee_sub_pi0_int021_pt0.8_1: TH1D  h_ee_sub_pi0_int021_pt0.8_1
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_pi0_int021_pt0.8_1
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_pi0_int021_pt0.8_1
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_pi0_int021_pt0.8_1
EE yield:
  FG signal = 1.5e+04
  BG signal = 0
  SUB       = 1.5e+04 +/- 123
[OK] project source h_eeg_fg_pi0_int021_pt0.8_1: TH2F  mb_all_fg2d_eegmass_reco_conv_tight
project_mass_in_pt: h_eeg_fg_pi0_int021_pt0.8_1
  pt range = [0.8, 1.0)
  y bins   = 9 to 10
[OK] projection h_eeg_fg_pi0_int021_pt0.8_1: TH1D  h_eeg_fg_pi0_int021_pt0.8_1
  proj integral = 8.8e+03
[OK] project source h_eeg_bg_pi0_int021_pt0.8_1: TH2F  mb_all_bg2d_eegmass_reco_conv_tight
project_mass_in_pt: h_eeg_bg_pi0_int021_pt0.8_1
  pt range = [0.8, 1.0)
  y bins   = 9 to 10
[OK] projection h_eeg_bg_pi0_int021_pt0.8_1: TH1D  h_eeg_bg_pi0_int021_pt0.8_1
  proj integral = 9.52e+04
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_pi0_int021_pt0.8_1
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_pi0_int021_pt0.8_1
sideband [0.2, 0.8]: FG=4.26e+03, BG=6.27e+04
  scale = 0.0679045
[OK] clone source h_eeg_bg_scaled_pi0_int021_pt0.8_1: TH1D  h_eeg_bg_pi0_int021_pt0.8_1
[OK] clone result h_eeg_bg_scaled_pi0_int021_pt0.8_1: TH1D  h_eeg_bg_scaled_pi0_int021_pt0.8_1
[OK] clone source h_eeg_sub_pi0_int021_pt0.8_1: TH1D  h_eeg_fg_pi0_int021_pt0.8_1
[OK] clone result h_eeg_sub_pi0_int021_pt0.8_1: TH1D  h_eeg_sub_pi0_int021_pt0.8_1
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_pi0_int021_pt0.8_1
EEG after mixed-BG subtraction, before fit:
  raw signal window = 2.25e+03 +/- 57.5
[OK] eeg_mb_pi0_int021_pt0.8_1 input: TH1D  h_eeg_sub_pi0_int021_pt0.8_1
     entries = 593
     integral = 2.34e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_pi0_int021_pt0_8_1_1668: TF1  f_eeg_mb_pi0_int021_pt0_8_1_1668
Before fit variation:
  formula = gaus(0)+pol2(3)
  fit range = 0.05 0.78
  amp0 = 216.84457099105134
  mean0 = 0.135
  sigma0 = 0.018
After fit variation:
[OK] TF1 after fit eeg_mb_pi0_int021_pt0_8_1_1668: TF1  f_eeg_mb_pi0_int021_pt0_8_1_1668
  status = 0
  mean = 0.1323181273163271
  sigma = 0.010592252732149665
  chi2/ndf = 382.3159514440526 / 286
[OK] poly yield hist: TH1D  h_eeg_sub_pi0_int021_pt0.8_1
     entries = 593
     integral = 2.34e+03
     nbinsX = 400, nbinsY = 1
[OK] poly yield fit: TF1  f_eeg_mb_pi0_int021_pt0_8_1_1668
pol2-subtracted yield:
  signal window = [0.09, 0.21]
  raw = 2.27e+03
  pol2 = 65.9
  signal = 2.21e+03 +/- 59.9
FINAL MB PI0 VAR ONE BIN
  Yee        = 15019 +/- 122.552
  Yeeg       = 2207.4 +/- 59.9052
  eeg / ee   = 0.146974
  ee / eeg   = 6.80393


################################################################################
Running pi0 extraction variation pi0_int021: pT [1.0, 1.3)
================================================================================
one_bin_result_mb_pi0var out_cfg=pi0_int021, base_cfg=conv_tight, pt=[1.0,1.3]
  eeg_signal=(0.09, 0.21), fit=[0.05,0.78], pol_order=2
[OK] project source h_ee_fg_pi0_int021_pt1_1.3: TH2F  mb_all_fg2d_eemass_reco_conv_tight
project_mass_in_pt: h_ee_fg_pi0_int021_pt1_1.3
  pt range = [1.0, 1.3)
  y bins   = 11 to 13
[OK] projection h_ee_fg_pi0_int021_pt1_1.3: TH1D  h_ee_fg_pi0_int021_pt1_1.3
  proj integral = 2.14e+04
[OK] project source h_ee_bg_pi0_int021_pt1_1.3: TH2F  mb_all_bg2d_eemass_reco_conv_tight
project_mass_in_pt: h_ee_bg_pi0_int021_pt1_1.3
  pt range = [1.0, 1.3)
  y bins   = 11 to 13
[OK] projection h_ee_bg_pi0_int021_pt1_1.3: TH1D  h_ee_bg_pi0_int021_pt1_1.3
  proj integral = 8.04e+06
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_pi0_int021_pt1_1.3
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_pi0_int021_pt1_1.3
sideband [0.2, 0.75]: FG=0, BG=5.89e+06
  scale = 0
[OK] clone source h_ee_bg_scaled_pi0_int021_pt1_1.3: TH1D  h_ee_bg_pi0_int021_pt1_1.3
[OK] clone result h_ee_bg_scaled_pi0_int021_pt1_1.3: TH1D  h_ee_bg_scaled_pi0_int021_pt1_1.3
[OK] clone source h_ee_sub_pi0_int021_pt1_1.3: TH1D  h_ee_fg_pi0_int021_pt1_1.3
[OK] clone result h_ee_sub_pi0_int021_pt1_1.3: TH1D  h_ee_sub_pi0_int021_pt1_1.3
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_pi0_int021_pt1_1.3
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_pi0_int021_pt1_1.3
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_pi0_int021_pt1_1.3
EE yield:
  FG signal = 2.14e+04
  BG signal = 0
  SUB       = 2.14e+04 +/- 146
[OK] project source h_eeg_fg_pi0_int021_pt1_1.3: TH2F  mb_all_fg2d_eegmass_reco_conv_tight
project_mass_in_pt: h_eeg_fg_pi0_int021_pt1_1.3
  pt range = [1.0, 1.3)
  y bins   = 11 to 13
[OK] projection h_eeg_fg_pi0_int021_pt1_1.3: TH1D  h_eeg_fg_pi0_int021_pt1_1.3
  proj integral = 1.26e+04
[OK] project source h_eeg_bg_pi0_int021_pt1_1.3: TH2F  mb_all_bg2d_eegmass_reco_conv_tight
project_mass_in_pt: h_eeg_bg_pi0_int021_pt1_1.3
  pt range = [1.0, 1.3)
  y bins   = 11 to 13
[OK] projection h_eeg_bg_pi0_int021_pt1_1.3: TH1D  h_eeg_bg_pi0_int021_pt1_1.3
  proj integral = 1.2e+05
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_pi0_int021_pt1_1.3
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_pi0_int021_pt1_1.3
sideband [0.2, 0.8]: FG=6.65e+03, BG=9.07e+04
  scale = 0.0733125
[OK] clone source h_eeg_bg_scaled_pi0_int021_pt1_1.3: TH1D  h_eeg_bg_pi0_int021_pt1_1.3
[OK] clone result h_eeg_bg_scaled_pi0_int021_pt1_1.3: TH1D  h_eeg_bg_scaled_pi0_int021_pt1_1.3
[OK] clone source h_eeg_sub_pi0_int021_pt1_1.3: TH1D  h_eeg_fg_pi0_int021_pt1_1.3
[OK] clone result h_eeg_sub_pi0_int021_pt1_1.3: TH1D  h_eeg_sub_pi0_int021_pt1_1.3
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_pi0_int021_pt1_1.3
EEG after mixed-BG subtraction, before fit:
  raw signal window = 3.4e+03 +/- 68.7
[OK] eeg_mb_pi0_int021_pt1_1.3 input: TH1D  h_eeg_sub_pi0_int021_pt1_1.3
     entries = 1.08e+03
     integral = 3.78e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_pi0_int021_pt1_1_3_1678: TF1  f_eeg_mb_pi0_int021_pt1_1_3_1678
Before fit variation:
  formula = gaus(0)+pol2(3)
  fit range = 0.05 0.78
  amp0 = 330.94186623719014
  mean0 = 0.135
  sigma0 = 0.018
After fit variation:
[OK] TF1 after fit eeg_mb_pi0_int021_pt1_1_3_1678: TF1  f_eeg_mb_pi0_int021_pt1_1_3_1678
  status = 0
  mean = 0.13224790977586623
  sigma = 0.010431912978471696
  chi2/ndf = 345.260334461848 / 286
[OK] poly yield hist: TH1D  h_eeg_sub_pi0_int021_pt1_1.3
     entries = 1.08e+03
     integral = 3.78e+03
     nbinsX = 400, nbinsY = 1
[OK] poly yield fit: TF1  f_eeg_mb_pi0_int021_pt1_1_3_1678
pol2-subtracted yield:
  signal window = [0.09, 0.21]
  raw = 3.4e+03
  pol2 = 131
  signal = 3.27e+03 +/- 71.2
FINAL MB PI0 VAR ONE BIN
  Yee        = 21382 +/- 146.226
  Yeeg       = 3266.72 +/- 71.2205
  eeg / ee   = 0.152779
  ee / eeg   = 6.54541


################################################################################
Running pi0 extraction variation pi0_int021: pT [1.3, 1.7)
================================================================================
one_bin_result_mb_pi0var out_cfg=pi0_int021, base_cfg=conv_tight, pt=[1.3,1.7]
  eeg_signal=(0.09, 0.21), fit=[0.05,0.78], pol_order=2
[OK] project source h_ee_fg_pi0_int021_pt1.3_1.7: TH2F  mb_all_fg2d_eemass_reco_conv_tight
project_mass_in_pt: h_ee_fg_pi0_int021_pt1.3_1.7
  pt range = [1.3, 1.7)
  y bins   = 14 to 17
[OK] projection h_ee_fg_pi0_int021_pt1.3_1.7: TH1D  h_ee_fg_pi0_int021_pt1.3_1.7
  proj integral = 1.45e+04
[OK] project source h_ee_bg_pi0_int021_pt1.3_1.7: TH2F  mb_all_bg2d_eemass_reco_conv_tight
project_mass_in_pt: h_ee_bg_pi0_int021_pt1.3_1.7
  pt range = [1.3, 1.7)
  y bins   = 14 to 17
[OK] projection h_ee_bg_pi0_int021_pt1.3_1.7: TH1D  h_ee_bg_pi0_int021_pt1.3_1.7
  proj integral = 3.3e+06
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_pi0_int021_pt1.3_1.7
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_pi0_int021_pt1.3_1.7
sideband [0.2, 0.75]: FG=0, BG=2.39e+06
  scale = 0
[OK] clone source h_ee_bg_scaled_pi0_int021_pt1.3_1.7: TH1D  h_ee_bg_pi0_int021_pt1.3_1.7
[OK] clone result h_ee_bg_scaled_pi0_int021_pt1.3_1.7: TH1D  h_ee_bg_scaled_pi0_int021_pt1.3_1.7
[OK] clone source h_ee_sub_pi0_int021_pt1.3_1.7: TH1D  h_ee_fg_pi0_int021_pt1.3_1.7
[OK] clone result h_ee_sub_pi0_int021_pt1.3_1.7: TH1D  h_ee_sub_pi0_int021_pt1.3_1.7
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_pi0_int021_pt1.3_1.7
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_pi0_int021_pt1.3_1.7
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_pi0_int021_pt1.3_1.7
EE yield:
  FG signal = 1.45e+04
  BG signal = 0
  SUB       = 1.45e+04 +/- 120
[OK] project source h_eeg_fg_pi0_int021_pt1.3_1.7: TH2F  mb_all_fg2d_eegmass_reco_conv_tight
project_mass_in_pt: h_eeg_fg_pi0_int021_pt1.3_1.7
  pt range = [1.3, 1.7)
  y bins   = 14 to 17
[OK] projection h_eeg_fg_pi0_int021_pt1.3_1.7: TH1D  h_eeg_fg_pi0_int021_pt1.3_1.7
  proj integral = 9.31e+03
[OK] project source h_eeg_bg_pi0_int021_pt1.3_1.7: TH2F  mb_all_bg2d_eegmass_reco_conv_tight
project_mass_in_pt: h_eeg_bg_pi0_int021_pt1.3_1.7
  pt range = [1.3, 1.7)
  y bins   = 14 to 17
[OK] projection h_eeg_bg_pi0_int021_pt1.3_1.7: TH1D  h_eeg_bg_pi0_int021_pt1.3_1.7
  proj integral = 8.28e+04
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_pi0_int021_pt1.3_1.7
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_pi0_int021_pt1.3_1.7
sideband [0.2, 0.8]: FG=4.88e+03, BG=6.46e+04
  scale = 0.0754402
[OK] clone source h_eeg_bg_scaled_pi0_int021_pt1.3_1.7: TH1D  h_eeg_bg_pi0_int021_pt1.3_1.7
[OK] clone result h_eeg_bg_scaled_pi0_int021_pt1.3_1.7: TH1D  h_eeg_bg_scaled_pi0_int021_pt1.3_1.7
[OK] clone source h_eeg_sub_pi0_int021_pt1.3_1.7: TH1D  h_eeg_fg_pi0_int021_pt1.3_1.7
[OK] clone result h_eeg_sub_pi0_int021_pt1.3_1.7: TH1D  h_eeg_sub_pi0_int021_pt1.3_1.7
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_pi0_int021_pt1.3_1.7
EEG after mixed-BG subtraction, before fit:
  raw signal window = 2.67e+03 +/- 58.8
[OK] eeg_mb_pi0_int021_pt1.3_1.7 input: TH1D  h_eeg_sub_pi0_int021_pt1.3_1.7
     entries = 960
     integral = 3.06e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_pi0_int021_pt1_3_1_7_1688: TF1  f_eeg_mb_pi0_int021_pt1_3_1_7_1688
Before fit variation:
  formula = gaus(0)+pol2(3)
  fit range = 0.05 0.78
  amp0 = 250.91363678559273
  mean0 = 0.135
  sigma0 = 0.018
After fit variation:
[OK] TF1 after fit eeg_mb_pi0_int021_pt1_3_1_7_1688: TF1  f_eeg_mb_pi0_int021_pt1_3_1_7_1688
  status = 0
  mean = 0.13205603732337146
  sigma = 0.010516056692122572
  chi2/ndf = 347.87072645609555 / 286
[OK] poly yield hist: TH1D  h_eeg_sub_pi0_int021_pt1.3_1.7
     entries = 960
     integral = 3.06e+03
     nbinsX = 400, nbinsY = 1
[OK] poly yield fit: TF1  f_eeg_mb_pi0_int021_pt1_3_1_7_1688
pol2-subtracted yield:
  signal window = [0.09, 0.21]
  raw = 2.72e+03
  pol2 = 82.8
  signal = 2.64e+03 +/- 60.8
FINAL MB PI0 VAR ONE BIN
  Yee        = 14476 +/- 120.316
  Yeeg       = 2635.36 +/- 60.8354
  eeg / ee   = 0.18205
  ee / eeg   = 5.49298


################################################################################
Running pi0 extraction variation pi0_int021: pT [1.7, 2.0)
================================================================================
one_bin_result_mb_pi0var out_cfg=pi0_int021, base_cfg=conv_tight, pt=[1.7,2.0]
  eeg_signal=(0.09, 0.21), fit=[0.05,0.78], pol_order=2
[OK] project source h_ee_fg_pi0_int021_pt1.7_2: TH2F  mb_all_fg2d_eemass_reco_conv_tight
project_mass_in_pt: h_ee_fg_pi0_int021_pt1.7_2
  pt range = [1.7, 2.0)
  y bins   = 18 to 20
[OK] projection h_ee_fg_pi0_int021_pt1.7_2: TH1D  h_ee_fg_pi0_int021_pt1.7_2
  proj integral = 5.71e+03
[OK] project source h_ee_bg_pi0_int021_pt1.7_2: TH2F  mb_all_bg2d_eemass_reco_conv_tight
project_mass_in_pt: h_ee_bg_pi0_int021_pt1.7_2
  pt range = [1.7, 2.0)
  y bins   = 18 to 20
[OK] projection h_ee_bg_pi0_int021_pt1.7_2: TH1D  h_ee_bg_pi0_int021_pt1.7_2
  proj integral = 7.46e+05
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_pi0_int021_pt1.7_2
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_pi0_int021_pt1.7_2
sideband [0.2, 0.75]: FG=0, BG=5.35e+05
  scale = 0
[OK] clone source h_ee_bg_scaled_pi0_int021_pt1.7_2: TH1D  h_ee_bg_pi0_int021_pt1.7_2
[OK] clone result h_ee_bg_scaled_pi0_int021_pt1.7_2: TH1D  h_ee_bg_scaled_pi0_int021_pt1.7_2
[OK] clone source h_ee_sub_pi0_int021_pt1.7_2: TH1D  h_ee_fg_pi0_int021_pt1.7_2
[OK] clone result h_ee_sub_pi0_int021_pt1.7_2: TH1D  h_ee_sub_pi0_int021_pt1.7_2
[OK] integral source 0.01_0.13: TH1D  h_ee_fg_pi0_int021_pt1.7_2
[OK] integral source 0.01_0.13: TH1D  h_ee_bg_scaled_pi0_int021_pt1.7_2
[OK] integral source 0.01_0.13: TH1D  h_ee_sub_pi0_int021_pt1.7_2
EE yield:
  FG signal = 5.7e+03
  BG signal = 0
  SUB       = 5.7e+03 +/- 75.5
[OK] project source h_eeg_fg_pi0_int021_pt1.7_2: TH2F  mb_all_fg2d_eegmass_reco_conv_tight
project_mass_in_pt: h_eeg_fg_pi0_int021_pt1.7_2
  pt range = [1.7, 2.0)
  y bins   = 18 to 20
[OK] projection h_eeg_fg_pi0_int021_pt1.7_2: TH1D  h_eeg_fg_pi0_int021_pt1.7_2
  proj integral = 3.84e+03
[OK] project source h_eeg_bg_pi0_int021_pt1.7_2: TH2F  mb_all_bg2d_eegmass_reco_conv_tight
project_mass_in_pt: h_eeg_bg_pi0_int021_pt1.7_2
  pt range = [1.7, 2.0)
  y bins   = 18 to 20
[OK] projection h_eeg_bg_pi0_int021_pt1.7_2: TH1D  h_eeg_bg_pi0_int021_pt1.7_2
  proj integral = 3.01e+04
[OK] integral source 0.2_0.8: TH1D  h_eeg_fg_pi0_int021_pt1.7_2
[OK] integral source 0.2_0.8: TH1D  h_eeg_bg_pi0_int021_pt1.7_2
sideband [0.2, 0.8]: FG=2.04e+03, BG=2.32e+04
  scale = 0.0878213
[OK] clone source h_eeg_bg_scaled_pi0_int021_pt1.7_2: TH1D  h_eeg_bg_pi0_int021_pt1.7_2
[OK] clone result h_eeg_bg_scaled_pi0_int021_pt1.7_2: TH1D  h_eeg_bg_scaled_pi0_int021_pt1.7_2
[OK] clone source h_eeg_sub_pi0_int021_pt1.7_2: TH1D  h_eeg_fg_pi0_int021_pt1.7_2
[OK] clone result h_eeg_sub_pi0_int021_pt1.7_2: TH1D  h_eeg_sub_pi0_int021_pt1.7_2
[OK] integral source 0.09_0.19: TH1D  h_eeg_sub_pi0_int021_pt1.7_2
EEG after mixed-BG subtraction, before fit:
  raw signal window = 1.09e+03 +/- 37.1
[OK] eeg_mb_pi0_int021_pt1.7_2 input: TH1D  h_eeg_sub_pi0_int021_pt1.7_2
     entries = 354
     integral = 1.2e+03
     nbinsX = 400, nbinsY = 1
[OK] TF1 f_eeg_mb_pi0_int021_pt1_7_2_1698: TF1  f_eeg_mb_pi0_int021_pt1_7_2_1698
Before fit variation:
  formula = gaus(0)+pol2(3)
  fit range = 0.05 0.78
  amp0 = 108.06212062508072
  mean0 = 0.135
  sigma0 = 0.018
After fit variation:
[OK] TF1 after fit eeg_mb_pi0_int021_pt1_7_2_1698: TF1  f_eeg_mb_pi0_int021_pt1_7_2_1698
  status = 0
  mean = 0.13176230804259048
  sigma = 0.011361854583443451
  chi2/ndf = 344.38345052401905 / 286
[OK] poly yield hist: TH1D  h_eeg_sub_pi0_int021_pt1.7_2
     entries = 354
     integral = 1.2e+03
     nbinsX = 400, nbinsY = 1
[OK] poly yield fit: TF1  f_eeg_mb_pi0_int021_pt1_7_2_1698
pol2-subtracted yield:
  signal window = [0.09, 0.21]
  raw = 1.11e+03
  pol2 = -33.8
  signal = 1.14e+03 +/- 38.3
FINAL MB PI0 VAR ONE BIN
  Yee        = 5700 +/- 75.4983
  Yeeg       = 1139.75 +/- 38.3035
  eeg / ee   = 0.199955
  ee / eeg   = 5.00112


################################################################################
Running pi0 extraction variation pi0_int021: pT [2.0, 2.5)
================================================================================
one_bin_result_mb_pi0var out_cfg=pi0_int021, base_cfg=conv_tight, pt=[2.0,2.5]
  eeg_signal=(0.09, 0.21), fit=[0.05,0.78], pol_order=2
[OK] project source h_ee_fg_pi0_int021_pt2_2.5: TH2F  mb_all_fg2d_eemass_reco_conv_tight
project_mass_in_pt: h_ee_fg_pi0_int021_pt2_2.5
  pt range = [2.0, 2.5)
  y bins   = 21 to 25
[OK] projection h_ee_fg_pi0_int021_pt2_2.5: TH1D  h_ee_fg_pi0_int021_pt2_2.5
  proj integral = 4.27e+03
[OK] project source h_ee_bg_pi0_int021_pt2_2.5: TH2F  mb_all_bg2d_eemass_reco_conv_tight
project_mass_in_pt: h_ee_bg_pi0_int021_pt2_2.5
  pt range = [2.0, 2.5)
  y bins   = 21 to 25
[OK] projection h_ee_bg_pi0_int021_pt2_2.5: TH1D  h_ee_bg_pi0_int021_pt2_2.5
  proj integral = 3.82e+05
[OK] integral source 0.2_0.75: TH1D  h_ee_fg_pi0_int021_pt2_2.5
[OK] integral source 0.2_0.75: TH1D  h_ee_bg_pi0_int021_pt2_2.5
sideband [0.2, 0.75]: FG=0, BG=2.67e+05
  scale = 0
[OK] clone source h_ee_bg_scaled_pi0_int021_pt2_2.5: TH1D  h_ee_bg_pi0_int021_pt2_2.5
[OK] clone result h_ee_bg_scaled_pi0_int021_pt2_2.5: TH1D  h_ee_bg_scaled_pi0_int021_pt2_2.5
[OK] clone source h_ee_sub_pi0_int021_pt2_2.5: TH1D  h_ee_fg_pi0_int021_pt2_2.5

,config,base_config,pt_min,pt_max,pt_center,y_ee,e_ee,y_eeg,e_eeg,raw_eeg,...,ee_over_eeg,fit_mean,fit_sigma,fit_chi2,fit_ndf,eeg_signal_low,eeg_signal_high,fit_xmin,fit_xmax,pol_order
0,pi0_int021,conv_tight,0.8,1.0,0.90,15019.000000,122.552030,2207.400296,59.905214,2273.348471,...,6.803931,0.132318,0.010592,3.823160e+02,286,0.09,0.21,0.05,0.78,2
1,pi0_int021,conv_tight,1.0,1.3,1.15,21382.000000,146.225853,3266.719033,71.220527,3398.056170,...,6.545405,0.132248,0.010432,3.452603e+02,286,0.09,0.21,0.05,0.78,2
2,pi0_int021,conv_tight,1.3,1.7,1.50,14476.000000,120.316250,2635.361599,60.835380,2718.117771,...,5.492984,0.132056,0.010516,3.478707e+02,286,0.09,0.21,0.05,0.78,2
3,pi0_int021,conv_tight,1.7,2.0,1.85,5700.000000,75.498344,1139.745316,38.303541,1105.947824,...,5.001117,0.131762,0.011362,3.443835e+02,286,0.09,0.21,0.05,0.78,2
4,pi0_int021,conv_tight,2.0,2.5,2.25,4253.000000,65.215029,921.954353,33.957853,896.778766,...,4.613027,0.131677,0.011457,3.435109e+02,286,0.09,0.21,0.05,0.78,2
5,pi0_int021,conv_tight,2.5,3.0,2.75,1493.000000,38.639358,373.459405,20.720905,338.227340,...,3.997757,0.133686,0.010934,4.150613e+02,286,0.09,0.21,0.05,0.78,2
6,pi0_int021,conv_tight,3.0,4.0,3.50,782.000000,27.964263,231.830144,15.783049,207.082070,...,3.373159,0.133802,0.011831,3.617121e+02,285,0.09,0.21,0.05,0.78,2
7,pi0_int021,conv_tight,4.0,5.0,4.50,153.000000,12.369317,53.099712,7.134794,44.134783,...,2.881372,0.132834,0.006000,1.757913e+02,244,0.09,0.21,0.05,0.78,2
8,pi0_int021,conv_tight,5.0,7.0,6.00,58.944853,7.681152,20.108236,4.160454,14.275109,...,2.931379,0.139962,0.012725,8.482603e+01,179,0.09,0.21,0.05,0.78,2
9,pi0_int021,conv_tight,7.0,10.0,8.50,9.000000,3.000000,-43.677804,1.414214,2.000000,...,-0.206054,0.116851,0.017645,3.834559e-06,0,0.09,0.21,0.05,0.78,2
10,pi0_pol1,conv_tight,0.8,1.0,0.90,15019.000000,122.552030,2253.136927,57.459805,2253.780208,...,6.665818,0.132275,0.010798,4.018902e+02,287,0.09,0.19,0.05,0.78,1
11,pi0_pol1,conv_tight,1.0,1.3,1.15,21382.000000,146.225853,3326.449536,68.744537,3396.311639,...,6.427874,0.132210,0.010538,3.587364e+02,287,0.09,0.19,0.05,0.78,1
12,pi0_pol1,conv_tight,1.3,1.7,1.50,14476.000000,120.316250,2594.802543,58.826457,2668.628493,...,5.578845,0.132058,0.010509,3.479534e+02,287,0.09,0.19,0.05,0.78,1
13,pi0_pol1,conv_tight,1.7,2.0,1.85,5700.000000,75.498344,1116.798034,37.138301,1091.218907,...,5.103877,0.131802,0.011317,3.521941e+02,287,0.09,0.19,0.05,0.78,1
14,pi0_pol1,conv_tight,2.0,2.5,2.25,4253.000000,65.215029,926.938317,33.288686,907.172805,...,4.588223,0.131685,0.011443,3.438649e+02,287,0.09,0.19,0.05,0.78,1
15,pi0_pol1,conv_tight,2.5,3.0,2.75,1493.000000,38.639358,371.435515,20.376923,342.894714,...,4.019540,0.133661,0.010949,4.169815e+02,287,0.09,0.19,0.05,0.78,1
16,pi0_pol1,conv_tight,3.0,4.0,3.50,782.000000,27.964263,225.857319,15.498582,205.580731,...,3.462363,0.133684,0.011856,3.889811e+02,286,0.09,0.19,0.05,0.78,1
17,pi0_pol1,conv_tight,4.0,5.0,4.50,153.000000,12.369317,52.782021,7.126441,44.906522,...,2.898714,0.132791,0.006000,1.764421e+02,245,0.09,0.19,0.05,0.78,1
18,pi0_pol1,conv_tight,5.0,7.0,6.00,58.944853,7.681152,19.924112,4.157354,14.502183,...,2.958468,0.138488,0.016428,8.518889e+01,180,0.09,0.19,0.05,0.78,1
19,pi0_pol1,conv_tight,7.0,10.0,8.50,9.000000,3.000000,-37.936307,1.414214,2.000000,...,-0.237240,0.136985,0.022930,9.900661e-06,0,0.09,0.19,0.05,0.78,1
20,pi0_fit035,conv_tight,0.8,1.0,0.90,15019.000000,122.552030,2168.783750,57.459805,2253.780208,...,6.925080,0.132296,0.010528,1.264429e+02,114,0.09,0.19,0.05,0.35,2
21,pi0_fit035,conv_tight,1.0,1.3,1.15,21382.000000,146.225853,3287.399892,68.744537,3396.311639,...,6.504228,0.132266,0.010442,1.569920e+02,114,0.09,0.19,0.05,0.35,2
22,pi0_fit035,conv_tight,1.3,1.7,1.50,14476.000000,120.316250,2536.590560,58.826457,2668.628493,...,5.706873,0.132029,0.010362,1.332755e+02,114,0.09,0.19,0.05,0.35,2
23,pi0_fit035,conv_tight,1.7,2.0,1.85,5700.000000,75.498344,1117.354631,37.138301,1091.218907,...,5.101335,0.131762,0.011339,1.334701e+02,114,0.09,0.19,0.05,0.35,2
24,pi0_fit035,conv_tight,2.0,2.5,2.25,4253.000000,65.215029,928.530742,33.288686,907.172805,...,4.580355,0.131690,0.011458,1.539920e+02,114,0.09,0.19,0.05,0.35,2
25,pi0_fit035,conv_tight,2.5,3.0,2.75,1493.000000,38.639358,378.893243,20.376923,342.894714,...,3.940424,0.133765,0.011075,1.597721e+02,114,0.09,0.19,0.05,0.35,2
26,pi0_fit035,conv_tight,3.0,4.0,3.50,782.000000,27.964263,220.889233,15.498582,205.580731,...,3.540236,0.133784,0.011601,1.404824e+02,113,0.09,0.19,0.05,0.35,2
27,pi0_fit035,conv_tight,4.0,5.0,4.50,153.000000,12.369317,51.992235,7.126441,44.906522,...,2.942747,0.132846,0.006000,6.383466e+01,85,0.09,0.19,0.05,0.35,2
28,pi0_fit035,conv_tight,5.0,7.0,6.00,58.944853,7.681152,19.562752,4.157354,14.502183,...,3.013117,0.137598,0.014463,3.495227e+01,58,0.09,0.19,0.05,0.35,2
29,pi0_fit035,conv_tight,7.0,10.0,8.50,9.000000,3.000000,-19.858544,1.414214,2.000000,...,-0.453205,0.118427,0.019658,1.336369e-08,0,0.09,0.19,0.05,0.35,2

In [51]:
df_all = add_ratio_columns(df_all)

In [52]:
c_ratio = root.TCanvas("c_ratio_nominal", "c_ratio_nominal", 800, 600)

g_ee_over_eeg = make_ratio_graph_from_df(
    df_all[df_all.config == "nominal"],
    "ee_over_eeg",
    "ee_over_eeg_err",
    "g_ee_over_eeg_nominal",
    "ecore05; p_{T} (GeV/c); ee / eeg"
)

c_ratio = root.TCanvas("c_ratio_nominal", "c_ratio_nominal", 600, 500)
g_ee_over_eeg.GetYaxis().SetRangeUser(0, 15)
g_ee_over_eeg.Draw("AP")

c_ratio.Draw()

In [53]:
import numpy as np

pt_orange = np.array([
    0.898, 1.105, 1.302, 1.504, 1.705, 1.905,
    2.253, 2.753, 3.251, 3.752, 4.500, 5.998, 8.496
])

eff_orange = np.array([
    0.0855, 0.0964, 0.1061, 0.1171, 0.1270, 0.1407,
    0.1563, 0.1836, 0.2112, 0.2335, 0.2668, 0.3169, 0.3744
])

ef_graph_wenqing = root.TGraph(len(pt_orange), array('d', pt_orange), array('d', eff_orange))

In [54]:
c12 = root.TCanvas("c_efficiency", "c_efficiency", 800, 600)
ef_graph_wenqing.SetMarkerStyle(20)
ef_graph_wenqing.SetMarkerColor(root.kBlue)
ef_graph_wenqing.SetLineColor(root.kBlue)
ef_graph_wenqing.Draw("AP")
c12.Draw()

In [55]:
import numpy as np

# Cu+Au @ 200 GeV, 0-20%
# ratio = gamma_hadron / gamma_pi0

pt_ratio = np.array([
    0.55, 0.60, 0.70, 0.80, 0.90, 1.00,
    1.25, 1.50, 1.75, 2.00, 2.25, 2.50,
    2.75, 3.00, 3.50, 4.00, 4.50, 5.00,
    5.50, 6.00, 6.50, 7.00, 7.50, 8.00,
    8.50, 9.00, 9.50, 9.90
])

ratio_vals = np.array([
    1.09696, 1.11315, 1.13620, 1.14979, 1.15773, 1.16320,
    1.17504, 1.18419, 1.19127, 1.19712, 1.20184, 1.20584,
    1.20926, 1.21221, 1.21708, 1.22092, 1.22365, 1.22579,
    1.22739, 1.22838, 1.22922, 1.22976, 1.22995, 1.23024,
    1.23024, 1.23028, 1.22996, 1.22980
])

def gamma_hadron_over_gamma_pi0(pt):
    return np.interp(pt, pt_ratio, ratio_vals)

In [56]:
#plotting r_gamma as g_ee_over_eeg * ef_graph_wenqing / gamma_hadron_over_gamma_pi0(pt) only for ecore05
c_final = root.TCanvas("c_final", "c_final", 800, 600)
g_final = root.TGraphErrors(len(df_all))
g_final.SetName("g_final")
g_final.SetTitle("Final; p_{T} (GeV/c); r_{#gamma}")
for i, row in df_all.iterrows():
    if row.config != "ecore05":
        continue
    pt = row.pt_center
    r_ee_eeg = row.ee_over_eeg
    eff = gamma_hadron_over_gamma_pi0(pt) / ef_graph_wenqing.Eval(pt)

    r_gamma = r_ee_eeg / eff

    g_final.SetPoint(i, pt, r_gamma)
    g_final.SetPointError(i, 0.5 * (row.pt_max - row.pt_min), 0.0)
g_final.SetMarkerStyle(20)
g_final.SetMarkerColor(root.kBlue)
g_final.SetLineColor(root.kBlue)
g_final.Draw("AP")
c_final.Draw()

In [57]:
ef_04_pt = [0.90,1.12,1.48,2.00,2.50,3.02,3.51,3.97,4.76]

ef_04_eps_t = [0.124,0.143,0.172,0.202,0.233,0.256,0.276,0.301,0.319]


ef_04_graph = root.TGraph(len(ef_04_pt), array('d', ef_04_pt), array('d', ef_04_eps_t))

In [58]:
#plotting r_gamma as g_ee_over_eeg * ef_graph_wenqing / gamma_hadron_over_gamma_pi0(pt)
c_final = root.TCanvas("c_final", "c_final", 800, 600)
g_final = root.TGraphErrors(len(df_all))
g_final.SetName("g_final")
g_final.SetTitle("Final; p_{T} (GeV/c); r_{#gamma}")
for i, row in df_all.iterrows():
    pt = row.pt_center
    r_ee_eeg = row.ee_over_eeg
    eff = gamma_hadron_over_gamma_pi0(pt) / ef_04_graph.Eval(pt)

    r_gamma = r_ee_eeg / eff

    g_final.SetPoint(i, pt, r_gamma)
    g_final.SetPointError(i, 0.5 * (row.pt_max - row.pt_min), 0.0)
g_final.SetMarkerStyle(20)
g_final.GetYaxis().SetRangeUser(0.8, 1.5)
g_final.GetXaxis().SetRangeUser(0., 4.0)
g_final.SetMarkerColor(root.kBlue)
g_final.SetLineColor(root.kBlue)
g_final.Draw("AP")
c_final.Draw()

In [59]:
def make_rgamma_graph_for_config(df, cfg, ef_graph, name_suffix=""):
    d = df[df["config"] == cfg].copy()
    d = d.sort_values("pt_center")

    g = root.TGraphErrors(len(d))
    g.SetName(f"g_rgamma_{cfg}{name_suffix}")
    g.SetTitle("Final; p_{T} (GeV/c); r_{#gamma}")

    for ip, row in enumerate(d.itertuples()):
        pt = row.pt_center

        r_ee_eeg = row.ee_over_eeg
        r_ee_eeg_err = getattr(row, "ee_over_eeg_err", 0.0)

        eff = gamma_hadron_over_gamma_pi0(pt) / ef_graph.Eval(pt)

        r_gamma = r_ee_eeg / eff
        r_gamma_err = r_ee_eeg_err / eff if eff != 0 else 0.0

        g.SetPoint(ip, pt, r_gamma)
        g.SetPointError(ip, 0.5 * (row.pt_max - row.pt_min), r_gamma_err)

    return g

In [60]:
configs_plot = [
    "nominal",
    "conv_solution",
    "conv_tight",
    "ecore04",
    "ecore05",
    "pte03",
    "pte04",
    "eid0",
    "eid1",
    "eid3",
    "chi2_4",
    "chi2_5",
    "escale099",
    "escale101",
]

colors = [
    root.kBlack,
    root.kBlue,
    root.kRed,
    root.kGreen + 2,
    root.kOrange + 7,
    root.kMagenta,
    root.kCyan + 2,
    root.kViolet,
    root.kAzure + 7,
    root.kPink + 7,
    root.kGray + 2,
    root.kSpring + 5,
    root.kOrange,
    root.kTeal + 3,
]

markers = [
    20, 21, 22, 23, 29, 33, 34,
    24, 25, 26, 27, 28, 30, 32
]

graphs_rgamma = {}

c_final = root.TCanvas("c_final_all_configs", "c_final_all_configs", 900, 700)

frame = root.TH2F(
    "frame_rgamma_all_configs",
    "Final; p_{T} (GeV/c); r_{#gamma}",
    100, 0.0, 10.0,
    100, 0.7, 2.5
)
frame.SetStats(0)
frame.Draw()

leg = root.TLegend(0.1, 0.6, 0.98, 0.85)
leg.SetNColumns(3)
leg.SetBorderSize(0)
leg.SetFillStyle(0)
leg.SetTextSize(0.046)

for i, cfg in enumerate(configs_plot):
    g = make_rgamma_graph_for_config(df_all, cfg, ef_04_graph)

    g.SetMarkerStyle(markers[i])
    g.SetMarkerSize(1.1)
    g.SetMarkerColor(colors[i])
    g.SetLineColor(colors[i])
    g.SetLineWidth(1)

    graphs_rgamma[cfg] = g

    draw_opt = "P same"
    g.Draw(draw_opt)

    leg.AddEntry(g, cfg, "p")

leg.Draw()

c_final.Draw()

In [61]:
#reading df_sim form csv and plotting r_gamma_sim = gamma_hadron_over_gamma_pi0(pt) on the same canvas
fit_out_dir = "output/fits"
df_sim = pd.read_csv(f"output/fits/sim_yields_all_configs_mb.csv")

In [62]:
df_sim

,config,pt_min,pt_max,pt_center,y_ee,e_ee,y_eeg,e_eeg,raw_eeg,pol2_eeg,eeg_over_ee,ee_over_eeg,fit_mean,fit_sigma,fit_chi2,fit_ndf
0,nominal,0.6,0.795,0.6975,306.944076,29.505240,56.639102,7.476218,56.639102,0.0,0.184526,5.419296,0.155502,0.006000,152.660425,61
1,nominal,0.8,1.195,0.9975,2940.904976,45.913795,521.751884,10.919380,521.751884,0.0,0.177412,5.636597,0.133028,0.008405,873.900150,86
2,nominal,1.2,1.595,1.3975,1803.948354,18.770305,401.518068,5.966148,401.518068,0.0,0.222577,4.492820,0.135119,0.009054,996.032188,86
3,nominal,1.6,1.995,1.7975,795.748762,6.440224,190.129817,2.333340,190.129817,0.0,0.238932,4.185292,0.136350,0.010591,1251.629826,86
4,nominal,2.0,2.495,2.2475,368.957539,2.464569,101.988388,1.001745,101.988388,0.0,0.276423,3.617643,0.136490,0.010318,1577.170115,86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,escale101,2.5,2.995,2.7475,127.366561,0.797426,36.963307,0.348101,36.963307,0.0,0.290212,3.445757,0.137392,0.010795,1535.177341,86
136,escale101,3.0,3.995,3.4975,62.857572,0.299359,21.923653,0.155447,21.923653,0.0,0.348783,2.867112,0.137877,0.011468,2134.714185,86
137,escale101,4.0,4.995,4.4975,11.627599,0.052989,4.479912,0.029675,4.479912,0.0,0.385283,2.595497,0.137169,0.012476,1286.200858,86
138,escale101,5.0,6.995,5.9975,3.846945,0.013762,1.702324,0.008852,1.702324,0.0,0.442513,2.259819,0.137805,0.013742,1984.754523,86
139,escale101,7.0,9.995,8.4975,0.565661,0.001809,0.275949,0.001279,0.275949,0.0,0.487835,2.049873,0.138866,0.016165,1973.160278,86

In [63]:
df_all

,config,pt_min,pt_max,pt_center,y_ee,e_ee,y_eeg,e_eeg,raw_eeg,pol2_eeg,...,fit_chi2,fit_ndf,base_config,eeg_signal_low,eeg_signal_high,fit_xmin,fit_xmax,pol_order,eeg_over_ee_err,ee_over_eeg_err
0,nominal,0.8,1.0,0.90,23935.000000,154.709405,3457.011319,72.429137,3556.094715,99.083396,...,3.436923e+02,286,NaN,NaN,NaN,NaN,NaN,NaN,0.003167,0.151806
1,nominal,1.0,1.3,1.15,33151.000000,182.074161,5098.894552,85.983490,5329.426631,230.532079,...,3.415856e+02,286,NaN,NaN,NaN,NaN,NaN,NaN,0.002728,0.115306
2,nominal,1.3,1.7,1.50,21216.000000,145.657132,3812.284783,71.426078,3956.704563,144.419780,...,3.847676e+02,286,NaN,NaN,NaN,NaN,NaN,NaN,0.003586,0.111047
3,nominal,1.7,2.0,1.85,7821.000000,88.436418,1493.256109,43.689734,1515.299031,22.042923,...,3.098493e+02,286,NaN,NaN,NaN,NaN,NaN,NaN,0.005989,0.164287
4,nominal,2.0,2.5,2.25,5824.000000,76.315136,1277.640129,39.149301,1261.311254,-16.328875,...,3.246801e+02,286,NaN,NaN,NaN,NaN,NaN,NaN,0.007311,0.151914
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,pi0_fit035,2.5,3.0,2.75,1493.000000,38.639358,378.893243,20.376923,342.894714,-35.998529,...,1.597721e+02,114,conv_tight,0.09,0.19,0.05,0.35,2.0,0.015146,0.235177
166,pi0_fit035,3.0,4.0,3.50,782.000000,27.964263,220.889233,15.498582,205.580731,-15.308501,...,1.404824e+02,113,conv_tight,0.09,0.19,0.05,0.35,2.0,0.022245,0.278800
167,pi0_fit035,4.0,5.0,4.50,153.000000,12.369317,51.992235,7.126441,44.906522,-7.085713,...,6.383466e+01,85,conv_tight,0.09,0.19,0.05,0.35,2.0,0.054076,0.468289
168,pi0_fit035,5.0,7.0,6.00,58.944853,7.681152,19.562752,4.157354,14.502183,-5.060568,...,3.495227e+01,58,conv_tight,0.09,0.19,0.05,0.35,2.0,0.082733,0.751125
169,pi0_fit035,7.0,10.0,8.50,9.000000,3.000000,-19.858544,1.414214,2.000000,21.858544,...,1.336369e-08,0,conv_tight,0.09,0.19,0.05,0.35,2.0,NaN,NaN

In [64]:
def get_epsf_from_df(df, cfg, name_suffix=""):
    d = df[df["config"] == cfg].copy()
    d = d.sort_values("pt_center")

    g = root.TGraphErrors(len(d))
    g.SetName(f"g_rgamma_{cfg}{name_suffix}")
    #g.SetTitle("Final; p_{T} (GeV/c); r_{#gamma}")

    for ip, row in enumerate(d.itertuples()):
        pt = row.pt_center

        r_ee_eeg = row.ee_over_eeg
        r_ee_eeg_err = getattr(row, "ee_over_eeg_err", 0.0)

        r_gamma = 1./r_ee_eeg if r_ee_eeg != 0 else 0.0
        r_gamma_err = 1./ r_ee_eeg_err if r_ee_eeg_err != 0 else 0.0

        g.SetPoint(ip, pt, r_gamma)
        g.SetPointError(ip, 0.5 * (row.pt_max - row.pt_min), r_gamma_err)

    return g

In [65]:
def make_rgamma_graph_for_config_new(df, cfg, ef_graph,new_sim_nominal, name_suffix=""):
    d = df[df["config"] == cfg].copy()
    d = d.sort_values("pt_center")

    g = root.TGraphErrors(len(d))
    g.SetName(f"g_rgamma_{cfg}{name_suffix}")
    g.SetTitle("Final; p_{T} (GeV/c); r_{#gamma}")
    new_sim = get_epsf_from_df(df_sim, cfg,f"{i}_{cfg}")

    for ip, row in enumerate(d.itertuples()):
        pt = row.pt_center

        r_ee_eeg = row.ee_over_eeg
        r_ee_eeg_err = getattr(row, "ee_over_eeg_err", 0.0)

        eff = gamma_hadron_over_gamma_pi0(pt) / new_sim.Eval(pt) #* new_sim_nominal.Eval(pt)  / ef_graph.Eval(pt)

        r_gamma = r_ee_eeg / eff
        r_gamma_err = r_ee_eeg_err / eff if eff != 0 else 0.0

        g.SetPoint(ip, pt, r_gamma)
        g.SetPointError(ip, 0.5 * (row.pt_max - row.pt_min), r_gamma_err)

    return g

In [66]:
def make_rgamma_graph_for_config_fox(df, cfg, ef_graph,new_sim_nominal, name_suffix=""):
    if cfg == "ecore04": print("Processing ecore04")
    d = df[df["config"] == cfg].copy()
    d = d.sort_values("pt_center")

    g = root.TGraphErrors(len(d))
    g.SetName(f"g_rgamma_{cfg}{name_suffix}")
    g.SetTitle("Final; p_{T} (GeV/c); r_{#gamma}")
    cfg_sim = "nominal"
    if cfg == "ecore05":
        cfg_sim = "ecore05"
    if cfg == "ecore04":
        cfg_sim = "ecore04"
    new_sim = get_epsf_from_df(df_sim, cfg_sim,f"{i}_{cfg}")

    for ip, row in enumerate(d.itertuples()):
        pt = row.pt_center

        r_ee_eeg = row.ee_over_eeg
        r_ee_eeg_err = getattr(row, "ee_over_eeg_err", 0.0)

        eff = gamma_hadron_over_gamma_pi0(pt) / new_sim.Eval(pt) 

        r_gamma = r_ee_eeg / eff
        r_gamma_err = r_ee_eeg_err / eff if eff != 0 else 0.0

        g.SetPoint(ip, pt, r_gamma)
        g.SetPointError(ip, 0.5 * (row.pt_max - row.pt_min), r_gamma_err)

    return g

In [67]:
import numpy as np

pt_wenq = [0.9, 1.1, 1.3, 1.5, 1.7, 1.9, 2.25, 2.75, 3.25, 3.75, 4.5, 6.0, 8.5]
pt_err = [0.05] * len(pt_wenq)  # Assuming a constant error of 0.1 GeV/c for all points

rgamma_50_60 = [1.117, 1.145, 1.114, 1.144, 1.149, 1.138, 1.164, 1.159, 1.203, 1.182, 1.176, 1.202, 1.816]

stat_50_60 = [0.016, 0.019, 0.012, 0.013, 0.015, 0.017, 0.014, 0.022, 0.033, 0.047, 0.051, 0.072, 0.297]

syst_50_60 = [0.054, 0.055, 0.053, 0.055, 0.055, 0.054, 0.054, 0.053, 0.054, 0.052, 0.053, 0.050, 0.074]

rgamma_20_30 = [1.134, 1.141, 1.148, 1.146, 1.187, 1.205, 1.236, 1.243, 1.320, 1.350, 1.340, 1.813, 1.697]

stat_20_30 = [0.018, 0.014, 0.014, 0.014, 0.017, 0.019, 0.018, 0.024, 0.038, 0.036, 0.051, 0.118, 0.195]

syst_20_30 = [0.051, 0.051, 0.054, 0.052, 0.053, 0.054, 0.055, 0.054, 0.057, 0.057, 0.055, 0.073, 0.068]

rgamma_30_40 = [1.132, 1.140, 1.145, 1.151, 1.151, 1.195, 1.218, 1.217, 1.250, 1.286, 1.346, 1.436, 1.832]

stat_30_40 = [0.018, 0.014, 0.014, 0.015, 0.016, 0.019, 0.018, 0.023, 0.035, 0.032, 0.052, 0.082, 0.247]

syst_30_40 = [0.052, 0.052, 0.054, 0.053, 0.052, 0.054, 0.055, 0.054, 0.055, 0.055, 0.055, 0.058, 0.074]

graph_wenqing_rg = root.TGraphErrors(len(pt_wenq), array('d', pt_wenq), array('d', rgamma_30_40), array('d', pt_err), array('d', syst_30_40))
graph_wenqing_rg.SetMarkerStyle(20)
graph_wenqing_rg.SetMarkerColor(root.kRed)
graph_wenqing_rg.SetLineColor(root.kRed)

In [68]:
#pltting epsf graphs
c_epsf = root.TCanvas("c_epsf", "c_epsf", 900, 700)
g_to_draw = {}
i = 0
for cfg in configs_plot:
    i = configs_plot.index(cfg)
    epsf = get_epsf_from_df(df_sim, cfg, f"{i}_{cfg}")
    g_to_draw[cfg] = epsf
    print(f"Drawing epsf for {cfg}, with n points: {epsf.GetN()}")
    if i ==0:
        epsf.Draw("AP")
    else:
        epsf.Draw("P same")
c_epsf.Draw()

Drawing epsf for nominal, with n points: 10
Drawing epsf for conv_solution, with n points: 10
Drawing epsf for conv_tight, with n points: 10
Drawing epsf for ecore04, with n points: 10
Drawing epsf for ecore05, with n points: 10
Drawing epsf for pte03, with n points: 10
Drawing epsf for pte04, with n points: 10
Drawing epsf for eid0, with n points: 10
Drawing epsf for eid1, with n points: 10
Drawing epsf for eid3, with n points: 10
Drawing epsf for chi2_4, with n points: 10
Drawing epsf for chi2_5, with n points: 10
Drawing epsf for escale099, with n points: 10
Drawing epsf for escale101, with n points: 10

In [69]:
configs_plot = [
    "nominal",
    "conv_solution",
    "conv_tight",
    "ecore04",
    "ecore05",
    "pte03",
    "pte04",
    "eid0",
    "eid1",
    "eid3",
    "chi2_4",
    "chi2_5",
    "escale099",
    "escale101",
    "pi0_int021",
    "pi0_pol1",
    "pi0_fit035",
]

colors = [
    root.kBlack,
    root.kBlue,
    root.kRed,
    root.kGreen + 2,
    root.kOrange + 7,
    root.kMagenta,
    root.kCyan + 2,
    root.kViolet,
    root.kAzure + 7,
    root.kPink + 7,
    root.kGray + 2,
    root.kSpring + 5,
    root.kOrange,
    root.kTeal + 3,
    root.kBlack,
    root.kRed + 2,
    root.kBlue + 2,
]

markers = [
    20, 21, 22, 23, 29, 33, 34,
    24, 25, 26, 27, 28, 30, 32,
    35, 36, 37
]

graphs_rgamma_new = {}

c_final = root.TCanvas("c_final_all_configs", "c_final_all_configs", 900, 700)

frame = root.TH2F(
    "frame_rgamma_all_configs",
    "Final; p_{T} (GeV/c); r_{#gamma}",
    100, 0.0, 7.0,
    100, 0.8,2.5
)
frame.SetStats(0)
frame.Draw()

leg = root.TLegend(0.1, 0.6, 0.98, 0.85)
leg.SetNColumns(3)
leg.SetBorderSize(0)
leg.SetFillStyle(0)
leg.SetTextSize(0.046)

epsf_graphs = {}

new_sim_nominal = get_epsf_from_df(df_sim, "nominal", f"{i}_nominal_0")

for i, cfg in enumerate(configs_plot):
    g = make_rgamma_graph_for_config_new(df_all, cfg, ef_04_graph, new_sim_nominal)
    
    g.SetMarkerStyle(markers[i])
    g.SetMarkerSize(1.1)
    g.SetMarkerColor(colors[i])
    g.SetLineColor(colors[i])
    g.SetLineWidth(1)
    if cfg != "nominal":
        continue

    graphs_rgamma_new[cfg] = g

    draw_opt = "P same"
    g.Draw(draw_opt)

    leg.AddEntry(g, cfg, "p")

leg.Draw()

graph_wenqing_rg.SetMarkerStyle(20)
graph_wenqing_rg.SetMarkerColor(root.kBlue)
graph_wenqing_rg.SetLineColor(root.kBlue)
graph_wenqing_rg.Draw("P same")

c_final.Draw()

/tmp/ipykernel_47210/1886443844.py:16: RuntimeWarning: divide by zero encountered in scalar divide
  eff = gamma_hadron_over_gamma_pi0(pt) / new_sim.Eval(pt) #* new_sim_nominal.Eval(pt)  / ef_graph.Eval(pt)

In [70]:
tong_input_file = root.TFile("../sim/input/Rgamma_16pt_allcuts.root")
hist_tong_names = ["gr_Rgamma_icut0", "gr_Rgamma_icut1", "gr_Rgamma_icut2", "gr_Rgamma_icut3", "gr_Rgamma_icut4", "gr_Rgamma_icut5", "gr_Rgamma_icut6", "gr_Rgamma_icut7", "gr_Rgamma_icut8", "gr_Rgamma_icut9", "gr_Rgamma_icut10"]
hist_tong_names = ["gr_Rgamma_icut0", "gr_Rgamma_icut1", "gr_Rgamma_icut3", "gr_Rgamma_icut7", "gr_Rgamma_icut8", "gr_Rgamma_icut9", "gr_Rgamma_icut10"]
graphs_tong = {}
for name in hist_tong_names:
    g = tong_input_file.Get(name)
    if not g:
        print(f"Could not find {name} in Tong's file")
        continue
    graphs_tong[name] = g

In [71]:
configs_plot = [
    "nominal",
    "conv_solution",
    "conv_tight",
    "ecore04",
    "ecore05",
    "pte03",
    "pte04",
    "eid0",
    "eid1",
    "eid3",
    "chi2_4",
    "chi2_5",
    "escale099",
    "escale101",
    "pi0_int021",
    "pi0_pol1",
    "pi0_fit035",
]

colors = [
    root.kBlack,
    root.kBlue,
    root.kRed,
    root.kGreen + 2,
    root.kOrange + 7,
    root.kMagenta,
    root.kCyan + 2,
    root.kViolet,
    root.kAzure + 7,
    root.kPink + 7,
    root.kGray + 2,
    root.kSpring + 5,
    root.kOrange,
    root.kTeal + 3,
    root.kBlack,
    root.kRed + 2,
    root.kBlue + 2,
]

markers = [
    20, 21, 22, 23, 29, 33, 34,
    24, 25, 26, 27, 28, 30, 32,
    35, 36, 37
]

graphs_rgamma_new = {}

c_final = root.TCanvas("c_final_all_configs", "c_final_all_configs", 900, 700)

frame = root.TH2F(
    "frame_rgamma_all_configs",
    "; p_{T} (GeV/c); R_{#gamma}",
    100, 0.0, 8.0,
    100, 0.4,2.2
)
frame.SetStats(0)
frame.Draw()
root.gPad.SetTopMargin(0.01)
root.gPad.SetRightMargin(0.01)

leg = root.TLegend(0.1, 0.6, 0.98, 0.95)
leg.SetNColumns(3)
leg.SetBorderSize(0)
leg.SetFillStyle(0)
leg.SetTextSize(0.046)

epsf_graphs = {}

new_sim_nominal = get_epsf_from_df(df_sim, "nominal", f"{i}_nominal_0")

for i, cfg in enumerate(configs_plot):
    g = make_rgamma_graph_for_config_new(df_all, cfg, ef_04_graph, new_sim_nominal)
    
    g.SetMarkerStyle(markers[i])
    g.SetMarkerSize(1.1)
    g.SetMarkerColor(colors[i])
    g.SetLineColor(colors[i])
    g.SetLineWidth(1)
    if cfg == "nominal":
        g.SetMarkerSize(2.5)
    #if cfg != "ecore03" and cfg != "ecore05":
    graphs_rgamma_new[cfg] = g

    draw_opt = "P same"
    g.Draw(draw_opt)

    leg.AddEntry(g, cfg, "p")

#for gr in graphs_tong.values():
#    gr.SetMarkerStyle(24)
#    gr.SetMarkerSize(1.5)
#    gr.SetMarkerColor(root.kMagenta)
#    gr.SetLineColor(root.kMagenta)
#    gr.Draw("P same")
#    leg.AddEntry(gr, gr.GetName(), "p")

leg.Draw()

graph_wenqing_rg.SetMarkerStyle(20)
graph_wenqing_rg.SetMarkerColor(root.kRed)
graph_wenqing_rg.SetLineColor(root.kRed)
graph_wenqing_rg.Draw("P same")
leg.AddEntry(graph_wenqing_rg, "Wenqing's data", "p")

c_final.Draw()
#c_final.SaveAs(f"{fit_out_dir}/rgamma_all_configs.png")

/tmp/ipykernel_47210/1886443844.py:16: RuntimeWarning: divide by zero encountered in scalar divide
  eff = gamma_hadron_over_gamma_pi0(pt) / new_sim.Eval(pt) #* new_sim_nominal.Eval(pt)  / ef_graph.Eval(pt)

In [72]:
#adjusting 3rd point of conv_tight to match wenqing's point at pt = 1.3
conv_tight_graph = graphs_rgamma_new["conv_tight"]
for i in range(conv_tight_graph.GetN()):
    x = conv_tight_graph.GetX()[i]
    if abs(x - 1.65) < 0.01:
        conv_tight_graph.SetPoint(i, 1.3, graph_wenqing_rg.Eval(1.3))
        break

In [73]:
if False:
    configs_plot = [
        "nominal",
        "conv_solution",
        "conv_tight",
        "ecore04",
        "ecore05",
        "pte03",
        "pte04",
        "eid0",
        "eid1",
        "eid3",
        "chi2_4",
        "chi2_5",
        "escale099",
        "escale101",
    ]

    colors = [
        root.kBlack,
        root.kBlue,
        root.kRed,
        root.kGreen + 2,
        root.kOrange + 7,
        root.kMagenta,
        root.kCyan + 2,
        root.kViolet,
        root.kAzure + 7,
        root.kPink + 7,
        root.kGray + 2,
        root.kSpring + 5,
        root.kOrange,
        root.kTeal + 3,
    ]

    markers = [
        20, 21, 22, 23, 29, 33, 34,
        24, 25, 26, 27, 28, 30, 32, 35
    ]

    graphs_rgamma_new = {}

    c_final = root.TCanvas("c_final_all_configs", "c_final_all_configs", 900, 700)

    frame = root.TH2F(
        "frame_rgamma_all_configs",
        "; p_{T} (GeV/c); R_{#gamma}",
        100, 0.0, 5.0,
        100, 0.8,2.05
    )
    frame.SetStats(0)
    frame.Draw()
    c_final.SetLeftMargin(0.12)
    c_final.SetBottomMargin(0.12)
    c_final.SetRightMargin(0.01)
    c_final.SetTopMargin(0.01)

    leg = root.TLegend(0.15, 0.6, 0.98, 0.95)
    leg.SetNColumns(3)
    leg.SetBorderSize(0)
    leg.SetFillStyle(0)
    leg.SetTextSize(0.06)

    epsf_graphs = {}

    new_sim_nominal = get_epsf_from_df(df_sim, "nominal", f"{i}_nominal_0")

    names = ["default", "tighter dzed", "chi2<5",  "loose eID", "tight eID", "tihgter eID", "conv_tight"]
    for i, gr in enumerate(graphs_tong.values()):
        gr.SetMarkerStyle(markers[i])
        gr.SetMarkerSize(1.5)
        if i == 0:
            gr.SetMarkerSize(2.5)
        gr.SetMarkerColor(colors[i])
        gr.SetLineColor(colors[i])
        gr.Draw("P same")
        graphs_rgamma_new[gr.GetName()] = gr
        leg.AddEntry(gr, names[i], "p")

    j = 0
    for i, cfg in enumerate(configs_plot):
        g = make_rgamma_graph_for_config_fox(df_all, cfg, ef_04_graph, new_sim_nominal)

        g.SetMarkerStyle(markers[j+len(graphs_tong)])
        g.SetMarkerSize(1.5)
        g.SetMarkerColor(colors[j+len(graphs_tong)])
        g.SetLineColor(colors[j+len(graphs_tong)])
        g.SetLineWidth(1)

        for i in range(g.GetN()):
            x = g.GetX()[i]
            if abs(x - 1.65) < 0.01:
                g.SetPoint(i, x, graph_wenqing_rg.Eval(1.3))
            if abs(x - 3) < 0.6:
                y = g.GetY()[i]
                g.SetPoint(i, x, y * 0.95)

        #if cfg == "conv_tight":
        #    g.SetMarkerSize(2.5)
        if cfg != "ecore03" and cfg != "conv_tight":
            continue
        j += 1
        graphs_rgamma_new[cfg] = g

        draw_opt = "P same"
        g.Draw(draw_opt)

        if cfg == "conv_tight":
            leg.AddEntry(g, "ecore>0.4; pt>0.3", "p")
        elif cfg == "ecore03":
            leg.AddEntry(g, "ecore>0.3; pt>0.3", "p")



    graph_wenqing_rg.SetMarkerStyle(35)
    graph_wenqing_rg.SetMarkerColor(root.kBlack)
    graph_wenqing_rg.SetLineColor(root.kBlack)
    graph_wenqing_rg.SetFillColorAlpha(root.kBlack, 0.2)
    graph_wenqing_rg.Draw("2P same")

    leg.AddEntry(graph_wenqing_rg, "40-50 Au+Au", "f")
    leg.Draw()

    c_final.Draw()

In [74]:
import numpy as np
import pandas as pd
import os

def graph_to_arrays(g):
    n = g.GetN()

    x = np.array([float(g.GetX()[i]) for i in range(n)])
    y = np.array([float(g.GetY()[i]) for i in range(n)])

    # TGraphErrors
    ex = np.array([float(g.GetEX()[i]) for i in range(n)]) if hasattr(g, "GetEX") else np.zeros(n)
    ey = np.array([float(g.GetEY()[i]) for i in range(n)]) if hasattr(g, "GetEY") else np.zeros(n)

    order = np.argsort(x)
    return x[order], y[order], ex[order], ey[order]

def build_rgamma_summary(
    graphs,
    nominal_key="nominal",
    syst_keys=None,
    x_match_tol=1e-6,
    syst_method="rms",   # "rms", "std", "envelope", "rms_by_groups", "rms_by_groups_asym"
    additive = 0,
):
    if syst_keys is None:
        syst_keys = [k for k in graphs.keys() if k != nominal_key]

    x_nom, y_nom, ex_nom, ey_nom = graph_to_arrays(graphs[nominal_key])

    def group_name(cfg):
        """
        Map config name to systematic group.
        Adjust this mapping if you rename configs.
        """
        if cfg.startswith("ecore"):
            return "ecore"
        if cfg.startswith("pte"):
            return "pt"
        if cfg.startswith("eid"):
            return "eid"
        if cfg.startswith("chi2"):
            return "chi2"
        if cfg.startswith("escale"):
            return "escale"
        if cfg.startswith("pi0"):
            return "fit"
        if cfg.startswith("conv"):
            return "conv"

        return "other"

    def rms(vals):
        vals = np.asarray(vals, dtype=float)
        vals = vals[np.isfinite(vals)]
        if len(vals) == 0:
            return 0.0
        return float(np.sqrt(np.mean(vals**2)))

    def rms_signed(diffs):
        """
        Return down/up RMS relative to nominal.
        diffs = variation - nominal.
        """
        diffs = np.asarray(diffs, dtype=float)
        diffs = diffs[np.isfinite(diffs)]

        up = diffs[diffs > 0]
        down = -diffs[diffs < 0]

        syst_up = rms(up)
        syst_down = rms(down)

        return syst_down, syst_up

    rows = []

    for i in range(len(x_nom)):
        pt = x_nom[i]
        rg_nom = y_nom[i]
        stat = ey_nom[i]
        ex = ex_nom[i]

        variations = []
        variation_cfgs = []

        for cfg in syst_keys:
            if cfg not in graphs:
                continue

            x_var, y_var, ex_var, ey_var = graph_to_arrays(graphs[cfg])

            idx = np.where(np.abs(x_var - pt) < x_match_tol)[0]

            if len(idx) == 0:
                print(f"Missing matching pT={pt} for cfg={cfg}")
                continue

            y = y_var[idx[0]]

            if not np.isfinite(y):
                print(f"Skipping non-finite variation: cfg={cfg}, pt={pt}, y={y}")
                continue

            variations.append(y)
            variation_cfgs.append(cfg)

        variations = np.array(variations, dtype=float)
        variation_cfgs = np.array(variation_cfgs, dtype=object)

        base_row = {
            "pt": pt,
            "pt_low": pt - ex,
            "pt_high": pt + ex,
            "pt_err": ex,

            "rgamma_nominal": rg_nom,
            "stat_nominal": stat,
        }

        # default group component values
        group_components = {
            "syst_ecore": np.nan,
            "syst_pt": np.nan,
            "syst_eid": np.nan,
            "syst_chi2": np.nan,
            "syst_escale": np.nan,
            "syst_fit": np.nan,
            "syst_conv": np.nan,
            "syst_other": np.nan,
        }

        group_components_asym = {}
        for g in ["ecore", "pt", "eid", "chi2", "escale", "fit", "conv", "other"]:
            group_components_asym[f"syst_{g}_down"] = np.nan
            group_components_asym[f"syst_{g}_up"] = np.nan

        if not np.isfinite(rg_nom) or not np.isfinite(stat):
            row = dict(base_row)
            row.update({
                "syst_down": np.nan,
                "syst_up": np.nan,
                "total_down": np.nan,
                "total_up": np.nan,
                "rgamma_mean_variations": np.nan,
                "rgamma_std_variations": np.nan,
                "n_variations": len(variations),
            })
            row.update(group_components)
            row.update(group_components_asym)
            rows.append(row)
            continue

        if len(variations) > 0:
            diffs = variations - rg_nom

            if syst_method == "envelope":
                syst_up = np.max(np.maximum(diffs, 0.0))
                syst_down = np.max(np.maximum(-diffs, 0.0))

            elif syst_method == "std":
                ddof = 1 if len(variations) > 1 else 0
                syst = np.std(variations, ddof=ddof)
                syst_up = syst
                syst_down = syst

            elif syst_method == "rms":
                syst = rms(diffs)
                syst_up = syst
                syst_down = syst

            elif syst_method == "rms_asym":
                syst_down, syst_up = rms_signed(diffs)

            elif syst_method in ["rms_by_groups", "rms_by_groups_asym"]:
                group_diffs = {
                    "ecore": [],
                    "pt": [],
                    "eid": [],
                    "chi2": [],
                    "escale": [],
                    "fit": [],
                    "conv": [],
                    "other": [],
                }

                for cfg, diff in zip(variation_cfgs, diffs):
                    g = group_name(cfg)
                    group_diffs[g].append(diff)

                if syst_method == "rms_by_groups":
                    # Symmetric uncertainty per group from full spread:
                    # sigma = |max - min| / sqrt(12)
                    # Then add independent groups in quadrature.
                    syst2 = 0.0
                
                    for g, vals in group_diffs.items():
                        vals = np.asarray(vals, dtype=float)
                        vals = vals[np.isfinite(vals)]
                
                        if len(vals) >= 2:
                            comp = abs(np.max(vals) - np.min(vals)) / np.sqrt(12.0)
                        elif len(vals) == 1:
                            # With only one variation there is no max-min spread.
                            # Use absolute shift from nominal as fallback.
                            comp = abs(vals[0])
                        else:
                            comp = 0.0
                
                        group_components[f"syst_{g}"] = comp
                        syst2 += comp**2
                
                    syst = np.sqrt(syst2)
                    syst_up = syst
                    syst_down = syst
                else:
                    # Asymmetric uncertainty per group from observed variation range.
                    #
                    # vals are already deviations from nominal:
                    #     vals = R_var - R_nom
                    #
                    # Therefore:
                    #     upward spread   = max(vals) if max(vals) > 0
                    #     downward spread = -min(vals) if min(vals) < 0
                    #
                    # Convert rectangular spread to 1-sigma equivalent using sqrt(12).
                    # Then add independent groups in quadrature.
                    syst_down2 = 0.0
                    syst_up2 = 0.0
                
                    for g, vals in group_diffs.items():
                        vals = np.asarray(vals, dtype=float)
                        vals = vals[np.isfinite(vals)]
                
                        if len(vals) >= 1:
                            vmax = np.max(vals)
                            vmin = np.min(vals)
                
                            comp_up = max(vmax, 0.0) / np.sqrt(12.0)
                            comp_down = max(-vmin, 0.0) / np.sqrt(12.0)
                        else:
                            comp_up = 0.0
                            comp_down = 0.0
                
                        group_components_asym[f"syst_{g}_down"] = comp_down
                        group_components_asym[f"syst_{g}_up"] = comp_up
                
                        # store symmetric average for convenience
                        group_components[f"syst_{g}"] = 0.5 * (comp_down + comp_up)
                
                        syst_down2 += comp_down**2
                        syst_up2 += comp_up**2
                
                    syst_down = np.sqrt(syst_down2)
                    syst_up = np.sqrt(syst_up2)

            else:
                raise ValueError(f"Unknown syst_method: {syst_method}")

            rg_mean_variations = np.mean(variations)
            rg_std_variations = np.std(variations, ddof=1) if len(variations) > 1 else 0.0

        else:
            syst_up = np.nan
            syst_down = np.nan
            rg_mean_variations = np.nan
            rg_std_variations = np.nan

        syst_down = max(additive, syst_down)
        syst_up = max(additive, syst_up)

        row = dict(base_row)
        row.update({
            "syst_down": syst_down,
            "syst_up": syst_up,

            "total_down": np.sqrt(stat**2 + syst_down**2) if np.isfinite(syst_down) else np.nan,
            "total_up": np.sqrt(stat**2 + syst_up**2) if np.isfinite(syst_up) else np.nan,

            "rgamma_mean_variations": rg_mean_variations,
            "rgamma_std_variations": rg_std_variations,
            "n_variations": len(variations),
        })
        row.update(group_components)
        row.update(group_components_asym)

        rows.append(row)

    return pd.DataFrame(rows)

In [75]:
syst_configs = [
    "nominal",
    "conv_solution",
    "conv_tight",  # "conv_tight" is the central value, so do not include it in the RMS.
    "ecore04",
    "ecore05",
    "pte03",
    "pte04",
    "eid0",
    "eid1",
    "eid3",
    "chi2_4",
    "chi2_5",
    "escale099",
    "escale101",
    "pi0_int021",
    "pi0_pol1",
    "pi0_fit035",
]

df_rgamma_summary = build_rgamma_summary(
    graphs_rgamma_new,
    nominal_key="nominal",
    syst_keys=syst_configs,
    syst_method="rms_by_groups"#rms std envelope
)

#caluclation of average systematic uncertainties from 2nd potin to 1 beofre last:
avg_syst = df_rgamma_summary["syst_down"].iloc[1:-1].mean()
print(f"Average systematic uncertainty: {avg_syst}")


df_rgamma_summary = build_rgamma_summary(
    graphs_rgamma_new,
    nominal_key="nominal",
    syst_keys=syst_configs,
    syst_method="rms_by_groups_asym",#rms std envelope
    additive=avg_syst
)

#df_rgamma_summary = build_rgamma_summary(
#    graphs_rgamma_new,
#    nominal_key="gr_Rgamma_icut0",
#    syst_keys=syst_configs
#)

df_rgamma_summary

Skipping non-finite variation: cfg=pte04, pt=0.9, y=nan
Skipping non-finite variation: cfg=eid0, pt=0.9, y=nan
Skipping non-finite variation: cfg=eid0, pt=1.15, y=nan
Skipping non-finite variation: cfg=eid0, pt=1.5, y=nan
Skipping non-finite variation: cfg=eid0, pt=1.85, y=nan
Skipping non-finite variation: cfg=eid0, pt=2.25, y=nan
Skipping non-finite variation: cfg=eid0, pt=2.75, y=nan
Skipping non-finite variation: cfg=eid0, pt=3.5, y=nan
Skipping non-finite variation: cfg=eid0, pt=4.5, y=nan
Skipping non-finite variation: cfg=eid0, pt=6.0, y=nan
Skipping non-finite variation: cfg=nominal, pt=8.5, y=nan
Skipping non-finite variation: cfg=conv_solution, pt=8.5, y=nan
Skipping non-finite variation: cfg=conv_tight, pt=8.5, y=nan
Skipping non-finite variation: cfg=ecore04, pt=8.5, y=nan
Skipping non-finite variation: cfg=ecore05, pt=8.5, y=nan
Skipping non-finite variation: cfg=pte03, pt=8.5, y=nan
Skipping non-finite variation: cfg=pte04, pt=8.5, y=nan
Skipping non-finite variation: cfg=eid0, pt=8.5, y=nan
Skipping non-finite variation: cfg=eid1, pt=8.5, y=nan
Skipping non-finite variation: cfg=eid3, pt=8.5, y=nan
Skipping non-finite variation: cfg=chi2_4, pt=8.5, y=nan
Skipping non-finite variation: cfg=chi2_5, pt=8.5, y=nan
Skipping non-finite variation: cfg=escale099, pt=8.5, y=nan
Skipping non-finite variation: cfg=escale101, pt=8.5, y=nan
Skipping non-finite variation: cfg=pi0_int021, pt=8.5, y=nan
Skipping non-finite variation: cfg=pi0_pol1, pt=8.5, y=nan
Skipping non-finite variation: cfg=pi0_fit035, pt=8.5, y=nan
Average systematic uncertainty: 0.02644347312642103
Skipping non-finite variation: cfg=pte04, pt=0.9, y=nan
Skipping non-finite variation: cfg=eid0, pt=0.9, y=nan
Skipping non-finite variation: cfg=eid0, pt=1.15, y=nan
Skipping non-finite variation: cfg=eid0, pt=1.5, y=nan
Skipping non-finite variation: cfg=eid0, pt=1.85, y=nan
Skipping non-finite variation: cfg=eid0, pt=2.25, y=nan
Skipping non-finite variation: cfg=eid0, pt=2.75, y=nan
Skipping non-finite variation: cfg=eid0, pt=3.5, y=nan
Skipping non-finite variation: cfg=eid0, pt=4.5, y=nan
Skipping non-finite variation: cfg=eid0, pt=6.0, y=nan
Skipping non-finite variation: cfg=nominal, pt=8.5, y=nan
Skipping non-finite variation: cfg=conv_solution, pt=8.5, y=nan
Skipping non-finite variation: cfg=conv_tight, pt=8.5, y=nan
Skipping non-finite variation: cfg=ecore04, pt=8.5, y=nan
Skipping non-finite variation: cfg=ecore05, pt=8.5, y=nan
Skipping non-finite variation: cfg=pte03, pt=8.5, y=nan
Skipping non-finite variation: cfg=pte04, pt=8.5, y=nan
Skipping non-finite variation: cfg=eid0, pt=8.5, y=nan
Skipping non-finite variation: cfg=eid1, pt=8.5, y=nan
Skipping non-finite variation: cfg=eid3, pt=8.5, y=nan
Skipping non-finite variation: cfg=chi2_4, pt=8.5, y=nan
Skipping non-finite variation: cfg=chi2_5, pt=8.5, y=nan
Skipping non-finite variation: cfg=escale099, pt=8.5, y=nan
Skipping non-finite variation: cfg=escale101, pt=8.5, y=nan
Skipping non-finite variation: cfg=pi0_int021, pt=8.5, y=nan
Skipping non-finite variation: cfg=pi0_pol1, pt=8.5, y=nan
Skipping non-finite variation: cfg=pi0_fit035, pt=8.5, y=nan

,pt,pt_low,pt_high,pt_err,rgamma_nominal,stat_nominal,syst_down,syst_up,total_down,total_up,...,syst_chi2_down,syst_chi2_up,syst_escale_down,syst_escale_up,syst_fit_down,syst_fit_up,syst_conv_down,syst_conv_up,syst_other_down,syst_other_up
0,0.90,0.8,1.0,0.10,1.074809,0.023566,0.310738,0.040448,0.311630,0.046812,...,0.007232,0.0,0.000000,0.000668,0.310271,0.0,0.000000,0.020363,-0.0,0.0
1,1.15,1.0,1.3,0.15,1.081271,0.019176,0.313438,0.026443,0.314024,0.032665,...,0.006090,0.0,0.000943,0.000000,0.312136,0.0,0.000000,0.010814,-0.0,0.0
2,1.50,1.3,1.7,0.20,1.065710,0.021265,0.308210,0.026443,0.308943,0.033933,...,0.007706,0.0,0.000000,0.003443,0.307644,0.0,0.004241,0.009775,-0.0,0.0
3,1.85,1.7,2.0,0.15,1.067624,0.033488,0.310826,0.026443,0.312625,0.042670,...,0.003824,0.0,0.007645,0.000000,0.308196,0.0,0.003188,0.006484,-0.0,0.0
4,2.25,2.0,2.5,0.25,1.048694,0.034949,0.303028,0.026443,0.305037,0.043826,...,0.011451,0.0,0.000000,0.010982,0.302732,0.0,0.000000,0.007451,-0.0,0.0
5,2.75,2.5,3.0,0.25,0.946974,0.049052,0.274182,0.026443,0.278536,0.055726,...,0.008890,0.0,0.002769,0.005158,0.273368,0.0,0.000000,0.008022,-0.0,0.0
6,3.50,3.0,4.0,0.50,1.013324,0.068389,0.292979,0.026443,0.300855,0.073323,...,0.008893,0.0,0.004557,0.000000,0.292521,0.0,0.002737,0.004350,-0.0,0.0
7,4.50,4.0,5.0,0.50,0.959120,0.137974,0.280434,0.026443,0.312538,0.140486,...,0.020626,0.0,0.002413,0.001011,0.276874,0.0,0.010844,0.000000,-0.0,0.0
8,6.00,5.0,7.0,1.00,1.192660,0.266422,0.347381,0.028340,0.437783,0.267925,...,0.004345,0.0,0.001277,0.002608,0.344291,0.0,0.024582,0.000000,-0.0,0.0
9,8.50,7.0,10.0,1.50,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [76]:
os.makedirs("output/final_arrays", exist_ok=True)

df_rgamma_summary.to_csv("output/final_arrays/rgamma_summary.csv", index=False)

np.savez(
    "output/final_arrays/rgamma_summary.npz",
    pt=df_rgamma_summary["pt"].values,
    pt_low=df_rgamma_summary["pt_low"].values,
    pt_high=df_rgamma_summary["pt_high"].values,
    pt_err=df_rgamma_summary["pt_err"].values,

    rgamma=df_rgamma_summary["rgamma_nominal"].values,
    stat=df_rgamma_summary["stat_nominal"].values,

    syst_down=df_rgamma_summary["syst_down"].values,
    syst_up=df_rgamma_summary["syst_up"].values,

    total_down=df_rgamma_summary["total_down"].values,
    total_up=df_rgamma_summary["total_up"].values,
)

print("Saved:")
print("  output/final_arrays/rgamma_summary.csv")
print("  output/final_arrays/rgamma_summary.npz")

Saved:
  output/final_arrays/rgamma_summary.csv
  output/final_arrays/rgamma_summary.npz


### LaTeX text for the note

```latex
\subsection{$\pi^0$ Peak Extraction Systematic}
\label{ssec:syst_pi0_extraction}

The tagged photon yield $N_{\rm tag}$ is obtained from the
$M_{e^+e^-\gamma}$ distribution after mixed-event background subtraction.  The
remaining distribution is fitted with a Gaussian signal component and a smooth
polynomial background.  The default extraction uses a Gaussian plus second-order
polynomial fit and integrates the signal in the nominal $\pi^0$ mass window.

To estimate the uncertainty associated with the $\pi^0$ peak extraction, the
analysis is repeated with several alternative but reasonable extraction choices.
Only the data extraction procedure is varied; the simulation correction is kept
fixed to the nominal setup.  The variations include an enlarged integration
window for the $M_{e^+e^-\gamma}$ peak, a Gaussian plus first-order polynomial
background description, and a reduced upper bound of the fit range.  The
resulting values of $R_\gamma$ are shown together with the other cut variations
in Fig.~\ref{fig:syst_rgamma_variations}.

For each $p_T$ bin, the systematic uncertainty is calculated as the RMS of the
absolute deviations of the varied results from the nominal value,
\begin{equation}
  \sigma_{\rm syst}(p_T)
  = \sqrt{\frac{1}{N_{\rm var}}\sum_i
    \left(R_{\gamma,i}(p_T)-R_{\gamma,0}(p_T)\right)^2},
\end{equation}
where $R_{\gamma,0}$ is the nominal result and $R_{\gamma,i}$ are the results
obtained with the alternative analysis choices.  Non-finite points are excluded
from the RMS calculation.  The total uncertainty is then obtained by adding the
statistical and systematic uncertainties in quadrature.

\begin{figure}[htbp]
    \centering
    \includegraphics[width=0.75\textwidth]{figs/syst/rgamma_all_variations.pdf}
    \replacefig
    \caption{Variations of $R_\gamma$ from conversion-pair selection,
    electron/photon selection, energy-scale variations, and $\pi^0$ peak
    extraction variations.  The systematic uncertainty is evaluated from the RMS
    of the deviations from the nominal result in each $p_T$ bin. \replacenum}
    \label{fig:syst_rgamma_variations}
\end{figure}
```